### PR TITLE
Support Mapnik 3 in install docs

### PR DESCRIPTION
**Pull request by pnorman**
There are no known major Mapnik 3 issues left.

After merging, I'll have a look at the issues against the Mapnik 3 milestone. Those which will require Mapnik 3 style features can be left, but others can be closed.

### CODE REVIEW

**Comment by matkoniecz** [comment]
#1579 is closed but "Text is farther away from lines" and "maxzoom depreciated and will be removed in 4.x spams the log(...)" are not marked as solved.

Also, it seems that according to https://github.com/mapnik/mapnik/issues/2913 we still need add vertical-alignment:middle to labels on lines using offsets.

**Comment by pnorman** [comment]
> #1579 is closed but "Text is farther away from lines" and "maxzoom depreciated and will be removed in 4.x spams the log(...)" are not marked as solved. First problem is in the section "Major issues".

I don't plan to fix the max/min zoom stuff anytime soon, because it's a minor issue.

When I last did a review, I couldn't see any other problems.

**Comment by math1985** [comment]
I have been exclusively using Mapnik 3 in Kosmtik for a couple of months, and I haven't encountered any issues.

What would be the next step? Are we ready to recommend the server admins to move to Mapnik 3?

**Comment by gravitystorm** [comment]
Sounds great to me. I've opened a ticket at https://github.com/openstreetmap/chef/issues/39

This should allow us to "fix" various text-rendering issues. I'm also happy to *require* mapnik3 at any point - we'll just need to bump the version number when we start using mapnik3-only features.

**Comment by math1985** [comment]
Just to be clear, I haven't tested exhaustively on possible Mapnik 3 issues - I just haven't encountered any while doing development.

So I guess we shouldn't be too surprised if some issues pop up anyway.

**Comment by gravitystorm** [comment]
Dont' worry, I carefully hedged my statement on that issue :-)

**Pull request merged**
