### PR TITLE
Add playground equipment rendering

### PR DESCRIPTION
**Pull request by pietervdvn**
Changes proposed in this pull request:
- Add icons for playground equipment, such as slides and swings

Test rendering with links to the example places:

See https://www.openstreetmap.org/#map=19/51.20569/3.23290

Before:
screenshot from 2018-04-01 13-52-44

After
screenshot from 2018-04-01 13-38-01

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
The svgs should be exported so they dont have all inkscape metadata anymore.

But most important we have to decide if we want to render this high detail in this general purpose style
I am unsure it we should even if i tagged many of them

**Comment by kocio-pl** [comment]
Interesting work, especially for z19+. My comments:
- please be more specific what elements exactly you include in this PR, with links to wiki pages and the numbers of uses
- save the icons as plain SVG instead of default Inkscape, which adds a lot of unneeded metadata
- be ready to discuss and tune the shapes :smile:

**Comment by kocio-pl** [comment]
One more thing - it's good to join paths in the image, see:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines

**Comment by pietervdvn** [comment]
- This renders some playground equipments, [as described here in the wiki](https://wiki.openstreetmap.org/wiki/Key:playground). It adds support for swing, sandpit, slide, climbing_frame and springy, with respectively 4'255, 3'208, 3099, 1946 and 1840 occurences. Up to date numbers can be found on [taginfo](https://taginfo.openstreetmap.org/keys/playground#values).

- Plain SVG: is done

- Oh god... Let the bikeshedding begin.

**Comment by pietervdvn** [comment]
What do you mean by joining the paths?

Also: yes: I do think we should render this. It shows the richness and possibilities of OSM, and I would love to fill the playgrounds with more details.

**Comment by kocio-pl** [comment]
Path > Combine probably.

**Comment by Tomasz-W** [comment]
I'm against - it's creating too much mess and I don't see a need for details of playgrounds.

**Comment by pietervdvn** [comment]
- It is only shown on the highest zoom level (19) to avoid the mess
- This detail has an added value, for showing the richness. And I like very
much to see what a playground has to offer beforehand. And it will
stimulate the better mapping of playgrounds as well.


Met vriendelijke groeten,
Pieter Vander Vennet

2018-04-01 20:34 GMT+02:00 Tomasz Wójcik <notifications@github.com>:

**Comment by lakedistrictOSM** [comment]
Some feedback on the icons:
- make the icons smaller (14x14)
- slide: make the ladder thicker
- springy: could probably be simplified
- sandpit: needs simplifying
- swing: again, could be simplified ([perhaps try something like this](https://thenounproject.com/search/?q=swing&i=131407))

**Comment by kocio-pl** [comment]
I don't believe it creates mess. If you go down to the playground and zoom in to z19 it's hard for me to believe that it was by accident and you don't want to see the details other than just the leisure background color all around.

The mess is when some features can be found in different places, like wayside shrine for example - beside being useful outdoor landmark it can be found in the city where once upon the time was the old way and now it's crowded place. That's why we had to tune zoom level to avoid mess while trying to show them relatively early for the more typical cases. Playground equipment is just a detail of a playground and this is where it can be found, so it's natural to expect it here - but of course on later zoom level than the playground as a whole. Z19 is very safe choice in that respect.

**Comment by HolgerJeromin** [comment]
Could someone render this dense mapped playground?
https://www.openstreetmap.org/way/286032344

**Comment by pietervdvn** [comment]
I will have a look at the icons in a few days, when more people had the chance to comment on them. I'll try to fix all issues at once then.

@HolgerJeromin : The difference is small, as play_structure is not rendered. It's difficult to make an icon for that.



screenshot from 2018-04-02 12-17-50

**Comment by pnorman** [comment]
Aside from the issues with the idea in general, the SVGs do meet our [map icon style guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines) for canvas size, SVG XML formatting, and likely pixel alignment and reduced complexity.

**Comment by kocio-pl** [comment]
> Their benefit for finding something by looking at the map or orienting yourself when there in person are minimal, nor are there are special considerations which make playground equipment cartographically significant.

It strongly depends on which scale we're talking about. It's absolutely unsignificant (and I would call it just wrong) on a country or city level. Yet there are many detailed plans for such places on a high zoom level, for example:

https://sherbornplayground.files.wordpress.com/2014/04/playground-design-optional-1558562-preliminary-plan.jpg

Someone took the time to tag these objects, so she thinks it's important enough and I understand very well why micromapping is important for people.

> Aside from the issues with the idea in general, the SVGs do meet our map icon style guidelines for canvas size, SVG XML formatting, and likely pixel alignment and reduced complexity.

Complexity is not that big in presented icons and pixel alignment is not top priority for everything other than simple geometrical shapes, but size doesn't look like 14 px in all the cases and it looks like a different style currently - BTW, are these icons yours or taken from some other style (I want to be sure the license is proper for us to use them)?

**Comment by pietervdvn** [comment]
Hello everyone,

Yes, this is meant to be a fun gimmick for families, on high zoom level (only 19 ATM). I will look at the icons once more in a few days, when everyone has given his opinion.

I designed them myself (although one piece came from a CC0-image).

**Comment by polarbearing** [comment]
@pnorman: did you mean "the SVGs do _not_ meet our map icon style guidelines" ? None of the icons works in 14px.

@pietervdvn - sorry but your concept does not work here, for me. 

The existing 'playground' icon cites a typical equipment, the see-saw. We would need to find an equipment-agnostic icon for 'playground' if we started rendering specific equipment. These equipment icons would need to cite the general playground icon, so the viewer could recognise the relation between them.

Even if that could be solved, the problem would be that you could not recognise the playground because there are too many equipment icons. Like not finding the wood because there are too many trees.

> Oh god... Let the bikeshedding begin.

If you refer to the [Bikeshedding](https://en.wikipedia.org/wiki/Law_of_triviality) in a sense that we are nitpicking on unnecessary details, your criticism is inappropriate. If everybody would throw her own design in the field, we would not recognise anything anymore. Imagine a soccer team with everybody wearing their own dress.

> meant to be a fun gimmick for families

Indeed it would be fabulous on a family or kids oriented map style. Don't get me wrong. I contributed a lot to the wiki page and map every swing I find. But this is the general style.

**Comment by kocio-pl** [comment]
> Even if that could be solved, the problem would be that you could not recognise the playground because there are too many equipment icons. Like not finding the wood because there are too many trees.

This is a vaild problem and thanks for noticing it, but we have it with other types of objects. 

Do you recognize park with fountains, artworks, buildings, footways, waterways, ponds, lawns, trees, playgrounds etc? I do, because usually they are rendered later than park. The only bad situation is when objects belonging to something bigger are visible too early. I have no idea how to move cemetery alleys/footpaths to higher zoom levels. Also well mapped hospitals or schools are no longer seen as yellow areas. The same with shops inside marketplace. See #2896.

With playground objects we no such problems. We see playgrounds from z17 as icon and even earlier as an area. The area is still visible on z19, so you won't forget what are you zooming in.

**Comment by dieterdreist** [comment]
sent from a phone

> On 11. Apr 2018, at 19:23, Mateusz Konieczny <notifications@github.com> wrote:
> 
> I admit that I have (again) doubts whatever it is too much or is it still OK to render such details.


It would be nice to show actual geometries of the things (playground castles, slides, ...
slides can be huge (generally they aren’t): https://goo.gl/images/xzxCAe

**Comment by dieterdreist** [comment]
sent from a phone

> On 11. Apr 2018, at 21:24, kocio-pl <notifications@github.com> wrote:
> 
> I would like to hear some arguments about source of these doubts, especially when these objects are rendered only on highest level


if it’s rendered as symbol it could lead to “cluttered heaps of icons”, as there are typically many “features” in a small space on playgrounds.

**Comment by HolgerJeromin** [comment]
The main problem is see is from [polarbearing](https://github.com/gravitystorm/openstreetmap-carto/pull/3161#issuecomment-379591654):
The `leisure=playground` icon is in the same class of the `playground=` icons. 

first scenario: playground without `playground=` detail
you zoom in and see the see-saw in every zoom level. Or only till 18 (airport like). This would work

second scenario: playground with only one `playground=slide`
first option:
you zoom in and see the see-saw in every zoom level. At zoom 19 you see a see-saw and a slide. But in the reality there is no see-saw... Not good

second option:
you zoom in and see the see-saw in every zoom level till 18. At zoom 19 you see a slide. 
We swap the wrong see-saw with the correct slide. "where is see-saw gone?" Not good

**Comment by pietervdvn** [comment]
@polarbearing @HolgerJeromin 
Yes, the 'polarbearing' is a problem, but I think it is only small one.

The only 'perfect' option I currently see is a new icon for playgrounds which does not feature a playground equipment icon (e.g. a kid running as seen with fitnesses icons or something similar), although I do not have a very good idea for that and I'm not willing to pick up that battle.

IMHO, showing the seesaw at high zoom levels is not perfect, but not a big issue. I'd rather have a map which shows icons and one to much, then having no icons as well. 

However, hiding the seesaw-icon at high zoom levels is problematic. A playground without playground equipment would suddenly lose all icons. For now, I would let the seesaw in place, even if no seesaw is present.


On the other criticisms: as they icons render only on Z19, I don't think the cluttering of the map will pose any problem.

I'm having a look to the icons again to make them 14px.

And yes, rendering playground outlines would be great, but I'll only be trying that if this icon set goes somewhere.

**Comment by meased** [comment]
Assuming that there was a nice 14x14 icon for each type of equipment, and each of these icons could be interpreted as a playground at lower zoom levels (may be a big assumption), then perhaps we could use the seesaw icon if no other equipment is  tagged, or if equipment is tagged, just pick one and use that as the playground icon for that playground on all zoom levels.

**Comment by kocio-pl** [comment]
Since there are few voices against having this feature at all and I think it would be hard even for a skilled graphic designer to make the icons 14 px, I will close this ticket without merging. Sorry, I hope next time you will have more luck.

However i was talking lately with @dotevo and he said he was trying to create special app exactly for showing playground equipment, so you could talk with him about that.

**Comment by dotevo** [comment]
Ohh... I like this idea :-/ It is very useful for parents. I think the benches look bolder than this.

**Comment by SomeoneElseOSM** [comment]
@pietervdvn I'd be happy to take a pull request at https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/ for symbols to show at zoom 20 and above (that style is designed for around up to zoom 24), but the graphics would still need to look characteristic even when rendered in 14x14 pixels - something that would be tricky with e.g. https://github.com/pietervdvn/openstreetmap-carto/blob/60cdab62b8696ce8d550897a16d078df9a8c2e7e/symbols/playground/swing.svg as it stands.

**Comment by pietervdvn** [comment]
I appreciate all the feedback and its a bit sad that the PR didn't go
through. For now, I do not have the time to follow this up or to redesign
the icons; but perhaps one day I might retry of send a PR to SomeoneElseOSM.

Bye everyone, I'm sure we'll meet again someday soon!


Met vriendelijke groeten,
Pieter Vander Vennet

2018-04-27 23:27 GMT+02:00 SomeoneElseOSM <notifications@github.com>:

**Comment by polarbearing** [comment]
There are specialised maps now that render these features. I doubt it is useful on the general style.

**Comment by JesseWeinstein** [comment]
What are the specialized maps that render this? Got links?

**Comment by niedakh** [comment]
Maybe a parental layer for OSM like we have with OPVN or bike layes could be made? I'd gladly prepare such a PR, if OSM folks were open to including it.

**Comment by SomeoneElseOSM** [comment]
> What are the specialized maps that render this

Offtopic for this repository, but to just answer that question, taginfo pages such as 

    https://taginfo.openstreetmap.org/tags/playground=swing#projects

will show projects that consume particular tags.  Not necessarily all projects, but it will show those who have advertised themselves as doing so.

**Comment by BertMule** [comment]
I was not aware of distinction between playground-**items**.
I thought it was just either playground or some 'playhouse'.

The latter is what I missed in a park, in issue https://github.com/gravitystorm/openstreetmap-carto/issues/4816.

I would be happy if it was just those 2 possibilities, not going into further (too much) detail.

**Pull request closed without merging**
