### PR TITLE
add tourism=apartment

### LINKED ISSUE #401: Add rendering for tourism=apartment
Hello,

there is a new key tourism=apartment. Which is similar to tourism=chalet, but likely to be in more crowded areas. I suggest to render it with the same symbol as tourism=chalet, but starting at lower zoom-level.

thanks, nounours77

### PR DESCRIPTION
**Pull request by polarbearing**
Resolves #401 
Renders from z>=18, i.e. one higher than hotel etc.
On a node: ta_node  On a way: ta_building
Node on residential background: ta_residential_background

### CODE REVIEW

**Comment by kocio-pl** [comment]
Your third test has a different color of the label, but the code and my tests show there's no such problem in reality, both nodes and ways are working as expected.

The only thing I would change is a name of the image - it should be rather `apartment.svg` for simplicity.

**Comment by matkoniecz** [comment]
Is it using transparency?

**Comment by polarbearing** [comment]
I was using tourism_* intentionally so it would not get confused with building=apartments or so. 

As for the icon: I applied the same method than guest_house for creating the halftone bars, this is using fill-opacity in the SVG. The reason is that when mapnik colours the icon, it applies the map-colour to all elements in the SVG equally. So setting an element to solid black, grey, or even white all results in solid tourism-blue. Fill-opacity was also used for other cases in the amenity.mss to faint certain icons, so I assume it would be usable.

**Comment by kocio-pl** [comment]
Since we're not showing any icons for buildings, I don't think it would be a problem to simplify file name.

I think we can use halftones more often, because we need more tools to make icons different and more meaningful. It's hard enough because of small canvas and using basically one color (rarely it's two, like in a bus station). Average icon design time is many months or even years, which is bad enough for me. Luckily Mapnik accepts halftones in SVG, so we can use this feature whenever it's suitable.

**Comment by polarbearing** [comment]
Fine. Are you able to adjust the filename in the merge, or do you need the commit amended?

**Comment by kocio-pl** [comment]
I'm not sure, therefore I prefer if you just do it, please.

**Comment by polarbearing** [comment]
done, and squashed commits

**Comment by kocio-pl** [comment]
Thanks! I will check it soon and if it still works, I'll merge it.

**Comment by polarbearing** [comment]
Thanks. 
Talking about subdirectories, would you see a value in creating further subdirectories under symbols, e.g. one PR per theme? tourism and transport would be good candidates.

**Comment by kocio-pl** [comment]
That makes sense for me. Of course some icons are reused in different categories (like bookshop/library), but I guess anything with more than 10 elements is a natural candidate for making subdirectory.

**Pull request merged**
