### PR TITLE
order placement of city/towns names

### LINKED ISSUE #1083: Bigger town's names occluded by clearly smaller town's names
When I see Vilanova i la Geltrú (south of Barcelona) 
http://www.openstreetmap.org/#map=12/41.22392/1.72511
, a town with 65000 population, and all these tags 

addr:country_code	ES
addr:postcode	08800
admin_level	8
capital	8
ele	25
is_in:country	Spain
is_in:country_code	ES
is_in:municipality	Vilanova i la Geltrú
is_in:province_code	08
name	Vilanova i la Geltrú
name:ca	Vilanova i la Geltrú
name:es	Villanueva y Geltrú
place	town
population	66532
population:date	2009
ref:ine	08307000100
source	Instituto Geográfico Nacional
source:date	2011-06
source:ele	MDT5
source:file	http://centrodedescargas.cnig.es/CentroDescargas/equipamiento/BD_Municipios-Entidades.zip
source:name	Nomenclátor Geográfico de Municipios y Entidades de Población
wikipedia	ca:Vilanova i la Geltrú

It gets hidden by other smaller towns, with less priority like Sant Pere de Ribes

name	Sant Pere de Ribes
name:ca	Sant Pere de Ribes
name:es	San Pedro de Ribas
place	town
population	11904

and same priority but less population as Vilafranca del Penedès

admin_level	8
capital	8
designation	town
ele	229
is_in:country	Spain
is_in:country_code	ES
is_in:municipality	Vilafranca del Penedès
is_in:province_code	08
name	Vilafranca del Penedès
place	town
population	35864
ref:ine	08305000500
source	Institut Cartogràfic de Catalunya, IDESCAT
source:date	2011-06
source:ele	MDT5
source:file	http://www.idescat.cat/cat/idescat/publicacions/cataleg/pdfdocs/nomencat2010.pdf
source:name	Nomenclátor Geográfico de Municipios y Entidades de Población
website	http://www.vilafranca.cat/
wikipedia	ca:Vilafranca del Penedès

When I ask that to the catalan list they say me it happens in other towns like Mataró pop. 116698 vs. Argentona pop. 11544.
All these happens at lower levels than 11.These towns (Vilanova i la Geltrú and Mataró) should start to appear from level 9 http://www.openstreetmap.org/#map=9/41.7734/1.7413 and the smaller towns would start to appear from level 11 http://www.openstreetmap.org/#map=11/41.3552/1.9398 .

But also I notify other thing.As OSM standards tags a city starting from 100000 population http://wiki.openstreetmap.org/wiki/Tag:place%3Dcity (spanish OSM standards also http://wiki.openstreetmap.org/wiki/ES:Key:place )  , in Spain there are so many cities that also be with same tag (town) and same name's size but not the same population (from 10000 to 100000 there are more than 400,some near to others so it is important to make a difference).Is there anyway render would count population to make the name bigger than other towns with less population?

### PR DESCRIPTION
**Pull request by cquest**
use population tag to place city/town names of major cities/towns first.

Fixes #1083

### CODE REVIEW

**Comment by daganzdaanda** [comment]
Just for future reference:
In another issue, Vincent linked to an intersting talk at "SOTM-EU 2014": [Maxim Rylov, Cartographically Plausible Label Placement] (http://sotm-eu.org/en/slots/16)

**Comment by pnorman** [comment]
Closing. Would need rewriting against YAML, and the SQL chosen isn't the best method.

**Comment by math1985** [comment]
> the SQL chosen isn't the best method.

Could you expand on what is wrong with this method? I would like to fix the SQL,  so reopening.

**Comment by pnorman** [comment]
The SQL done for layernotnull is better. But unless @cquest wants to rebase this we need to close **this** PR and open a new one.

**Comment by kocio-pl** [comment]
@cquest: 
>I've been using this population ordering on the OSM-FR tiles and Seattle is there: 

The problem is more complex than the population alone - Seattle is also tagged as a city with importance=national, while Bellevue is just a town. I guess admin_centre can also be a hint for rendering (https://github.com/gravitystorm/openstreetmap-carto/issues/1391). So we have 4 factors of visibility - which should we use and in what order? :
1. place
2. population
3. importance
4. admin_level + admin_centre

**Comment by mrwojo** [comment]
Bellevue was place=city when this was originally written. This is looking at population merely as a tiebreaker when the place tags are equal.

**Comment by kocio-pl** [comment]
But my question is still valid: what should we render if the capital is less populated than a place with conflicting name label? Do we want to use "importance" tag (long time draft)? There can be many cases involving one or more of these tags, so it would be good to know which tags/features labels we want to show on general map.

**Comment by gravitystorm** [comment]
> Do we want to use "importance" tag (long time draft)?

No, absolutely not. That's a completely subjective tag and a hugely bad proposal for tagging.

**Comment by kocio-pl** [comment]
So we're left with "only" 3 more or less objective hinting tags. =} I guess I would treat admin_* tags as the most important hint, then I would check place type (this one is less objective than the rest) and population as the last resort. However that's only my intuition that it would work the best.

**Comment by imagico** [comment]
The usual approach would be to calculate a score based on the various properties that are to be considered.  For example you could use the population as score and multiply it with a factor of for example three in case it is a national capital.  This would mean a larger city is only rendered with preference if its population is more than three times that of the capital.

**Comment by dieterdreist** [comment]
2015-03-24 13:32 GMT+01:00 Andy Allan <notifications@github.com>:

> No, absolutely not. That's a completely subjective tag and a hugely bad
> proposal for tagging.



while I agree, it should be noted that every ranking of cities will be
subjective / colored / biased, including the natural earth dataset we are
currently using. Even if you try your best to set up very objective
scientific rules how to bring in and compare several properties, it can
always be contested how you balance these properties or which aspects you
look at and which you ignore, etc.

**Comment by gravitystorm** [comment]
> every ranking of cities will be subjective / colored / biased

Of course. But the way it works is that the consumers of the data (e.g. openstreetmap-carto) each have their own subjective ranking, based on whatever objective information we choose to use in OSM and/or elsewhere. But that's where the subjective decisions get made, not by the mappers (otherwise chaos and endless edit wars ensue).

Ranking cities by importance is like choosing what roads show up on which zoom levels - it's a subjective issue, for the cartographers to juggle. Each map will choose differently. Thankfully we don't have a "zoom" tag in OSM (e.g. "highway=motorway;zoom=6") and we shouldn't have an "importance" tag either.

**Pull request closed without merging**
