### PR TITLE
Add rendering for man_made=pipeline ways

### LINKED ISSUE #640: Pipeline should be visible
Why are pipelines not rendered?
They are good landmarks.

### PR DESCRIPTION
**Pull request by jeisenbe**
Fixes #640
Related to #3180 and #3179

Changes proposed in this pull request:
- Add rendering of man_made=pipeline ways from z14 when tagged with location=overground, =overhead, =surface, or =outdoor, or with documented bridge=* values.
- Add different renderings for substance=water, substance=oil and substance=gas from z17:

- - gas `#c1c1c1` Lch(78,0,0) 
- - oil `#d7bd93` Lch(78,25,83), 
- - water in `@water-color` (currently `#aad3df`)

There are several "substances" related to heat, like "steam", "hot water" and "heat" but no consensus yet, and no other substances are common yet.

- Add text label for named pipelines from z17
- Change aerialway minimum-distance to margin and repeat-distance (The property minimum-distance is deprecated and cannot be used with the new properties margin and repeat-distance)

This feature is rendering in the aerialways layers, so that above-ground pipelines will render above roads but below bridges. 

Since the last test images in #640 I've adjusted the rendering to make the line thinner at low zoom levels and to make the outline thinner at higher zoom levels. 

Test rendering with links to the example places:

### Heating pipelines in Latvia:
- https://www.openstreetmap.org/#map=15/56.9186/24.2719
- No sustance shown for these still (tagging has not settled on one way to tag steam/hot_water/heating pipes)
z15
pipeline-z15-latvia-heating-pipes-15:56 9186:24 2719

z16
pipeline-z16-latvia-heating-pipes

z17
pipeline-z17-latvia-heating-pipes

z18
pipeline-z18-latvia-heating-pipes-18:56 91964:24 26579

z19
pipeline-z19-latvia-heating-pipes-19

### Other industrial pipelines in Latvia
https://www.openstreetmap.org/#map=14/56.9818/24.1827
z14
pipeline-z14-latvia-14:56 9818:24 1827

### Oil pipelines in Latvia:
https://www.openstreetmap.org/#map=17/57.04748/24.08014
z14
pipeline-z14-latvia-port-14:57 0453:24 0982

z15
pipeline-z15-latvia-oil

z16
pipeline-oil-z16-latvia

z17 - oil color now visible
pipeline-oil-z17-latvia

z19 
pipeline-oil-19:57 04772:24 07960

### Water pipeline, Corsica
https://www.openstreetmap.org/#map=17/41.70543/9.05265
z14
z14-water-pipeline-corsica

z16
z16-water-pipeline-corsica

z17
z17-water-pipeline-corsica

z18
z18-water-pipeline-corsica

z19
z19-water-pipleline-corsica

### Gas pipeline, Singapore
https://www.openstreetmap.org/#map=17/1.2313/103.7527
z17
pulau-busing-z17

z18
pulau-busing-z18

z19
pulau-busing-z19

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Colors enclosed in backticks gets an rendering on github:
gas `#c1c1c1`
oil `#d7bd93`

**Comment by Adamant36** [comment]
Thanks for doing the PR on this. I was planning on doing it, but I got busy with other things. It looks good though. The rendering on higher zoom levels doesn't look as bad as I remember either.

**Comment by kocio-pl** [comment]
That looks OK for me.

**Comment by jeisenbe** [comment]
> The rendering on higher zoom levels doesn't look as bad as I remember either.

I've adjusted it slightly since then: the lines are about 1/3rd narrower than previously.

**Comment by imagico** [comment]
I think this is too heavy in particular at the lower zoom levels compared to other features - i.e. roads, paths and railways.

I would also try reducing the gaps between the segments - they look almost like bridges over some linear feature to me.

**Comment by jeisenbe** [comment]
> I think this is too heavy in particular at the lower zoom levels compared to other features - i.e. roads, paths and railways.

It needs to be a thinner line or a lighter color? Is this at z14 and z15 only, or also at z16?

> try reducing the gaps between the segments

The gaps in the same direction as the way? Currently they are 1 pixel wide at all zoom levels. Perhaps that is okay at z18 and z19, but I can try reducing the gap to 0.5 pixel at lower zoom levels. 

I do think that the "pipeline-segment" shape helps with recoginizing that these are pipelines rather than some sort of highway or railway or waterway.

**Comment by imagico** [comment]
> It needs to be a thinner line or a lighter color? Is this at z14 and z15 only, or also at z16?

I think the problem is strongest at z14 obviously but it is still an issue at z16 - less because of the drawing width but more because of the strong color.  I would probably not draw a centerline at z16 because that is mostly visual noise anyway.

> The gaps in the same direction as the way? Currently they are 1 pixel wide at all zoom levels. 

Your dasharray has a one pixel gap at start and end leading to a two pixel gap as i read it.

> I do think that the "pipeline-segment" shape helps with recoginizing that these are pipelines rather than some sort of highway or railway or waterway.

I think it is a concept that can work - but it is visually heavy which makes adjusting it in a way that balances with the rest of the map somewhat tricky.

**Comment by jeisenbe** [comment]
OK, I've made some changes. I realize now that this was still using the same dark gray color as aerialways and mainline railways, rather than something more similar to the minor types of railways. 

So I've changed the line color from `#707070` to `#909090` - this is just a bit darker than `railway=preserved`/`railway=subway`/`railway=miniature` and highway casings.

I've also tried adjusting the width of the gap between pipeline "segments", but if we make it 1 pixel the gap is too blurry when the pipeline is on a diagonal (e.g. NW to SE), at standard resolution. If we were using 2x resolution (retina tiles) then this could be an option.

New tests:
z14
z14-pipeline-test-4

z15
z15-pipeline-test-4

z16
z16-pipeline-test-4

z17
z17-pipeline-test-4

Water pipeline, Corsica:
https://www.openstreetmap.org/#map=17/41.70543/9.05265
z14
pipeline-water-corsica-after-3-z14

z15
pipeline-water-corsica-after-3-z15

z16
pipeline-water-corsica-after-4-z16

z17
pipeline-water-corsica-after-3-z17

z18
pipeline-water-corsica-after-3-z18

z19
pipeline-water-corsica-after-3-z19

Retina (2x resolution) versions:
z14 at 2x resolution
pipeline-water-corsica-after-3-z14-export2x

z16 at 2x resolution
pipeline-water-corsica-after-4-z16-export2x

Wow, changing to 2x resolution looks so much better.

**Comment by jeisenbe** [comment]
Industrial pipelines (gas and unspecified) in Singapore port area.

- This is right near the equator, so features are almost twice as close to each other on the rendered map as they would be in northern Europe.

z16 - Jurong Island - https://www.openstreetmap.org/#map=14/1.2660/103.6744
z16-pipelines-4-jurong-island

z15
z15-pipelines-4-jurong-island

z14
z14-pipelines-4-jurong-island

z16 - Pulau Busing
z16-pipelines-4-pulau-busing

z15
z15-pipelines-4-pulau-busing

z14
z14-pipelines-4-pulau-busing

Water pipeline in Singapore
https://www.openstreetmap.org/#map=17/1.41629/103.72429

z18
z18-pipeline-water-singapore

z17
z17-pipeline-water-singapore

z16
z16-pipeline-water-singapore

z15
z15-pipeline-water-singapore

z14
z14-pipeline-water-singapore

**Comment by jeisenbe** [comment]
Oil pipelines in port terminal, Riga, Latvia:
https://www.openstreetmap.org/#map=16/57.0474/24.0800

z17
z17-pipeline-oil-latvia-4

z16
z16-pipeline-oil-latvia-4

z15
z15-pipeline-oil-latvia-4

z14
z14-pipeline-oil-latvia-4


Closely parallel pipelines (heating, steam/hot water) in industrial areas of Riga, Latvia:
- https://www.openstreetmap.org/#map=15/56.9232/24.2002
- These are only about 2 or 3 meters apart, center to center.

z18
z18-pipelines-parallel-latvia-4

z17
z17-pipelines-parallel-latvia-4

z16
z16-pipelines-parallel-latvia-4

z15
z15-pipelines-parallel-latvia-4

z14
z14-pipelines-parallel-latvia-4


Retina tiles (Exported at 2x):
z15 at 2x - somewhat clearer
z15-pipelines-parallel-latvia-4-export-2x

z14 at 2x
z14-pipelines-parallel-latvia-4-export-2x

**Comment by jeisenbe** [comment]
Any comments about the colors for the 3 types of substances that will be rendered?

The centerline at z17 to z19 is in `land-color` when the `substance` is not tagged, or if it is a rare value of `substance`.

- - gas `#c1c1c1` Lch(78,0,0) - gray
- - oil `#d7bd93` Lch(78,25,83), - orange-brown
- - water in `@water-color` (currently `#aad3df`) - blue

I tried to look up common colors used to identify gas vs oil pipeline, but generally they use the same symbols for flammable liquids / gases: yellow or brown. 

Another option would be to use a low-chroma purple instead of gray for gas.

I tried yellow, but this would be a little too similar to highway=secondary

**Comment by kocio-pl** [comment]
At z14 and z15 the spaces between segments aren't too visible for me, so maybe they could be a bit bigger or the segment endings could be wider? Other than that it looks OK to me.

**Comment by jeisenbe** [comment]
Above (https://github.com/gravitystorm/openstreetmap-carto/pull/4070#issuecomment-598142985) there was a request to reduce the gaps between segments, rather than increase them, and also to make the line less prominent. 

So perhaps the current rendering is the best I can do, as a compromise?

**Comment by kocio-pl** [comment]
I consider it a minor problem, so I don't mind merging it. We can tune it later if needed.

**Comment by jeisenbe** [comment]
@pnorman Is it ok if I use "rebase and merge"? This will keep the history, but organize it all in one part of the log, at the moment it is merged.

**Comment by pnorman** [comment]
> @pnorman Is it ok if I use "rebase and merge"? This will keep the history, but organize it all in one part of the log, at the moment it is merged.

If you want to, but there's no need to

**Comment by jeisenbe** [comment]
Here's examples of the name label rendering, which starts at z17:

https://www.openstreetmap.org/#map=17/44.80862/6.56654
pipeline-name-17:44 80862:6 56654

https://www.openstreetmap.org/#map=17/-33.50165/138.60810
pipeline-name-17:-33 50165:138 60810

https://www.openstreetmap.org/#map=18/54.73891/-5.72469
pipeline-name-18:54 73891:-5 72469

**Pull request merged**
