### PR TITLE
Adding shop=toys icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1414.

toys-after-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
Not bad. The icon has a small stroke, which should be removed because the shop colour does not get applied to it. Some things that come to my mind: maybe have the ears more distinct, add a round hole for an "eye" and make the tail look more horse-like.

**Comment by kocio-pl** [comment]
toys-after-z19-nebulon

I knew there's something strange! - but was too tired already to check the stroke...

Any bigger ears will destroy the silhouette of the SVG (see my remarks with the shop=chemist) and even too big eye on SVG is not to be spotted on PNG, so I didn't touch it. Tail is thicker, but I'm afraid that the space below it will disappear - for now it's acceptable.

**Comment by nebulon42** [comment]
Looks better, now the bottom is a bit fragile but I didn't check how much compromises are necessary to fit it into the small rectangle.

**Comment by daganzdaanda** [comment]
Overall a really nice icon! Maybe the bottom quarter-circle could be thicker, but that's not important.

**Comment by kocio-pl** [comment]
Even better, thanks! - toys-14

**Comment by kocio-pl** [comment]
I still don't know how to squash latest commits into one... Sorry for the mess. 

git reset --hard HEAD~ + git merge --squash HEAD@{1} + git commit + git push 

gives me the information that origin and local branches have diverged, and after pulling git push makes another commits in origin....

**Comment by kocio-pl** [comment]
@nebulon42 I was not aware you're making [Osmic version of this icon](https://github.com/nebulon42/osmic/blob/master/shop/toys-14.svg) - don't you want to get it here? Mine is OK, but yours is probably better and it fits into the style of some others, so I would prefer it for better visual consistency.

**Comment by nebulon42** [comment]
When I looked at the horse in detail I found myself re-drawing it, but I don't plan to make additional icon PRs for now other than replacing existing symbols. If you feel it fits better, feel free to use it!

**Comment by kocio-pl** [comment]
I will stay with my latest icon, because I forgot to check PNG and while Osmic SVG is clearly better, the resulting PNG is harder to recognize:

toys-z19-bold

**Comment by nebulon42** [comment]
How comes PNG into play here?

**Comment by kocio-pl** [comment]
SVGs are converted into raster form, PNG is just a form of showing it: toys-14-osmic - especially head is too small for me.

**Pull request merged**
