### PR TITLE
display communication towers

### PR DESCRIPTION
**Pull request by kolesar-andras**
Currently only masts are rendered. Towers tagged this way are hidden:

	man_made=tower
	tower:type=communication

I have included them to queries and css.

### CODE REVIEW

**Comment by math1985** [comment]
It seems we have too many of them to render them at z17, or maybe at all:

http://overpass-turbo.eu/s/89B

What is in OSM the difference between a mast and a tower?

**Comment by kolesar-andras** [comment]
Mobile base stations in the centre of Amsterdam seem to be tagged improperly:

    height=7
    man_made=tower
    technology=GSM 900
    tower:type=communication
    
According to [derstefan's proposal](http://wiki.openstreetmap.org/wiki/Proposed_features/Telecommunications_tower) base stations on building roofs should be tagged this way:

    height=7
	communication:mobile_phone=gsm
	
I have just started to tag base stations without own tower/mast with a location tag:

	location=roof
	location=church
	
See base stations in [Budapest](http://overpass-turbo.eu/s/89Q), only a very few are on a tower or mast. Check the same in [Heidelberg](http://overpass-turbo.eu/s/89T).

The difference between a tower ot mast is the architecture. A [mast](http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast) is only a metal pipe or concrete column with small diameter, below 10-15 meters. All higher are real [towers ](http://wiki.openstreetmap.org/wiki/Proposed_features/Communications_tower) built with lattice structure.

Base stations in Amsterdam are mapped 5 years ago. User is still active, we may ask him to tag them according to current practice.

**Comment by math1985** [comment]
According to the wiki, a man_made=mast is 'a small tower of only a few meters'. I think a small tower of only a few metres is relevant enough for a general purpose map (compare lampposts). So I will reject this pull request. Thank you for the effort though @kolesar-andras!

**Comment by dieterdreist** [comment]
2015-03-16 11:29 GMT+01:00 math1985 <notifications@github.com>:

> According to the wiki, a man_made=mast is 'a small tower of only a few
> meters'. I think a small tower of only a few metres is relevant enough for
> a general purpose map (compare lampposts). So I will reject this pull
> request.



this is disputed, see recent discussions e.g. on tagging ML. From the wiki
you can see that there was appearantly no proposal for this tag and that
this page is mainly written by user Derstefan
http://wiki.openstreetmap.org/w/index.php?title=Tag:man_made%3Dmast&oldid=760381
AFAIR the current wiki definition wasn't discussed before adding it. The
German translation also doesn't state the "mast" has to be small (OK, not
relevant, as it should be a translation of the English one).

**Comment by kolesar-andras** [comment]
Many communication towers/masts are tagged properly. For example in Switzerland 269 nodes are tagged this way:

    man_made=tower
    tower:type=communication

These are unfortunately not shown on mapnik output. See an [example](http://www.openstreetmap.org/node/3256458390). By rejecting this pull request it seems you want to keep them hidden. Why?

**Comment by dieterdreist** [comment]
2015-03-16 11:45 GMT+01:00 Kolesár András <notifications@github.com>:

> Many communication towers/masts are tagged properly. For example in
> Switzerland 269 nodes are tagged this way:
>
> man_made=tower
> tower:type=communication
>
>

do these describe towers or masts?

**Comment by kolesar-andras** [comment]
Switzerland was a bad example: most of them are masts (solid metal pipes). Tagging of these does not follow wiki guidelines. These small masts should be tagged as man_made=mast. They are short: only 10-20 meters. See on Google StreetView:

* [osm](http://www.openstreetmap.org/way/318559969) | [streetview](http://goo.gl/maps/XuDP7)
* [osm](http://www.openstreetmap.org/node/2914512557) | [streetview](http://goo.gl/maps/SjHrz)
* [osm](http://www.openstreetmap.org/node/2630643785) | [streetview](http://goo.gl/maps/cyzKg)

In Hungary most mobile antennas are on towers. Examples:

* [osm](http://www.openstreetmap.org/node/3376693710) | [streetview](http://goo.gl/maps/LY06F) (compare height to the water tower)
* [osm](http://www.openstreetmap.org/node/3306027323) | [streetview](http://goo.gl/maps/4W2EV) (compare height to electric towers)
* [osm](http://www.openstreetmap.org/node/3306027327) | [streetview](http://goo.gl/maps/xQYzl) (compare height to electric tower)

As you can see, these lattice towers are much higher than masts: about 50 meters high.

Current mapnik output is inconsistent. Displays masts but hides much higher towers. My solution displays them all. Another solution would hide masts. (I'm sure some people would protest against hiding masts, just like me about towers.)

**Comment by math1985** [comment]
Sorry, I confused mast and tower in my rationale to close this issue.

If towers are typically higher than masts, it doesn't make sense to render masts and hide towers.

I have [asked the Dutch community](http://forum.openstreetmap.org/viewtopic.php?pid=491530#p491530) to change their tagging scheme.

Is there any native English speaker who can comment on the difference between mast and tower in everyday language?

**Comment by RAytoun** [comment]
See under 'mast or tower' in Wikipedia.

A very loose guide would be
A tower is a self supporting structure while a mast is supported (using
guys or stays to maintain it's stability).

But you can have a mast on top of a tower or building. (A tower structure
with the antenna mast attached to the top of the tower or building and
supported with stays).

Just to help confuse things

**Comment by kolesar-andras** [comment]
Masts used for mobile communications are mostly self-supported, see streetview links above. Some very high lattice towers are supported, see [this famous tower](http://goo.gl/maps/VUOX5) or a [shorter nearby](http://goo.gl/maps/4qhT1). Being supported is not the best way to distinguish them.

See definition of words in the Oxford dictionary:

[tower](http://www.oxforddictionaries.com/definition/english/tower): A tall narrow building, either free-standing or forming part of a building such as a church or castle. [with modifier] A tall structure that houses machinery, operators, etc. "a control tower".

[mast](http://www.oxforddictionaries.com/definition/english/mast): A tall upright post on land, especially a flagpole or a television or radio transmitter.

The example sentences above show both words are used for all kind of telecommunication buildings.

If you see count of search results in a popular search engine, towers are mentioned ten times more than masts.

* "telecommunication tower" 338k
* "telecommunication mast" 31k
* "communication tower" 357k
* "communication mast" 21k
* "mobile tower" 400k
* "mobile mast" 58k
* "cell phone tower" 386k
* "cell phone mast" 25k

That's why many people tag these objects as towers.

Images for these search terms are generally the same, many lattice towers and a few solid masts, independent from the word searched.

A mast is solid, see synonyms: pole, spar, post. That's why I tag a tall upright post on land as a mast. Lattice structures are towers for me.

**Comment by dieterdreist** [comment]
> Am 16.03.2015 um 13:43 schrieb Kolesár András <notifications@github.com>:
> 
> As you can see, these lattice towers are much higher than masts: about 50 meters high.


actually some masts are several hundred meters high...
250 m Rugby radio mast
http://en.m.wikipedia.org/wiki/Rugby_Radio_Station

and often you'll find a mast atop a tower, like this 98m high mast http://de.m.wikipedia.org/wiki/Datei:Bettingen_-_Fernsehturm_St._Chrischona5.jpg

**Comment by dieterdreist** [comment]
> Am 16.03.2015 um 16:20 schrieb Kolesár András <notifications@github.com>:
> 
> Images for these search terms are generally the same, many lattice towers and a few solid masts, independent from the word searched.
> 
> A mast is solid, see synonyms: pole, spar, post. That's why I tag a tall upright post on land as a mast. Lattice structures are towers for me.
> 


if it's a structure accessible for people, eg with a restaurant or viewing deck it will always be a tower, while a mast is a big pole
and not accessible unless for maintenance

**Comment by kolesar-andras** [comment]
I meant "metal pipe" (solid from seen outside) mobile masts with 10-20 meter height. Rugby Radio Station was actually a lattice structure.

Most mobile towers and masts are not accessible, closed with fence and forbidden to climb. It does not depend on building structure.

**Comment by matkoniecz** [comment]
> this is disputed, see recent discussions e.g. on tagging ML.

@dieterdreist  @kolesar-andras Maybe wiki should be changed? Or at least contain information about controversy?

My opinion is that man_made=mast is not usable at this moment due to conflict of Wiki and different tagging, and in that situation should not be rendered.

**Comment by jidanni** [comment]
I finally found a way to get a cell tower rendered,
following the example on 
http://wiki.openstreetmap.org/wiki/Tag:man_made%3Dmast#Mobile_phone
I was able to get it rendered at magnification 17 and 18 at least. Disappearing again at 19.

**Comment by martinum4** [comment]
still think this is not solved yet can't see the towers on the rendered map, but the masts appear...
Why not render man_made=mast not at all and only render tower:type=communication with the symbol the mast currently has? that would also solve the issue of lighting towers being rendered as communication towers (http://www.openstreetmap.org/node/3798790703 ).

**Comment by jidanni** [comment]
Please render as many types of these things as possible. In the countryside at least they are very important for orientation, being the only noticeable item on the horizon often no matter how short.

**Comment by kolesar-andras** [comment]
I have waited a year for answer from [Stefan de Konink](https://www.openstreetmap.org/user/Stefan%20de%20Konink) who imported several thousands of mobile base stations from Antennebureau. I have got no answer from him.

These objects made my pull request rejected, @math1985 have linked an overpass query in Amsterdam: http://overpass-turbo.eu/s/89B

I have checked a node at [Paulus Potterstraat 40](http://www.openstreetmap.org/node/599591957). This is not a tower, this is an antenna on roof, clearly visible on [Google StreetView](http://goo.gl/maps/Ys7E9).

Now I'm going to remove man_made=tower tag from these objects. Do you agree? Will @math1985 accept my pull request for rendering man_made=tower with tower:type=communication tag?

**Comment by martinum4** [comment]
@kolesar-andras Well, it definitly isn't a tower but it could be a man_made=mast, not really high (maybe 3 meters max) man_made=antenna kind implies for me that it is just ONE antenna, not multiple ones fixed at one mast, also the mast is missing the layer=1 here because it is on top of a building

**Pull request closed without merging**
