### PR TITLE
Adding shop=chemist icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1528.

chemist-after

Check carefully as I'm newbie in PRs.

### CODE REVIEW

**Comment by nebulon42** [comment]
You should squash commits into one (maybe just before merge) and also mention the resolved issue in your commit message so it gets automatically closed (see https://help.github.com/articles/closing-issues-via-commit-messages/).

Please add a preview.

**Comment by kocio-pl** [comment]
Preview added.

How to squash them? I thought git rebase will do it, but now I do it and no such effect appears.

**Comment by nebulon42** [comment]
Try http://stackoverflow.com/a/5189600

**Comment by kocio-pl** [comment]
$ git rebase -i master
warning: Cannot merge binary files: project.mml (HEAD vs. 897bdcf... Icon and YAML for shop=chemist)
error: could not apply 897bdcf... Icon and YAML for shop=chemist

**Comment by nebulon42** [comment]
Have you edited project files more often than once? Maybe that's the reason. Have you force pushed?

Regarding the icon: This one is a bit blurry, especially at the bottom of the tube and at the brush head. I suggest making the brush handle thicker and replace the individual parts of the head by a solid part with zigzag outline on the left. Maybe a more straight tube could help against blurriness. On close inspection of the file I saw that you are using very subtle arcs that are unlikely to be visible at small sizes at all, either more curved or not curved at all would be better. Your nodes could be more aligned to the pixel grid.

**Comment by kocio-pl** [comment]
New version:

chemist-after-nebulon

1. Brush head redone and handle is thicker. I liked the previous version because the head was visibly softer (like the material it is made of) and the handle had better proportion, but now it's more visible, so this is acceptable.

2. I see nothing wrong with the tube and it seems to me (previous session and today also) it can be only worse: straight tube (1 px less from both sides) is just a rectangle and it's harder to recognize, wider a bit and we loose the proper ratio.

3. Arcs was so subtle that it made sense only when looking at higher sizes - and that made it look better with SVG not damaging the small PNG. Now it's more aligned, but I don't see the real improvement on PNG, while SVG looks much worse to me now (head zigzag looks also worse here). I don't know if we don't care too much for SVGs, but I would like it to also get some love, because what's the use of trying to have them rather then PNGs then?

**Comment by nebulon42** [comment]
Definitely an improvement! The tube bottom has a bit of blur but let's leave it at that for now.

**Comment by daganzdaanda** [comment]
We're really deep in nit-picking territory here ;) but I'd combine the toothbrush with the fat handle and the first kind of brush-hairs. Like you said, the anti-alias gives a semi-transparent look and for this part it works well for me (same as in shop=books)

**Comment by kocio-pl** [comment]
Probably the best:

chemist-after-daganzdaanda

> We're really deep in nit-picking territory here ;)

Well said. =} But that's good - it means to me that overall shape works and it's fun to test other people ideas, and sometimes they are really better or at least interesting and just different.

**Pull request merged**
