### PR TITLE
Add icons for man_made=storage_tank, man_made=silo

### LINKED ISSUE #588: Suggestion for man_made=storage_tank
The below is my suggestion for rendering the feature man_made=storage_tank in main OSM layer:
storage_tank

### LINKED ISSUE #2909: `man_made=silo` is not being rendered
I recently changed a lot of silos and storage tanks along Aalborg Harbour from `building=yes` to `man_made=silo` and `man_made=storage_tank`, because I find that a more accurate reflection of what is actually there. However, now they are no longer rendered on openstreetmap.org. Why does it not render these - physically quite prominent - features?

### PR DESCRIPTION
**Pull request by Adamant36**
This PR adds icons for both man_made=storage_tank and man_made=silo. Closes #588, closes #2909 

storage tank
https://www.openstreetmap.org/#map=19/37.97589/-122.66540 (node)
storage tank node
https://www.openstreetmap.org/#map=19/37.94376/-122.51119 (way)
storage tank way

Silo 
https://www.openstreetmap.org/#map=19/38.17840/-122.81463 (node)
silo node
https://www.openstreetmap.org/#map=19/38.21552/-122.60608 (way)
silo way

### CODE REVIEW

**Comment by kocio-pl** [comment]
Icon shape looks OK for me, but I'm not sure that z17+ is not too early for such items.

There are a lot of such objects in OSM database:
taghistory 43

**Comment by Adamant36** [comment]
I was actually thinking that. What zoom level do you think would be good instead?

**Comment by kocio-pl** [comment]
I have already proposed z18+ - see https://github.com/gravitystorm/openstreetmap-carto/issues/2909#issuecomment-390166279. It should be safer, but maybe someone wants to look closer at this problem.

**Comment by Adamant36** [comment]
Oh, my bad. I didn't see your comment. Z18+ is the obvious zoom level though. I updated it.

**Comment by kocio-pl** [comment]
There are some conflicts now after merging #3376, please resolve them.

**Comment by kocio-pl** [comment]
Travis is right :smile:  : 

`amenity-points.mss:3040:0 missing closing `}``

When you look at this part:

```
    [feature = 'man_made_chimney'] { 
    [feature = 'man_made_water_works'],
    [feature = 'man_made_wastewater_plant'] { 
```

you will notice that after chimney line there is a bracket instead of colon.

This is why I insist on checking every change with rendering test. You would know there's a problem if you would fire a Kosmtik just in case. :smile: This kind of errors is very common and simple rendering test is enough to catch them.

**Comment by kocio-pl** [comment]
You can simply pull the changes to your local repository (as I did) and then test it. I advise to always check the code changes if possible.

**Comment by Adamant36** [comment]
Hhhhmmm, for some reason I assumed that if I did that it wouldn't pull the merge conflict with it for some reason. Since it would be pulling from the branch or something and wouldn't fast forward whatever changes there were in meantime. Or it would just pull from the upstream repository and screw everything up somehow. I'll have to try that next time though. Its a lot to keep track of.

**Comment by kocio-pl** [comment]
If you have local branch for that, you can always try to pull. And if you're not feeling safe, you can make another branch of this branch just to test it.

However I understand the difficulty of playing with different problems when you just want to update the code. Now I understand git better in the scope of this repo, but it took me some time to learn it.

**Comment by Adamant36** [comment]
OK. Good to know there is that option. It can definitely feel like I'm in way over my head sometimes. Especially with a bunch of different branches and PRs going at once. At least it was a fairly simple problem this time though.

**Comment by kocio-pl** [comment]
Thanks, this is working good. z18+ looks like good initial level since some of them can be quite small, another thing for the future might be color tuning, since they are quite heavy/dark too.

**Comment by Adamant36** [comment]
@kocio-pl, your welcome. Hey, whats the website for showing the chart of tag usage like you have in the message above? I can't seem to find a link to it anywhere.

**Comment by kocio-pl** [comment]
It's from this service:

http://taghistory.raifer.tech

**Pull request merged**
