### PR TITLE
Render `leisure=dance`

### PR DESCRIPTION
**Pull request by wyskoj**
## Changes proposed in this pull request:
**Add rendering for [`leisure=dance`](https://wiki.openstreetmap.org/wiki/Tag:leisure%3Ddance)**

`lesiure=dance` [is used 11k times](https://taginfo.openstreetmap.org/tags/leisure%3Ddance#overview) across a wide geographic area, and it [has been approved](https://wiki.openstreetmap.org/wiki/Proposal:Dance) since 2009.

## Icon

I designed a simple icon.

dance

I did my best to follow as many icon style guidelines as possible, most notably aligning to a 14x14 pixel grid:

image

### [Location 1](https://www.openstreetmap.org/way/1061553113)

On a way with `building=*`.

#### Before

_No rendering (name is rendered with building)._

image

##### z19

image

##### z18

image

##### z17

image

##### <=z16

_No render, consistent with other `leisure` and `amenity` features._

### [Location 2](https://www.openstreetmap.org/node/6928807436)

On a node.

#### Before

_No rendering._

image

##### z19

image

##### z18

_Text occluded by other features._

image

##### z17

image

_Icon happens to have precedent here._

##### <=z16

_No render, consistent with other `leisure` and `amenity` features._

## Notes
- Style is grouped in with `leisure=sauna` for ease of implementation. I don't have a strong preference for this feature's color, but I think it makes sense since most other `leisure` features use this color.

Thanks for considering my PR!

### CODE REVIEW

**Comment by imagico** [comment]
Thanks for the pull request.

I think the tag is suitable for rendering, no competing tag with comparable adoption, geographically broad use by individual mappers in different parts of the world, well established over several years.

The symbol design principle seems suitable as well - dancing human figure and music notes to avoid confusion with sports.

I am a bit wary about the readability of the symbol because of the elements being very small.  One thing that might help is avoiding the bottom diagonal line formed by the feet of the figure and the music notes - which could be misread as the two symbols components forming a geometric unit.  Maybe you could try re-arranging - mirroring/swapping the two elements in some form that disrupts this line.

Side note: I generally dislike the use of green for social amenity symbols because IMO green should be reserved for vegetation related features.  But that is not a matter significant for this PR, it is a more general comment.

**Comment by dch0ph** [comment]
Nice job!

I agree that the symbol works - figure + note unlikely to be confused with a sport symbol. The musical notes are quite small and not instantly recognizable. You could try using a mitre join for the top bar (rather than rounded corners). A thicker top bar (1.5 px), as in conventional musical notation, might also help?

**Comment by wyskoj** [comment]
> Maybe you could try re-arranging - mirroring/swapping the two elements in some form that disrupts this line.

> You could try using a mitre join for the top bar (rather than rounded corners). A thicker top bar (1.5 px), as in conventional musical notation, might also help?

I've enacted both of these suggestions, and I think they improve readability.

image

> I generally dislike the use of green for social amenity symbols because IMO green should be reserved for vegetation related features.

I'm happy to set a different color if there's one you prefer—should be a simple fix.

**Comment by imagico** [comment]
Merging this to be included in the next release, sorry for the long wait time.  The use of green color for not vegetation related symbols is a different and more general issue, which will need to be discussed separately.

Nice work on the design.

**Pull request merged**
