### PR TITLE
Render administrative boundary text labels for relations only

### LINKED ISSUE #2663: Administrative boundary tagging on closed ways
I was inspecting the changes in rendering due to fixing #59 a bit further and wonder if we correctly interpret boundary tags on closed ways.  I am in particular thinking about cases like

http://www.openstreetmap.org/way/162691988

and

http://www.openstreetmap.org/way/10364857

We interpret these as administrative unit areas (see the labels) and not just as administrative boundary lines although the mapper clearly intended the administrative boundary tagging to apply to the line and the name tag only to the place=island - and as i interpret them tagging conventions say that administrative units have to be boundary relations and ways with boundary tags are always just boundary lines.

I know this kind of tagging is inherently ambiguous and should probably be avoided (by creating a multipolygon relation for the island) but IMO ideally we should require administrative unit areas to be boundary relations.

### LINKED ISSUE #3761: Text labels display without borders for administrative boundaries mapped as closed ways
### Expected behavior:
- Text labels should only display when the border lines are also visible on an administrative boundary
- Since borders are only rendered as lines when tagged on relations (with `osm_id < 0`), this filter should also be used for `admin-text`, `country-names` and `state-names`.

### Actual behavior
- `admin-text, `country-names` and `state-names` are rendered from both closed ways and relations. 
- Some closed ways tagged boundary=administrative are imported as polygons. This happens when the closed way is also tagged with a key that is imported as a polygon, for example place = island, islet, hamlet, archipelago etc, or landuse = residential / meadow etc
- These polygons then have text labels rendered. 
- In the case countries and provinces (admin_level = 2 and 4) the label is rendered at the center of the polygon, with the name that is used on the polygon. This means that an island, islet or archipelago name can appear in country or province text style at lower zoom levels, and along the border in higher zoom levels.
- In the case of smaller administrative boundaries tagged with landuse or place=village/town etc, the administrative boundary name is rendered along the boundary, but there is no line rendering. This leads to confusing, floating labels without an associated geometry.

### Links and screenshots illustrating the problem
z16 Keaukaha Hawaiian Homeland, Hawaii USA
- closed way tagged landuse=residential + boundary=administrative + admin_level=5
z16-keaukaha-closed-way-residential

z15 Delmar, Delaware, USA
- closed way tagged place=town + boundary=administrative + admin_level=8
z15-delmar-before

z17 Woodside, Delaware USA
- closed way tagged place=town + boundary=administrative + admin_level=8
z17-woodside-before

z16 Ilheus Das Cabras, Azores, Portugal
- closed ways tagged `natural=coastline`+ `place=islet` + `name=Ilheus das Cabras` + `boundary=administrative` + `admin_level=4` (the administrative boundary of the Azores province follows the coastline)
- This renders as if Ilheas das Cabras were the name of a province! The real province name also renders properly from a relation with `type=boundary` which has this way as a member. 
z16-ilheus-das-cabras-before
z18 

z16 Ilheau Da Praia, Azores, Portugal
- Same as the other islets above; coastline is tagged as an islet and also boundary=administrative
z16
z16-ilheu-da-praia-before
z18
z18-ilheu-da-praia-before

### PR DESCRIPTION
**Pull request by jeisenbe**
### Fixes #3761 and Fixes #2663

# Changes proposed in this pull request:
- Render text labels along borders of admin boundary relations only, not from closed ways
- Render name labels for country and province/state from relations only, not from closed ways

### Explanation:
- Currently the border lines are only rendered for borders mapped as relations (with `osm_id < 0`)
- But the text labels along the borders are rendered for both relations and closed ways, in the case when the closed way is also tagged with a key that is imported as a polygon, such as `place=island` or `landuse=residential`. 
- This commit adds a filter for "AND osm_id < 0" to the admin-text layer, so that the text labels do not appear in the rare occasions when an administrative boundary is mapped as a closed way instead of a relation

# Test renderings:

## Keaukaha Hawaiian Homeland, Hawaii USA
https://www.openstreetmap.org/way/146660105/
- closed way tagged landuse=residential + boundary=administrative + admin_level=5
z16 Before
z16-keaukaha-closed-way-residential
After
z16-keaukaha-after

## Ilheus Das Cabras, Azores, Portugal
https://www.openstreetmap.org/way/157531901/
- closed ways tagged `natural=coastline`+ `place=islet` + `name=Ilheus das Cabras` + `boundary=administrative` + `admin_level=4` (the administrative boundary of the Azores province follows the coastline)
- This renders as if Ilheas das Cabras were the name of a province! The real province name also renders properly from a relation with `type=boundary` which has this way as a member. 
z16 Before
z16-ilheus-das-cabras-before
After
z16-ilheu-das-cabras-after

z18 Before
z18-ilheus-das-cabras-before
After
z18-ilheus-das-cabras-after

### CODE REVIEW

**Comment by jeisenbe** [comment]
Is anyone available to review this PR? 

I would like to submit other improvements to the administrative boundaries, but I can't until this one is merged.

**Comment by matkoniecz** [comment]
It also turns #713 into a declined request.

**Comment by matkoniecz** [comment]
I edited top post to fix https://www.openstreetmap.org/way/way/146660105/ link

**Comment by imagico** [comment]
Just noticed this had not been merged yet, sorry for the delay.

**Pull request merged**
