### PR TITLE
render wayside_shrine the same way as wayside_cross

### PR DESCRIPTION
**Pull request by xsuchy**
Wayside shrine is just more robust form of wayside cross.
Since it is bigger and more visible in real life, it is shame
that we display cross and not shrine.
Until somebody provides better icon, it is good enough to render it
as cross (as sometime it is called by local people cross anyway).

See
http://wiki.openstreetmap.org/wiki/Tag:historic=wayside_shrine
http://wiki.openstreetmap.org/wiki/Tag:historic%3Dwayside_cross

### CODE REVIEW

**Comment by matkoniecz** [comment]
What about shrines for other religions?

**Comment by math1985** [comment]
@xsuchy You forgot to update project.mml, you can do so automatically with ./scripts/yaml2mml.py < project.yaml > project.mml.

**Comment by xsuchy** [comment]
@math1985 fixed
@kocio-pl  (although deleted) it should look like http://mtbmap.cz/#zoom=18&lat=49.218494&lon=16.387597 This is little renderer because I find that wayside_cross are in fact not rendered - and I can swear that I seen it rendered in past. E.g here http://www.openstreetmap.org/#map=18/49.48159/16.48200 is wayside cross and it is not rendered despite the fact that with current carto it should be rendered. Strange.
@matkoniecz I would say: "small steps". This is IMO step forward. If someone want to change it for other religion the he can send another PR. But I guess that will be long discussion. Well, it already is. See https://github.com/gravitystorm/openstreetmap-carto/issues/131

**Comment by matkoniecz** [comment]
> despite the fact that with current carto it should be rendered

OSM servers are not using latest openstreetmap-carto version (latest released version is not including new road style and later changes, including rendering of crosses).

Rendering only wayside_shrine with religion=christian with cross symbol would not be bad (though I am not sure is it a good idea). But rendering [historic=wayside_shrine, religion=shinto] with cross symbol (examples findable with http://overpass-turbo.eu/s/bC8 ) is completely unacceptable and I oppose merging this PR in the current form.

**Comment by xsuchy** [comment]
Is this better?

**Comment by matkoniecz** [comment]
I think that assuming that religion is certainly Christian is a poor idea. Also - is it tested?

Also, I would dispute

> Wayside shrine is just more robust form of wayside cross.

It is very similar in function but it is far away from "just more robust form of wayside cross"

**Comment by kocio-pl** [comment]
@matkoniecz +1.

**Comment by dieterdreist** [comment]
@matkoniecz +1

**Comment by xsuchy** [comment]
So should I remove line with `[religion = '']`?

**Comment by matkoniecz** [comment]
Yes, I would also remove "Wayside shrine is just more robust form of wayside cross." from the commit description.

**Comment by xsuchy** [comment]
Updated according your comments.

**Comment by math1985** [comment]
@xsuchy I get the following error message:

" ERROR: column "religion" does not exist LINE 1: ...","feature","is_building","name","operator","ref","religion"... ^ "

I think you also need to add religion to the SQL statement.

Did you test this in Kosmtik or Tilemill?

**Comment by math1985** [comment]
I still can't get this to work unfortunately. @xsuchy if you can get it to work, feel free to submit a new PR!

**Pull request closed without merging**
