### PR TITLE
Add icon for shop=bookmaker

### LINKED ISSUE #3186: Add icon for shop=bookmaker
https://wiki.openstreetmap.org/wiki/Tag:shop=bookmaker
6.5k uses

@SomeoneElseOSM icon: https://github.com/SomeoneElseOSM/openstreetmap-carto-AJT/blob/master/symbols/shop_bookmaker.p.16.png

Or maybe something combining luck/gambling and a ticket?: bookmaker02png

### PR DESCRIPTION
**Pull request by Adamant36**
Adds icon for shop=bookmaker closes #3186
https://www.openstreetmap.org/#map=19/40.87865/-73.59622 (node)
bookmaker node
https://www.openstreetmap.org/#map=19/40.65692/-74.11743 (way)
bookmaker way

### CODE REVIEW

**Comment by Tomasz-W** [comment]
@Adamant36 Auto-closing keyword in first post doesn't work (it should be "closes")

**Comment by Adamant36** [comment]
@Tomasz-W Thanks for the heads up.

**Comment by lakedistrictOSM** [comment]
Even though I designed it I don't think that this icon works. Maybe just a suit of clubs would be better? You should be able to find a suitably licensed one somewhere that you can use.

**Comment by Adamant36** [comment]
Hhmm ok. Icons arent really my thing. I know nothing about SVG etc. Can you or @Tomasz-W come up with another one if this one doesnt work? I like the current icon,  it seems consistant with getting a ticket for a bet or something, but I have no experince with bookmakers. So I'm sure theres a better icon out there.

**Comment by Adamant36** [comment]
Node
bookmaker node
Way
bookmaker way

What do you guys think?

**Comment by Tomasz-W** [comment]
I'm not fully satysfied by both icons, but I think there are no any different options for bookmaker icon. so we should choose from ticket one, table one or stay with a dot.
@kocio-pl @meased ?

**Comment by kocio-pl** [comment]
I'm not convinced at all by @Tomasz-W design in this case. @lakedistrictOSM design of this icon is OK for me.

**Comment by Adamant36** [comment]
@kocio-pl I'm good with @lakedistrictOSM's icon also compared to that of @Tomasz-W. So can we go with that one?

**Comment by kocio-pl** [comment]
Since I have the impression that @lakedistrictOSM is not interested in further working on this and it's sane design for me, I'm going to merge it soon.

**Comment by Adamant36** [comment]
Ok. Thanks. Sounds good to me.

**Comment by kocio-pl** [comment]
Thanks, works as expected also on other places.

**Pull request merged**
