### PR TITLE
Align baseline of icon for Towers and other vertical features

### LINKED ISSUE #3176: Tower baseline alignment
There are a few icons representing tall objects now shown on the map. For example, wind turbines and communications towers. But the icons are aligned such that the centre of the icon is over the actual node position which leads to them looking misplaces, especially at lower zoom levels.

An example can be seen here with the wind turbine in the middle: https://www.openstreetmap.org/#map=16/52.5975/1.2626 It looks like it's in the water but it's not.

Can the alignment be changed so that the bottom of the icon is at the node position?

### PR DESCRIPTION
**Pull request by jeisenbe**
Fixes #3176

### Changes proposed in this pull request:

Edited PR:
I have removed the changes for most of the icons. What remains:

1. man_made=mast, type:communication - translate icon up 4 pixels
2. man_made=tower, type:communication - translate icon up 4 pixels
3. man_made=communications_tower - translate icon up 4 pixels
Also, the text-dy will be reduced by 4 pixels for each of these types.

### New renderings:
Before
tower-communications1-before
After - up 4 pixels
towers-communication-up4

Before
tower-mast-before
After
mast-tower-communications-up4

### Originally proposed changes:

Add ` marker-transform: translate` to masts, towers, monuments and similar vertical features. 

(EDITED: See below for new list)
1. man_made_mast - translate icon up 6 pixels
2. man_made_tower - translate icon up 6 pixels]
3. man_made_communications_tower - translate icon up 6 pixels
4. man_made_chimney - translate icon up 6 pixels
5. man_made_water_tower - translate icon up 5 pixels
6. man_made_obelisk - translate icon up 5 pixels
7. historic_monument - translate icon up 4 pixels
8. man_made_lighthouse - translate icon up 4 pixels
9. power_generator (wind turbine) - translate icon up 6 pixels
10. man_made_windmill - translate icon up 6 pixels

Text-dy is reduced by a similar amount for each of the features to keep the name label at the right position relative to the adjusted icon.

Currently, the icons are aligned such that the centre of the icon is over the node position or the center of the polygon, which leads to them looking misplaced, especially at lower zoom levels. This adjustment sets the apparent baseline of the icon so that it is about 1 pixel below the node. 

**Test renderings:**
Before
towers1-z17
towers2-z17

After
towers1-after
towers2-after

z18 Mast with name label - Before
mast1
After
mast-after

**Real-world examples:**
z14 Communications towers Original
z14-honolulu-0
Up 6 pixels
z14-honolulu-6

z18 Lighting towers original
z18-honolulu-0
Up 6
z18-honolulu-6up

Diamond Head Lighthouse, Honolulu
z15 original

z15 up 4 pixels
lighthouse-up4

Monuments in Beirut, before
http://openstreetmap.org/#map=17/33.89653/35.50498
monuments-before
Monuments up 4
monument-up4

Mast in Lebanon, before
mast-before
Up 6 pixels
mast-up6

Watertower before
watertower-before
Watertower up 5 pixels
watertower-z17-up5

Windmill in rural Lebanon before
windmill-before
Windmill up 6p
windmill-up6

Wind Turbines Hawaii
Before z15
windturbinesz15-before
z15 up 6
windturbinesz15-up6

Man_made Obelisk, Washington DC:
z15 original
obelisk-before
z15 up 6 pixels (thin base, tall icon)
obelisk-up6

Man_made Chimney
Before z16
chimneys-up6
Up 6 pixels z16
chimneys-before

### CODE REVIEW

**Comment by kocio-pl** [comment]
Could you explain more why do you think we need such aligning at all? 

Looking at examples, I see more problems than gains with it. For example Washington Monument looks probably similar, because it has label (although I would prefer non-aligned version), but Wind Turbines Hawaii look displaced out of the industrial area (where they probably belong) and Watertower looks just worse having no label at all - they are visibly out of place.

**Comment by jeisenbe** [comment]
Edited PR:
I have removed the changes for most of the icons. What remains:

1. man_made=mast, type:communication - translate icon up 4 pixels
2. man_made=tower, type:communication - translate icon up 4 pixels
3. man_made=communications_tower - translate icon up 4 pixels
Also, the text-dy will be reduced by 4 pixels for each of these types.

New renderings:
Before
tower-communications1-before
After - up 4 pixels
towers-communication-up4

Before
tower-mast-before
After
mast-tower-communications-up4

**Comment by jeisenbe** [comment]
Real-world tests for towers, masts, and communications_tower near Dover, England:

Before: Communications_tower at z14
com_tower-z14-before
After up 4 pixels
com_tower-z14-up4

z16 Before
com_tower-z16-before
After
com_tower-z16-up4

Towers (type:communication) before
2towers-dover-before
After
2-towers-dover-up4

Mast (type:communication)
Before z15
z15com-mast-dover-before
After (up 4)
z15com-mast-dover-up4

z18 before
z18-mast-before
after
z18-mast-up4

In Honolulu, Hawaii:
z14 before
chinatown-before
after
chinatown-up4
z14 before
alamoana-before
ala-moana-z14-up4

The communications_tower icon is probably fine either way, but I do think the towers and masts icons are improved by this change.

**Comment by dieterdreist** [comment]
sent from a phone

> On 13. Nov 2018, at 08:55, jeisenbe <notifications@github.com> wrote:
> 
> The communications_tower icon is probably fine either way, but I do think the towers and masts icons are improved by this change.


it is hard to see the difference in a sequence, but this is something that becomes very obvious when zooming on a slippy map. Icons with a clear bottom/ground should generally be placed with the ground on the POI position, and the lower the zoom level the more relevance it has.

**Comment by daganzdaanda** [comment]
Maybe this should only be done on nodes. Then in the cases where a building has been mapped, the icon stays centered and does not look weird.

**Comment by dieterdreist** [comment]
Am Mi., 14. Nov. 2018 um 17:27 Uhr schrieb daganzdaanda <
notifications@github.com>:

> Maybe this should only be done on nodes. Then in the cases where a
> building has been mapped, the icon stays centered and does not look weird.
>


usually it looks weirder if the tower icon's base is not at the base of the
icon. Usually icons are bigger than the features in lower zoom levels at
least.

**Comment by jeisenbe** [comment]
I've reexamined the chimney icon, and I believe it needs realignment, like the communications towers and masts.
Because of the "smoke" coming out of the top, the center of the "chimney" part of the icon is not centered, and so it appears to be shifted vertically down and to the left. So I've moved it up 4 pixels and to the right 4 pixels:

z19 Before
z19-chimney-before
z19 up 4 pixels, right 4 pixels
z19-chimney-after

z18 Before
z18-chimney-before
z18 up 4, right 4
z18-chimney-after

z16 Before
z16-chimney-before
z16 up 4, right 4
z16-chimney-after

In these test images, the node is placed precisely at the intersection of 2 power lines, but in the current rendering the chimney appears to be down and to the left of the intersection. In the "after" images, the chimney part of the icon is now properly aligned.

**Comment by jeisenbe** [comment]
@kocio-pl do you have any thoughts about the PR? The last comment was 6 days ago. 

Here are the changes:

1) man_made=mast, type:communication - translate icon up 4 pixels
2) man_made=tower, type:communication - translate icon up 4 pixels
3) man_made=communications_tower - translate icon up 4 pixels
4) man_made=chimney - translate icon up 4 pixels and right by 4 pixels 

Also, the text-dy will is reduced by 4 pixels for each of these types.

All of these icons look misaligned due to the communication waves or smoke at the top of the icon, which pushes the tower/chimeny area to the bottom of the icon.

**Comment by jeisenbe** [comment]
@matthijsmelissen - this PR is ready for review. It's mainly a cartographic choice.

**Comment by matthijsmelissen** [comment]
Although I initially was in favour of this change, I think I agree with @meased now:

> Where is this idea going? Everything that "stands up" gets an offset icon? embassy? fuel? cafe? camping? golf? picnic? waste_basket?
> This is a 2D map, not a 3D map. Icons represent an object, they don't have to look like a vectorized aerial image of the object.

For these reasons, I'm going to reject this change. Thanks a lot for trying though, and thanks for creating a clear and easy to review pull request!

**Pull request closed without merging**
