### PR TITLE
Match label colors to icons

### PR DESCRIPTION
**Pull request by math1985**
Match the color of the following labels to their respective icons:

* natural=peak
* natural=volcano
* natural=saddle
* natural=cave_entrance
* historic=memorial
* historic=archaeological_site
* man_made=lighthouse

### CODE REVIEW

**Comment by math1985** [comment]
Before:
screenshot from 2015-03-04 13 45 47

After:
screenshot from 2015-03-04 13 43 49

**Comment by mkoniecz** [comment]
Maybe also caravan site should be changed?

**Comment by imagico** [comment]
I think the peak/saddle label is too weak to be well readable.

**Comment by math1985** [comment]
> Maybe also caravan site should be changed?

For caravan site, see #1355.

**Comment by math1985** [comment]
The peaks are readable for me, but I could make them darker. This is how they look now:

screenshot from 2015-03-06 18 17 51

**Comment by mkoniecz** [comment]
I think that for peaks and saddles old version is better. This is barely readable - and what about peaks on natural=bare_rock areas?

**Comment by imagico** [comment]
Having peak/volcano the same color except for the symbol itself (as it is now) seems a well working concept to me.  Reducing the color difference between the peak/saddle symbol and the label would not hurt but with your current setting the label appears even brighter (due to the thin lines and the white casing) than the symbol.  At the same time the symbol color could be somewhat stronger/darker IMO - to compensate the symbol could be slightly reduced in size for z=11/12.

Here your current color on different backgrounds

sample 1
sample 2
sample 3
sample 4

**Comment by mkoniecz** [comment]
For me it is not really readable. It is possible to decipher it, but it requires effort that should not be needed.

Maybe new color for peak symbol/label may be something between current symbol and current label colour?

**Comment by pnorman** [comment]
I also prefer the current colour to the proposed one.

**Comment by mboeringa** [comment]
I would simply darken the color for the label, and stay with the same adjusted hue. I am pretty sure that will solve the readability issue. There is no reason why a label could not have a darker color than the icon, as long as the hue stays the same. I think the recognizability of the combination will not suffer.

Any specific reason why playground and water_park aren't adjusted as well? (I noticed the playgrounds don't have labels yet... but for consistency maybe?)

**Comment by HolgerJeromin** [comment]
playground have a label: http://osm.org/?mlat=50.78457&mlon=6.05799#map=19/50.78457/6.05799

**Comment by mboeringa** [comment]
> playground have a label: http://osm.org/?mlat=50.78457&mlon=6.05799#map=19/50.78457/6.05799

Then I was unlucky to only look at a couple of ones actually missing a name tag...

**Comment by math1985** [comment]
> Any specific reason why playground and water_park aren't adjusted as well? (I noticed the playgrounds don't have labels yet... but for consistency maybe?)

This depends on #1355, for which there is still no clear preferred option.

**Comment by math1985** [comment]
I darkened the labels.

screenshot from 2015-03-09 21 00 34

**Comment by mboeringa** [comment]
That looks a lot better...

**Comment by mkoniecz** [comment]
Yes, it is now much better.

**Comment by pnorman** [comment]
Looks good - I'll try for a full review tomorrow.

**Comment by pnorman** [comment]
Peaks start at z13 in production with text at z13, but on this branch they start at z12 with text at z14.

Is this intentional, or is there something else that has been merged in and not released yet?

**Comment by math1985** [comment]
> Peaks start at z13 in production with text at z13, but on this branch they start at z12 with text at z14.

Are you sure? As far as I can see, in both production and branch, icons start at z11 and text at z13.

**Comment by mkoniecz** [comment]
> Are you sure? As far as I can see, in both production and branch, icons start at z11 and text at z13.

The same happens according to my test.

natural peak name eeeeee eeeeee eeeeee ref 1 ele 8000 node master - math_text-colors

**Comment by math1985** [comment]
> The same happens according to my test.

If I understand @mkoniecz's picture correctly, 'the same' refers to the same as I reported.

**Comment by mkoniecz** [comment]
> If I understand @mkoniecz's picture correctly, 'the same' refers to the same as I reported.

Yes, at least for lone peaks only label color is changed.

**Pull request merged**
