### PR TITLE
Change area decisions at import time

### LINKED ISSUE #3611: Different geometry decisions (point/line/polygon) on database re-import
Currently there is no database re-import planned. And apparently also no urgent need to do so. Anyway it might be useful to have a list of geometry decisions (point/line/polygon) that we might maybe change if in the future we would make a database re-import.

- `barrier=toll_booth` as _line_ geometry (reference #3249 and #3244)

### PR DESCRIPTION
**Pull request by pnorman**
Fixes #3611

### CODE REVIEW

**Comment by pnorman** [comment]
Originally I was wondering if this needed a benchmarking run, but looking at the diff I don't see anything with performance implications, either at import time or at run time.

**Comment by pnorman** [comment]
I wasn't expecting that much of a performance difference, so I'm running a benchmark myself

**Comment by pnorman** [comment]
I don't find a noticeable performance difference on Geofabrik's Canada extract with `--slim --drop --flat-nodes`.

**Comment by jeisenbe** [comment]
That's great. Is there documentation about how to use these options (`--slim --drop --flat-nodes `) when importing with docker?

**Comment by pnorman** [comment]
> Is there documentation about how to use these options (`--slim --drop --flat-nodes `) when importing with docker?

I don't use docker, so don't know.

**Pull request merged**
