### PR TITLE
add documentation for generating forest pattern

### PR DESCRIPTION
**Pull request by matkoniecz**
current PNG pattern used in rendering is impossible to easily tweak and modify
this instructions were already present but buried as a commit message
fixes part of #1529

### CODE REVIEW

**Comment by imagico** [comment]
You can meanwhile also set the pattern color without modifying the svg:

http://www.imagico.de/map/jsdotpattern.php#x,512,jdp6894;g,30,32,32;s,jdp33742;s,jdp81637;rx,250,2,32,32;s,jdp28824;s,jdp59702;s,jdp91550;s,jdp27774;rx,250,2,64,64;rd,1,0,0,tree%20pair,1,5,5,0,jdp52898,6b8d5e,add19e;

**Comment by matkoniecz** [comment]
Thanks! I kept background transparent as it is easier to modify it in CartoCSS rather than regenerate pattern.

**Comment by imagico** [comment]
Background color is only for display, the svg is always generated without.

**Comment by matkoniecz** [comment]
Again - thanks! Now preview in jsdotpattern is with background colour.

**Pull request merged**
