### PR TITLE
Add halo to roads on z8-11

### PR DESCRIPTION
**Pull request by math1985**
This PR adds a halo to roads on z8-11.

Before/after:
screenshot_2017-03-29_00-58-04 screenshot_2017-03-29_00-58-24

Before/after:
screenshot_2017-03-29_01-09-12 screenshot_2017-03-29_00-59-50

Before/after:
screenshot_2017-03-29_01-00-35 screenshot_2017-03-29_01-05-35

### CODE REVIEW

**Comment by math1985** [comment]
Changed title to 'Add halo to roads on z8-11', something went wrong with the original title.

**Comment by math1985** [comment]
This depends on #2602.

**Comment by math1985** [comment]
This is a rather subtle change, but this should increase contrast between the roads (in particular primary) and landuse.

**Comment by math1985** [comment]
Known issue: on z9 there is a problem with gaps in the roads, likely caused by interaction with the low-zoom layer.

**Comment by imagico** [comment]
The gaps might be bridge related.

Regarding the change itself - i can see the better readability of large roads but i also see more noise in the map overall, esp. at z8/z9 and the halo takes up space and covers other stuff which is less visible, in particular rivers.

I already mentioned this when @matkoniecz introduced halos for the minor roads.  This does not necessarily mean i am against this change but i clearly see that this will not improve readability overall as much as you might think if you only look at the roads.

**Comment by nebulon42** [comment]
I'm not quite sure about this. Might likely be an improvement but I would prefer it to be more subtle. Maybe less thick or more transparent? Right now I think it is a bit too noisy especially with motorways.

**Comment by pnorman** [comment]
> This depends on #2602.

Do you mean a different issue, as **this** is #2602

**Comment by math1985** [comment]
> Do you mean a different issue, as this is #2602

I meant #2601, I can however change the PR so that it no longer depends on it.

**Comment by pnorman** [comment]
As this has cartography changes, this PR is currently held up by the [feature freeze until 4.0.0 has been released](https://github.com/gravitystorm/openstreetmap-carto/pull/2533#issuecomment-295931948).

**Comment by math1985** [comment]
This has been implemented as part of the midzoom changes.

**Pull request closed without merging**
