### PR TITLE
Add icon for Bureau_de_change

### LINKED ISSUE #3185: Add icon for amenity=bureau_de_change
https://wiki.openstreetmap.org/wiki/Tag:amenity=bureau_de_change
9.8k uses

Maybe something similar to amenity=bank but with two different note designs? Or note and coins? 

I've had a go at a few designs but haven't produced anything suitable yet.

### PR DESCRIPTION
**Pull request by jragusa**
Fixes #3185

Changes proposed in this pull request:
Render `amenity=bureau_de_change` from z17

Test rendering with links to the example places:
https://www.openstreetmap.org/node/2140012378

Before
bureau_de_change_before

After
bureau_de_change 2

### CODE REVIEW

**Comment by kocio-pl** [comment]
Works for me. Please check also way rendering (with name label).

**Comment by jragusa** [comment]
@kocio-pl it works correctly on way
https://www.openstreetmap.org/way/384831563
bureau_de_change_way

**Comment by kocio-pl** [comment]
Vertical line on "$" symbol is too weak for me, so it looks like "S", could you tune it a bit?

**Comment by Tomasz-W** [comment]
@jragusa Updated icon: https://gist.github.com/Tomasz-W/b438cd0bd7305fec2c29b6bdc766e48f

**Comment by jragusa** [comment]
thanks @Tomasz-W 
bureau_de_change 3

**Comment by kocio-pl** [comment]
Thanks. Some additional thoughts: maybe adding 2 verticals would be even better? Or maybe these are not needed inside the letter S, only 2 endings on top and on the bottom would be good?

**Comment by Tomasz-W** [comment]
With pixel alligned $:

amenity bureau_de_change2

Gist link: https://gist.github.com/Tomasz-W/b438cd0bd7305fec2c29b6bdc766e48f

I tried with 2 vertical bars, but it didn't work well.

**Comment by jragusa** [comment]
bureau_de_change 4

**Comment by kocio-pl** [comment]
Thanks, this code has been tested in some other places and it works as expected.

**Pull request merged**
