### PR TITLE
money related SVG icons

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 and focuses on money related icons.

The original icons used stroke and fill so I had to change them. I also tried to reduce complexity a bit.
Following symbols are affected:

amenity=atm ([atm-16.svg](https://github.com/nebulon42/osmic/blob/master/money/atm-16.svg))
atm-16

amenity=bank ([bank-16.svg](https://github.com/nebulon42/osmic/blob/master/money/bank-16.svg))
bank-16

http://www.openstreetmap.org/#map=19/48.20196/16.39171
before:
money_before

after:
money_after

### CODE REVIEW

**Comment by math1985** [comment]
I also tested this with someone unfamiliar to the icons - I can confirm that bank is recognisable, but ATM is not.

Creating recognizable icons is hard, so I don't mind accepting icons of which users need to learn the meaning, but icons that are recognizable immediately are better of course.

**Comment by nebulon42** [comment]
@math1985 for bank, did you test the stacked bills or the roof variant?
Maybe we should re-introduce the dollar sign? @imagico might be quite right that it is biased but recognisable.

**Comment by math1985** [comment]
For bank I tested the stacked bills.

**Comment by pnorman** [comment]
> Maybe we should re-introduce the dollar sign? @imagico might be quite right that it is biased but recognisable

Another problem with the dollar sign is that at the sizes we need it's close to a blob anyways. Even fonts with hinting have problems.

**Comment by nebulon42** [comment]
> Another problem with the dollar sign is that at the sizes we need it's close to a blob anyways. Even fonts with hinting have problems.

Yes, also true. So maybe leave it like it is and change accordingly if there are problems?!
I have updated the PR to reflect the fact that symbols shouldn't be grouped in subdirectories.

**Comment by Vort** [comment]
Banknotes have different design in different countries.
Someone may not know how dollar looks like, but I'm sure everyone knows the dollar sign.
For the same reason I like coins better than dollar's stack.
Maybe coins under the roof is a good idea for bank?

**Comment by math1985** [comment]
Is this ready to be merged?

**Comment by nebulon42** [comment]
A little sum up from me: I'm not convinced of the roof approach. Coins are not bad, but I would like to reuse core symbology for bank and ATM, coins won't work for ATM. I don't really like the dollar sign, but I acknowledge that it is familiar. To be legible it has to be big, so simply adding it inside the center of the bill wouldn't work so well.

There was the feedback that ATM isn't recognisable, but I don't have any better ideas at the moment. So I'd suggest to merge and to risk that ATM isn't that recognisable at the start.

**Comment by math1985** [comment]
Thanks. If anyone has a better suggestion, we can consider, but this seems to be the best we can come up with for now.

**Comment by math1985** [comment]
@mkoniecz I suspect the text-dy might need to be adapted (decreased, fortunately) to the new icons, could you check that?

**Pull request merged**
