### PR TITLE
Adding amenity=car_wash icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Implements part of https://github.com/gravitystorm/openstreetmap-carto/issues/108:

car_wash-19

BTW: it looks like shop=car_repair should be rendered also in brown, because it doesn't sell things, but services, so it is in fact amenity too!

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
nice icon. It is surprising with the brown, but you are right.

**Comment by kocio-pl** [comment]
We have also taxi and car sharing icons, which are transportation-blue, because their function is transporting people (which is a special kind of service, if we look closer), so we have the car icon in different colors. :smiley:

**Comment by matkoniecz** [comment]
@kocio-pl  Can you rebase it?

**Comment by kocio-pl** [comment]
Sure, done (and checked that it renders as before).

**Comment by kocio-pl** [comment]
...and once again.

**Pull request merged**
