### PR TITLE
Add icon for shop=interior_decoration

### LINKED ISSUE #1406: Add special rendering for shop=interior_decoration
We should start rendering shop=furniture and shop=interior_decoration, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/furniture.svg

[It was proposed in meta-issue #1402]

### PR DESCRIPTION
**Pull request by Adamant36**
This pull request adds an icon for shop=interior_decoration and closes #1406
https://www.openstreetmap.org/#map=19/37.77273/-122.42231 (node)
interior_decoration node
https://www.openstreetmap.org/#map=19/37.77735/-122.40954 (way)
interior_decoration way

### CODE REVIEW

**Comment by Adamant36** [comment]
@kocio-pl so I did the thing with branches so I could do more then pull request at a time, but it looks like it combined them on this one. Is that correct? If I change the icon on shop=ticket do I have to recommit this one or something?

**Comment by kocio-pl** [comment]
I won't be available for a few days and have no time to look closer now, so please be patient or - preferably - somebody else could respond you.

**Comment by Adamant36** [comment]
OK. No worries.

**Comment by Tomasz-W** [comment]
@matthijsmelissen https://github.com/gravitystorm/openstreetmap-carto/pull/3293#issuecomment-402331422 Can you check it? I don't have enough knowledge, and Kocio is busy :)

**Comment by kocio-pl** [comment]
`symbols/shop/ticket.svg` should be just removed from this PR and all the code moved into just 1 commit.

Remember to change phrasing so closing would happen automatically.

**Comment by Adamant36** [comment]
@kocio-pl So I deleted ticket.svg, but it I had to update the branch first to get it inline with this one and now its failing The Travis CL build because it needs it needs ticket.svg there since the code has been updated to include it. If I re add ticket.svg though, I assume it will just go back being part of the commit again and create another one which I assume I don't want. Plus, instead of rolling back to one commit like it was suppose to, it created a bunch of other ones. I'm not sure why it didn't work out like the other did when it was essentially the same problem.  

So, any idea what to do at this point? Is there a way to role back the whole thing and do it over or something? I don't want to just keep making it worse by adding more unnecessary commits but I tried everything I could find. So it would be good if I could get some advice from someone here about it before I do anything else.

Sorry for the issues.

**Comment by kocio-pl** [comment]
Could anybody more fluent with git help here?

**Comment by kocio-pl** [comment]
BTW: You don't need to apologize and feel sorry, version control is kind of art in itself, and sometimes it looks to me like a martial art. :-) I'm grateful that you've tried and i understand your frustration that it didn't work as expected. Been there, seen that!

**Comment by jragusa** [comment]
@Adamant36 look at your `project.mml`. You have to remove duplication lines 1662-1666, 2069-2073, 2240-2244. You can do that on the GitHub page by editing the text. Then you click to merge.

**Comment by kocio-pl** [comment]
@Adamant36 Do you need more help with this?

**Comment by Adamant36** [comment]
@kocio-pl Its good to go now :)

**Comment by kocio-pl** [comment]
It effectively removes existing `ticket.svg` icon. So please add this icon again (to not make things harder by removing commit deleting it) and I will take care of squashing the commits if everything else will be OK.

**Comment by Adamant36** [comment]
Done. I don't know why it did that.

**Comment by kocio-pl** [comment]
It was probably because you were adding ticket when it was not available n master, then you have deleted it, and when ticket was in master, deletion was still active.

Thanks anyway, I tested it in some other places and it works OK.

**Pull request merged**
