### PR TITLE
[WIP] Render natural=water (lakes, lagoons) differently when tagged salt=yes.

### LINKED ISSUE #3893: Render water areas differently when tagged salt=yes
### Expected behavior
- The tag `salt=yes` should be used to render salt lakes differently than fresh water lakes
- Currently the tag is used over 14,000 times, including 8000 uses with `natural=water`: https://wiki.openstreetmap.org/wiki/Key:salt
- It was approved in 2011: https://wiki.openstreetmap.org/wiki/Proposed_features/Water_details

### Actual behavior
- Oceans, seas, lagoons and salt lakes are currently all rendered the same as freshwater rivers.
- Recently we just began to render `wetland=saltmarsh` differently than `wetland=marsh` by using a random white dot pattern.

### PR DESCRIPTION
**Pull request by StyXman**
Fixes #3893 

Changes proposed in this pull request:
Render salt water areas in old pink color. This does not include salt ponds (might come soon), and does not include seas/oceans.

Test rendering with links to the example places:

https://www.openstreetmap.org/#map=13/37.9948/-0.7054

Before
Screenshot_20190924_145328

After
Screenshot_20190924_145031

I just noticed that this pink is close to mud and industrial zone, so most probably will need some changes, bu the basics are in.

Also nevermind that my render does not show sea/ocean, I have a bug with kosmtik.

### CODE REVIEW

**Comment by kocio-pl** [comment]
For me it's too far from the water color. Maybe some pattern on it would work better. However it's interesting if there's a way to make uniform rendering for all the salty waters.

**Comment by ferdinand0101** [comment]
In my opinion white dots would fit well
Maybe basically the style of wetlands inverted
1. Salt is also white
2. Also used in other maps
3. Simple

**Comment by StyXman** [comment]
I agree, but for instance the Laguna de la Mata besides just north east seems to also be salty (just not tagged so right now, I added a note), which already has a pattern for the marsh. I don't know if they will play well together.

**Comment by StyXman** [comment]
To be fair, given that this lagoon has paths on it and wetlands in the coast, I guess it also has wetlands inside.

**Comment by StyXman** [comment]
This kinda fixes #545 because salt_ponds are sometimes also tagged as salt=yes.

https://www.openstreetmap.org/way/534624892

**Comment by ferdinand0101** [comment]
I guess it might be simplest to just not render the salt tag if there is the wetland tag I'd say inthe case you just pointed out the wetland tag is more important

**Comment by StyXman** [comment]
And then we have this render from the wiki page:

https://wiki.openstreetmap.org/wiki/Tag:wetland%3Dsaltmarsh

**Comment by ferdinand0101** [comment]
oh I didn't know that part of the tagging
In this case there shouldn't be a problem
saltmarsh should then obviously be preffered to marsh and salt

**Comment by StyXman** [comment]
Salt marshes:

https://www.openstreetmap.org/relation/9646555#map=15/36.4278/-6.2188

Maybe then yes, the white dots.

**Comment by jeisenbe** [comment]
I agree with adding a lighter pattern of dots for lakes with `salt=yes`. You can try reusing the [pattern from saltmarshes](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/salt-dots-2.png).

Alternatively, you can try the patterns from the alt-colors style:

https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/water_salt.png)

https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/water_intermittent_salt.png

But salt lakes should still be a shade of blue like other water areas.

(BTW, I was thinking of something like this for oceans: lighter blue for oceans vs lakes (and darker blue for rivers on the right. But this does not have to be changed in this PR)

Imagico-water

**Comment by StyXman** [comment]
New render:

Screenshot_20190925_122108

**Comment by jeisenbe** [comment]
Thanks for the new test rendering. 
I designed that `salt-dots-2.png` pattern for use with salt marshes, which have a lighter green color, so it looks a little strong on the blue water color. Could you try using a little opacity? 

Or perhaps test https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/water_salt.png instead?

Ideally there should also be a rendering for water areas with `salt=yes` + `intermittent=yes`.

**Comment by StyXman** [comment]
opacity 0.4, 0.6 and 0.8:

salt-pattern-op-0 4-13-1044467-808970
salt-pattern-op-0 6-13-1044467-808970
salt-pattern-op-0 8-13-1044467-808970

**Comment by StyXman** [comment]
Pattern op 0.4, 0.6 and 0.8:

salt-pattern-op-0 4-13-1044467-808970
salt-pattern-op-0 6-13-1044467-808970
salt-pattern-op-0 8-13-1044467-808970

**Comment by kocio-pl** [comment]
0.6 looks like the best for me, 0.4 is hard to be noticed on my screens. What about intermittent waters?

**Comment by StyXman** [comment]
I can't do anything with intermittent because both use polygon pattern, unless I move the salt pattern to `landcover-area-symbols`?

**Comment by kocio-pl** [comment]
> However it's interesting if there's a way to make uniform rendering for all the salty waters.

I guess making dots on the big areas like ocean is not nice, but we might start with average color from salty lakes and (like 90% of blue + 10% of white) apply it as a new color. This way both would look as similar as possible.

**Comment by StyXman** [comment]
> lighter blue for oceans vs lakes, and darker blue for rivers

So lighter blue for all salt waters, oceans, seas, lakes, lagoons? It's something I could implement here too.

**Comment by jeisenbe** [comment]
It's certainly not required for this PR. Normally a major change like
this requires a lot of discussion.

But since @imagico (one of the other maintainers of this style) and I
have already tested this option, I believe it would be possible to try
using the colors here:
https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/style.mss

```
@water-color: #a2d1e0;     // Lch(81,17,227)
@ocean-color: #b5d7e3;     // Lch(84,13,227)
```
Then `ocean-color` could also be used for salt lakes. This will be
helpful at low zoom levels, since the salt pattern doesn't work for
very small features, but the lighter blue will still be visible.

However, if there isn't consensus for the change to the ocean color,
we could certainly just add the pattern to start.

**Comment by jeisenbe** [comment]
> I can't do anything with intermittent because both use polygon pattern, unless I move the salt pattern to landcover-area-symbols?

You can also make a new .png file for salt + intermittent features, combining the blue horizontal stripes with the white dot pattern.

**Comment by StyXman** [comment]
Given that the three color schema is so contentious, I will try @jeisenbe 's last suggestion.

**Comment by jeisenbe** [comment]
Once the new pattern is ready for intermittent + salt water, you can remove the "[WIP]" from the title, if it is ready for review.

**Comment by jeisenbe** [comment]
I've tested this rendering in a couple of places. The current pattern, with full opacity, is too strong compared to other patterns in this style:

Ramsar, Corsica:
z14 salt-dots-2 full opacity (current commit in this PR)
z14-ramsar-salt-dots

z12 salt-dots-2 full opacity
z12-ramsar-salt-dots

Here's how it would look with the alt-colors style, using a lighter ocean/salt water color and a much less prominent pattern:

z14 lighter ocean, alt-colors pattern
z14-ramsar-altcolors

z12 lighter ocean, alt-colors pattern
z12-ramsar-alt-colors

Of the test images shown above, the 60% opacity option is best, but I think it might be improved by using a higher density of dots and a less prominent pattern. Even better would be to pick a lighter salt water fill color, but that step could be done later. 

Laguna de Torrevieja, 60% opacity of salt-dots-2.png (from above)
laguna-small-60percent

**Comment by jeisenbe** [comment]
> You can also make a new .png file for salt + intermittent features, combining the blue horizontal stripes with the white dot pattern.

@StyXman do you have time to update the PR as planned, to include a salt water pattern for intermittent water areas?

**Comment by StyXman** [comment]
Hi @jeisenbe. I know I have 3 PRs open, they're in the top of my TODO list, but life has consumed a little more of my free time, so if anybody wants to take over I have no issue with that. It's a shame that we don't work with [feature branches à la nvie](https://nvie.com/posts/a-successful-git-branching-model/), which would make taking over more easily.

**Comment by StyXman** [comment]
Also, in the particular case of this PR, the discussion branched a little bit, even to other tickets, so I wanted for the dust to settle down a bit. It's sometimes exhausting to propose a change and many improvements and changes pop up. I'm not sure how we should handle those, maybe again the nvie branching model would help by allowing whoever wants to suggest a change just grab the code and try it themselves.

**Comment by jeisenbe** [comment]
There is no rush for this, feel free to work on it whenever you have the time. 

Thank you for the link about the [Nvie model](https://nvie.com/posts/a-successful-git-branching-model/). It appears that our development model is similar, because we also have feature branches: in this case [StyXman:3893](https://github.com/StyXman/openstreetmap-carto/tree/3893). As mentioned at the link "Feature branches typically exist in developer repos only, not in origin."

If anyone wants to copy the code in the `StyXman:3893`, open up your command line and type:
```
git remote add StyXman https://github.com/StyXman/openstreetmap-carto.git
```
then
```
git fetch Styxman 3893
```
then you can check out the branch:
```
git checkout Styxman/3893
```

**Comment by jeisenbe** [comment]
> It's sometimes exhausting to propose a change and many improvements and changes pop up

I'm sorry about that. Since this style is complicated and many features are related it can be hard to make a single change without affecting something else.

In this PR it looks like we already have consensus on using some sort of pattern of lighter dots to show salt water, so it should be possible to get this PR accepted.

**Comment by jeisenbe** [comment]
@StyXman do you have any time to update this PR now?

**Comment by StyXman** [comment]
@jeisenbe not really, sorry. If someone else wants to pick it up...

**Comment by pnorman** [comment]
Closing as stale

**Comment by jeisenbe** [comment]
> You can also make a new .png file for salt + intermittent features, combining the blue horizontal stripes with the white dot pattern.

I tried this, and it doesn't work. The salt dots are not visible with the strong horizontal lines.

This is a good reason to reconsider the current intermittent water pattern.

**Comment by jeisenbe** [comment]
Example before:
https://www.openstreetmap.org/#map=15/43.3847/4.7884
france-salt-ponds-intermittent-etc-before-15:43 3847:4 7884 png

With dots added for salt=yes + intermittent=yes:
dots-and-stripes-test-france-salt-ponds-intermittent--15:43 3847:4 7884

With new dots pattern for salt + intermittent:
france-salt-ponds-intermittent-etc-after-15:43 3847:4 7884

It would be best to change the horizontal stripes so they are not soo different.

**Comment by jeisenbe** [comment]
Here's one more try, with subtler dots:
salt-dots-plus-intermittent-lines-test

Horizontal stripes do not play well with random dots. 

Compared to alt-colors style, with dots for all intermittent water:
alt-colors-salt-intermittent-test

**Pull request closed without merging**
