### PR TITLE
Create USECASES.md

### PR DESCRIPTION
**Pull request by math1985**
Brain storm area for usecases for the low zoom levels. Hopefully this will help with #2688.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Markdown table is broken in github preview - https://github.com/math1985/openstreetmap-carto/blob/c7aba5ae2c02ac9c29ffc17837555839a2999563/USECASES.md

Is it fixable?

**Comment by matkoniecz** [comment]
Tables are supposed to work: see https://help.github.com/articles/organizing-information-with-tables/

**Comment by math1985** [comment]
Should be fixed now!

**Comment by matkoniecz** [comment]
In general I like this idea, what follows is a minor nitpicking.

> Roads

I think that it should be more specific (after all, we are not showing highway=service at z7).

>z5,z6,z7

Maybe "z5, z6, z7", or "5, 6, 7" would be more readable?

**Comment by math1985** [comment]
Some features that we currently render for which we do not (yet) have a use case:

* Province/state names and borders on z5
* City names on z5
* Roads on z5
* National parks on z7
* Railways on z7
* Minor water areas on z5/6/7

Should we add use cases or drop rendering these features?

**Comment by matkoniecz** [comment]
Also, it would be a good idea to include how this table is supposed to be grown - it it OK to make PRs for lower zoom levels? Higher zoom levels? Just zoom level one higher that currently processed one?

Should we have a list of rendered features not covered by any usecase?

**Comment by kocio-pl** [comment]
Wouldn't it be better to use wiki page instead? For example:

https://wiki.openstreetmap.org/wiki/Standard_tile_layer/use_cases

**Comment by math1985** [comment]
> minor nitpicking.

Fixed.

>  it it OK to make PRs for lower zoom levels?

I have no strong opinion, shall we first try this out for the current zoomlevels, and then extend it later if we're happy with this way of working?

**Comment by math1985** [comment]
> Wouldn't it be better to use wiki page instead?

I'd prefer to keep development here and not spread out over different mediums. Also, I think it's good to keep editing restricted to the maintainers here, and accept changes from others only by accepting pull requests. Otherwise it might get an inconsistent mess quite quickly.

**Comment by matkoniecz** [comment]
> Wouldn't it be better to use wiki page instead?

I think that it would preferable to

- keep this together with other map-style content (in repository)
- keep additions under review

> I have no strong opinion, shall we first try this out for the current zoomlevels, and then extend it later if we're happy with this way of working?

Any version would be OK, but it would be a good idea to mention it in document ("For now, this table covers zoom levels 5, 6 and 7." does not give info whatever at this moment PRs for additional zoom levels are considered as a good idea)

**Comment by math1985** [comment]
>  it would be a good idea to mention it in document 

Done.

**Comment by matkoniecz** [comment]
One more thing - maybe it should be linked from CARTOGRAPHY? And maybe also from README or CONTRIBUTING?

**Comment by math1985** [comment]
Merging already so we have it within the repository. Feel free to create further PRs or suggestions.

**Comment by matkoniecz** [comment]
> Merging already so we have it within the repository

Squashing on merge would be probably a good idea in this case.

**Comment by math1985** [comment]
You're right, I should have done that, guess it's too late now.

**Pull request merged**
