### PR TITLE
Better line spacing

### LINKED ISSUE #2358: Reduce vertical spacing in labels
Noto has a lot larger vertical spacing than the old font. This looks rather ugly for cartography (at least for Latin script).

Before/after:

screenshot_2016-09-20_23-55-12 screenshot_2016-09-20_23-54-38

We can use a negative text-line-spacing attribute to reduce the vertical spacing by a couple of pixels.

### PR DESCRIPTION
**Pull request by sommerluk**
Resolves #2358 (last part is solved by this PR)

Before:
screenshot 1

After:
screenshot 2

### CODE REVIEW

**Comment by kocio-pl** [comment]
Could you also show examples how would other scripts look like with this change?

**Comment by sommerluk** [comment]
screenshot 3
screenshot 4
screenshot 5
screenshot 6

Note that the used line spacing is simply the same that we have also applied in the rest of openstreetmap-carto (−0.15 em for line wrap ≤ 3 em).

This is the last one of various PR that implemented the fine-tuned line spacing.

**Comment by math1985** [comment]
Thanks! By the way, it would also make sense to keep the wrap-width a constant em amount.

**Comment by verdy-p** [comment]
Closed without testing with Myanmar ?

**Comment by verdy-p** [comment]
And still no test for Arabic : (high Khufi font, suitable for real trafic signs where they are isolated and have cumfortable line-height) or UI font (better suited for multilingual text on a dense map) ?
I summary the tests above are only for alphabetic (Latin/Greek/Cyrillic) script, Indic script, CJK scripts, it will probably work for Hebrew and Tifinagh
But I still have doubts for Arabic, Myanmar, Khmer, Lao, and Tibetan, and possibly even with Thai.

**Comment by kocio-pl** [comment]
Could you provide test rendering for missing scripts?

**Comment by verdy-p** [comment]
All these scripts were in  the initial #2358
When closing this bug with limited tests, someone marked #2358 as resolved even if you tested much less things here.

**Pull request merged**
