### PR TITLE
Adding rendering for shop=coffee

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2227.

The number of uses is currently 1986, so very close to a safe 2k limit.

78ebfvb5

### CODE REVIEW

**Comment by micahcochran** [comment]
shop=coffee is now at 2070 uses.

**Comment by math1985** [comment]
@kocio-pl Could you rebase this?

**Comment by kocio-pl** [comment]
Done.

**Comment by nebulon42** [comment]
The icon is ok. But I'm against merging this until the shop discussion has progressed further.

**Comment by kocio-pl** [comment]
Depends on https://github.com/gravitystorm/openstreetmap-carto/issues/2444 then.

**Comment by kocio-pl** [comment]
There's no progress in the shop discussion, so I'm not sure what to do - I'm ready to rebase it, but it's tedious for me as a casual git user, so it makes sense only if merging probability is high.

**Comment by math1985** [comment]
I think we need to give the shop discussion some more time.

**Comment by math1985** [comment]
Yes, good idea.

**Comment by kocio-pl** [comment]
Done. I hope that SVG code is proper.

**Comment by kocio-pl** [comment]
Is there any problem left to solve here?

**Comment by nebulon42** [comment]
Sorry for the long delay. I would merge it right away, but I saw that you are using a transform to rotate the bean. If you could clean this up (remove the transform) this would be great. If this is too much work I would also merge it as is.

**Comment by kocio-pl** [comment]
I have used file from @Jotam and I don't know how to fix this problem. If you or him (or anybody else) could fix the icon, I would simply update the code.

**Comment by nebulon42** [comment]
Turned out to be quite easy. Can you check for the last time? Then I will merge this.

**Comment by kocio-pl** [comment]
Ready. I've checked and it works as expected. I made it to be just one commit.

**Pull request merged**
