### PR TITLE
Public service POI category

### PR DESCRIPTION
**Pull request by kocio-pl**
Another follow up to #2824.

Basic testing has been made to make sure that labels are still here and they look the same as before.

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Do we want further divide public (prison, police ...) and private (atm, bank ...) operators?

**Comment by math1985** [comment]
The Uk privately run prisons and publicly owned banks :)

**Comment by kocio-pl** [comment]
"Public" part is not about operators, it's about services. But of course the lines are blurry and we can rearrange in some other way.

**Comment by kocio-pl** [comment]
Any comments or reviews now?

**Pull request merged**
