### PR TITLE
Fixing missing amenity name labels regression

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1800.

Fixing YAML/MML broken in commit 4745130e3d4a67472e046c9a7c0c25eed6c132c6. It is still spaghetti code, which is hard to compare (long lines and all the layers together), so please check if I didn't make a mistake!

I have checked it works with:
- school
- kindergarten
- university
- college
- grave_yard

so all the missing labels are back.

### CODE REVIEW

**Comment by matkoniecz** [comment]
Why in some cases order of listed amenities was changed from ```'pub', 'restaurant'``` to ```'shelter', 'atm'``` (coalesce in amenity-points-poly) and in some reverse happened (where clause in text-poly).

I am not sure whatever one order is preferable over another but it would be better to make it consistent.

**Comment by HolgerJeromin** [comment]
I propose a PR with a commit fixing the problem and a second commit adding new lines and sorting stuff.
With this strategy review if easier and we are faster on at the desired yaml style.

**Comment by kocio-pl** [comment]
I was trying to make as few changes as possible and just reverted the broken lines (adding only community_centre when needed). This is meant as a quick fix, I don't think more changes are sane before we will introduce the solution [@gravitystorm have proposed lately](https://github.com/gravitystorm/openstreetmap-carto/issues/1802#issuecomment-138809013).

**Comment by kocio-pl** [comment]
Does anybody from the team plan to merge this code or is there any problem with it that needs to be solved? 

I would really like have it done ASAP and then go further with code cleaning to avoid such problems in the future.

**Comment by HolgerJeromin** [comment]
You reverted the commit and readded the needed value. 
That is probably a good idea, but to review we have to compare to the state before the broken commit.
Another approach would be fixing the broken things from the current state, so the github diff is showing exactly what you have fixed.

But probably the maintainer are skilled enough to be able to review both approaches. :-)

**Comment by math1985** [comment]
As far as I'm concerned, I haven't had time to review any pull requests lately. I will look at it as soon as possible!

In the future, I'll try to be more explicit when I'm not merging something because I'm not convinced enough about the merits of a PR (but that was not the case here).

@HolgerJeromin Either way is fine with me, that's not the reason nothing has happened so far.

**Comment by kocio-pl** [comment]
> As far as I'm concerned, I haven't had time to review any pull requests lately. I will look at it as soon as possible!

Thanks!

But I'm confused: are you assigned for this task and the rest of the team in general does not pull any code in - or it works in some other way?

> In the future, I'll try to be more explicit when I'm not merging something because I'm not convinced enough about the merits of a PR (but that was not the case here).

It's always good to know what is the status of a PR not being actively discussed/reworked. Few days with no additional input should not be a problem (if it's not something serious like this regression), but a week or two would be a good mark of PR being forgotten or having some general problems that should be resolved (or just to be closed for some reason).

@matkoniecz [wrote elsewhere](https://github.com/openstreetmap/openstreetmap-website/issues/1038#issue-102617686) about the experience of being uncertain with creating PRs and this is also the problem I share sometimes in this repo.

**Comment by math1985** [comment]
> But I'm confused: are you assigned for this task and the rest of the team in general does not pull any code in - or it works in some other way?

No, any of the maintainers can accept pull request, there is no agreed distribution of tasks within the team.

> but a week or two would be a good mark of PR being forgotten or having some general problems that should be resolved (or just to be closed for some reason).

It happens regularly that there are two weeks in a row in which I have no time to spend on this project. Just a natural thing for a project run by volunteers, and no indication of the quality of proposed PR's!

**Comment by matkoniecz** [comment]
> But I'm confused: are you assigned for this task and the rest of the team in general does not pull any code in - or it works in some other way?

At least for me it is 100% hobby so whenever I am in the mood to review PRs and I have spare time I am doing this. Otherwise I am doing other things.

> It's always good to know what is the status of a PR not being actively discussed/reworked.

Whenever I see some kind of problem I comment immediately (here it was https://github.com/gravitystorm/openstreetmap-carto/pull/1825#issuecomment-139358836), in case of starting review that will last for a long time I assign PR to myself (like at https://github.com/gravitystorm/openstreetmap-carto/pull/991#event-254340763 ). Anything else means that I did nothing with given PR.

> Few days with no additional input should not be a problem (if it's not something serious like this regression), but a week or two would be a good mark of PR being forgotten or having some general problems that should be resolved (or just to be closed for some reason).

It means that PR waits for somebody who will review it. It is not possible that PR will be lost - we have no huge backlog of proposed patches and github interface is OK.

And on finding "general problems that should be resolved" people will give comment.

**Comment by kocio-pl** [comment]
Thank you both for the comments! 

Sorry for sounding too alarming probably - I was just not sure how is it supposed to be working (especially in the context of this fix). Lack of time for OSM is something I can perfectly understand because I'm doing it also as a pure hobbyist, it was just not clear to me if it may be also some other problem with decision making or workflow within a project.

**Comment by kocio-pl** [comment]
@gravitystorm Any chance to release v2.35 containing this fix anytime soon (there were more changes lately, so naming it v2.34.1 wouldn't make sense probably)?

**Comment by matkoniecz** [comment]
@kocio-pl You may want to subscribe to updates from https://github.com/openstreetmap/chef/ (for example https://github.com/openstreetmap/chef/issues/36 is relevant in that case).

**Comment by kocio-pl** [comment]
Thanks!

**Pull request merged**
