### PR TITLE
Adding shop=boutique icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1706.
boutique-clothes

It looks like there is no way to really recognize the difference between fashion, boutique and general clothes shops. As shop=fashion is already displayed the same as shop=clothes, only shop=boutique rendering change was needed.

### CODE REVIEW

**Comment by math1985** [comment]
As far as I'm concerned, shop=clothes is preferred over shop=boutique for boutique clothes shops, so I'm not sure whether we should encourage the shop=boutique tagging?

**Comment by kocio-pl** [comment]
Hm, I'm not sure. This "preference" is only a suggestion on Wiki and a "discussion" on this topic is short and it rather supports the existence of such shops. 

I will open next thread on Tagging to make sure what community thinks about it now and will report the outcome, because maybe there will be some clue how to deal with it and it's always good to at least try to make things straight once in a while.

**Comment by kocio-pl** [comment]
Seems I was already asking about it and [this is the only response I have received](https://lists.openstreetmap.org/pipermail/tagging/2015-August/025842.html). What do you think about it?

**Comment by kocio-pl** [comment]
My feeling now is it's in most cases the same as fashion, so should be rendered the same - the number of uses is so high, that we shouldn't ignore it and let tagging dept resolve the issue of clothes/fashion/boutique real meaning. I leave it to your discretion if you merge this code or just close, because for now I can't see anything more we could do with it.

**Comment by math1985** [comment]
I still think these shops would be better tagged as shop=clothes, so I'll closed this PR. Thanks anyway!

**Pull request closed without merging**
