### PR TITLE
Order landcover by osm_id

### LINKED ISSUE #2782: Should landcover be ordered by osm_id in addition to way_area?
Recently i saw a landcover area where the color varied arbitrarily depending on zoom level because there are two different areas with different tags but identical geometry and therefore identical way_area:

https://www.openstreetmap.org/way/346109314
https://www.openstreetmap.org/way/49188959

I think cases like this should get a consistent drawing order, probably best by ordering by osm_id in addition.

### PR DESCRIPTION
**Pull request by matthijsmelissen**
This resolves #2782

### CODE REVIEW

**Comment by andrzej-r** [comment]
Do you thing it would be possible to sort by feature instead. I understand sorting by osm_id would produce different rendering when someone deletes/recreates an object, which seems like a hack to me.

**Comment by matthijsmelissen** [comment]
> Do you thing it would be possible to sort by feature instead.

Hmm, good point. I've been thinking about it, but I think it would add quite a lot of code for a relatively small gain. So I think I'd prefer to leave it as it.

**Comment by sommerluk** [comment]
>  it would add quite a lot of code

Wouldn’t it be enough to leave the inner query as it is currently (without this PR), and add to the outer query ` ORDER BY feature, osm_id`? This should order by feature alphabetically (which is just as arbitrary as osm_id, but independent from deleting/re-creating objects in the OSM database) before ordering by osm_id…

**Comment by matthijsmelissen** [comment]
My bad, this would work of course. Will fix it.

**Comment by sommerluk** [comment]
Hm, my bad, should be `ORDER BY way_area DESC, feature, osm_id` on the outer query (and no order in the inner query), otherwise way_area wouldn’t be the primary order criterium any more.

**Comment by ImreSamu** [comment]
>I don't see that we need osm_id ordering if we've got feature in the ordering

imho - the original varied color problem is solved,  but  it can be a similar problem in the varied landcover labels.  ( in rare cases )

**Comment by pnorman** [comment]
> imho - the original varied color problem is solved, but it can be a similar problem in the varied landcover labels. ( in rare cases )

The landcover layer is used for fills, not labels.

**Comment by pnorman** [comment]
It needs changes to stop ordering after `feature`.

**Comment by Tomasz-W** [comment]
It resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1291 also.

**Comment by kocio-pl** [comment]
@matthijsmelissen What would you like to do with code? Do you have any plans?

**Comment by HolgerJeromin** [comment]
> It resolves #1291 also.

Why that?

**Comment by matthijsmelissen** [comment]
Updated.

**Comment by kocio-pl** [comment]
I'm not sure if you've seen this, but there's 1 conflict left (related to #2874).

**Comment by matthijsmelissen** [comment]
Superseded by #3441.

The current PR is a PR from a branch on gravitystorm directly, it should of course come from matthijsmelissen:landcover, which is fixed in the new PR.

**Pull request closed without merging**
