### PR TITLE
Render offices as dots + names

### LINKED ISSUE #271: Add rendering for office=government or office=administrative
It's quite common that big buildings used by the government are having several administrative department. It's not really good to tag all the departments within the name of the complete building like "name=department one and department two ...".

It would be nice if office=government and office=administrative would be rendered. In this case multiple points within one building could be tagged like this and the result would be rendered.

### LINKED ISSUE #1922: Render office=lawyer
Currently law offices aren't rendered at all, which is a problem in areas such as [this one](https://www.openstreetmap.org/#map=19/26.64414/-81.86889) in which an entire side of the block is law offices. They are useful and I see no reason not to render them. As for how they should be rendered, I suggest using the amenity pink styling with a [lawyer scale](https://2012thetrial.files.wordpress.com/2012/03/law-scale_jpg2.jpg) icon. Even though they are really tagged as offices, they are more comparable to medical offices like shop=optician or amenity=dentist.

### LINKED ISSUE #2570: Icon for office=newspaper
Hi!
office=newspaper is currently not rendered in the map. Can this be changed?

http://wiki.openstreetmap.org/wiki/Tag:office%3Dnewspaper
Icon: http://osm-icons.org/wiki/File:25040.svg
https://taginfo.openstreetmap.org/tags/office=newspaper

### PR DESCRIPTION
**Pull request by andrzej-r**
Rebased #3061 to a new master branch. No changes to the code. Incremental commits merged into a single one. So far testing yields the same results as with #3061.

RE #108
Fixes #271
Fixes #1922
Fixes #2570

### CODE REVIEW

**Comment by kocio-pl** [comment]
I guess we could close #3163 then?

**Comment by kocio-pl** [comment]
Thanks. I started testing and it looks like dark blue is too strong - maybe orange (like in natural=peak) would be better, because it blends better with brown buildings:

qregsgyf

**Comment by andrzej-r** [comment]
I agree darkblue stands out a bit too much among surrounding labels. I'll try to tone it down a bit. The colour is otherwise fine to me.

Landform-color is much too weak (barely readable) and it doesn't "feel like an office" to me ([example](https://www.openstreetmap.org/#map=18/51.51546/-0.09271)).
office3_l18_london8

**Comment by kocio-pl** [comment]
I think the dot is OK (but might be darker too), but the name could be then made darker to balance the problem how thin the letters are when using halo.

**Comment by andrzej-r** [comment]
Honestly, an office is the last thing coming to my mind when I see orange.

How about #4863A0 aka steelblue?
office3_l18_london9

**Comment by kocio-pl** [comment]
The text is too weak now to read it easily, but something in between might be good:

ox7iuxzg

**Comment by matthijsmelissen** [comment]
Another option would be simple gray text, or perhaps gray text with a gray dot.

**Comment by andrzej-r** [comment]
"gray" looks OK but it may be too similar to regular building labels. In fact, it looks more like a feature of a building than a POI:

office3_l18_london10

**Comment by andrzej-r** [comment]
I have to leave. Let me know if you've got other ideas to try and/or state your preference. I am not pushing anything yet.

**Comment by andrzej-r** [comment]
Any objections to I changing the colour to #4863A0 (steel blue)? @kocio-pl, looks like you liked the gray version. is that what you prefer? Any other ideas?

**Comment by kocio-pl** [comment]
I prefer steel blue. I was trying to indicate that I agree with your comment.

**Comment by rrzefox** [comment]
I've now deployed current master with this PR (with color-value changed to #4863A0) as well as 3164 on my server. Not all zoom levels have finished rerendering yet.

Links to the demo-places from above:
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#18.00/52.26082/20.99056
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#18.00/51.51546/-0.09271

**Comment by lakedistrictOSM** [comment]
I've had a look at a few places on the link above and I've noticed that `office=architect`, `office=accountant` and `office=insurance` all render in purple. Is this intentional? 

Also, `office=taxi` doesn't render at all.

**Comment by andrzej-r** [comment]
The intention was to render "amenity-like" offices the same way as other amenities. I don't have a strong opinion on that. I would like know what others prefer.

I haven't seen office=taxi neither in the wiki (unlike amenity=taxi) nor in iD presets. There are only 150 office=taxi tags in taginfo. Again, if popular opinion is that it is good to add it - I will do so.

It may be good to go through https://taginfo.openstreetmap.org/keys/office#values and check what other office= values should be rendered. Volunteers?

**Comment by Tomasz-W** [comment]
I still think we should use dark-blue for all offices, and make only one exeption - black government ones. I don't see reason for using purple or brown, which may be confusing for map users.

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Apr 2018, at 00:56, lakedistrictOSM <notifications@github.com> wrote:
> 
> I've had a look at a few places on the link above and I've noticed that office=architect, office=accountant and office=insurance all render in purple. Is this intentional?
> 


I think it’s strange architect and accountant (people you will have to  commission and then they’ll work a significant time on your project or accounting) are in the same category as an insurance office (not sure what that’s about, but it’s probably either an office where you might go to get an insurance contract (i.e. a kind of “shop”), or a back office where you can’t go at all as a client.

**Comment by andrzej-r** [comment]
Below is a list of the first 240 (out of 3708) office tag values from taginfo. The checkbox means the value is implemented in this PR.

- The PR implements most important office= values as encouraged by Wiki and supported in iD.
- There is a very long tail of perfectly valid and useful office= values.

What do you think about rendering all office tag values instead? Perhaps after filtering out discouraged tags. I think this may be a good approach for mapping feedback, would simplify the code and is not harmful (other than a few exceptions we can render all of them the same way).

The list:
- [x] government 94 636 22.82% ✔ An office of a (supra)national, regional or local government agency or department
- [x] company 86 853 20.94% ✔ An office of a private company
- [x] yes 35 367 8.53% ✔ Generic tag for unspecified office type.
- [x] estate_agent 27 658 6.67% ✔ A place where you can rent or buy a house.
- [x] insurance 22 567 5.44% ✔ An office at which you can take out insurance policies.
- [x] lawyer 17 373 4.19% ✔ An office for a lawyer.
- [x] administrative 14 379 3.47% ✔ DISCOURAGED, use office=government instead.
- [x] educational_institution 13 496 3.25% ✔ An office for an educational institution.
- [x] telecommunication 12 909 3.11% ✔ An office for a telecommunication company
- [x] ngo 9 408 2.27% ✔ An office for a non-government organisation.
- [x] it 6 345 1.53% ✔ An office for an IT specialist.
- [x] association 6 261 1.51% ✔ An office of a non-profit organisation, society, e.g. student, sport, consumer, automobile, bike association, etc…
- [x] accountant 5 364 1.29% ✔ An office for an accountant.
- [x] employment_agency 5 222 1.26% ✔ An office for an employment service.
- [x] research 5 046 1.22% ✔ An office for research and development
- [x] religion 4 708 1.14% ✔ An office of an religion instance.
- [x] architect 3 769 0.91% ✔ An office for an architect or group of architects.
- [x] financial 3 567 0.86% ✔ An office of a company in the financial sector
- [x] newspaper 3 253 0.78% ✔ An office of a newspaper
- [x] physician 3 099 0.75% -  
- [x] travel_agent 2 616 0.63% ✔  
- [x] therapist 2 585 0.62% ✔ Office for a physical therapy, such as physiotherapy, therapy against neurologic diseases or osteopathy.
- [x] political_party 2 386 0.58% ✔ An office of a political party
- [x] advertising_agency 1 763 0.43% ✔ A service-based business dedicated to creating, planning, and handling advertising.
- [x] tax_advisor 1 638 0.40% ✔ An office for a financial expert specially trained in tax law
- [x] notary 1 537 0.37% ✔ An office for a notary public.
- [x] energy_supplier 1 403 0.34% ✔ An office for a energy supplier.
- [x] foundation 961 0.23% ✔ An office of a foundation
- [x] logistics 630 0.15% ✔ An office for a forwarder / hauler.
- [ ] medical 544 0.13% -  
- [x] tax 469 0.11% ✔ Fiscal authorities, tax and revenue office.
- [ ] consulting 456 0.11% -  
- [ ] parish 447 0.11% ✔  
- [x] forestry 427 0.10% ✔ A forestry office
- [ ] coworking 419 0.10% ✔  
- [x] water_utility 383 0.09% ✔ The office for a water utility company or water board.
- [ ] property_maintenance 383 0.09% -  
- [ ] construction_company 383 0.09% -  
- [ ] vacant 340 0.08% -  
- [x] charity 277 0.07% ✔ An office of a charitable organization
- [ ] publisher 244 0.06% -  
- [x] quango 242 0.06% ✔ An office of a quasi-autonomous non-governmental organisation.
- [ ] camping 231 0.06% ✔  
- [x] guide 225 0.05% ✔ An office for tour guides, mountain guides, dive guides, etc.
- [x] moving_company 219 0.05% ✔ An office which offers a relocation service.
- [ ] engineering 203 0.05% -  
- [ ] university 200 0.05% -  
- [ ] cooperative 175 0.04% -
- [ ] podologist 173 0.04% -  
- [ ] administration 170 0.04% -  
- [x] surveyor 165 0.04% ✔ An office of a person doing surveys, this can be land survey, risk and damage evaluations of properties and equipment, opinion surveys or statistics.
- [ ] real_estate 161 0.04% -  
- [ ] transport 152 0.04% -  
- [ ] taxi 150 0.04% -  
- [ ] engineer 137 0.03% ✔ An office for an engineer or group of engineer.
- [ ] solicitor 131 0.03% -  
- [ ] healer 116 0.03% -  
- [ ] utility_charge_accounting 111 0.03% -  
- [ ] union 111 0.03% -  
- [ ] security 109 0.03% -  
- [ ] design 107 0.03% -  
- [ ] marketing 104 0.03% -  
- [ ] commercial 98 0.02% -  
- [ ] financial_advisor 95 0.02% -  
- [ ] bank 94 0.02% -  
- [ ] health_insurance 94 0.02% -  
- [ ] recruitment 88 0.02% -  
- [ ] construction 88 0.02% -  
- [ ] education 86 0.02% -  
- [ ] finance 80 0.02% -  
- [ ] psychologist 78 0.02% -  
- [ ] graphic_design 77 0.02% -
- [ ] church 75 0.02% -  
- [x] property_management 74 0.02% ✔ Office of a company, which manages a real estate property.
- [ ] private 72 0.02% -  
- [ ] utility 70 0.02% -  
- [ ] investment 70 0.02% -  
- [ ] Station␣2 69 0.02% -  
- [ ] healthcare 67 0.02% -  
- [ ] courier 66 0.02% -  
- [ ] fire_department 64 0.02% -  
- [ ] consultant 62 0.01% -  
- [ ] club 60 0.01% -  
- [ ] public_transport 59 0.01% -  
- [ ] financial_services 58 0.01% -  
- [ ] labor_union 57 0.01% -  
- [ ] auctioneer 55 0.01% -  
- [ ] nursing_service 55 0.01% -  
- [ ] travel_agency 54 0.01% -  
- [ ] organization 51 0.01% -  
- [ ] realtor 50 0.01% ✔  
- [ ] trade_union 50 0.01% -  
- [ ] communication 50 0.01% -  
- [ ] translation 50 0.01% -  
- [ ] radio_station 48 0.01% -  
- [ ] military 46 0.01% -  
- [ ] logistic 44 0.01% -  
- [ ] delivery 43 0.01% -  
- [ ] software 43 0.01% -  
- [ ] translator 43 0.01% -  
- [ ] media 43 0.01% -  
- [ ] solicitors 42 0.01% -  
- [ ] labour_union 42 0.01% -  
- [ ] real_estate_agent 42 0.01% ✔ DISCOURAGED - Use office=estate_agent instead
- [ ] mortgage 42 0.01% -  
- [ ] international_organization 41 0.01% -  
- [ ] builder 40 0.01% -  
- [ ] igo 39 0.01% -  
- [ ] incubator 39 0.01% -  
- [ ] goverment 38 0.01% -  
- [ ] estate_agency 37 0.01% -  
- [ ] doctor 36 0.01% -  
- [ ] insurance_agent 35 0.01% -  
- [ ] register 35 0.01% ✔ DISCOURAGED, use office=government + government=register_office instead.
- [ ] tourism 34 0.01% -  
- [ ] coworking_space 33 0.01% -  
- [ ] web_design 33 0.01% -  
- [ ] police 31 0.01% -  
- [ ] tutoring 31 0.01% -  
- [ ] service 30 0.01% -  
- [ ] electronics 30 0.01% -  
- [ ] Station␣3 30 0.01% -  
- [ ] letting_agent 30 0.01% -  
- [ ] airline 29 0.01% -  
- [x] private_investigator 29 0.01% ✔ An office of a private investigator
- [ ] reception 29 0.01% -  
- [ ] politician 28 0.01% -  
- [ ] camp_resident_committee 28 0.01% -  
- [ ] power_utility 27 0.01% -  
- [ ] NGO 26 0.01% -  
- [ ] consultancy 26 0.01% -  
- [ ] printing 26 0.01% -  
- [ ] laboratory 26 0.01% -  
- [ ] cleaning 26 0.01% -  
- [ ] training 25 0.01% -  
- [ ] advertising 25 0.01% -  
- [ ] school 25 0.01% -  
- [ ] dentist 24 0.01% -  
- [ ] television␣station 24 0.01% -  
- [ ] midwife 24 0.01% -  
- [ ] civil_engineer 23 0.01% -  
- [ ] wedding_planner 23 0.01% -  
- [ ] interior_design 21 0.01% -  
- [ ] apartments 21 0.01% -  
- [ ] pawnbroker 21 0.01% -  
- [ ] industrial 21 0.01% -  
- [ ] ingo 20 0.00% -  
- [ ] shipping_agent 20 0.00% -  
- [ ] social_facility 20 0.00% -  
- [ ] un-government 19 0.00% -  
- [ ] business 19 0.00% -  
- [ ] telecommunications 18 0.00% -  
- [ ] foreign_national_agency 18 0.00% -  
- [ ] rectory 18 0.00% -  
- [ ] council 18 0.00% -  
- [ ] public_service_provider 17 0.00% -  
- [ ] trade 17 0.00% -  
- [ ] unknown 17 0.00% -  
- [ ] Station␣1 17 0.00% -  
- [ ] Courier_Service 17 0.00% -  
- [ ] apartment 16 0.00% -  
- [ ] building_maintenance 16 0.00% -  
- [ ] radio 16 0.00% -  
- [ ] funeral_directors 15 0.00% -  
- [ ] Miteinander␣Teilen 15 0.00% -  
- [ ] administrate 14 0.00% -  
- [ ] news_agency 14 0.00% -  
- [ ] shipping 14 0.00% -  
- [ ] funeral_director 14 0.00% -  
- [ ] attorney 14 0.00% -  
- [ ] Private 13 0.00% -  
- [ ] broker 13 0.00% -  
- [ ] drainage_board 13 0.00% -  
- [ ] public 13 0.00% -  
- [ ] money_lender 12 0.00% -  
- [ ] utilities 12 0.00% -  
- [ ] Government 12 0.00% -  
- [ ] services 12 0.00% -  
- [ ] television 12 0.00% -  
- [ ] online_shop 12 0.00% -  
- [ ] post_office 12 0.00% -  
- [ ] chiropractor 12 0.00% -  
- [ ] non-governmental_organization 11 0.00% ✔  
- [ ] Massachusetts␣Trial␣Court␣Law␣Libraries 11 0.00% -  
- [ ] reli 11 0.00% -  
- [ ] cbo 11 0.00% -  
- [ ] general_contractor 11 0.00% -  
- [ ] nurse 11 0.00% -  
- [ ] * 11 0.00% -  
- [ ] information 11 0.00% -  
- [ ] bail_bond_agent 11 0.00% -  
- [ ] minicab 11 0.00% -
- [ ] catering 10 0.00% -  
- [ ] advertisement 10 0.00% -  
- [ ] leasing 10 0.00% -  
- [ ] land_surveyor 10 0.00% -  
- [ ] legal 10 0.00% -  
- [ ] driving_school 10 0.00% -  
- [ ] contractor 10 0.00% -  
- [ ] trade_organisation 10 0.00% -  
- [ ] Station␣4 10 0.00% -  
- [ ] Station␣5 10 0.00% -  
- [ ] political 10 0.00% -  
- [ ] designer 9 0.00% -  
- [ ] computer 9 0.00% -  
- [ ] customs 9 0.00% -  
- [ ] recruitment_agency 9 0.00% -  
- [ ] Manufacturer 9 0.00% -  
- [x] adoption_agency 9 0.00% ✔ A place where prospective parent/s may adopt a child or children.
- [ ] clerical 9 0.00% -  
- [ ] mortgage_broker 9 0.00% -  
- [ ] culture 9 0.00% -  
- [ ] home_care 9 0.00% -  
- [ ] state_agent 9 0.00% -  
- [ ] energy 9 0.00% -  
- [ ] general 9 0.00% -  
- [ ] fuel 9 0.00% -  
- [ ] print 8 0.00% -  
- [ ] rental 8 0.00% -  
- [ ] electrician 8 0.00% -  
- [ ] sport 8 0.00% -  
- [ ] railway 8 0.00% -  
- [ ] housing_association 8 0.00% -  
- [ ] printer 8 0.00% -  
- [ ] publishing 8 0.00% -  
- [ ] craft 8 0.00% -  
- [ ] employment 8 0.00% -  
- [ ] insurance_agency 8 0.00% -  
- [ ] nonprofit 8 0.00% -  
- [ ] bookmaker 8 0.00% -  
- [ ] chiropractic 8 0.00% -  
- [ ] survey 8 0.00% -  
- [ ] event_management 7 0.00% -  
- [ ] civic 7 0.00% -  
- [ ] public_utilities 7 0.00% -  
- [ ] electricity 7 0.00% -  
- [ ] serviced_offices 7 0.00% -  
- [ ] quantity_surveyor 7 0.00% -  
- [ ] building_management 7 0.00% -  
- [ ] estate 7 0.00% -

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Apr 2018, at 10:56, Andrzej <notifications@github.com> wrote:
> 
> Below is a list of the first 240 (out of 3708) office tag values from taginfo. The checkbox means the value is implemented in this PR.


I don’t think it makes sense to implement low usage tags of common things, and I am not sure the definitions are commonly agreed on (e.g. the suggestion to tag some public administration offices with office=government and subtags).

I also don’t know for example about office=property_management, whether this really should relate only to real estate, IMHO it would be much better to use a term like real_estate_management for the avoidance of doubt 
In any case it would also be a subclass of financial. 

Looking at the list, I believe we should at this time not implement most of these values, while a few (generally the most used) are probably fine. Still the whole office tagging doesn’t look mature for now

**Comment by dieterdreist** [comment]
sent from a phone

> On 7. Apr 2018, at 10:56, Andrzej <notifications@github.com> wrote:
> 
>  yes 35 367 8.53% ✔ Generic tag for unspecified office type.


rendering office=yes would be giving a strong incentive to people to not add any office class (especially if it is not currently rendered) but rather keep it “yes”. Should only be considered if we render all kinds of offices

**Comment by lakedistrictOSM** [comment]
If possible, all values of office=* should be rendered. 

IMO, using purple makes them look like shops which they are not - all values should be in dark blue. The only exception might be estate agents, but I don't have a strong opinion either way.

**Comment by andrzej-r** [comment]
OK, looks like the consensus is to render all office tags in steelblue colour (and not e.g. purple like I currently do for some of them). I will change that.

Things to decide:
- Shall we use a whitelist (current implementation), render all office=*, or use a blacklist (not render certain values). The more I think about it I feel we should render everything and let the mappers decide what tag values to use. Otherwise we will end up with a constantly evolving list of hundreds of tag values (just wait for bug reports "office=X is not supported"). We should simply not be in charge of that.
- rendering dots/icons on buildings/landuse/... areas. Positives: Dots help to identify an object there is no name= tag or when the label does not fit. Negatives: Dots are distracting when a simple label on a building would suffice. The implementation is surprisingly complicated, though. For example how do we test if at z19 a label will not be fit so that we should add a dot instead (we can't)? What to do with areas different from building=? What to do when both building= and office= tags are set but there is no name= tag? All of these issues are solved by adding a dot, which may not be pretty but is simple, functional, and provides a good feedback to the mappers. On a purely technical side, I have no code for hiding the dots on buildings and I don't expect anything working well anytime soon.

**Comment by andrzej-r** [comment]
Change colour of all office tags to steelblue. Removed office=yes.

Other than the two potential modifications mentioned above, which would require going back to a drawing board and a new PR, I think the code is in a good shape for merging.

[Example:](https://www.openstreetmap.org/#map=19/51.51945/-0.09855)
office3_l19_london11

**Comment by kocio-pl** [comment]
I think it's a good decision. In my opinion offices should always have dot (I'm still unsure what about the whole buildings, but I'm not against it) and we should exclude some values, similar to shops (with `office=yes` as additional value for exclusion). Prioritizing with zoom levels is a nice tool, however I haven't tested it well enough yet.

**Comment by andrzej-r** [comment]
I'll try a blacklist approach separately to see how it works.

I think we only need to exclude office=yes when using a whitelist, so we don't create an incentive to tag everything that isn't supported as office=yes. This is not a problem with a blacklist because we'd support all office values anyway. So my proposal is to use the same exclusions as we use for shops.

As for dots on buildings, we need them in certain situations so I will keep them. I will check if there is anything we can do to minimise visual noise.

Do you know how to check a type of an object (point, way) in carto?

**Comment by kocio-pl** [comment]
My current idea is to merge this PR as it is and later add all the other offices (minus exclusions) on z19+.

> Do you know how to check a type of an object (point, way) in carto?

In this case you mean probably not the shape, but the helper value `is_building`, for example:

https://github.com/gravitystorm/openstreetmap-carto/blob/6bf5512bfb2c40246552d37b093b6113cf4da25a/amenity-points.mss#L1649

**Comment by andrzej-r** [comment]
I am OK with that. I also prefer to first release what we have and focus on possible improvements later. 

The simplest and the cleanest solution would be to replace the current "other offices" sections with a catch all clause. But, if you want, we can indeed introduce a 3rd category of office pois rendered from z19.

BTW, the is_building test is not sufficient. I have seen occurrences of office ways with area=yes, landuse=*, or even nothing at all (just office). It would be good to have something like is_way/is_point.

**Comment by kocio-pl** [comment]
These informations are on the database layer level, but then they are somehow unified, so we might add some special values, but I'm not sure if it's really needed. Not using the dots just for the buildings would be OK for me.

**Comment by andrzej-r** [comment]
I think it all boils down to Mapnik not implementing: "Render this label but if it doesn't fit render this icon/shape instead". Or at least I think it cannot do that. Without that, the only solution that guarantees that something will remain visible is to always render the icon (plus, optionally, the label).

**Comment by andrzej-r** [comment]
Anything left to do in the current version?

As suggested, I am deferring the blacklist-type implementation changes until after this PR is merged.

**Comment by matthijsmelissen** [comment]
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#18.00/52.06148/4.52525
Looks fine to me.

**Comment by matthijsmelissen** [comment]
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#18.00/52.06148/4.52525
Looks fine to me.

Thanks for your work @andrzej-r!

**Comment by matthijsmelissen** [comment]
@kocio-pl I think we can merge this. As you have been most active in this discussion, I'll leave that to you.

**Comment by kocio-pl** [comment]
The only thing that we could change before I merge it is that we could start rendering all the "other" offices with just a dot (without name) from z17, because when they have an address number, it looks to me both more cluttered than dots and less intuitive (one building should normally have just one address, multiple numbers suggest more complicated addressing, not more POIs). This place is a good example of this problem.

What do you think about it?

**Comment by dieterdreist** [comment]
sent from a phone

> On 16. Apr 2018, at 19:47, kocio-pl <notifications@github.com> wrote:
> 
> one building should normally have just one address, multiple numbers suggest more complicated addressing, not more POIs


in Italy every access door and gate gets a housenumber, so buildings will usually have more than one housenumber. Basically in Italy addresses are not about buildings but about entrances (and even potential entrances).

Cheers,
Martin

**Comment by kocio-pl** [comment]
Exactly - that's more complicated addressing system and I think that bunch of offices should look different than this. I have created a ticket #962 long time ago for avoiding this.

**Comment by andrzej-r** [comment]
I can do that but afair you wanted to implement this feature outside of this pr, so I don't have anything ready just yet. 

It should be fairly easy to do but it may still take several days because I can't access my computer atm.

**Comment by kocio-pl** [comment]
OK, sure. Sorry for such a late suggestion, but this is non obvious change of cartography, so I try to judge all the details from different angles, even if the general idea and code are quite simple.

This change would make office priority system less clear, which was quite nice idea, but dots are not as big source of clutter as labels (or address numbers) are, so it makes sense for me to render all office dots on z17+ and indicate the priority just by initial zoom level for labels (z17+ for important ones, z18+ for less important ones - and z19+ for all the rest in the next step).

**Comment by andrzej-r** [comment]
I'm referring to the issues you reported in https://github.com/gravitystorm/openstreetmap-carto/pull/3061#comment-368566582

although (afair) in that case the dot was rendered at a higher zoom level than the label. I understand you would like to render the dot from z17 and the labels from z17-19 - it may work this way around. I will try that.

**Comment by dieterdreist** [comment]
sent from a phone

> On 17. Apr 2018, at 02:31, kocio-pl <notifications@github.com> wrote:
> 
> dots are not as big source of clutter as labels (or address numbers) are


the dots are “thick” compared to other signatures, and in color, they probably have a much bigger visual impact than fine black lines like housenumbers or gates.

**Comment by andrzej-r** [comment]
Office dot sizes are consistent with that of other points (shops, amenities). I don't mind changing them all (I agree they could be smaller) but IMHO that's outside the scope of this PR.

**Comment by kocio-pl** [comment]
I like the result. The same example place in Warsaw as before shows nice labels progression:

z17: office=newspaper
dpxkk lh

z18: + office=lawyer and office=company
acqg_gyg

z19: + office=yes
4zmdg4nt

**Comment by kocio-pl** [comment]
[London example](https://www.openstreetmap.org/#map=17/51.51264/-0.10366):

z17

Before
d1g1b9c3

After
jpoc71sl

z18

Before
33y3gtxr

After
dcygs4gv

z19

Before
kykqidxy

After
sr7f2pcd

**Comment by Tomasz-W** [comment]
Just my thoughts about first comment here, and what this PR is actually resolving:
* https://github.com/gravitystorm/openstreetmap-carto/issues/108 Most people are against adding generic dot for amenities, and there are separate tickets when someone want special icon for certain amenity=* tag, so I think that issue will be resolved when this PR will be merged
* https://github.com/gravitystorm/openstreetmap-carto/issues/271 There was disscusion about using townhall icon or black dots for gov offices, but I don't know what was the output
* https://github.com/gravitystorm/openstreetmap-carto/issues/1922 There is pending disscusion about use a section sing for this feature
* https://github.com/gravitystorm/openstreetmap-carto/issues/2570 There was no icon proposal or even idea for it, so it will be resolved with this PR as a dot.

**Comment by kocio-pl** [comment]
Thanks for the work, I think it's mature enough and it's time to release it. Further tuning is always possible and might be even needed (just like with towers), but that's a solid base which should not be talked to death on this stage. Soon we will know what the people think about it and I'm curious about it...

It's also good to review which issues have been really fixed by this code, but it's a separate problem which we could solve later.

**Pull request merged**
