### PR TITLE
Check range of supported Carto and Mapnik with Travis

### PR DESCRIPTION
**Pull request by pnorman**
Doing a PR to test the travis build

### CODE REVIEW

**Comment by pnorman** [comment]
Our minimum version of CartoCSS doesn't support the `-a` option, so I'm not sure what version of Mapnik it's assuming, so it's possible it's producing output that 2.1.0 doesn't support.

What's going to finally drive me to writing a new style based on different technologies is struggling with Mapnik.

**Comment by kocio-pl** [comment]
That would be a huge porting effort... What technologies do you mean?

**Comment by kocio-pl** [comment]
I guess this PR is no longer needed and can be closed because od merging https://github.com/gravitystorm/openstreetmap-carto/pull/2473?

**Comment by math1985** [comment]
Agree.

**Pull request closed without merging**
