### PR TITLE
Add rendering for power=plant

### LINKED ISSUE #1835: Recognize and render power=plant
osm-carto currently recognizes and draws power=station, but this seems deprecated and is not listed in the OSM wiki (if it ever was). Instead, the wiki states to use power=plant. Please consider making osm-carto draw it.

Example objects: http://osm.org/way/237100663

### PR DESCRIPTION
**Pull request by kreed**
This will render names for power plants.

Closes #1835, supersedes #1771

### CODE REVIEW

**Comment by matkoniecz** [comment]
I would expect that power=plant would be anyway tagged as landuse=industrial. Are there cases of correctly tagged places where rendering power=plant like landuse=industrial would improve situation?

Also, #1835 mentions that power=station should not be rendered, maybe it should be removed from rendering?

**Comment by HolgerJeromin** [comment]
right now we have about four times more stations that plants. So perhaps it is too early to drop station rendering. But as this tagging has no documentation this could be a valid thing.

But you are right, most power=plant should have landuse=industral or for small things building tag. So perhaps drop power=plant and station for promoting landuse/building.

**Comment by kreed** [comment]
> I would expect that power=plant would be anyway tagged as landuse=industrial. Are there cases of correctly tagged places where rendering power=plant like landuse=industrial would improve situation?

It would be helpful in cases where the power plants are located inside of larger industrial areas. Adding a landuse=industrial tag to such plants would be redundant.

About one-third of all power plants are currently tagged with landuse=industrial (I'm analyzing the [extract from here](http://enipedia.tudelft.nl/wiki/Extracting_Power_Data_from_OpenStreetMap), since the tag isn't common enough for taginfo statistics).

```
power=# SELECT count(*) FROM planet_osm_polygon WHERE power='plant';                                                                                                                
 count 
-------
  2592

power=# SELECT count(*) FROM planet_osm_polygon WHERE power='plant' AND landuse='industrial';                                                                                       
 count 
-------
   867
```

> Also, #1835 mentions that power=station should not be rendered, maybe it should be removed from rendering?

Yes, power=station is problematic because of ambiguous tagging. Both power plants and power substations are tagged with it. I would prefer to deal with it in a separate PR though.

**Comment by HolgerJeromin** [comment]
thanks i did not thought about a plant within an industrial complex.

i just fixed a few substations which were tagged as `power=plant` (while searching `power=plant and landuse!=industrial` with overpass). 8-/
I cannot think of a rendering (aka an icon which is plant, but no substation) to prevent this.

**Comment by matkoniecz** [comment]
> plant within an industrial complex

In that case rendering only name would be better. My test found many mistagged substations and individual power plants without tagged landuse=industrial.

Rendering area (like landuse=industrial) hides that some data is missing - for example see https://cloud.githubusercontent.com/assets/899988/9902546/92f733ee-5c6f-11e5-8e17-32d9056488b6.png

**Comment by kreed** [comment]
Good point. That sounds like a good solution. I'll update the code.

**Comment by kreed** [comment]
Updated. I also reordered the coalesce statement so that the power color is used over the industrial color when both tags are present.

**Comment by matkoniecz** [comment]
If you are interested in making more pull requests - #887 is very similar.

**Pull request merged**
