### PR TITLE
move memorial icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Icon: [nebulon42/osmic/memorial-16.svg](https://github.com/nebulon42/osmic/blob/master/tourism/memorial-16.svg)

before
memorial_before

after
memorial_after

### CODE REVIEW

**Comment by math1985** [comment]
Tester recognizes neither before nor after.

I'm not sure if this should rendered significantly/on low zoomlevels at all. Some mrmorials are significant landmarks, but others are very minor compared to yhe surroundings.

**Comment by pnorman** [comment]
I think the new icon is an improvement - but the basic idea of the icon needs revisiting, as in my experience it's not clear what it means.

**Comment by HolgerJeromin** [comment]
yes,  the icon is good, but especially the german "Stolpersteine" are much too prominent.

**Comment by nebulon42** [comment]
Prominence: Agreed, but the icon is now smaller although sharper. This needs adressing by categorising using other tags.

Other icon: I thought about this a bit and it is hard to come up with something distinctive for memorial. The idea of depiciting a plate or stone with text on it is not so bad. Sometimes this are statues, but depiciting e.g. a head would not include all the other possibilities of memorial. The other icon I meant to use for monument ([monument-16.svg](https://github.com/nebulon42/osmic/blob/master/tourism/monument-16.svg)) might imply a larger structure.

**Comment by althio** [comment]
Regarding the icon itself: :+1: 

Regarding previous comments: I very much agree with @math1985 and @nebulon42 
> I'm not sure if this should rendered significantly/on low zoomlevels at all. Some mrmorials are significant landmarks, but others are very minor compared to yhe surroundings.
> Prominence: [...] This needs adressing by categorising using other tags.

As many other features, it would be great to have subtags and established rules (tiers for zoom threshold and rendering) so that:
* first tier: important/landmark/monumental features are rendered early (z16?) and maybe special rendering when second tier appears (slightly larger icon size? icon in square/circle?)
* second tier: common features are rendered at closer zoom levels (z18?)
* negligible features are not rendered or only a maximal zoom level and maybe special rendering (lighter as in private POI?).

**Comment by polarbearing** [comment]
@althio - would be good, but apparently (see #1066) subtags are not yet supported. 
If the monumental features are tagged as monument they could get a different icon as proposed in #758.

**Comment by kocio-pl** [comment]
Sooner or later we will need the subtags rendering - memorial table and memorial cemetery are very different beasts.

**Comment by math1985** [comment]
Memorial rendering clearly has issues, but at least everyone agrees that the new icon is an improvement, so I don't mind merging this.

**Pull request merged**
