### PR TITLE
Adding water park styles and icon

### PR DESCRIPTION
**Pull request by kaldari**
This change is to fix issue #370. It adds the necessary styles, icon,
and SQL queries to properly render water parks.

### CODE REVIEW

**Comment by kaldari** [comment]
Thank you!!

**Comment by Klumbumbus** [comment]
The area does not have a fill color. Is this intended? I think it should have one. maybe the same like leisure=park, or similar.

Example: http://www.openstreetmap.org/way/40724815

**Comment by nebulon42** [comment]
I just noticed that the icon is brown, while text is green. Was this intended to be like that?

**Comment by polarbearing** [comment]
Apparently the water_park did not make it into the landuse section in the project.yaml and thus is no more in the project.mml ?

**Comment by kaldari** [comment]
@nebulon42 The current styling was intended to match the styling of playgrounds. If this styling is incorrect, it should be changed for playgrounds as well.

**Comment by kaldari** [comment]
@polarbearing @gravitystorm When I originally created this patch, there was no project.yaml file. Could someone add it to the yaml file and re-add it to project.mml? Thanks!

**Comment by HolgerJeromin** [comment]
the project.yaml is right in master. the feature would not work otherwise, as the mml is regenerated from the yaml. math1985 fixed it while merging.
Only this pull request is showing the original code.

**Comment by polarbearing** [comment]
@HolgerJeromin: "the project.yaml is right in master. the feature would not work otherwise"

We are just discussing why it does not work for the landcover.

project.yaml 
Line 147 (landcover):  ('leisure_' || (CASE WHEN leisure IN ('swimming_pool', 'playground', 'park', 'recreation_ground', 'common', 'garden', 'golf_course', 'miniature_golf', 'picnic_table', 'sports_centre', 'stadium', 'pitch', 'track') THEN leisure ELSE NULL END)) AS leisure,

Line 1325 (amenity-points-poly): OR leisure IN ('water_park', 'playground', 'picnic_table', 'golf_course', 'miniature_golf')

Line 1351 (amenity-points): OR leisure IN ('water_park', 'playground', 'slipway', 'picnic_table', 'golf_course', 'miniature_golf')

The PR did add the water_park in line 124 to the project.mml, but that was before yaml was used.

**Pull request merged**
