### PR TITLE
remove leftover from background line for intermittent waterways

### LINKED ISSUE #2633: Rendering of intermittent streams broken
Rendering of intermittent streams seems broken in master.

Screen shot:
screenshot_2017-05-14_22-58-37

### PR DESCRIPTION
**Pull request by nebulon42**
fixes #2633

### CODE REVIEW

**Comment by pnorman** [comment]
The plan is to look at this tomorrow and release 3.3.1 and 4.0.0.

**Comment by nebulon42** [comment]
If you release 4.0.0 then please bump the carto requirement to the latest released version. Planned 0.18 has only one improvement in it which decreases parsing time for osm carto. Unfortunately, it is detrimental for OSM Bright. If I can fix this today there will be 0.18. Otherwise we would be fine with 0.17.3.

**Comment by imagico** [comment]
I can confirm this fixes the stream problem, however it does not fix the waterway bridge problem mentioned in https://github.com/gravitystorm/openstreetmap-carto/issues/2633#issuecomment-302891419

See also http://www.openstreetmap.org/#map=16/52.3037/8.9295

**Comment by imagico** [comment]
If i move

https://github.com/nebulon42/openstreetmap-carto/blob/63c559ab405826c03332aabec5f56f2198cf84f6/water.mss#L106-L109

after the bridgecasing block this seems to be fixed.  As said the code is fairly difficult to read and understand with the mixture of different things and drawing order sensitivity.  There could be other side effects we have not yet spotted.

**Comment by nebulon42** [comment]
@imagico Yes, you are right. This was the wrong drawing order. Sorry about that. Fixed now.

**Comment by nebulon42** [comment]
FYI. just released carto 0.18.

**Comment by javiersanp** [comment]
Please confirm that the waterway=streams, intermittent=yes black lines rendering of issue #2633 is fixed. I still view this problem in tiles drawn just now. See:
http://c.tile.openstreetmap.org/18/119298/109368.png/status
http://www.openstreetmap.org/#map=16/28.5444/-16.1554

Best regards, Javier.

**Comment by imagico** [comment]
As i have mentioned in 

https://lists.openstreetmap.org/pipermail/dev/2017-May/029904.html

3.3.1 has not yet been rolled out.  Just look when https://github.com/openstreetmap/chef/issues/124 is closed.

**Comment by javiersanp** [comment]
Waiting anxious :)
Thank you Christoph

**Pull request merged**
