### PR TITLE
move hairdresser icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
This particular icon is from Nori icon set used by https://github.com/hotosm/HDM-CartoCSS.

before
hairdresser_before

after
hairdresser_after

### CODE REVIEW

**Comment by matkoniecz** [comment]
Thanks for your work! I support accepting this PR.

**Comment by kocio-pl** [comment]
I feel new icon is much too "square", but it's perfectly recognizable anyway.

**Comment by nebulon42** [comment]
Maybe having the comb a bit rounded helps: hairdresser-182

**Comment by math1985** [comment]
I prefer the rounded comb.

**Comment by nebulon42** [comment]
Updated icon and preview.

**Pull request merged**
