### PR TITLE
move eat & drink related icons to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 by moving bar, pub, cafe, biergarten, fast_food and restaurant icons to SVG.
For icons see [nebulon42/osmic/eat-drink](https://github.com/nebulon42/osmic/tree/master/eat-drink).

(mostly) http://www.openstreetmap.org/#map=19/48.21218/16.37415

before
eatdrink_before
biergarten_before fastfood_before

after
eat_v2
biergarten_after fast_food_after

### CODE REVIEW

**Comment by pnorman** [comment]
I'd suggest rounding the tines of the fork, and also for both pieces of cutlery making the handle longer relative to the end, more like before.

**Comment by math1985** [comment]
Thanks for the PR.

I'm not still sure whether I prefer the clearer icons over the old icons, but I can't quite tell why.

Concrete suggestions:
- I would put the knife and fork a bit (1px?) closer together.
- Why is the top of the beer diagonal? If it is meant to represent foam, I think it doesn't work very well.

**Comment by mkoniecz** [comment]
In general - I like these new icons.

As usually it is a bit strange to see map with a changed icons, butI am gettng used to these new ones.

Handle for spoon and fork seem to be too short and/or wide. Biergarten icon is too geometrical - it is prettier than old but less obvious what it is representing (maybe changing foam shape would help?).

**Comment by nebulon42** [comment]
Thanks for the feedback.

> I'm not still sure whether I prefer the clearer icons over the old icons, but I can't quite tell why.

I agree with @mkoniecz that it might have to do with the unfamiliarity of the map, but I'm not sure.

The biergarten icon was not made by me but came from [Nori](https://github.com/hotosm/HDM-CartoCSS/blob/master/icons/poi/_nori.svg). I liked it quite a lot and I also think it works (maybe only for me). And since you recognised the foam part, it apparently works too. :-) For the restaurant icon, cutlery was intended to have incomplete handles as the important and recognisable parts are at the top.

I see that main concerns are with biergarten and restaurant, so I will try to improve these.

**Comment by mkoniecz** [comment]
> And since you recognised the foam part, this apparently works too

Well, to guess that I needed to know that it is representing biergarten.

**Comment by althio** [comment]
bar
Good

pub
Wavy surface is strange at lower resolution (hence maybe some remarks about
inclined/diagonal)

cafe
Good

biergarten
I like it too. I would prefer the foam to really spill out of the frame of
the glass to the side.

fast_food
Quite simple. Maybe add more 'layers' for cheese or salad?

restaurant
Fork is good for me, handle size and sharpness and all.
Spoon is too pointy to my taste, please consider making it rounder.
Alternatively I think a better icon for restaurant could be based on a fork
and a glass or a fork and a plate.

**Comment by nebulon42** [comment]
I have removed the wavy surface from pub, because, indeed, it did not look so good on small resolutions. I have updated restaurant too.

I still like the biergarten icon, but I can offer this as alternative:
biergarten_v2

**Comment by math1985** [comment]
What about an entirely different icon for biergartens? As far as I know, the type of beer served in biergardens is not different from the type of beer served in German pubs, so the icons currently make not very much sense. On the other hand, expressing both 'garden' and 'beer' in one picture is probably hard.

**Comment by kocio-pl** [comment]
Maybe this icon plus a bit of sun/cloud/grass/bench/tree would be sufficient to express beer+outdoor (not necessary the garden itself).

**Comment by nebulon42** [comment]
I have no idea why there even exists the Biergarten distinction. I would see a Biergarten simply as being an outdoor pub. Actually, the above depicted location is none. It is more a "Schanigarten", where you can sit outside a restaurant or pub.

For me the use of different types of beer glasses makes sense. The types may not have an intrinsic meaning, but I more associate the Pint glass with (English) pubs and Steins/Humpen with Germany/Austria/Biergarten.

> Maybe this icon plus a bit of sun/cloud/grass/bench/tree would be sufficient to express beer+outdoor (not necessary the garden itself).

I would like to avoid complex combinations as they make it harder to create legible icons.

**Comment by math1985** [comment]
Difference between bar and pub is unclear (but that might be a deeper OSM problem). Tester is confused about the fact that the glasses are half-empty. Other icons are fine.

**Comment by daganzdaanda** [comment]
*Tester is confused about the fact that the glasses are half-empty.*
Tester is clearly a pessimist. The glasses are definitely full and have a nice crown ;-) By the color of it, they all serve Guinness...
I like all of these. Especially the restaurant and fast-food.

**Comment by nebulon42** [comment]
Thanks again for testing. I guess this leaves us with biergarten as being left open for decision. As I like the first proposed icon, I suggest to have it in as well. But I'm happy for other concrete biergarten proposals/sketches (apart from descriptions).

**Comment by math1985** [comment]
Would making the beer glass 1px fuller be an option? Cultural differences, I know...

**Comment by nebulon42** [comment]
Here would be a more optimistic beer glass (new=left): pub-162 pub-16

For me also the fuller variant is ok.

**Comment by math1985** [comment]
I prefer the left one (but as I said, the optimal amount of foam on a glass of beer is heavily debated between countries...)

**Comment by nebulon42** [comment]
I have updated to the left pub version to get this merged. ;-)

**Comment by sommerluk** [comment]
@nebulon42 Maybe you could also provide an icon for food courts (different from the restaurant icon)? Idea: something like http://osm-icons.org/wiki/File:12050.svg maybe? Was first discussed at #1040

**Comment by nebulon42** [comment]
@sommerluk I would rather not add anything to this PR at this stage, but we can discuss at #868.

**Comment by math1985** [comment]
Thanks!

**Pull request merged**
