### PR TITLE
Drop rendering for landuse=field, military=barracks, and natural=desert

### LINKED ISSUE #589: landuse=field/natural=field
image

The middle-left brown-green transparent area is a [``landuse=field``](http://www.openstreetmap.org/way/23890170). It's a strong image with an opacity of 0.2

The [wiki documentation](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfield) says

> Although this landuse is rendered by Mapnik, it is not an officially recognised OpenStreetMap tag. Please use landuse=farm instead.
> There is no such thing as an "Officially recognised OpenStreetMap (sic) tag". People are free to use an tag.

It's not obvious from the rendering what it's supposed to be. The docs are no more helpful. JOSM doesn't have a preset for it.

There are 15k of them. 56% are last edited by MichaelCollinson, 21% are from Warofdreams, and only 23% last touched by other users.

https://www.openstreetmap.org/#map=15/53.9470/-1.8155 is an area with a bunch. There's no ``landuse=farm`` or ``landuse=farmland`` there.

There are also some ``landuse=field`` ``type=land_parcel`` relations, which I believe are discarded by osm2pgsql.

Do we really want to be encouraging such eccentric undocumented tagging by rendering this? If so, what do we want it to render like, because the current rendering is strange, to say the least, and it's not obvious from the colour what it means.

natural=field has 172 uses, and should probably be removed regardless of landuse=field.

### LINKED ISSUE #773: Change rendering natural=desert
The following issue has been moved over from [trac](https://trac.openstreetmap.org/ticket/4430):

I know that till today the proposal of the desert feature is not approved ( http://wiki.openstreetmap.org/wiki/Proposed_features/Deserts) but it is rendered in Mapnik already.

The problem is the kind of way the desert is rendered today. The rendering doesn't make sense at all as you can see here: http://www.openstreetmap.org/?lat=30.374&lon=34.836&zoom=9&layers=M

############

    The color 

############

The color needs to be changed as it doesn't make sense to show a desert that dark in brown. Desert should not be darker than a forest and as there is a lot of life and also villages in this area. The desert shouldn't be that present in Mapnik!

############

    The desert name 

############

    zoomlevel that show desert 

############

currently the zoomlevel = showing of desert doesn't make sense. The desert gets rendered already in zoom=8 in dark brown. The same way as the forest gets rendered in zoom=8. In zoom=9 the landuse farmland is rendered and in zoom=10 also landuse=sand is added. It looks very much like a swiss cheese.

In zoom=13 there is no desert rendered anymore.

############ Summary ############

The whole concept of showing the desert has to be reconsidered. The current displaying doesn't make so much sense.

We consider in Israel to remove the whole desert just because it is showing this strange way. I know that we shouldn't map to a renderer but in this case it looks just to bad to keep it this way.

Please see this thread in the discussion board:  http://forum.openstreetmap.org/viewtopic.php?id=14806

### PR DESCRIPTION
**Pull request by math1985**
Rationale for military=barracks:
We have landuse=military for the area already, and the buildings
themselves are just as well rendered as regular builidings.

Rationale for landuse=desert:
Ergs (sand dunes) are better tagged as natural=sand.
Other type of deserts don't have strict borders.

Rationale for landuse=field:
This is duplicate with landuse=farmland and landuse=grass.

Resolves #589.
Resolves #773.
Resolves #1053 (superceded).
Resolves #1072 (superceded).
Resolves #1074 (superceded).

### CODE REVIEW

**Comment by kocio-pl** [comment]
+1 for military=barracks.

**Comment by nebulon42** [comment]
+1
Field is already rendered like farmland, right? Why is it duplicate with grass?

**Comment by mkoniecz** [comment]
Note also that http://wiki.openstreetmap.org/wiki/Tag:military%3Dbarracks has "Status: Unspecified", http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfield describes tag as abandoned and rejected, http://wiki.openstreetmap.org/wiki/Tag:natural%3Ddesert is mainly warning that it is not verifiable.

**Comment by mkoniecz** [comment]
Also, there is some potential in using natural=desert for labels but it requires at least (1) improving natural=desert proposal, including solving "deserts don't have strict borders" problem, (2) finding method to properly display labels for large scale features (at least repeating labels are necessary).

**Comment by dieterdreist** [comment]
2015-01-06 1:00 GMT+01:00 math1985 <notifications@github.com>:

> Rationale for military=barracks:
> We have landuse=military for the area already, and the buildings
> themselves are just as well rendered as regular builidings.
>
>

I'd render a name for military=barracks. This is not to be confused with
landuse=military, which doesn't constitute an entity (like barracks does,
which are typically named, fenced etc.), but is rather a landuse attribute
for an area (e.g. can be arbitrarily split without loosing information),
i.e. it tells that the main usage of the tagged area is by the military,
but it doesn't tell for what it is used.

Please note that barracks can be very big features, useful for orientation
and "advertized" by street signs.

**Pull request merged**
