### PR TITLE
Reduce noise of swimming pools at low zoom

### LINKED ISSUE #585: swimming_pool outlines too noisy
It's not a big problem, but have a look at 
http://www.openstreetmap.org/#map=18/-20.27700/-40.29099 
and then zoom out. The outlines of the many small pools create a lot of visual clutter. Even at z14 there are tiny dark blue lines: 
http://www.openstreetmap.org/#map=14/-20.2731/-40.2982

I would say that the outlines should only render at close up zooms, 18 and 19 maybe. And the outlines could be less prominent.

### PR DESCRIPTION
**Pull request by jragusa**
Fixes #585

Changes proposed in this pull request:
* Remove outline of swimming pools between z14 and z17
* Lighten colour of outline

Test rendering with links to the example places:
https://www.openstreetmap.org/#map=15/43.7081/7.3168
Before
z15
swimming_poolfinal_before_z15

z17
swimming_poolfinal_before_z17

z19
swimming_poolfinal_before_z19

After
z15
swimming_poolfinal_after_z15

z17
swimming_poolfinal_after_z17

z19
swimming_poolfinal_after_z19

### CODE REVIEW

**Comment by jragusa** [comment]
with outline from z14
z15
swimming_poolfinal2_after_z15

z17
swimming_poolfinal2_after_z17

**Comment by Tomasz-W** [comment]
@jragusa I think you confused choosen one values. In the ticket we decided on `line-color: saturate(darken(@water-color, 20%), 20%);` and in this PR it's different (outlines are less visible)

**Comment by jragusa** [comment]
@Tomasz-W I indeed pushed wrong value for outline. See below same pictures with corrected outline. They are better visible.
z15
swimming_poolfinal2_after_z15
z17
swimming_poolfinal2_after_z17

**Comment by matthijsmelissen** [comment]
Thanks!

**Comment by matthijsmelissen** [comment]
I didn't - thanks for the pointer.

**Pull request merged**
