### PR TITLE
Add landuse=port same as landuse=industrial

### PR DESCRIPTION
**Pull request by sabas**
Simple addition of the landuse=port tag (http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dport)

Same as #437 but as a pull request, original idea proposed in #300

### CODE REVIEW

**Comment by matkoniecz** [comment]
> Files project.mml and - differ

> project.yaml and project.mml are not in sync!

> You should only modify project.yaml, not project.mml and run scripts/yaml2mml.py before committing.

> Read https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#editing-layers for further information.


Also, I think that accepting this would encourage fragmentation of landuse. I think that it is similar situation as #1716.

Most likely landuse=industrial, industrial=port or landuse=commercial, commercial=port (depending on a port type) would be a better tagging.

**Comment by matkoniecz** [comment]
I added industrial=port to http://wiki.openstreetmap.org/wiki/Proposed_features/industrial#Industrial

**Comment by imagico** [comment]
Although the tag page on the wiki mentions the tag is for land areas only current use frequently covers water which cannot currently be rendered in a reasonable way.

Apart from that i partly share the concerns of @matkoniecz - a port is not necessarily an industrial area.  It could make sense to better render port features in a distinct way (in a similar way as airport features are rendered for example) but this is technically challenging, especially from the water side.

**Comment by sabas** [comment]
@matkoniecz "commercial" isn't needed imho (as in available to general public): I left out ferries and marinas because are already covered by other established tags.

My test area is http://overpass-turbo.eu/s/aQx
As you can see I added cargo=* to a ferry_terminal although unnecessary.

I could retag if the combination landuse=industrial + industrial=port is a better fit (as the majority of this tag was added by myself)

**Comment by matkoniecz** [comment]
From view of data consumer landuse=industrial + industrial=port is far better - one of the most frustrating things in using OSM data is discovering that there is yet another way to express the same thing.

With such cascading tagging scheme one may support just landuse=industrial and ports will also be handled. And somebody interested in special display for port areas may check key industrial.

But it is better to continue this discussion on tagging mailing list or on wiki - http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/industrial or http://wiki.openstreetmap.org/wiki/Talk:Tag:landuse%3Dport

**Comment by pnorman** [comment]
Low number of uses, tagging needs working out still.

I'm skeptical about adding *another* landuse tag, as this makes consuming data more difficult.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 08.08.2015 um 20:40 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> Most likely landuse=industrial, industrial=port or landuse=commercial, commercial=port (depending on a port type) would be a better tagging.


a lot of ports will be industrial, (not sure for passenger oriented ports), commercial doesn't seem right for a port. Anyway, rather than looking at subtags for attributes like landuse we should focus on main tags like man_made=port or similar

**Comment by mboeringa** [comment]
> **From view of data consumer landuse=industrial + industrial=port is far better - one of the most frustrating things in using OSM data is discovering that there is yet another way to express the same thing.**
> 
> With such cascading tagging scheme one may support just landuse=industrial and ports will also be handled. And somebody interested in special display for port areas may check key industrial.

+1, this is a major issue, especially with only marginally documented tagging schemes. However, even with better documented tagging schemes, the issue of multiple tagging schemes remains a headache from the point of data consumers, like you say. The SQL statements or filter expressions needed to extract what are essentially the same objects, can get really complicated to the point of being completely incomprehensible for novice users.

**Comment by dieterdreist** [comment]
sent from a phone

> Am 08.08.2015 um 20:54 schrieb Christoph Hormann <notifications@github.com>:
> 
> Apart from that i partly share the concerns of @matkoniecz - a port is not necessarily an industrial area. It could make sense to better render port features in a distinct way (in a similar way as airport features are rendered for example) but this is technically challenging, especially from the water side.


I agree.

If mappers were starting to adopt this proposal it would mean moving to a different way of tagging. Until now we had quite rough landuse attributes (at least for the main built up uses like residential industrial etc) and used keys like man_made and amenity for features. If I read this proposal correctly it suggests to use a landuse subtag to say eg something is an oil mill.

My suggestion is to deprecate the proposal in its current form and use the industrial key  to subtag industrial landuse on a less specific level (eg heavy industry vs light industry, producing vs storage, etc.)

**Comment by matkoniecz** [comment]
It is better to continue this discussion on tagging mailing list or on wiki - http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/industrial or http://wiki.openstreetmap.org/wiki/Talk:Tag:landuse%3Dport

**Pull request closed without merging**
