### PR TITLE
Junction names also on areas

### LINKED ISSUE #1253: Render junction=yes on areas
Since #813 the name of junction=yes is rendered on points. This tagging is used for simple junctions. A tagging for complex junctions was in discussion when #813 was merged. In the meantime, discussion/voting has been terminated. So it would be nice to render the name of junction=yes also when it occurs on areas (same font/style like on points).

### PR DESCRIPTION
**Pull request by sommerluk**
Fixes #1253 by rendering junction names also on areas.

### CODE REVIEW

**Comment by math1985** [comment]
Please remind me, why does this need to go into the lua branch?

**Comment by sommerluk** [comment]
Honestly, I’m not even sure.

junction=yes is treated as linestring by the current database import. So it will not work without a database reload. So I’ve tested this code in the lua branch.

However, looking at the code, I suppose that it could also be merged into the normal branch without producing errors (but I would have to test this before…). It would simply not change the rendering while the database import continues using the old/current style file. But it might be easier to synch between master branch und lua branch? Do you prefer a PR against master?

**Comment by math1985** [comment]
> . So it will not work without a database reload

I think then the lua branch is the right one place :)

**Comment by pnorman** [comment]
I'm inclined against accepting any PRs for style changes with the Lua branch and would rather focus on technical work with it right now.

**Comment by math1985** [comment]
> I'm inclined against accepting any PRs for style changes with the Lua branch and would rather focus on technical work with it right now.

+1, let's not accept new features in the lua branch until it has been rolled out to the openstreetmap.org servers, also to make debugging any possible problems easier.

**Comment by sommerluk** [comment]
> not accept new features in the lua branch until it has
> been rolled out to the openstreetmap.org servers

What would be the timeframe for this?

**Comment by math1985** [comment]
> What would be the timeframe for this?

There are interdependencies between a large number of volunteers, so unfortunately it's rather difficult to give a timeframe.

**Comment by pnorman** [comment]
Closing since we're not accepting PRs against the Lua branch and a new PR will need to be opened post-merge. The exact same branch might be usable, but it has to be a new PR for technical reasons.

**Pull request closed without merging**
