### PR TITLE
Manually add max/min zoom to layers

### PR DESCRIPTION
**Pull request by pnorman**
**For discussion**

I had to manually compute min/max zooms for layers and ended up storing them as if it were a TM2 style YAML file. Is this something that would be generally useful?

cc @yohanboniface

### CODE REVIEW

**Comment by math1985** [comment]
I think this would make it harder to edit the code, as minzoom's will need to be edited at two places in the code.

What's the benefit of this? Is there a performance benefit?

**Comment by pnorman** [comment]
> What's the benefit of this? Is there a performance benefit?

Vector tiles - which enforce a separation between data layer generation and styling that layer. Without it, it's not practical to render any vector tiles as there is no information about which layers are valid at a particular zoom.

**Comment by math1985** [comment]
@pnorman Sorry for my ignorance, but what would be the effect of having all layers valid from zoom 0 to 20?

One of the goals of this project was to make the code easier to edit, and I'm quite sure people new to the project will overlook this and wonder why their changes don't work. If it's absolutely necessary for vector tiles we can merge it though.

**Comment by pnorman** [comment]
> @pnorman Sorry for my ignorance, but what would be the effect of having all layers valid from zoom 0 to 20?

You would generate end up generating every layer at every zoom - so buildings for the world at z0

**Comment by gravitystorm** [comment]
I think this is worth doing. I realise that it's unnecessary for the current rendering stack so it's a maintenance overhead, but the first thing anyone looking into vector tiles will have to do is recreate this work. If 3-4 people are experimenting then that's a bunch of time going to waste!

**Comment by matkoniecz** [comment]
I am not sure whatever it is some coincidence that I am misinterpreting or is it TileMill stupidity but I discovered noticeable performance gain for removing building layer from z12, where it was not affecting rendering (#2190).

Given that performance gain was not expected I will test it again whatever change is real.

**Pull request merged**
