### PR TITLE
Add more barrier icons

### LINKED ISSUE #846: Add rendering for barrier points
barrier=stile is not rendered. It should be where ever gate is being shown. Knowing where stiles are on country footpaths is useful when walking.

See also https://trac.openstreetmap.org/ticket/3546.

### PR DESCRIPTION
**Pull request by Adamant36**
This PR adds more icons for barriers. It closes #846 

Motorcycle barrier
https://www.openstreetmap.org/#map=19/53.20660/-1.41045
motorcycle barrier
Cycle barrier
https://www.openstreetmap.org/#map=19/53.22609/-1.41716
cycle barrier
Kissing gate
https://www.openstreetmap.org/#map=19/52.45566/-1.58009
kissing gate
Full height turnstile
https://www.openstreetmap.org/#map=19/52.19147/-1.48791
full-height turnstile
Turnstile
https://www.openstreetmap.org/#map=19/51.50322/-0.11377
turnstile

Lots of gratitude to everyone involved, especially @Tomasz-W for making the icons and keeping track of everything.

### CODE REVIEW

**Comment by matthijsmelissen** [comment]
Great to see these being added!

**Comment by Adamant36** [comment]
I dont know. I like the kissing gate icon. Even if its bigger. The normal gate icon is pretty tiny. So I think its more on that. Their different things anyway. Plus, the current gate tagging is also used for pedestrian walkway gates in front houses. Its not just exclusive to cars. 

I'll test it. You want it done with the bollard dot or with an icon?

**Comment by Tomasz-W** [comment]
> I'll test it. You want it done with the bollard dot or with an icon?

Bollard dot. The thing is that turnstiles are often mapped very dense and underground, so it may be unreadable, so it needs testing.

**Comment by jragusa** [comment]
Motorcycle barriers look like a pliers and the vertical shape is not intuitive. Why not using the same for both motorcycle and cycle barriers ?

**Comment by Adamant36** [comment]
Google pictures of them. They dont look the same in real life. The motorcyle barrier looks pretty close to how it looks in real life.

**Comment by Adamant36** [comment]
@Tomasz-W, here you go. I think all the locations look OK. Location 1 and 2 in particular should probably be tagged as lines anyway. 
**Location 1** 
z17
location 1 z17
z18
location 1 z18
z19
location 1 z19
**Location 2**
z17
location 2 z17
z18
location 2 z18
z19
location 2 z19
Location 3
z17
location 3 z17
z18
location 3 z18
19
location 3 z19

**Comment by trigpoint** [comment]
> Google pictures of them. They dont look the same in real life. The motorcyle barrier looks pretty close to how it looks in real life.
I would agree, looking at that symbol on the map I would instantly know what it is without needing to look at that the map legend.

**Comment by matthijsmelissen** [comment]
To be honest, cycle barrier is not intuitive to me either - but I don't know if we can come up with something better?

**Comment by Adamant36** [comment]
It looks like the picture of the cycle barrier on the wiki from above at least. I think the fact that its tagged on a highway would help to. Theres only a small number of things it could be. Plus, I dont know how else the icon could look.

**Comment by Adamant36** [comment]
@matthijsmelissen, I wouldn't necessarily call this a WIP. There doesn't seem to be a next step in the testing process anywhere. Unless I'm missing something. Someone just saying they don't like an icon doesn't really count as needing more work in my opinion (especially if they don't provide an alternative and the vast majority of people are for it). So I think its ready for testing/merging by an admin.

**Comment by matthijsmelissen** [comment]
I wasn't sure if there's anything else you wanted to do with the suggestions given. Thanks for indicating it's ready, going to review it then!

**Comment by matthijsmelissen** [comment]
> The motorcyle barrier looks pretty close to how it looks in real life.

I think it's a misconception that icons should look like the object they depict. The best icons often don't. Clothes shops don't look like t-shirts, night clubs don't look like music notes, and churches don't (necessarily) look like crosses.

**Comment by matthijsmelissen** [comment]
I'm going to merge this now. If anyone has ideas for better icons, feel free to submit icons.

@Adamant36 Just a small note, in the future please be careful not to introduce unnecessary whitespace at the end of lines.

**Comment by Adamant36** [comment]
My bad. I thought I checked it. Thanks for merging it.

**Comment by Adamant36** [comment]
> I think it's a misconception that icons should look like the object they depict. 
Does that mean the next time I don't like an icon that I can argue against it by saying it doesn't look abstract enough?

**Comment by matthijsmelissen** [comment]
> Does that mean the next time I don't like an icon that I can argue against it by saying it doesn't look abstract enough?

No, but you cannot argue that something is a good icon just because it looks like the object its depicting.

**Comment by wilmaed** [comment]
My proposal:

------------------------------------------------------------------

barrier=kissing_gate
SVG:
https://github.com/wilmaed/foo/blob/master/kissing.svg
14px:
kissing2

------------------------------------------------------------------

barrier=turnstile
SVG:
https://github.com/wilmaed/foo/blob/master/drehkreuz.svg
14px:
drehkreuz2

------------------------------------------------------------------
barrier=swing_gate 
similar to a lift gate but rotates sidewards to open

SVG:
https://github.com/wilmaed/foo/blob/master/swing_gate.svg
14px:
swing_gate2

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dswing_gate
Usage: 21426 Entries
https://taginfo.openstreetmap.org/tags/barrier=swing_gate

------------------------------------------------------------------

barrier=hampshire_gate
SVG:
https://github.com/wilmaed/foo/blob/master/hampshire_gate.svg
14px:
hampshire_gate2

https://wiki.openstreetmap.org/wiki/Tag:barrier=hampshire_gate
Usage: 3259 Entries
https://taginfo.openstreetmap.org/tags/barrier=hampshire_gate

------------------------------------------------------------------

barrier=bump_gate
SVG:
https://github.com/wilmaed/foo/blob/master/bump_gate.svg
14px:
bump_gate2


https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dbump_gate
Usage: 2138 Entries
https://taginfo.openstreetmap.org/tags/barrier=bump_gate

------------------------------------------------------------------

barrier=full-height_turnstile
SVG:
https://github.com/wilmaed/foo/blob/master/full.svg
14px:
full2

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dfull-height_turnstile
Usage: 855 Entries (very low, but nevertheless an important info, because entry usually only with ticket)
https://taginfo.openstreetmap.org/tags/barrier=full-height_turnstile

------------------------------------------------------------------

barrier=log

SVG:
https://github.com/wilmaed/foo/blob/master/log.svg

14px:
log2

https://wiki.openstreetmap.org/wiki/Tag:barrier%3Dlog

**Comment by kocio-pl** [comment]
Please open new ticket with this proposition.

**Pull request merged**
