### PR TITLE
Update CoC to include ethnicity & national origin

### PR DESCRIPTION
**Pull request by rory**
I propose adding these "ethnicity" and "national origin" to discimrimination section. This mirrors [EU anti-discrimination](http://eur-lex.europa.eu/LexUriServ/LexUriServ.do?uri=CELEX:32000L0043:EN:HTML). Within Europe, there are many examples of racial/ethnic discrimination that might not fit into definitions of "race", and adding ethnicity can help clarify this here.

### CODE REVIEW

**Comment by pnorman** [comment]
We can change ours independently, but has this been suggested to the Go code of conduct which ours is based on?

**Comment by rory** [comment]
I haven't done that yet. Maybe I should...

**Comment by pnorman** [comment]
> I haven't done that yet. Maybe I should...

Otherwise, I could (eventually). Go is a bigger project so has more capacity for reviewing changes like this, and changes to the Go code will impact more conduct overall.

**Comment by pnorman** [comment]
Sent off an email.

I'm leaning in favour of merging, but of course want to see if they have anything to add.

**Comment by pnorman** [comment]
cross-reference https://go-review.googlesource.com/#/c/32133/

**Comment by pnorman** [comment]
I'm going to merge in the upstream changes and then look at the differences again to see if there's anything this covers that they didn't. I know this takes longer, but getting good changes upstream is worthwhile, and so is staying close to what upstream has.

**Comment by kocio-pl** [comment]
If I see correctly (the UI there is totally different than on a GitHub), the upstream change is already merged. What do you plan to do with this PR now?

**Comment by pnorman** [comment]
> If I see correctly (the UI there is totally different than on a GitHub), the upstream change is already merged. What do you plan to do with this PR now?

Replace "race" with "ethnicity" to match the Go changes. With nationality and ethnicity mentioned, do we also need to specifically call out national origin? We do mention "or similar personal characteristic", and I feel nationality and ethnicity cover national origin, but don't have strong views on the subject.

**Comment by kocio-pl** [comment]
I feel the same. I also like having CoC, but don't like splitting hairs when we didn't have such issue to make a reality check for these rules and we're just trying to say "be nice to others"...

**Comment by nebulon42** [comment]
I feel this to be unnecessary, if there is proper governance of a project this should be self-evident.

**Comment by rory** [comment]
@kocio-pl @nebulon42 One (big) goal of a modern CoC is detail and unambiguity. Just having "Be nice to everyone" is akin to not having a CoC at all.

I am happy with the Go change of just adding  "ethnicity". I merely added "national origin" because it's in EU anti-discrimination law.

**Comment by math1985** [comment]
> I feel this to be unnecessary, if there is proper governance of a project this should be self-evident.

+1

**Comment by math1985** [comment]
If we must have one, let's not reinvent the wheel and keep following an existing one. The discussion whether 'national origin' does or does not equal race/ethnicity should really be out of the scope of this project.

**Comment by kocio-pl** [comment]
Replaced by #2503.

**Pull request closed without merging**
