### PR TITLE
refactor yaml2mml.py (fixes #1866)

### LINKED ISSUE #1866: simplify yaml2mml.py execution
Currently yaml2mml.py needs the correct files provided to stdin and stdout. But given it's the same files every time, and the directing files to stdin/stdout isn't the worlds most common thing, we can simplify how it works.

* Currently: `python scripts/yaml2mml.py < project.yaml > project.mml`
* Target: `python scripts/yaml2mml.py` or even just `scripts/yaml2mml.py`

The files should be found relative to the script, not the current directory, so that `python scripts/yaml2mml.py` and `cd scripts; python yaml2mml.py` both work.

### PR DESCRIPTION
**Pull request by nebulon42**
Since I was at writing Python scripts I tried to fix #1866.

### CODE REVIEW

**Comment by nebulon42** [comment]
I overlooked that travis_check_project_files has to be rewritten too. Will do that later.

**Comment by HolgerJeromin** [comment]
Imo the `touch project.mml` could be dropped or integrated into the script. Disclaimer: I have no detailed knowledge about the reason for this in the first place.
Probably tilemill needs a new timestamp , but git has no problem with it either.

**Comment by HolgerJeromin** [comment]
Perhaps the script should be written to support  both call logics. But perhaps not :-)

**Comment by nebulon42** [comment]
Yes, I think it is a good idea to have the possibility to specify input and output with parameters if needed.

**Comment by matkoniecz** [comment]
> Yes, I think it is a good idea to have the possibility to specify input and output with parameters if needed.


I am not sure. In this project this script always takes the same files as input/output. Making it easily reusable for completely different project seems like unneeded additional code.

**Comment by nebulon42** [comment]
It's not about another project, it's about supporting reading from stdin and writing to stdout as well (or at least writing to stdout) to support travis_check_project_files.

**Comment by nebulon42** [comment]
I have updated the PR to support the Travis check script.

**Comment by math1985** [comment]
Thanks!

**Pull request merged**
