### PR TITLE
Use Noto Sans Arabic

### PR DESCRIPTION
**Pull request by sommerluk**
Use Noto Sans Arabic.

With the recent release of Noto, there is now a true “Sans” (=low constrast) arabic font available. It seems Naskh-like, but because it’s Sans, it fits much better with the rest of scripts and the styling is nevertheless Naskh-like. It is a little bigger with more spacing, what should improve legibility:

Before:
screenshot 1

After:
screenshot 2

As this release is not yet available as Ubuntu package (and therefor OSM servers unlikely to provide it right now), the current Naskh style is kept as fallback.

This PR contains now also code for Bold variant of Arabic and fallback.

### CODE REVIEW

**Comment by kocio-pl** [comment]
It looks a bit better, indeed, so I would be happy to have this patch.

**Comment by kocio-pl** [comment]
Any other comments or reviews? Fonts are not something I can deal with, that's why I can't make a proper review, but I trust Lukas with such changes if the output is OK for me.

**Comment by matkoniecz** [comment]
Unfortunately I am unable to judge readability of arabic text.

**Comment by kocio-pl** [comment]
For me that's about shapes being more contrast and bigger, but it's always good to ask some users that helped us with comments before (#2496):
@aso-mehmudi @lyxys @BoFFire @saeedghazijoolaee What do you think about this font change?

**Comment by sommerluk** [comment]
http://www.openstreetmap.org/#map=14/36.2941/59.6006

Left: Current rendering at openstreetmap.org
Right: This PR
screenshot 1

Note that subway stations are bolder with this PR because our current code did not have support for bold for Arabic script.

**Pull request merged**
