### PR TITLE
Change allotments color and pattern

### LINKED ISSUE #3411: Move allotments to some kind of green
Currently allotments are dark orange with white dots. We have just changed farmland color to a shade of green, because it makes sense to have all the vegetation areas in green. Allotments are also closely related to vegetation, so I think some kind of green is needed.

Initial proposition using grass/garden background and using farmland background with dark dots like in garden - they are probably too close to them, so it's just a starting point:

[Example area](https://www.openstreetmap.org/#map=16/52.2388/15.5479)

Before

rcwsp9gs

Garden/grass background

l8y7mbd0

Farmland background with garden dots

r6xci7mc

### PR DESCRIPTION
**Pull request by jeisenbe**
**Fixes #3411** 

**Changes proposed in this pull request:**
- Change allotments color to garden/grass green, i.e. #cdebb0, Lch(90,32,128)
- Change pattern to near-white, light green 2x2 pixel squares on a 4x4 pixel grid
       *Pattern is #f2faeb (Lch97,8,130) approximately 75% white with 25% grass color 
- Consolidate allotments on the same lines as garden and grass for text label rendering.
- Add allotments.svg and allotments.md to describe generating this pattern

**Explanation**:
Allotment gardens are currently a terra-cotta colour, similar to farmyards, with a pattern of white dots every 8 pixels. This looks nice and the relation to farmyards is sensible, but it does not immediately suggest that allotments are a type of garden. 

This PR will change allotments to use the same shade of green as landuse=garden (and landuse=grass), while changing the pattern to be distinct from gardens and grass areas.

**Test rendering with link:**
http://openstreetmap.org/#map=16/52.1940/21.0404
Warsaw z15 master
warsaw-z15-master
z16
warsaw-z16-master

After z15
warsaw-z15-new
z16 after
warsaw-allotments-after-z16

Also see previous test renderings in issue #3411, eg:
https://github.com/gravitystorm/openstreetmap-carto/issues/3411#issuecomment-443203388 
https://github.com/gravitystorm/openstreetmap-carto/issues/3411#issuecomment-443192445
https://github.com/gravitystorm/openstreetmap-carto/issues/3411#issuecomment-442807940

### CODE REVIEW

**Comment by jeisenbe** [comment]
**Allotments with gardens and grass**

_Glauchau, Germany: allotments next to grass_
glauchau-2px-4grid-on-garden

_Northern Ireland: allotments by residential gardens_
export-21

_Allotments between an area of grass and an area of garden_
export-7

**Comment by jeisenbe** [comment]
**Flamengos, Azores Islands**
http://www.openstreetmap.org/#map=15/38.55036/-28.65888

z15 - Small patches of allotments with many other green features (orchards, gardens, grass etc)
z15-flamengos-2px-white75-on-4p-grid-garden

z16 - Small areas of Allotments, garden, orchard, plant nursery, grass, 
z16-flamengos-2px-white75-on-4p-grid-garden

z17 - Allotments next to farmland, near botanic garden and orchards
z17-sao-lourenco-2px-white75-on-4p-grid-garden

**Wales, Great Britain**
Trethomas, Wales: 
Allotments next to grass/meadow (in center)


Marshfield, Wales. Allotments on mid-right, garden on left by church

**Comment by kocio-pl** [comment]
Could you provide the code of this pattern but with `#ddeec3` as a foreground? All is good with high zoom levels, but on midzoom (when the area is small) it's close to the grass. I'd like to check it, but pattern generation and producing raster image is not that simple.

**Comment by kocio-pl** [comment]
It looks like on z13 pattern is not used, which is OK for orange, but with the color change it looks exactly like grass (4x zoom to show it):

https://www.openstreetmap.org/way/25345944#map=13/52.1935/21.0956

pxayfnie

**Comment by kocio-pl** [comment]
You're right, gardens are already grass-looking on z13. Could you produce the lighter green pattern to test it anyway?

**Comment by kocio-pl** [comment]
Thanks. It is too light to see the pattern, so maybe 75% grass + 25% farmland would be better. I would like to have something that looks different than grass even when the area is too small to see the pattern anyway, but the pattern is important when zooming in.

**Comment by jeisenbe** [comment]
Here are a few more options. I checked for what could count as 75% grass plus farmland; the option with the most contrast from grass is #d8ecba, Lch(91,27,124)

25-50-75-grass-to-farmland

16) Allotments in #d8ecba with 75 percent white for pattern
z15a
3-d8ecba-75percent-llandaff
z13
3-marshfield-z13
z14
3-marshfield-z14
z15b
3-marshfield-z15
z15c
3-st-mellons-z15

I feel that the tests above were not much of an improvement; the color is still too close to grass. I also tried the current campsite / caravan site color, but this is not much of an improvement (it's also similar to grass). 

Here is one more option. I've shifted the color to be more blue, similar to orchards, vineyards and plant nurseries, but lighter and less saturated. This makes the allotments more similar to parks, leisure and orchard, though it is still close to the grass/garden color. #d7f3c9 is Lch(93,24,134)

17) Allotments in #d7f3c9 with 75 percent white for pattern
z15a
4-d7f3c9-75percent-llandaff-z15
z15b
4-bronynant-z15
z13
4-marshfield-z13
z14
4-marshfield-z14
z15c
4-z15-marshfield
z15d
4-st-mellons-z15

(I also tried both of these background colors with 100% white squares for the pattern, but this is too much contrast, so I haven't bothered to upload these).

**Comment by Adamant36** [comment]
Hhhmm, I don't know about the squares. It makes the area look out of place since nothing else uses them and they are to uniform. Maybe a pattern would be better. Either with or without them though, what about a slightly darker tint to farmland. I'm sick of green colors. So I liked that allotments weren't green. It doesn't seem like the right color for it. I don't think of gardens as green. Let alone allotments. Its more of a civic amenity (like university grounds) or a social facility then a surface.

**Comment by kocio-pl** [comment]
Thanks - I tested it and it's too light, I don't see the pattern. So let's go back to the original idea (just keep "converted to PNG" in documentation).

**Comment by kocio-pl** [comment]
Yes, please test this color, but with current pattern.

**Comment by jeisenbe** [comment]
**Test 18: Allotments in golf-color #b5e3b5 with 75% opacity white pattern:**
Lch(86,29,143)
z15
z15-golf-color

z16
z16-golf-color

**Test 19: Allotments in plant_nursery/orchard/vineyard color #aedfa3.**
Lch(84,36,138)

z15
z15-orchard-color

z16
z16-orchard-color

**Comment by kocio-pl** [comment]
It looks too dark, especially on z13, when we have no pattern, so I believe original change proposition is the best at this moment.

**Comment by jeisenbe** [comment]
OK, so we are going with #cdebb0, same as gardens and grass. I've pushed the changes. This should be identical to the initial commit, as seen here: https://github.com/gravitystorm/openstreetmap-carto/pull/3548#issue-235328745

**Comment by kocio-pl** [comment]
Hm, do we have to drop the pattern at z13? Could you try how would it be without dropping it at all?

**Comment by jeisenbe** [comment]
@kocio-pl, the other green landuse patterns generally begin at z14, eg vineyards, orchards, plant_nursery, garden, cemetery. These areas are generally fairly small and the pattern is unlikely to be visible at low zoom levels for most allotments (though your huge ones in Warsaw may be an exception)

Some of the natural patterns begin much earlier, because they can cover large areas. Specific wetland patterns begin at z14, along with beach and scrub. Screen/shingle and forests begin at z13, quarries and reef at z10. Bare_rock, sand, (generic) wetland and glacier patterns begin at z5.

The other issue is that z12 is where the landcover colors start to be faded, so it becomes harder to distinguish subtle differences.

I've tested this on the two larger towns/cities in southern Wales. Cardiff has several fairly larges areas of allotments; Newport only has small allotments (as is common in Britain). 

**Cardiff z14,** with pattern:
z14-cardiff-allotments

**z13**, No pattern:
z13-cardiff-no-pattern

With pattern:
z13-cardiff-allotments

**z12**, No pattern:
z12-cardiff-no-pattern

With pattern:
z12-cardiff-allotments

**Newport z14**
z14-newport-allotments

**z13** No pattern:
z13-newport-no-pattern

With pattern:
z13-newport-allotments

**z12** No pattern:
z12-newport-no-pattern

With pattern:
z12-newport-allotments

It looks like the pattern could work on z13, though it's only clearly visible on the larger allotments and can be confusing on small allotments that show only a few pixels. But z12 won't work.

**Comment by kocio-pl** [comment]
Since I see nothing bad with rendering pattern on small allotments and there are more places with the big ones, like here:

https://www.openstreetmap.org/#map=13/52.4557/13.4252
https://www.openstreetmap.org/#map=13/54.1680/19.4217

let's render allotments pattern from z13+. I see no problems with other patterns on low zoom levels so far, so it might be tweaked in the future in general (also in gardens etc.), but it's not worth digging even deeper for now.

**Comment by kocio-pl** [comment]
@jeisenbe It would be nice to have this merged in the new release on Friday, do you think you can add z13 rendering soon?

**Comment by jeisenbe** [comment]
I’ve pushed the change. The allotments pattern should now render from z13.

**Comment by kocio-pl** [comment]
Thanks, that was quite hard work to test, now let's see how it works full time on the map...

**Comment by kocio-pl** [comment]
I think some boundary line is missing in many cases.

**Comment by polarbearing** [comment]
Indeed, which surprised me a bit since the top post shows boundaries both for before and after. 
However in the code I see no line drawn, neither before nor after. Maybe they are barriers?

Should we focus on this one alone, or open a more general issue 'review boundaries for filled area'? At least school needs it darkened, there is one open.

**Comment by jeisenbe** [comment]
The similar features leisure=garden and landuse=plant_nursery / =orchard /
=vineyard also lack outlines, so perhaps there should be a new issue to
discuss this in general before adding more outlines.

**Comment by Adamant36** [comment]
Its questionable to me if things like orchards or vineyards, which dont usually represent the actual landuse boundary and only the bounds of the crop being grown are easy to seperate from other things on their own, need outlines in the first place (maybe not with plant nurserys though). So I suggest it goes through rigorous disscussion in their own seperate issues if they are going to be considered.

**Pull request merged**
