### PR TITLE
Changing windmill color to man_made

### PR DESCRIPTION
**Pull request by kocio-pl**
Follow up to #2833.

In general windmill is rather typical man made (orientation point) than amenity (to be used somehow).

Before
speyx8nr
After
v6lvl0xv

### CODE REVIEW

**Comment by kocio-pl** [comment]
Any comments or reviews?

**Comment by sommerluk** [comment]
I haven’t looked to the code, but the colour change makes sense to me.

**Comment by HolgerJeromin** [comment]
> Most windmills I know are also tourist sights, which fits in with the brown color.

How are windmills with "tourism=attraction" rendered? Could be a candidate for brown

**Comment by kocio-pl** [comment]
Currently windmill is always just brown, but that's interesting idea.

**Comment by sommerluk** [comment]
This needs to be rebased…

**Pull request merged**
