### PR TITLE
Add documentation about needing hstore

### LINKED ISSUE #2439: Document hstore extension need
There is no mention of CREATE EXTENSION hstore in the section about loading the data.

### PR DESCRIPTION
**Pull request by pnorman**
Replaces #2456 
Fixes #2439

### CODE REVIEW

**Comment by kocio-pl** [comment]
I think the line with creating hstore should be in a separate paragraph, as the other code one-liners, but that's simple and I would merge it..

**Comment by pnorman** [comment]
> I think the line with creating hstore should be in a separate paragraph, as the other code one-liners, but that's simple and I would merge it.

Merging for now, we can fix up readme formatting later.

**Comment by kocio-pl** [comment]
Paul, there's agreement among developers to not merge our own code. I wouldn't care if you were not strict about it when I was trying to follow your way. I'd like to know what is a rule and what is just a hint.

**Comment by math1985** [comment]
I'm not sure either, but note that a difference is that this was not a merge into master.

**Comment by pnorman** [comment]
Yes, this is going into a development branch. My reasons for doing a PR instead of committing directly to `lua` are to make use of github's issue closing features, avoid conflicting with others working on it, and get more people involved.

Also, it's been having other people **review** our code that's been key, not the merge itself. e.g. on the Mapnik 3 changes, I merged after everyone had reviewed it because I expected it to take some git magic to get it merged correctly. These are nothing special to us, but standard practices in a multi-contributor project with good code review.

**Pull request merged**
