### PR TITLE
Adding shop=musical_instrument icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1420.

musical_instrument

### CODE REVIEW

**Comment by matkoniecz** [comment]
As mentioned in #1420 I prefer version 3 for icon (but here it seems that difference is smaller than from my impression there - as result of colour change).

**Comment by kocio-pl** [comment]
7, 8 and 9 comparative field test (3 was too rough in SVG):
musical_instrument
musical-trumpet8
musical-trumpet9

I would choose 8.

**Comment by matkoniecz** [comment]
I think that 9 is slightly better.

**Comment by kocio-pl** [comment]
I just forgot to change the code because I didn't expect @math1985 will be so quick in this case, but when I look at it now, I still think 7 was the best (with 9 being the worst) and nobody else complained, so I'm happy with the outcome.

**Pull request merged**
