### PR TITLE
Place areas

### LINKED ISSUE #103: Render place names on areas the same way as on nodes
Currently place names are only "correctly" rendered when mapped on nodes. Place names should be rendered in the same way when placed on closed ways and relations.

### LINKED ISSUE #522: Non-capital=yes values
We currently check for ``capital='yes'`` on #placenames-capital, but this doesn't match capital=4. We should probably check either for ``capital = ANY (ARRAY['1','2','3','4','yes'])`` or ``capital IS NOT NULL AND capital != 'no'``

(note: is the NOT NULL check necessary, or implied by the inequality check?)

### PR DESCRIPTION
**Pull request by pnorman**
Superceeds #538
Fixes #103
Fixes #522

This will reveal two widespread problems in the data
* TIGER import place classifications are awful.
* There are frequently duplicate place areas and place points

There is a very minor performance boost overall to this pull, in spite of adding ``planet_osm_polygon`` which comes from combining some of the MSS.

The MSS could probably be further simplified, but I'll leave that to others.

### CODE REVIEW

**Comment by jojo4u** [comment]
With the routing now on the main page there is even more need for placement of the city centre.

**Comment by pnorman** [comment]
this would need complete rewriting against the current code and yaml. closing.

**Comment by lukaszkruk** [comment]
@gravitystorm 

> Never ever do anything with anything tagged as a "label", that way madness lies. Mapping a 'town centre point' or whatever is fine if all the mappers can agree on where that node should go, but label positioning is font-size and font-face and cartographic-choice specific so should never ever ever be in the OSM database. Anyone adding 'label' roles to relations should remove them.

Sorry to dig out the old thread, but https://wiki.openstreetmap.org/wiki/Relation:boundary#Relation_members permits (and has been like this for a long time) the label role for relations, recognizing it is not actually used by Mapnik. Doesn't this override carto rendering choices? 

Was there ever an attempt to repeal this?

Thanks for clearing this up for me.

**Comment by kocio-pl** [comment]
I would say there's a spirit of autonomy here. No wiki rules, nor the usage numbers or any other kind of agreement between the rest of OSM community has direct impact on this style.

**Pull request closed without merging**
