### PR TITLE
Add transparency to halo placename labels

### PR DESCRIPTION
**Pull request by math1985**
This looks prettier, and without compromising legibility as far as I see.

### CODE REVIEW

**Comment by math1985** [comment]
Before:
before
After:
after

**Comment by pnorman** [comment]
That's a surprising improvement. Are there any other halos we want to do at the same time?

**Comment by math1985** [comment]
> That's a surprising improvement. Are there any other halos we want to do at the same time?

I think all of them need manual checking. The gray place labels (one the higher zoomlevels) don't look well with a transparent halo.

**Comment by mkoniecz** [comment]
A great improvement.

> Are there any other halos we want to do at the same time?

POIs in amenity-points are promising (Yes, I am planning to do something with #710 in the near future).

**Comment by Rovastar** [comment]
Another good improvement.

**Comment by nebulon42** [comment]
Looks good. But maybe use 0.7 instead? How does that look?

**Comment by imagico** [comment]
Let me suggest to be careful with that with very small size labels (which includes placenames at low zooms) where readability is sometimes already tricky even as it is, especially with some non latin texts.

**Comment by mkoniecz** [comment]
> especially with some non latin texts

According to my tests - it is OK.

https://cloud.githubusercontent.com/assets/899988/5696401/8614847c-99d0-11e4-9f44-e6101a704beb.png

https://cloud.githubusercontent.com/assets/899988/5696402/86200b94-99d0-11e4-8190-3490ab753457.png

https://cloud.githubusercontent.com/assets/899988/5696403/86322810-99d0-11e4-844b-794fd78fb026.png

**Comment by pnorman** [comment]
http://mapnik.org/news/2012/04/20/smart-halos/ may be another technique for a similar effect

**Comment by talllguy** [comment]
Smart halos look pretty nice too, but this is a great improvement.

**Pull request merged**
