### PR TITLE
switch to book font for POI labels

### LINKED ISSUE #710: Inconsistencies in amenity-points
There are several inconsistencies in the amenity-points (https://github.com/gravitystorm/openstreetmap-carto/blob/master/amenity-points.mss) specification:

- [ ] The name of some POI is printed in bold or oblique, but it is not clear what the rationale behind that is
- [x] The name of POIs are printed in different text-sizes, again without a clear rationale.
- [x] Some POI have a larger halo-radius than others, without a clear reason.
- [x] Some landuse labels are rendered in black and others in the background color
- [x] Some POI have a smaller text-dy than others. This is likely to cause that some labels containing capitals or accents are never rendered. Note that text-dy depends both on the icon size and font size. It would probably be best to test this with a tall string such as 'ÉÉÉÉÉÉ'.
- [x] Some POI with icons, such as leisure = 'playground' (but potentially others), have no text-dy at all, meaning their text will never be rendered.
- [x] The length of text-wrap-width is inconsistent.
- [x] <s>The order of the attributes per selector is inconsistent (best resolve in separate commit)</s> =- now as #1172 .
- [x] Replace hardcoded colour values by variables

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #710 (yet, it is the final part!)

https://cloud.githubusercontent.com/assets/899988/16176415/215deece-360f-11e6-9f0a-d6274986a06d.png
https://cloud.githubusercontent.com/assets/899988/16176416/2160c0b8-360f-11e6-81c2-ea4034bc25d7.png

https://cloud.githubusercontent.com/assets/899988/16176417/2161001e-360f-11e6-856b-0bdf30279c57.png
https://cloud.githubusercontent.com/assets/899988/16176419/2161b6a8-360f-11e6-947d-72ba4c7bdd37.png

https://cloud.githubusercontent.com/assets/899988/16176418/21610186-360f-11e6-8fa3-4887c9aba5ba.png
https://cloud.githubusercontent.com/assets/899988/16176420/2161ea4c-360f-11e6-9729-7f8d5485cf25.png

https://cloud.githubusercontent.com/assets/899988/16176421/2174a06a-360f-11e6-8b2c-3b6e89769b58.png
https://cloud.githubusercontent.com/assets/899988/16176423/2179662c-360f-11e6-901d-b0a4e74bf53e.png

https://cloud.githubusercontent.com/assets/899988/16176424/217b9cee-360f-11e6-9c50-9672b4808932.png
https://cloud.githubusercontent.com/assets/899988/16176422/21793ef4-360f-11e6-80ff-865522bc336a.png

### CODE REVIEW

**Comment by matkoniecz** [comment]
There are some useful comments in #710 to be reviewed ( https://github.com/gravitystorm/openstreetmap-carto/issues/710#issuecomment-226988879 ).

**Comment by math1985** [comment]
Sorry, I meant to comment in here.

**Comment by nebulon42** [comment]
I think this degrades readability a bit and would therefore suggest to make the halo size bigger.

**Comment by sommerluk** [comment]
Nice work! Makes the map look better structured!

**Comment by matkoniecz** [comment]
To people noticing degradation in readability - is it affecting all labels in the same way?

For me it seems that brown ones are the worst - probably because buildings are closer to brown than too purple/black/etc. But it may be also effected of not being accustomed to it.

**Comment by matkoniecz** [comment]
> Sorry, I meant to comment in here.
 
That was my mistake to post the same thing in issue and PR.

**Comment by daganzdaanda** [comment]
I like this PR.
The labels should be in a regular font. Having all of them in **bold** is really like shouting. Having some bold and some regular labels gives a hierarchy that might have been intentional - or not.

Of course, the thinner lines of the regular font look a bit more "flimsy", probably as a result of anti-aliasing. This might be countered by a stronger and/or wider halo.

How difficult would it be to compare the appearance of the current font "Deja Vu" to "Noto Sans" or other candidates? The hinting and kerning might make a big difference.

**Comment by math1985** [comment]
> How difficult would it be to compare the appearance of the current font "Deja Vu" to "Noto Sans" or other candidates? The hinting and kerning might make a big difference.

I would be interested in seeing that too.

**Comment by matkoniecz** [comment]
> Noto Sans

Font `Noto Sans Regular` from `fonts-noto` package on Ubuntu 14.04 in Tilemill is broken, only " sign is displayed.

selection_011

**Comment by matkoniecz** [comment]
And works fine in Kosmtik.

selection_001

**Comment by math1985** [comment]
> To people noticing degradation in readability - is it affecting all labels in the same way?

I think all labels in your examples that used to be bold and are now regular are brown? But for the current purple shop labels, legibility also improves by boldening them.

Legibility is particularly bad for Dom Jana Matejki (current rendering), Oldsmobil and Restauracja Sekret, all at z17.

**Comment by sommerluk** [comment]
I like Noto also. It is designed with the goal to render all scripts and preserve a harmonic design between all these scripts. Noto is quite unique and quality and in internationalization coverage. For an international map style like openstreetmap-carto that renders many different scripts, but wants to preserve the same design in different countries, Noto might be the natural choise and could substiture all the other fonts. Furthermore, it offers for allmost all scripts also a bold typeface – nice to have. Its support for complex typography (like multiple combining diacritics on the same base character) is really good.

Quick guide: https://www.google.com/get/noto/help/guidelines/

It might be worth to use the “UI” version instead of the normal version. Quoting from https://github.com/googlei18n/noto-fonts/blob/master/FAQ.md :

> What’s the difference between the UI and non-UI versions? The UI fonts were initially prepared for use in Android’s UI. They have tighter vertical metrics, and some glyphs that would be clipped are redrawn to fit within the constrained space. They can be used anywhere that has limited vertical space.

**Comment by kocio-pl** [comment]
See also this discussion:

https://lists.openstreetmap.org/pipermail/dev/2016-June/029294.html

**Comment by mboeringa** [comment]
I don't know why @sommerluk and @kocio-pl didn't simply reference it, instead of duplicating posts, but have any of the concerns raised by others here https://github.com/gravitystorm/openstreetmap-carto/issues/1067 been invalidated by work on Noto in the past two years?

**Comment by kocio-pl** [comment]
Me, I was just fooled - I thought this is the same issue and my post was not saved. So I wrote it again...

**Comment by matkoniecz** [comment]
Can somebody test whatever noto works in their TileMill? I want to know whatever it is case of TileMill being a buggy abandonware, bug in my code or somethinge else.

My code is at https://github.com/gravitystorm/openstreetmap-carto/blob/d789bdac60a17ff8fe18e6d8b978423147c21c53/buildings.mss#L13

I tried restarting/reinstalling TileMill/restarting system, without change from

selection_011

**Comment by sommerluk** [comment]
It works fine for me on Ubuntu 14.04 with Tilemill and the standard fonts-noto package and the following style.mms:

```
Map {
  background-color: @land-color;
}

@book-fonts:    "Noto Sans UI Regular";
@bold-fonts:    "Noto Sans UI Bold";
@oblique-fonts: "Noto Sans UI Italic";

@water-color: #b5d0d0;
@land-color: #f2efe9;

```

**Comment by math1985** [comment]
> It works fine for me on Ubuntu 14.04 with Tilemill and the standard fonts-noto package and the following style.mms:

Same here. Note the 'Italic' instead of 'Oblique'. If it still doesn't work, what do you get with `dpkg -S /usr/share/fonts/truetype/noto/NotoSansUI-Regular.ttf` and `fc-list`?

**Comment by matkoniecz** [comment]
Thanks, `UI` version works in TileMill.

**Comment by matkoniecz** [comment]
Main problem with bold text that there is a noticeable mismatch between it and other labels (especially street labels). I will try with even smaller size for text but I am not too hopeful for that solution.

https://cloud.githubusercontent.com/assets/899988/16359289/09b9d4a2-3b2f-11e6-9fca-7f38569452ae.png
https://cloud.githubusercontent.com/assets/899988/16359290/09b9d164-3b2f-11e6-89f0-6047beb3e9e3.png
https://cloud.githubusercontent.com/assets/899988/16359291/09b9ed70-3b2f-11e6-8ba2-3a37bcf4c93d.png
https://cloud.githubusercontent.com/assets/899988/16359292/09ba62be-3b2f-11e6-88b0-8dede2b33bf1.png
https://cloud.githubusercontent.com/assets/899988/16359294/09bda71c-3b2f-11e6-946b-12bc542d6219.png
https://cloud.githubusercontent.com/assets/899988/16359293/09bb8432-3b2f-11e6-80b7-60a6111ad5bb.png
https://cloud.githubusercontent.com/assets/899988/16359295/09d0ce46-3b2f-11e6-9f4b-0874648a206f.png
https://cloud.githubusercontent.com/assets/899988/16359297/09d1a32a-3b2f-11e6-8ac4-2c22d73193e7.png
https://cloud.githubusercontent.com/assets/899988/16359296/09d1056e-3b2f-11e6-93b1-9b2465c49e39.png
https://cloud.githubusercontent.com/assets/899988/16359299/09d437ca-3b2f-11e6-8ea7-25c9e7936acf.png
https://cloud.githubusercontent.com/assets/899988/16359300/09d4bbf0-3b2f-11e6-9df4-87eecaf46c36.png
https://cloud.githubusercontent.com/assets/899988/16359298/09d43cde-3b2f-11e6-8563-508fdae00aac.png

**Comment by math1985** [comment]
The bold font in Noto is much less heavy, so in that respect switching fonts might help.

**Comment by matkoniecz** [comment]
> The bold font in Noto is much less heavy, so in that respect switching fonts might help.

Added to list of things to investigate.

**Comment by math1985** [comment]
> Main problem with bold text that there is a noticeable mismatch between it and other labels (especially street labels). I will try with even smaller size for text but I am not too hopeful for that solution.

That's quite a lot of images, could you add some accompanying text so I know what I'm looking at?

**Comment by matkoniecz** [comment]
> That's quite a lot of images, could you add some accompanying text so I know what I'm looking at?

bold mismatching street labels IMHO applies to all places that I tested. In that case no location is particularly important.

I attached subset of my test images to make possible to look at before/after without generating them.

**Comment by sommerluk** [comment]
> The bold font in Noto is much less heavy, so in that respect switching fonts might help.

The current Noto has only 2 weights (bold and regular). The next Noto will have more weights (thin, medium, light, extrabold, black) – but not all of them for all scripts.

**Comment by sommerluk** [comment]
Why use bold at all for POI? (I thought that this PR switches all POI to regular font – from what the code says…).

There are often many POI on the map. It does not make sense to make the POI labels bold. Bold text is a sort of emphasis, and when you emphasis everything, you emphasis nothing. I would rather let all POI in regular font, but play around with bold labels for place=*.

**Comment by math1985** [comment]
> Why use bold at all for POI?

Legibility of regular labels is sometimes insufficient.

**Comment by sommerluk** [comment]
> Legibility of regular labels is sometimes insufficient.

I think this can better be solved with quite more halo and/or a slightly bigger font size.

**Comment by matkoniecz** [comment]
> I think this can better be solved with quite more halo and/or a slightly bigger font size.

I have also potential version for these two ideas, waiting for testing.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 26 giu 2016, alle ore 02:35, Matthijs Melissen <notifications@github.com> ha scritto:
> 
> Why use bold at all for POI?
> 
> Legibility of regular labels is sometimes insufficient
> 


+1, bold is not necessarily an emphasis, font size is important as well (and size relations between different kind of object classes)

**Comment by sommerluk** [comment]
> bold is not necessarily an emphasis

Normally, bread-and-butter type face have emphasis as a design goal for the bold type face. Also italic is normally designed for emphasis. But “italic” is designed to keep the same “type colour” (black level/darkness). Bold type faces are “darker”; this makes it easy to spot a section of bold text within a hole page of regular text. Bold type face sections give structure to a document. However, this can only work well if you use them seldom and only for some important things (sort of landmarks) that help the user to structure the document.

**Comment by math1985** [comment]
> It does not make sense to make the POI labels bold. Bold text is a sort of emphasis, and when you emphasis everything, you emphasis nothing.

+1

I have merged this PR. Of course, further changes in font face/weight/size/falo are still welcome.

**Pull request merged**
