### PR TITLE
Adding shop=garden_centre icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1523.

garden_centre-after-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
Here I would suggest making the "pipe" and handle thicker and the handle less wide as the body. The tilted right side looks a bit odd, maybe having a straight line with a rounded corner at the bottom would look better?

**Comment by kocio-pl** [comment]
Next version then:

garden_centre-after-z19-nebulon

**Comment by nebulon42** [comment]
Better regarding thickness, I'm still not satisfied with the right side and the handle spanning the whole width of the bucket. Your decision.

**Comment by kocio-pl** [comment]
Why should I not try? But I hope I misunderstood you, because that would be unrecognizable and awful for me. =} - garden_centre-14-7 

If I really did, please try to describe it with other words maybe.

**Comment by nebulon42** [comment]
I tried to make it more symmetrical: garden_centre-14
But I'm not really satisfied with the shape overall. Maybe it's enough if you move the lower right corner in your icon a bit to the right.

**Comment by kocio-pl** [comment]
For me the shape is perfect now and even this slight correction you suggested made it less good, so I will stick to the current one. 

I also liked my original icon because its design was seen regardless such small size, but it's not a design contest and more typical shape is probably better for default map.

**Comment by matkoniecz** [comment]
https://github.com/gravitystorm/openstreetmap-carto/pull/1567#issuecomment-104444340 is my favorite

I wonder is it because that watering cans of that shape are more popular in Poland.

**Comment by kocio-pl** [comment]
Even if it was local influence, I like when the shape is not too square, because even 2x1 px difference between top and the bottom makes recognizing much easier ().

**Comment by kocio-pl** [comment]
Sorry, that was just accidental key pres...

**Pull request merged**
