### PR TITLE
Adding shop=variety_store icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1536.

variety_store-after-z19-digital

### CODE REVIEW

**Comment by matkoniecz** [comment]
For me it still looks like battery and icon is not intuitive.

**Comment by kocio-pl** [comment]
Luckily we have only [22 battery shops in our database](http://taginfo.openstreetmap.org/tags/shop=battery), so even if it's not clear just looking at the icon, the confusion will be very limited IMO, because probably nobody thinks about battery shops.

**Comment by nebulon42** [comment]
While you did a great job in making this recognizable I'm also not convinced by it. Maybe we are trying to put too much detail into it? On the other hand, I also don't have any other design in mind.

**Comment by matkoniecz** [comment]
@kocio-pl 

> Luckily we have only 22 battery shops in our database

This is not really convincing. I think that it is not enough "hard to confuse with other potential and existing icons" - goal me goal is "intuitive for a typical person".

In that case I would recommend rejecting this icon - I think that overall generic one is preferable.

**Comment by kocio-pl** [comment]
Another try:
variety-bag99
variety-bagpercent

**Comment by matkoniecz** [comment]
First one is clearly better than previously presented icons.

**Comment by math1985** [comment]
> First one is clearly better than previously presented icons.

+1, could you update the pull request?

**Comment by kocio-pl** [comment]
Sure.

**Pull request merged**
