### PR TITLE
Rendering man_made=works

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/887.

Warsaw, z18
Before
s5pama4i
After
vvfegrv5

### CODE REVIEW

**Comment by imagico** [comment]
As previously said multiple times i am against point label rendering of area features based on way_area if those are not at the same time rendered as areas.  This would create a bad mapping incentive.

**Comment by math1985** [comment]
> As previously said multiple times i am against point label rendering of area features based on way_area if those are not at the same time rendered as areas.

:+1:, this should be changed. However, this is an existing problem which is IMO outside of the scope of this PR.

**Comment by imagico** [comment]
> However, this is an existing problem which is IMO outside of the scope of this PR.

It is not, as far as i can see `man_made=works` is currently not rendered in any way, this PR adds rendering on point features (which is fine) and on area features with rendering being influenced by way_area (which i do not support).

**Comment by math1985** [comment]
As that is wider than only man_made=works, could you create a new issue for that?

**Comment by imagico** [comment]
I am not aware of any case currently where label styling is based on way_area for features that are not rendered as areas - unless i missed some changes that introduced this.

You could formally count place=island since the tag itself is not rendered but it is universally rendered as negative space through the coastline and water areas.

**Comment by math1985** [comment]
Sorry, I totally misunderstood you. I think shop=mall is another current example.

**Comment by imagico** [comment]
Good point, did not notice that one.

Could be fixed by rendering shop=mall (when not also building=yes) like landuse=retail in the landcover layer - see #2702.  Same could be done for this one (i.e. rendering it like landuse=industrial).

**Comment by math1985** [comment]
:+1: for both suggestions.

**Comment by HolgerJeromin** [comment]
works should be inside industrial area. So rendering only the name and not the area is on purpose. same as power plant.

**Comment by kocio-pl** [comment]
@imagico Would rendering the no-building works area the same as industrial be OK for you?

**Comment by polarbearing** [comment]
> rendering the border (but no fill)

That would mean a landuse=industrial without a man_made tag has a different border than with, which is inconsistent. It would also make it more difficult to recognise a mapped barrier=fence/wall. 

I find rendering the landuse with a fill sufficient. If it is a large plant with a name, it already has the name in way size from the landuse. If there are several small man_made=works in one larger landuse, rendering the small names is sufficient, as @HolgerJeromin pointed out.

**Comment by dieterdreist** [comment]
sent from a phone

> On 24. Jul 2017, at 08:53, polarbearing <notifications@github.com> wrote:
> 
> I find rendering the landuse with a fill sufficient. If it is a large plant with a name, it already has the name in way size from the landuse. If there are several small man_made=works in one larger landuse, rendering the small names is sufficient, as @HolgerJeromin pointed out.


IMHO this style focuses too much on landuse tags anyway, which leads to many (rendering oriented) mappers adding very few and rough further semantic information, as they have already "drawn everything" with the landuse.

**Comment by HolgerJeromin** [comment]
> That would mean a landuse=industrial without a man_made tag has a different border than with, which is inconsistent. 

This is not correct.
Two industrials which are sharing the same border are visible. This would not be the case if there was no border color. See the north border of:
https://www.openstreetmap.org/way/91224778

**Comment by pnorman** [comment]
I *think* the concerns raised have been resolved. @imagico, is this so?

**Comment by HolgerJeromin** [comment]
After read the code this i think features with only `man_made=works` without `landuse=industrial` would render only the name. No border and no fill. Am I right?

The dimension of [this](https://www.openstreetmap.org/way/408439828) would not be visible, or would it?

**Comment by imagico** [comment]
> I think the concerns raised have been resolved. @imagico, is this so?

No changes were made since the PR was originally started so the answer is no.

**Comment by kocio-pl** [comment]
What is desired solution then? Do we have an agreement here?

**Comment by kocio-pl** [comment]
> After read the code this i think features with only man_made=works without landuse=industrial would render only the name. No border and no fill. Am I right?

Yes. Because there are no changes in `landcover.mss`, no such area would be colored nor outlined.

> The dimension of this would not be visible, or would it?

It wouldn't.

**Comment by HolgerJeromin** [comment]
Oh, i thought that power=plant got a text and outline ([example](https://www.openstreetmap.org/way/53243836)). I was wrong. 

So with the current PR state, `works` will be rendered exactly like `plant`. Kind of ok for me.

**Comment by imagico** [comment]
Interesting observation about power=plant - did not realize that.  That is the same situation as shop=mall.  

My opinion is as before:

> As previously said multiple times i am against point label rendering of area features based on way_area if those are not at the same time rendered as areas. This would create a bad mapping incentive.

> Could be fixed by rendering shop=mall (when not also building=yes) like landuse=retail in the landcover layer - see #2702. Same could be done for this one (i.e. rendering it like landuse=industrial).

Other possibilities would be rendering with an icon or rendering with a point label independent of way_area for both point and area features.

**Comment by HolgerJeromin** [comment]
Rendering (on plant and works) an outline (same color like industrial outline) would show the dimension of a feature but still give a feedback that an landuse=industrial is missing.

**Comment by daganzdaanda** [comment]
> Rendering (on plant and works) an outline (same color like industrial outline) would show the dimension of a feature but still give a feedback that an landuse=industrial is missing.

That would be a good solution, also for offshore wind parks like https://www.openstreetmap.org/way/186609785 where landuse=industrial is just wrong.

**Comment by kocio-pl** [comment]
Thanks for a good example - it's hard to find them, because with so many rules Overpass Turbo is hitting the RAM limits. There's only a name and the outline, no filling, but if you want to make sure, I need another location where there's no industrial area. In the meantime I have removed industrial area filling+outline rendering rule just to show you how would it look like:

Verl, z18
Before
87zvg9zp
After
jrplgd_j
After (without industrial filling)
vrq ne50

**Comment by HolgerJeromin** [comment]
https://www.openstreetmap.org/way/53243836 has no underlying industrial (but should :-)

**Comment by kocio-pl** [comment]
But this is a different tag than man_made=works, so it won't fly with this code. Of course we can make another PR for power plats and other possible objects, but for now I'd like just to make sure if name+outline is the way to go for such cases.

**Comment by HolgerJeromin** [comment]
Here you go: https://www.openstreetmap.org/way/29388213 :-)

**Comment by kocio-pl** [comment]
So here you are :smile: :

Erkrath, z19
Before 
giiifyvg
After
pqebzzty

**Comment by HolgerJeromin** [comment]
One question: does this render nodes with this tag?

**Comment by kocio-pl** [comment]
Yes, the original example is a node:

http://www.openstreetmap.org/node/3428336388

**Comment by HolgerJeromin** [comment]
Btw, this is missing in the changelog

**Comment by kocio-pl** [comment]
Also some other things (like pattern on natural=sand), but Paul never did very detailed changelogs IIRC.

**Pull request merged**
