### PR TITLE
move wind power symbol to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
wind_power_before

after
wind_power_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
Could it be more rotated (to not overlap one part with another)? Otherwise I think it's OK.

**Comment by nebulon42** [comment]
Unfortunately not, otherwise the blades would have to be shorter.

**Comment by kocio-pl** [comment]
For me it's hard to say if I could recognize it not knowing what's this shape, we need more feedback probably.

**Comment by math1985** [comment]
Tester (unfamiliar with osm) recognizes the new icon as wind turbine.

**Comment by mboeringa** [comment]
Given the restricted icon size, I think this is a pretty good shot at it. It may be slightly less recognizable, but I never really liked the huge current ones, as they are so big as to overlap to much other stuff or each other.

**Pull request merged**
