### PR TITLE
Render amenity=lounger

### PR DESCRIPTION
**Pull request by starsep**
Changes proposed in this pull request:
Render amenity=lounger, right now 3269 uses.
https://taginfo.openstreetmap.org/tags/amenity=lounger#overview
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dlounger

Test rendering with links to the example places:
https://osm.org/#map=19/52.22657/20.93735
Before
image
After
image

Current icon:
image

It is my first icon and I'd appreciate feedback. I modified bench.svg

### CODE REVIEW

**Comment by pnorman** [comment]
I think the cartography needs consideration, but is the icon pixel aligned?

**Comment by starsep** [comment]
> I think the cartography needs consideration, but is the icon pixel aligned?

I am not sure yet what it means exactly, does this image answer this question?
image

**Review by imagico — CHANGES_REQUESTED** [review]
Related issues: #4469, #3187, #4568.

I have two things that IMO would need to be changed:

* The symbol is not intuitive in my eyes - it is essentially the bench symbol with a diagonal line on top which is not how these typically look like and not intuitive.  This requires some more design work.
* The special rendering of access restricted loungers is not a good idea.  Because of #4568, because access restriction tagging is not common on those and because practically access restricted loungers are very rare.  Either the lounger is open to use by everyone or it is located in an access restricted area (but is open to use within that area none the less).  In the latter case the tagging and display of access restrictions should be on that area and not on the bench (and it is common practice to map this way i might add - of the 1.8M `amenity=bench` only <2000 have an `access!=yes` tag)

I think this is in principle a feature suitable for rendering here although i am a bit concerned about the idea of rendering this with only 3300 uses while we have decided not to distinctly render backrests on benches in #3187 - although these are used on 860k features.  Yes, this is a question of rendering at all vs. rendering in a distinct fashion and for benches we have the additional difficulty of needing three symbol variants.  Based on that a point of consideration might be to render `amenity=lounger` like `amenity=bench` (as suggested in #4469).  I would make this dependent on if a good distinct symbol can be developed.

**Review by pnorman — CHANGES_REQUESTED** [review]
In #4469 we rejected rendering loungers with a dedicated icon, and in #3187 we rejected differentiating benches based on if they had a back.

I do not see that anything has changed since we rejected #4469. I could see maybe rendering them like benches.

**Comment by pnorman** [comment]
Closing for reasons above. Rendering them like a bench is an option that could be discussed.

**Pull request closed without merging**
