### PR TITLE
Change gastronomy objects to orange color

### LINKED ISSUE #3329: Change gastronomy objects colour to orange
This ticket is to discuss some old @kocio-pl's proposal with changing rendering of gastronomy objects from brown to orange (it was proposed as part of PR https://github.com/gravitystorm/openstreetmap-carto/pull/2824#issuecomment-328521710 then, but forgotten without discussion or merging later)

@kocio-pl's test rendering with #c64803

### PR DESCRIPTION
**Pull request by Adamant36**
This changes the color of gastronomy objects to orange using the hex value #cc6600 closes #3329
Test area https://www.openstreetmap.org/#map=19/37.78790/-122.41233
gastronomy test

### CODE REVIEW

**Comment by Tomasz-W** [comment]
@Adamant36 As this is quite important change and we need to know how would it look on different landcovers, please add more examples (icon-rare/ icon-dense areas, grass area, forest area)

**Comment by polarbearing** [comment]
The orange is 'screaming' to me loudly, like a warning colour. The blue and the purple icons struggle to compete, the remaining amenity-brown ones become harder to notice.

**Comment by lakedistrictOSM** [comment]
Not too keen on this colour, looks a bit light. Would like to see a few other shades tested before merging.

**Comment by Adamant36** [comment]
@polarbearing Do you have another, none 'screaming' shade to try? If so, I'm willing to test it.

**Comment by kocio-pl** [comment]
If that is too light, than maybe something closer to brown. It might be something like my initial idea, maybe it could be tweaked to look better: https://github.com/gravitystorm/openstreetmap-carto/issues/3329#issue-347679050.

I'm still hesitating, but it makes sense to render such broad category in a different way rather than use brown everywhere.

**Comment by Adamant36** [comment]
Same Color. It could be a tad darker maybe. Although it looks good with lighter stuff like the leisure green area or in the water park. 
download
download 1
download 2
download 3
download 4

**Comment by Adamant36** [comment]
@polarbearing So your willing to taint other people's opinions of the color by saying it "screams like a warning colour," but then it would somehow be bias of you to propose an alternative? Right....

**Comment by Tomasz-W** [comment]
It's quite ok, but I would like to see a little bit darker/ less bright version to compare. Especially in example place from picture no. 1, where orange icons look like competing with orange highways.

**Comment by Adamant36** [comment]
Slightly darker #B75B00
slightly darker b75b00
A little bit darker #A35100

I'm slightly leaning toward A35100. I can do tests of more areas on these or the original if needed. I think the original competed with orange highways a tad. Maybe these ones wouldn't.

**Comment by kocio-pl** [comment]
I like #B75B00 more, since this is easier to recognize both from brown (amenities) and roads. #A35100 is too close to brown, even in a direct proximity.

**Comment by polarbearing** [comment]
> So your willing to taint other people's opinions

@Adamant36 - could you please stop getting personal? Please read [here](../blob/master/CODE_OF_CONDUCT.md). I expressed my own, personal opinion, that I felt the visualisation was unbalanced. I did not taint anybody or anything. I am not obliged to make proposals for something I am not convinced that it is needed.

**Comment by Adamant36** [comment]
@polarbearing I don't see how I was being critical. I was just pointing that you were already introducing bias by commenting in the first place and since that was the case, it would have been cool if you helped me come up with a better color on top of it. Since I'm obviously no expert at this. It had everything to do with brainstorming a better color and nothing to do with you. The Last time I checked the rules say "don't merely decry the current state of affairs; offer—or at least solicit—suggestions as to how things may be improved." So it wasn't personal and I would of asked anyone for an improvement if they had of just been critical without proposing one. If I misinterpreted that rule though and I should keep my mouth shout and let you criticize things without asking you if you have a better suggestion, my bad. You could of followed the whole "Interpret the arguments of others in good faith" thing and just let it go. 

Since we are on the subject though, you do seem to have a tendency to just decry the current state of affairs with out suggesting how they can be improved. Not just in this PR. You did the same thing in the Wiki and my change set comments. You have been doing it for a while and long before we interacted here. I'm not going to be 100% pleasant to you every time we communicate after the confrontational, none productive way you acted toward me in those places. So don't expect me to. As long as I'm not outright insulting or demeaning, I'm not obligated to act like we are best friends or something and saying you were already introducing bias by commenting isn't anything in the grand scheme of things.  

outside of that, from now on take what I say in good faith and as a way to get improvements. Even if its slightly backbiting. Because that's all it is. If your not willing to do that and prefer to just only be critical, I would prefer you follow the "don't decry" rule by skipping over my PRs in the first place. Otherwise, it just adds pointless noise. Like your nonconstructive comments on the Wiki did. Its worthless to comment on something just for the sake of commenting. I pass over PRs and issues I don't like all the time because I have nothing constructive to add too them. I'm sure you can do the same, especially if they are my PRs or issues.

**Comment by Adamant36** [comment]
More tests of #B75B00. I think it looks good. It isn't to bright for the purple or anything and seems to go fine with the roads
download 1
download 2
download 3
download 4
download 5




.

**Comment by polarbearing** [comment]
> your nonconstructive comments on the Wiki

Do you refer to everybody telling you (as Adamant1 ‎) not to set proposal pages to 'delete'? And you are still doing that.

> you acted toward me

I am not acting towards your person, though I comment your actions or ideas if I agree or disagree with them.
Please distinguish these.

> just repeating the same thing

One was about the change in general, this is about a specific colour in context of others.

**Comment by polarbearing** [comment]
Despite my general hesitation, the #B75B00 appears more acceptable to me. 
(the last 3 files in the 06:50:39 GMT post are identical, all MD5 8f958aa23e21e24373455f9c2d420a39)

When comparing colours, it would be a good idea to show the same area, so the comparison could be made in the identical context.

**Comment by kocio-pl** [comment]
@Adamant36 @polarbearing I don't feel last comments between both of you are going to solve anything.

I admit, it's hard to draw the line between personal attacks and just commenting someone's stuff. The golden rule I use when doing a moderator's job (for example on OSM forum) is to avoid **any** personal notes (all with "you" included) when the debate become heated and any evaluating words (like "bad" or "critical"). This way one can still express their own preferences and propositions ("I like/want/don't understand") and concentrate on merits until the heat is over.

There's no way to assure mutual friendship in any group and this is not even a goal, even if it's nice if people appreciate each other and a friendly background makes things easier. However from my experience one of the worse factors escalating conflicts is if it's in public, because original opponents discussion tends to engage other people. So please remember about personal channels of communication in case you want to really talk about each other, not only the about mapping efforts.

That's not to say that anyone breaks the rules or something like that. I just feel it's safe to act early, before it grows too big. You're both welcome here and I'm happy with your respective work, be it code or comments.

**Comment by Adamant36** [comment]
@polarbearing I rather not re-litigate it here, but I will say that asking for pages to be deleted was discussed with multiple moderators and other users before you and the few detractors came along. They all approved it and gave me the go ahead. Which you and the others ignored when I pointed it out and   continued to harass me instead. I have no problem with you or anyone else telling me not to delete pages if they are pages that should be saved. I actually reverted some of my proposals when it was brought up in a civil manner. The aggressive, confrontational manor, you and the others went about it though was completely wrong. Especially the fact that you were unwilling to listen to other people who disagreed with you, not just me. Not to mention you guys reverting me, despite being in the minority and having multiple moderators saying not to do it. Your just extremely unwilling to acknowledge the part your approach plays in things. Its pretty ridiculous you quote me the rules and expect me to be 100% civil after the way you acted and the way you totally disregarded them. You shouldn't just badger people into getting your way. There was no reason I should of listened to you and the few loudest whiners over the moderators and other, more civil people who agreed with me that were in the majority. Outside of that, I have nothing else to say about it and I rather not discuss it anymore.

As far as the other things goes, I was only commenting on your actions originally and not you personally either. You choose to make it personal though by saying I was making it that way when I wasn't. So once again, its your approach to this and nothing else I have issue with. I'm sure your a perfectly reasonable, pleasant person in real life and I have no beef with you other then the fact that you only seem to follow the rules its convent for you and you rather criticize people then contribute "suggestions as to how things may be improved." as the rules say. If you did that, and weren't cherry picking the rules for your own benefit I wouldn't have an issue with you at all.

Also, I  think its extremely dishonest to thumbs up your own comments because it looks to people passing by, who might not check what user left the thumbs up, that there is more support for your ideas then there is. Otherwise, why do it?

**Comment by Adamant36** [comment]
@kocio-pl I respect your opinion and agree with your comment. I will do my best to leave my personal issues with @polarbearing out of things from now on and I wont take jabs at him anymore. I agree that personal issues are better not discussed here. Unfortunately I didn't see your message until after I sent the one below yours though. So you'll have to excuse me on that one. 

That being said, maybe polarbearing could meet me half way by agreeing to be more constructive in his comments or to not make them, and he could also stop thumbs upping his own comments. As it makes it seems like he has more support for his ideas then he does. Its just a suggestion though and I will still try and be more civil either way. 

@polarbearing, I'll take some comparison shots of the same area for you. I don't know what the deal with the last three screen shots was. They were suppose to be different.

**Comment by kocio-pl** [comment]
No need to excuse, it's coincidence and I'm not angry at you nor decline the right for you both to feel angry. I treat it as natural thing, it just does not help designing. :smile: 

I also don't expect any of you to be civil, it's just pure pragmatic rule to not send any personal messages on public place - there just won't be an opportunity to be not civil or to have such impression.

**Comment by Adamant36** [comment]
@kocio-pl OK. What do you think about the color #B75B00. Should I do more testing on it or do you think its adequate?

**Comment by kocio-pl** [comment]
How do you compare it to my original #c64803 proposition? They are quite close to each other, so maybe one could see some of their advantages and disadvantages.

**Comment by Tomasz-W** [comment]
As #CC6600 was too bright and similar to orange highways, #B75B00 is on the edge as close one to amenity-brown. If you are able to find some lighter, but not brighter colour, I would like to see test renderings.

**Comment by Adamant36** [comment]
@Tomasz-W What about any of these? I really want to believe it is somewhere around one of these. 
a07800
a07800
b78c00
b78c00
b77800
b77800

**Comment by trigpoint** [comment]
Still quite hard to see, very difficult to read the text.

The present brown works well, why are we fixing something that isn't broken?

**Comment by polarbearing** [comment]
Current order of preference:
no change > B75B00 > b77800

**Comment by Tomasz-W** [comment]
> why are we fixing something that isn't broken?

Because _amenity-brown_ includes too many objects from very different categories at hte moment

@Adamant36 Thanks for further testing! :) As I'm not a coder but designer, I was playing with potential colours in Photoshop. Can you prepare test renderings with #C77400 ? I like an effect with this colour because labels with it are well visible, and it's also not too dark to confuse with _amenity-brown_

**Comment by Tomasz-W** [comment]
Visualisation of osm-carto icons colours with proposed _gastronomy-orange_ and proposed _healthcare-red_:

_colours

I think #C77400 fits quite ok, and it has the same brightness level as rest of the already used colours, so it won't be "screaming" on map.

**Comment by imagico** [comment]
That is very incomplete - the current OSM-Carto point symbol colors - excluding tree and private parking - are AFAIK:

http://davidjohnstone.net/pages/lch-lab-colour-gradient-picker#d19057,b8a99c,724a08,0a8517,000000,555555,0493db,4d80b2,4964a1,7981b0,5a6ddf,8462c5,ac37ab,d80292

**Comment by polarbearing** [comment]
The C77400 is very close to the cc6600 we had in the very first posting. (btw, thomsz's colourbar shows C87400)

Pref order:
no change > B75B00 > b77800 > C77400 > cc6600

**Comment by Adamant36** [comment]
download
download 1
download 2
download 3
download 4
@Tomasz-W, what do you think? I say its good. I don't think we are going to get any better. If we modify it anymore it will be either to light or to dark. Plus, I think the almost caramel color goes good with cafe/coffee shops.

**Comment by Tomasz-W** [comment]
Generally I'm very satisfied with this colour, because:
* difference between _amenity-brown_ is visible very well
* it matches the rest of icons colours palette

The only problem I can see is a visibility of labels, which became lower as orange is lighter colour than brown. As shops and accomodation objects have one colour for icon and a second one (a little bit darker)  for text, I think the same solution should be applied here. 

Can you make test renderings with #C77400 as icon colour and #B36800/ #BF7000 as text colour?

**Comment by polarbearing** [comment]
the above is all #C77400 or any different?

**Comment by Adamant36** [comment]
@polarbearing, yes its more tests of #C77400. Sorry, I should have said so.

**Comment by Adamant36** [comment]
Text color #BA6D00
ba6d00
ba6d00 2
Text color #B36800
b36800
b36800 2
I'm not really seeing a difference. It could be my monitor though or how chrome handles color tones when exporting a screen shot. One of them should be a little darker though.

**Comment by Tomasz-W** [comment]
@Adamant36 You shouldn't see the difference ;) The trick is about make text darker, but not too dark. I presume no one would guess that parking rendering has different colour for icon and different one for text without being told, searching through the code or zooming the map in Photoshop like I did.

If you want, you can test one more text shade - #AD6500 , but I think it's the darkest one, and any darker colour would be too similar to _amenity-brown_

**Comment by Tomasz-W** [comment]
Thanks! I think it works good, so we should go with #C77400 for icon + #AD6500 for text.

**Comment by meased** [comment]
`#AD6500` is `#c77400` darkened by 25%.

It would be better to use  `darken(@gastronomy, 25%)` in the code to make it clear how the color was derived.

**Comment by Tomasz-W** [comment]
@meased Are you sure it's 25%? By this site: http://scg.ar-ch.org , it's 5% (but as I'm not a coder, it might be something different than we need in osm-carto code). How did you measure it?

**Comment by kocio-pl** [comment]
No matter what is the real percentage, last example (with AD6500 darkened labels) looks OK for me. Thanks all for so careful testing all the possibilities, this is much needed with such important kind of objects. Although it was initially my idea to make them different, it took a lot of time to get used to this. I'm still not entirely sure, but I think it makes sense and the time is right.

@Adamant36 Could you resolve code conflicts introduced by merging #3373?

**Comment by polarbearing** [comment]
The darker the better. 
pub=drink+watch, nightclub=drink+dance, I'd keep them both in the gastronomy catagory, it's all the 'going out' thing. 
And please don't drink+drive ;-)

**Comment by Adamant36** [comment]
@kocio-pl, I think its good to go now. Feel free to let me know if there is anything else to be done on it though.

**Comment by Tomasz-W** [comment]
@Adamant36 @kocio-pl What do you think about nightclubs thing mentioned above?

**Comment by polarbearing** [comment]
I still think C77400 is too bright. 

On the organisational side, I wonder why the colour is separated from amenity, but the icons placed in a``` symbols/amenity/*``` folder? Should it not be ```symbols/gastronomy/*``` then?

**Comment by Adamant36** [comment]
@Tomasz-W, oh yeah. Night clubs might work also. What about amenity=bbq? Id like to just get it through at this point though and not have to deal with anymore merge conflicts etc if I can. Then we can add them later. 

@polarbearing There was some suggestions of more icon folders on the PR I did for that. I can add it to the list and transfer them to a gastronomy folder when I update the other ones if other people agree. Personally, I'm fine with doing it that way. I would like to get this through as is right now if its possible though.

**Comment by Tomasz-W** [comment]
@polarbearing Current folders order is organised by tag's keys, not colour's keys. There is no eg. "accomodation" folder but "tourism" as accomodation objects are placed in `tourism=*` key.

@Adamant36 Sorry, I don't understand your response. Can you tell which colour do you prefer for `amenity=nightclub` - _amenity-brown_ or _gastronomy-orange_? 
I wouldn't use _gastronomy-orange_ for `amenity=bbq` as it is self-service small amenity, not a place where you can order something from menu all year long.

**Comment by Adamant36** [comment]
@Tomasz-W, sorry. Gastronomy color for amenity=nightclub. Your probably right about BBQ.

**Comment by Adamant36** [comment]
@Tomasz-W, any chance you would be willing to let the nightclub change go for now and have it added it to another PR later if need be so we can call this complete and get it merged finally? I really want it to be included in the next update.

**Comment by polarbearing** [comment]
sorry I don't get what it means "to let the nightclub change go". Go where, to yes or no?
If I read the code in 'files changed' correctly, nightclub _is_ included in the gastronomy colour, and bbq _is not_, and I understand that is what everybody was happy with?

**Comment by Adamant36** [comment]
@polarbearing, sorry. I know its in the code and I meant leave it as is. I think gastronomy color works for nightclubs and bbq isn't changed. I was just wanting a confirmation that everyone is good with that and it should be left as is, which you confirm. @kocio-pl never gave his opinion on nightclubs, but I'm sure he will eventually and will probably agree with us. So I guess its good to go then.

**Comment by Tomasz-W** [comment]
@Adamant36 Yeah, I'm not sure about right colour for amenity=nightclub, but if it will change to gastronomy-orange, I wouldn't have some big problem with it. 
I said that these places are strongly connected to music/ dancing what makes them cultural-like. @polarbearing said that these places are like "drink+dance", what makes them gastronomy-like. Both statements are true and reasonable, so I think nightclubs can be brown as well they can be orange. Sometimes we have "multi-meaning" tags which can be put in 2 or more categories as well, but finally we always have to choose one colour at the end.

**Comment by kocio-pl** [comment]
I don't have strong opinion about nightclubs. It's a fuzzy kind of place for me.

**Comment by dieterdreist** [comment]
sent from a phone

> On 14. Sep 2018, at 23:03, kocio-pl <notifications@github.com> wrote:
> 
> I don't have strong opinion about nightclubs. It's a fuzzy kind of place for me.
> 


yes, the name can probably refer to a wide variety of places, event venues, places with live music, for dancing. Usually I’d expect some sort of bar, lounge and dance floor as a minimum.

**Comment by Adamant36** [comment]
Its kind of fuzzy for me to. It would be interesting to know how many night clubs don't contain bars. I know alcohol is outlawed in some Muslim countries, but maybe they wouldn't have night clubs either or they would qualify more as leisure places then anything.  I'm sure There is also underage clubs that are alcohol free but might have soda/snack bars. I know (not from personal experience fyi) that in some places adult night clubs with strippers don't allow alcohol to be served there. Although, I think they still serve soda. So, who knows. I still think its fine to include them in the gastronomy category though.

**Comment by polarbearing** [comment]
Fine then. 
For the general categorisation I had opened #3395, and as the discussion unfolds there are indeed different outcomes depending on which criteria are applied.

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Sep 2018, at 05:24, kocio-pl <notifications@github.com> wrote:
> 
> If anybody still wants to add something new, this is the last minute chance, as I'm going to merge it as soon as today probably.


while I wasn’t a particular fan of the brown color, this lighter color (light brown or dirty orange) for me makes things worse.

**Comment by polarbearing** [comment]
@dieterdreist - I wasn't a friend of this hue either, but my analysis in #3395 convinced me that we indeed need to split the colourspaces for icon themes. This is a start now from the technical side, fine tuning of different icon colours in relation to each other can follow.

**Comment by dieterdreist** [comment]
sent from a phone

> On 15. Sep 2018, at 14:59, polarbearing <notifications@github.com> wrote:
> 
> @dieterdreist - I wasn't a friend of this hue either, but my analysis in #3395 convinced me that we indeed need to split the colourspaces for icon themes.


there’s a point in diversifying feature colors, I am not criticizing the idea as such, just the actual color that was chosen.

**Comment by kocio-pl** [comment]
Thanks again for discussing this issue. This problem is not easy and it was a pleasure for me to see the teamwork for solving it!

More than a month of work and ~10 people involved make me believe it's as good as it's possible at this moment. However I also hope that this change may motivate critics to come with even better idea.

**Comment by matthijsmelissen** [comment]
> However I also hope that this change may motivate critics to come with even better idea.

Great to see so many people involved. However I also think the current color is still too flashy. It would be great if someone still has suggestions to further finetune the color.

**Comment by claudiush** [comment]
Was this colour contrast tested for colourblind accessibility actually? Especially with brownish colors it's challenging for red-green colourblind.

**Comment by kocio-pl** [comment]
I believe it wasn't. We struggle with lack of colors for many months now, which makes it hard enough, and special cases are out of scope here - even color blindness includes different cases itself. However if you have some hint that could help with it, you are welcome to propose it.

**Comment by dieterdreist** [comment]
sent from a phone

> On 22. Sep 2018, at 21:20, polarbearing <notifications@github.com> wrote:
> 
> This question comes up once in a while, and I do not think this style has the resources to cater for these needs


in the past it was definitely part of the considerations how contrast will be for the color blind.

**Comment by kocio-pl** [comment]
This time contrast was discussed, so the problem hasn't been not neglected. I also remember color blind argument, but the outcome was that we can't follow it in general and specific solutions should be proposed if needed. Please look at #1945.

**Comment by LucFreitas** [comment]
Please check the readability and contrast of the new color in special buildings.

**Comment by kocio-pl** [comment]
Since major buildings are very strong, they could be maybe made bit lighter, because everything is less visible there.

**Pull request merged**
