### PR TITLE
Render ele also on polygon alpine_hut and shelter

### LINKED ISSUE #101: ele with alpine_hut when mapped as a building
Wish: If a building is tagged as tourism=alpine_hut, it would be fine if the ele was shown (as is done if it is mapped as a node).

http://www.openstreetmap.org/browse/way/232521425

http://www.openstreetmap.org/browse/node/389786530

### PR DESCRIPTION
**Pull request by sommerluk**
Resolves #101

### CODE REVIEW

**Comment by kocio-pl** [comment]
Could you paste this rendering?

**Comment by sommerluk** [comment]
It’s the same rendering as for points because it gets rendered by the same mss code:

screenshot 2

(At the left a test with an invalid “ele” value).

**Comment by kocio-pl** [comment]
> (At the left a test with an invalid “ele” value).

Is there a way to not display elevation in such case? 

I guess this problem is the same for peaks etc?

**Comment by sommerluk** [comment]
Well, that is what this code is doing 😉

The objects are just dummy test objects.

The tagging for the object left top (node) is:
```
name=alpine_hut point invalid
ele=12a34.5
```

Left bottom (closed way):
```
name=alpine_hut poly invalid
ele=12a34.5
```

So indeed the invalid ele value is not rendered. This is particularly important because otherwise, the conversion would fail, this means we would have an SQL error and the hole rendering would be broken.

This code should be functionally equivalent to the existing code for points – so for polygons it should behave in all aspects the same way as for points.

**Comment by kocio-pl** [comment]
I meant not rendering also such debug info... :smile:

**Comment by sommerluk** [comment]
To explain further:

This code for polygons does _not_ include rendering for the elevation of peaks and saddles (while the code for points does). This is because the wiki does not allow peaks and saddles and volcanos on ways, so no need to support this.

**Comment by kocio-pl** [comment]
I wouldn't like to see error messages also for points (I see "point invalid"), hiding it would be nice everywhere we try to show ele.

**Comment by sommerluk** [comment]
To be clear: There _is no error message_ anywere.

The screenshot is from a test rendering. I just had created objects to which I have given the name “amenity_hut point invalid” etc. because this way, I can easily recognize and remember, which object had which tags. It renders “amenity_hut point invalid” because this is the _name_ tag in the test database, _not_ because it is a generated error message.

Everything works fine.

**Pull request merged**
