### PR TITLE
Show aerialway name

### LINKED ISSUE #1807: show names of aerialways
http://overpass-turbo.eu/s/bfz - aerialways with names

### PR DESCRIPTION
**Pull request by Penegal**
This is the version with `text-dy` decreased by 2 px:
image

Resolves #1807.

### CODE REVIEW

**Comment by kocio-pl** [comment]
Please fix the name of the commit similar/the same as the updated PR name - see https://github.com/gravitystorm/openstreetmap-carto/pull/3129#issuecomment-374306276.

**Comment by Penegal** [comment]
Here you are.

**Comment by kocio-pl** [comment]
Could you post a test rendering on z17+ and z19+? The rendering should differ a bit according to the code and it's good to test it.

**Comment by Penegal** [comment]
z17:
image

z19:
image

**Comment by kocio-pl** [comment]
Thanks, I tested it elsewhere and it also works great!

**Comment by geozeisig** [comment]
Show aerialway name earlier on z16. [Example for testing](https://www.openstreetmap.org/#map=16/47.2474/11.9440)

**Comment by kocio-pl** [comment]
Makes sense, maybe even earlier (z15+ sounds good for me, z14+ might work too), but it needs to be tested on the places where this could hurt (probably in the cities). On the other hand if the way is too short, the name would simply not be displayed, because it would not fit, so it's safer than rendering node labels.

Could you test it a bit?

**Comment by geozeisig** [comment]
+1. Sorry but I have no test system.

**Pull request merged**
