### PR TITLE
render labels for named barriers

### PR DESCRIPTION
**Pull request by matkoniecz**
Done to handle case reported in #1824 

I am not sure whatever it should be changed to ignore polygons. On one hand it will ignore closed ways (and some are valid), on the other hand things like tagging landuse with name and barrier on one object is common.

I am not sure whatever this poor tagging should result in a poor rendering.

barrier wall name eeeeee eeeeee landuse cemetery ref 1 ele 8000 operator ee ee ee operator brand ee ee ee brand closed_way master - new_barrier_name 200px

https://cloud.githubusercontent.com/assets/899988/16034062/e5364a66-320f-11e6-80da-b113c257d7d0.png
https://cloud.githubusercontent.com/assets/899988/16034070/eae4594e-320f-11e6-8c6e-8f769dc3cf25.png
https://cloud.githubusercontent.com/assets/899988/16034045/d1569e10-320f-11e6-8270-13a91b3dc952.png

### CODE REVIEW

**Comment by matkoniecz** [comment]
> This branch has conflicts that must be resolved

That was not expected, but in this case it is useful - this one should not be merged too quickly. It will make map worse in many places and the question is whatever doing that for this type of poor tagging is desirable.

**Comment by matkoniecz** [comment]
Previous try - see  #1885

**Comment by matkoniecz** [comment]
To see how common area+barrier+name problem is see http://overpass-turbo.eu/s/gME

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 14 giu 2016, alle ore 09:11, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> I am not sure whatever it should be changed to ignore polygons. On one hand it will ignore closed ways (and some are valid), on the other hand things like tagging landuse with name and barrier on one object is common.
> 
> I am not sure whatever this poor tagging should result in a poor rendering.
> 

IMHO we should not encourage or endorse broken mapping like barrier=wall landuse=cemetery on the same object.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 14 giu 2016, alle ore 09:21, Mateusz Konieczny <notifications@github.com> ha scritto:
> 
> To see how common area+barrier+name problem is see http://overpass-turbo.eu/s/gME
> 

if we start to highlight the problem by showing names on these linear barriers as well (or maybe even show the whole area as barrier) we can be confident that people will clean it up quickly

**Comment by jojo4u** [comment]
Apart from violating the rule "one feature - one osm element" what data problems does the style have with this type of tagging?

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 14 giu 2016, alle ore 10:42, jojo4u <notifications@github.com> ha scritto:
> 
> Apart from violating the rule "one feature - one osm element" what data problems does the style have with this type of tagging?


the problem is that you don't know:
- which tag belongs to which object
- whether the feature is intended to be linear or a polygon (in some cases, like barriers)

**Comment by matkoniecz** [comment]
> whether the feature is intended to be linear or a polygon (in some cases, like barriers)

And this data problem was reported as style problem, see #971

**Comment by pnorman** [comment]
:-1: to anything which treats the same object as both a line feature and a polygon feature

**Comment by dieterdreist** [comment]
2016-06-14 23:15 GMT+02:00 Paul Norman <notifications@github.com>:

> 👎 to anything which treats the same object as both a line feature and a
> polygon feature




while I agree with this position, it should be actively communicated to the
community IMHO, because a lot of people do indeed map in a way where both,
linear and polygonal features, are mapped to the same OSM object,
especially barriers.

**Comment by SomeoneElseOSM** [comment]
@dieterdreist The place to do that is probably on http://wiki.openstreetmap.org/wiki/One_feature,_one_OSM_element .  That's I refer people to, and I suspect that others do too.  Also, of course raise it with new mappers in changeset discussions.

**Comment by matkoniecz** [comment]
@pnorman 

> :-1: to anything which treats the same object as both a line feature and a polygon feature

Is it rejection of [barrrier=* + landuse=*] tagging or is it rejection of this rendering? Or both?

**Comment by math1985** [comment]
> Is it rejection of [barrrier=* + landuse=*] tagging or is it rejection of this rendering? Or both?

barrier=city_wall + landuse=retail on a closed linestring should be interpreted as a polygon that is both a city wall and a retail area (i.e. a big city wall tagged as polygon with shops inside).

The rendering should match that interpretation.

I'd recommend waiting with this issue until the database reload, because this might change things.

**Comment by pnorman** [comment]
> I'd recommend waiting with this issue until the database reload, because this might change things.

I don't see that it'll change things, since it'll still be a polygon (or not).

The technical implementation of this is that there's a function which, given the tags of an object, tells you if it is a polygon or not.

**Comment by matkoniecz** [comment]
@pnorman What is your opinion about rendering names solely for lines?

**Comment by pnorman** [comment]
4M barriers, 17k named.

Selecting random ones I see a mix of descriptions and actual names. Most of the named ones old.

The problem is going to be coming up with a suitable style, and I have no ideas there.

**Pull request closed without merging**
