### PR TITLE
Add color fill for mangrove, reedbed and saltmarsh wetlands

### LINKED ISSUE #2013: Render reedbed with a non-transparent color
An area of reedbed is currently rendered as an overlay with a transparent color. This is imho incorrect because one doesn't see any water.

Example (the brown area in the west and north is reedbed):
bildschirmfoto 2016-01-02 um 08 45 23

The current rendering result (https://www.openstreetmap.org/#map=14/54.8719/8.3219):

bildschirmfoto 2016-01-02 um 08 46 34

I recommend to render reedbed this way (example):

bildschirmfoto 2016-01-02 um 08 49 24

Regards Klaus

### LINKED ISSUE #2025: Render wetland=mangrove with dark green fill
Mangroves are as dense as forests and `wetland=mangrove` should be rendered with a green fill, the same shade as `natural=wood`. There is already a green fill for `wetland=swamp`. I noticed it when I got myself adding `natural=wood` to mangroves, which would be as redundant as adding it to swamps. A rookie tagging-for-the-renderer mistake. :)

My suggestion is to keep rendering `natural=wetland` as a transparent layer with cyan dashes, but render every heavily used `wetland=*` with an icon and colour combination representative to each type of wetland. 

For instance, while `wetland=swamp` and `wetland=marsh` have this pattern (unique icons and colours identical to `natural=wood` and `natural=grassland`, respectively), `wetland=mangrove` and `wetland=reedbed` have only the unique icon. A similar issue was reported in #2013 for reedbeds, and in my opinion they should be coloured like `natural=scrub` or an already existing colour for `natural=*` with medium density.

### LINKED ISSUE #3799: Render wetland=saltmarsh with a fill color
- Unlike most wetlands, wetland=saltmarsh has only a pattern with no fill
- This is the same situation as with wetland=mangrove and wetland=reedbed; all 3 features currently have no fill, because when we used land polygons the ocean and water fill colors were rendered below landcover, and these features can be found outside of the coastline or over water areas.
- There are issues for the two other features requesting a color fill rendering: #2013 and #2025
- This new issue is created so that all 3 features can have a color fill added, now that the oceans and water areas are rendered above `landcover`
- Now, if wetland=saltmarsh is drawn outside of the coastline it will continue to have a blue, ocean color fill; the fill color would only be seen when the feature is over land. 
- It is suggested that wetland=saltmarsh could have the same color as wetland=marsh, or a similar color

### PR DESCRIPTION
**Pull request by jeisenbe**
Fixes #2013 
Fixes #2025
Fixes #3799

## Changes proposed in this pull request:
- Add `@scrub` color fill for `wetland=mangrove`
- Add `@grass` color fill for `wetland=reedbed`
- Add `@grass` color fill with a white dot pattern for `wetland=saltmarsh`

###  z13 Potowai

**Before**
https://www.openstreetmap.org/#map=13/-4.2983/134.9890
z13-potowai-mangroves-before
**After**
z13-potowai-mangroves-scrub-fill-after

### z15 mangroves by tidalflat
https://www.openstreetmap.org/#map=15/-4.4014/135.0908
**Before**
z15-mangroves-tidalflat-beach-before
**After**
z15-mangroves-scrub-fill-tidalflat-beach-aftrer

## 2) Saltmarsh with white dot pattern and `@grass` fill - `#cdebb0`
- Pattern from [http://www.imagico.de/map/jsdotpattern.php#x,128,jdp68152;g,5,32,32;rx,25,2,32,32;rx,25,2,32,32;rx,25,2,32,32;rd,0,0,0,dot,0.125,10,9,0,jdp48264,ffffff,cdebb0;]( http://www.imagico.de/map/jsdotpattern.php)

### A. **Salt marsh (left) and marsh (right) - before**
https://www.openstreetmap.org/#map=13/51.3590/4.1393
z13-schelde-saltmarsh-vs-marsh-before
After
z13-schelde-saltmarsh-dots2

### B. Before - Small salt marshes: one over sea water, one over land in database
https://www.openstreetmap.org/#map=15/51.4552/3.6555
z15-slufter-saltmarshes-zeeland-before
After
z15-slufter-saltmarsh-dots2

### C. **Before - saltmarsh (left) next to marsh (center), mouth of the Eel river, California**
z14-eel-river-saltmarsh-marsh-before
After
z14-eel-river-marsh-saltmarsh-dot2

### z18 reedbeds vs marshes before
https://www.openstreetmap.org/#map=18/51.73020/3.72768
18-reedbeds-vs-marshes-before
After
z18-reedbeds-marshes-grass-color-after

### z16 reedbed farm before
https://www.openstreetmap.org/#map=16/51.4514/3.9198
z16-reedbed-farm-before
After
z16-reedbed-farm-grass-color

### CODE REVIEW

**Comment by imagico** [comment]
By the way @jeisenbe - i sent you two emails about two weeks ago and i have not received a reply - could you check your spam filter?

**Comment by jeisenbe** [comment]
> By the way @jeisenbe - i sent you two emails about two weeks ago and i have not received a reply - could you check your spam filter?

I never got those emails @imagico, even after checking the spam filter. Did you every try resending them?

**Comment by jeisenbe** [comment]
I've made the suggested change to limit the pattern to z13 and above only.

And I've also tested using a pattern based on reef.svg but in white with partial opacity as suggested:

0) Current commit


1) Reef dots - 100% opacity white
z13-verdronken-saltmarsh-after-with-reef-100-percent-opacity

2) Reef dots - 75% opacity
z13-verdronken-saltmarsh-after-with-reef-75-percent-opacity

3) Reef dots - 50% opacity
z13-verdronken-saltmarsh-after-with-reef-50-percent-opacity

The 100% opacity version is ok, but the others seem too subtle to me.

**Comment by imagico** [comment]
> I never got those emails @imagico, even after checking the spam filter. Did you every try resending them?

I sent them again on June 20 - from two different mail clients.  That Google has an arrogant attitude in terms of what email they regard as legitimate and what not is known but i have never seen this in such extreme form with both mail from my gmx.de and from imagico.de being silently ignored (which is not ok by any measure - they'd either have to reject it or deliver it).

I tried using the OSM messaging system now - which should work no matter how much google tries to prevent it from working.

**Comment by jeisenbe** [comment]
Here are tests at https://www.openstreetmap.org/#map=#14/40.6192/-124.2910 with salt marsh and marsh in the same view:

0) Current commit


1) 100% opacity reef pattern in white
z14-eel-river-marshes-reef-dots-100percent

2) 75%
z14-eel-river-marshes-reef-dots-75percent

3) 50%
z14-eel-river-marshes-reef-dots-50percent

**Comment by jeisenbe** [comment]
@imagico thoughts on the current pattern vs the more subtle reef.svg white dot pattern?

**Comment by imagico** [comment]
The reef pattern seems a bit weak as is - you could try to make it heavier but ultimately the current version is fine as well.

**Comment by jeisenbe** [comment]
OK. I prefer having the slightly stronger pattern in the current
commit, if it's not a problem.

**Comment by jeisenbe** [comment]
I'm going to merge this now, since it's been approved by another maintainer and there were no other concerns. Just checking: is it best to "squash and merge" the 5 commits into one, or just rebase and merge the 5 separate commits? 

It seems like it would help keep the development history more concise to use squash and merge.

**Comment by imagico** [comment]
I don't really mind but others have indicated to prefer squash and merge.

**Comment by kocio-pl** [comment]
The motivation was that squash and merge keeps the code changes clean, so people outside the project can see what changes, not the inner technical details of the change. It also makes writing Changelog easier.

**Comment by jeisenbe** [comment]
Should I update the changelog when merging this PR, or is that done later?

**Pull request merged**
