### PR TITLE
Add icon for shop=massage

### LINKED ISSUE #3287: Add special icon for shop=massage
https://wiki.openstreetmap.org/wiki/Tag:shop=massage
8k uses

Icon could be a massage table? I haven't been able to design anything intuitive enough for this.

### PR DESCRIPTION
**Pull request by jragusa**
Fixes #3287

Changes proposed in this pull request:
Render `shop=massage` from z18 using leisure-green colour

Test rendering with links to the example places:

Node
https://www.openstreetmap.org/node/4992712423
massage_point

Way
https://www.openstreetmap.org/way/183708628
massage_way

### CODE REVIEW

**Comment by kocio-pl** [comment]
After merging #3293 this code needs to be updated to resolve conflicts.

**Comment by kocio-pl** [comment]
Hm, it works strange - for z17 instead of dot (which color should it be?) it shows miniaturized icon, for example:

screenshot_2018-07-19 jybq9re1 png obraz png 3155 x 3105 pikseli

**Comment by jragusa** [comment]
I see why there is an small icon at z17. But before to make changes, I would like to know whether we leave a dot for z17 like other shops or we bypass rendering for z17 ?

**Comment by lakedistrictOSM** [comment]
I think that we should bypass rendering at z17. z18 is good enough for massage places.

Purple would be the wrong colour and green dots aren't yet used (and also might look like trees).

**Comment by jragusa** [comment]
After correction:

z17
name appears as there is no pink dot (I suppose)
massage_z17

z18
massage_z18

z19
massage_z19

**Comment by kocio-pl** [comment]
I guess it's safe to render from z18. I don't have good idea for not typical colors of shops - BTW similar problem is with `shop=car_repair` (#1778).

**Comment by kocio-pl** [comment]
Could you update the code once again? I plan to merge it soon.

BTW: please, add some line breaks aligned to the lines above, so the code is more readable and easier to edit.

**Comment by jragusa** [comment]
Done, I also put some line breaks as suggested. 

Is it correct for you ?

**Comment by kocio-pl** [comment]
Thanks, this is good!

**Pull request merged**
