### PR TITLE
Replacing tourism information PNG icon with SVG version

### PR DESCRIPTION
**Pull request by kocio-pl**
Implements part of #1165.

I guess we should no longer wait for a database reload, because it is not going to be anytime soon, and instead just start with what's available now - here is just an osmic version of tourism information:

ccpf9yli

BTW: the name of such POI is not rendered - maybe we should start showing it?

### CODE REVIEW

**Comment by nebulon42** [comment]
That icon was intended for `tourism=information` `information=office`. Maybe it would be better to use a lighter version of i since it may be too heavy in areas where lots of guideposts are mapped.

**Comment by kocio-pl** [comment]
+1, I will try to make it thinner.

**Comment by kocio-pl** [comment]
Made thinner a bit:
5wdtt7rx

**Comment by daganzdaanda** [comment]
I like it - though it's still stronger than the current png and may still be a bit much for cities with lots of signposts. But fine-tuning can be done when information=* is available.

**Comment by matkoniecz** [comment]
Can you check how it would work in http://www.openstreetmap.org/#map=17/51.71219/10.51618 and other areas mentioned in #324?

**Comment by kocio-pl** [comment]
Looks like it's still too bold when it's more than one, so I'll try to make it even smaller:
pydr4zju

**Comment by kocio-pl** [comment]
Now it should be better (with icon resized to 12 px as some other small POIs):
kvbaukam

**Comment by matkoniecz** [comment]
Initial version would be great for information=office, https://github.com/gravitystorm/openstreetmap-carto/pull/2049#issuecomment-188778969 will be good for now. Thanks for SVGfication!

**Pull request merged**
