### PR TITLE
Switch vineyard to SVG

### PR DESCRIPTION
**Pull request by sommerluk**
Switch vineyard to SVG.

Before:
screenshot 4

After:
screenshot 5

### CODE REVIEW

**Comment by imagico** [comment]
I would suggest you increase the vertical gap between the symbol from 1/3 to 2/3 pixel - this way you would avoid a visual overlap between the lines in vertical direction.

However you would also more prominently see the problem from #2727:

vineyard_test

left is with `polygon-gamma: 1;` as per point 4 in https://github.com/gravitystorm/openstreetmap-carto/pull/2727#issuecomment-322042825, right as is with your code (which is equivalent to point 3).

**Comment by sommerluk** [comment]
> I would suggest you increase the vertical gap between the symbol from 1/3 to 2/3 pixel

That implies to reduce the height of the lines from 5 to 4⅔. If that’s okay, I can increase the gap…

Might it make sense to use round line caps?

**Comment by imagico** [comment]
> That implies to reduce the height of the lines from 5 to 4⅔.

That is correct.

Note the length perception of for example a 5px line differs significantly depending on if it is pixel aligned or not.

Ultimately any such changes are small compared to those caused by the SVG rendering issues (#2750).

**Comment by kocio-pl** [comment]
Is this code ready to be merged? How does this pattern look like now?

**Comment by sommerluk** [comment]
Rebased.

Implemented the suggestion of @imagico 

screenshot 1

**Comment by kocio-pl** [comment]
For me it's fine, you can join the commits into one.

**Comment by math1985** [comment]
I'd prefer if the person merging the PR does that.

**Comment by kocio-pl** [comment]
What would that help us with?

**Comment by sommerluk** [comment]
Oops, too late, the commits are yet joined (and I likely don’t know how to un-do that).

**Comment by sommerluk** [comment]
> What would that help us with?

Would mean less work for me 😉

**Comment by math1985** [comment]
The PR proposer normally doesnt know in advance when review of his PR is finished, so it's hard to know what's the right moment for squashing. In this case @kocio-pl explicitly asked for it, which requires an additional action from the proposer (and not all proposers respond as faat). My comment was more to point out general best practice, but in this particular case it really does not matter.

**Comment by kocio-pl** [comment]
I understand now, but I guess this would change the commit attribution (from the author to the merger)?

**Comment by math1985** [comment]
Good point, I'm not quite sure.

**Comment by HolgerJeromin** [comment]
> I understand now, but I guess this would change the commit attribution (from the author to the merger)?

I am pretty sure it will not. You can fake whatever you want with git. I have done nothing codewise for #1694 Mateusz has done everything by himself.

**Comment by matkoniecz** [comment]
In #1694 I probably manually added authorship information.

Git rebase is not changing authorship information (for merging commits by the same author), what github calls rebase is changing authorship metadata - see https://help.github.com/articles/about-pull-request-merges/#rebase-and-merge-your-pull-request-commits

**Comment by kocio-pl** [comment]
As far as I understand we should not move this pattern to SVG, since it uses gamma (#2750).

**Comment by kocio-pl** [comment]
Thanks for trying! I hope we will eventually switch raster patterns to SVG one day.

**Pull request closed without merging**
