### PR TITLE
Uniformize swamp rendering with forest/wood

### LINKED ISSUE #1920: Standardize pictos of wood/forest and swamp/mangrove
Hello, there.

Some weeks ago, the #1728 pull request changed the tree symbols used for `landuse=forest` and `natural=wood` for smoother ones:
forest

Now, I'm under the impression that the tree symbols used for `wetland=swamp`
swamp
and `wetland=mangrove`
mangrove
should be updated too to use the same tree symbol for swamp, and a multiroot version for mangroves, as they are now different, the difference being visible as the tree symbol for wetlands is not as smooth as the one for wetlands.

Just saying…

Regards.

### PR DESCRIPTION
**Pull request by Penegal**
This is my first PR, which I hope is good enough; it fixes #1920 using @imagico's pattern for `wetland=swamp`, which uniformizes the tree icons with the ones of `natural=wood` and `landuse=forest`.

Before:
image

After:
image

P.-S.: I closed a first PR for that, it had an authoring problem; it can be safely deleted, if relevant.

### CODE REVIEW

**Comment by kocio-pl** [comment]
Great, I hope I will test it soon! 

Two general questions:
1. Do we want to show different leaf types? I haven't found such tags [in combination with swamp](https://taginfo.openstreetmap.org/tags/wetland=swamp#combinations), so we may not bother and add it later if it ever start to be popular enough.

2. How did you made the images? Please document them if needed (I guess this was made with a [general instruction](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/wetland.md), but I want to make sure) and remove the [old image](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/swamp.svg) if not needed elsewhere.

You don't have to squeeze the commits, because maintainers can do it easily now while merging.

**Comment by Penegal** [comment]
Well, I merely added the images @imagico made, so I'm unsure about your questions, but, naively, I would say:
 1. let's not bother about that if there is no data, and
 2. @imagico did them, most probably using his [jsdotpattern](https://github.com/imagico/jsdotpattern); what the parameters were, however, I can't say.

**Comment by kocio-pl** [comment]
I meant how did you combine them if this is not already documented.

OK, so let just remove the old image if not needed (I guess it was used only for producing swamp image).

**Comment by kocio-pl** [comment]
OK, that's what I suspected. Any other comments or is it OK for you?

**Comment by kocio-pl** [comment]
> The change in symbol can be done on the SVG level, no need to re-generate the base pattern.

Do you mean producing SVG image (or what else)?

**Comment by imagico** [comment]
>> The change in symbol can be done on the SVG level, no need to re-generate the base pattern.

> Do you mean producing SVG image (or what else)?

I meant replacing the symbol in the SVG code in 

https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/master/symbols/generating_patterns/swamp.svg

with a different symbol.

**Comment by kocio-pl** [comment]
@Penegal Do you plan to fix this?

**Comment by Penegal** [comment]
Don't read this with an ironic tone, it is not my intent: as you 2 were talking on your own, I thought you were no longer waiting my contribution. I'll try, then, once I will have found the necessary symbols and the parameters of your pattern generation code.

**Comment by Penegal** [comment]
Upon reflection, I don't understand how I can use the pattern generation code with 2 symbols; the .md file for wetland doesn't help, as it describes the generation of a bitmap using ImageMagick, not a SVG. I could create the SVG myself, but there must be some semi-automated way to do it, isn't it?

**Comment by imagico** [comment]
The description in

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/wetland.md

describes in a generic way how to produce the composite wetland patterns from the generic wetland svg

https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/master/symbols/generating_patterns/wetland.svg

and the specific pattern svg (named `pattern.svg` in the document), in this case

https://raw.githubusercontent.com/gravitystorm/openstreetmap-carto/master/symbols/generating_patterns/swamp.svg

and the two colors `$SYMBOL` and `$WETLAND`.

This will allow you to re-create the current swamp png from the svg files.

To generate a new pattern with different symbols you do the same - but with a different `pattern.svg` where you replace the symbol SVG code (which you can find in the `defs` section on top) with a new symbol code.  This requires some knowledge of the svg format of course.

**Comment by kocio-pl** [comment]
> Don't read this with an ironic tone, it is not my intent: as you 2 were talking on your own, I thought you were no longer waiting my contribution. 

We have the open, public discussions here and this is very typical to nitpick all the details before merging from all the possible points of view. Not only your contribution is welcome, but also it looks like quite close to being accepted.

**Comment by Penegal** [comment]
@imagico: I followed the instructions, retrieved the colors from already existing patterns and used `symbols/leaftype_unknown.svg` as `pattern.svg`, but it still generated a PNG pattern, not a SVG one.

There must be something I'm missing here: AFAIK, `convert`, as all ImageMagick commands, can only generate bitmap images. How could it be that I should use it to generate an SVG pattern? What am I missing here?

Now, I could ask someone else to do it, but, now I'm on it, I would like to be able to understand and complete the task, as asking somebody else won't learn me anything.

@kocio-pl: OK, thanks for the note.

**Comment by imagico** [comment]
The wetland patterns are generated as PNG.  You could try implementing a similar process on SVG level but given the limited scripting abilities of Inkscape and the lack of any other tools that allow similar processing in an automated fashion makes this difficult.

And considering Mapnik's SVG pattern rendering is broken the practical usefulness of this would be rather limited.

**Comment by Penegal** [comment]
Oh, I think I see my error: I thought I had to generate the whole swamp pattern in SVG, but only had to regenerate `symbols/generating_patterns/swamp.svg` and create my PNG from it, right? Instead, I followed the instructions for wetland pattern generation, using `symbols/leaftype_unknown.svg`.

Could it be OK to simly use this 256*256 px pattern 4 times to generate the 512*512 px `symbols/generating_patterns/swamp.svg`?

**Comment by imagico** [comment]
The 512x512 pixel pattern size for wetlands was chosen because of the difficulty of creating a proper random relaxed pattern of this density at a smaller size.  Apart from that there is no reason why you cannot use a pattern of 256x256 pixel.

**Comment by Penegal** [comment]
Then I'll try to create the 512*512 px manually.

**Comment by Penegal** [comment]
And here you are! Is it OK now? BTW, FWIW
image

… I used jsdotpattern this way:
- selected _tree pair_ icon;
- selected 512*512 image;
- typed a distance of 25, then clicked _generate_;
- clicked _relax ×10_.

**Comment by kocio-pl** [comment]
Please have a look at the files, looks like something is wrong with both images - right and bottom parts have unexpected margin space with no tree pattern.

**Comment by Penegal** [comment]
Wow, I missed that! Strange… I'll check it; thanks for noticing.

**Comment by kocio-pl** [comment]
It also looks like `wetland_swamp@2x.png` is darker than `wetland_swamp.png` and I guess they shouldn't be different visually.

**Comment by Penegal** [comment]
That must be from the interpolation used when doubling the resolution, because I did nothing else.

**Comment by kocio-pl** [comment]
Could you try the same procedure with current versions to see if this problem will appear?

**Comment by kocio-pl** [comment]
@Penegal What is current state of this code, do you think you can fix it?

**Comment by Penegal** [comment]
Kept that in mind but had no time to correct; I'll try to fix it in the next days.

**Comment by Penegal** [comment]
Well, I don't understand why, but the `pattern_casing.png` file is truncated to 481×481 px, whereas the `swamp.svg` file is 512×512 px with no empty borders; here is `pattern_casing.png`:
pattern_casing

My knowledge about ImageMagick tools is near zero; do you see where the problem could lie?

**Comment by Penegal** [comment]
Is there someone with ImageMagick knowledge who could say why the first `convert` call shrinked the image, or, if normal, why it affects subsequent images when it shouldn't? I assume the generated `pattern_casing.png` mask should not be shrinked to 481×481 px.

**Comment by Penegal** [comment]
I inadvertently added a text file to this PR which contains the actual command I used for the pattern generation. I'll remove it later, but not now, as it could be helpful to find out why the pattern generation commands failed to produce the expected result.

**Comment by kocio-pl** [comment]
> I'll remove it later, but not now, as it could be helpful to find out why the pattern generation commands failed to produce the expected result.

It would be better to have these all instructions to make the process of producing final images predictable and straightforward. @imagico (or anybody else who was doing the conversion): Do you know precise commands which are needed to produce them?

**Comment by imagico** [comment]
@Penegal - I can't reproduce the problem:

```
$> convert -depth 8 swamp.svg swamp.png
$> convert -depth 8 swamp_new.svg swamp_new.png
$> convert -depth 8 leaftype_unknown.svg leaftype_unknown.png
$> identify swamp.png 
swamp.png PNG 512x512 512x512+0+0 8-bit sRGB 256c 12.9KB 0.000u 0:00.000
$> identify swamp_new.png 
swamp_new.png PNG 512x512 512x512+0+0 8-bit sRGB 256c 44.9KB 0.000u 0:00.000
$> identify leaftype_unknown.png
leaftype_unknown.png PNG 256x256 256x256+0+0 8-bit sRGB 29c 2.25KB 0.000u 0:00.010
$> convert --version
Version: ImageMagick 6.9.5-9 Q16 x86_64  http://www.imagemagick.org
Copyright: Copyright (C) 1999-2016 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib cairo djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png rsvg tiff webp wmf x xml zlib
$> convert -list format | grep SVG
     MSVG  SVG       rw+   ImageMagick's own SVG internal renderer
      SVG  SVG       rw+   Scalable Vector Graphics (RSVG 2.40.10)
     SVGZ  SVG       rw+   Compressed Scalable Vector Graphics (RSVG 2.40.10)
```

You can also try rasterizing with inkscape or sanitizing the SVG before rasterizing using jsdotpattern `svg_pattern.sh`.

**Comment by Penegal** [comment]
@imagico: I tried both your solutions, and none worked, I still got a 481×481 px `pattern_casing.svg`.
```
~/o/s/generating_patterns (swamp_icon|✚1…) $ convert -version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jp2 jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

**Comment by imagico** [comment]
Your ImageMagick does not appear to include RSVG support.  It might still be able to correctly process the sanitized SVG code but i would probably not recommend that.

You could rasterize the SVG with Inkscape and use that instead of the SVG in the process (not sure if you mean you tried that when you say _I tried both your solutions_).

**Comment by Penegal** [comment]
Yes, I meant I also tried to sanitize the SVG using Inkscape with your `svg_pattern.sh` sanitizing script. I prefer not replace the packaged version of imagemagick with a manually installed one, but I can deal with it if you think it is useful.

**Comment by kocio-pl** [comment]
Any news with this PR?

**Comment by Penegal** [comment]
Nope; I wasn't able to find why ImageMagick messed with my SVG patter. If someone wants to generate a correct pattern from my SVG to allow me to PR, or PR this himself from my branch, that would be great.

**Comment by matthijsmelissen** [comment]
Is anybody willing to help @Penegal with generating the pattern from his SVG?

**Comment by kocio-pl** [comment]
I'm trying to produce new wetland_swamp image on Ubuntu 18.04 with standard ImageMagick using commands from https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/generating_patterns/wetland.md 

First I got something like this:

wetland_pattern

It has the same problem as Penegal image, but it's also pale.

So I removed and installed ImageMagick once again just in case. Now I discovered that the code assumes existence of `pattern.png`. So I created it just by:

`convert pattern.svg pattern.png`

and the resulting image is already broken - it has only 485 px:

pattern

but even:

`convert -depth 8 -size 512x512 pattern.svg pattern.png`

does not help. But it looks like the source of the problem.

So what is the proper way to convert `pattern.svg` into `pattern.png` using ImageMagick so it has 512 px?

**Comment by kocio-pl** [comment]
Well, it looks like ImageMagick has a problem with both old and new swamp SVGs and that's why it converts them into smaller PNGs:

```bash
$ identify swamp.svg 
swamp.svg SVG 485x485 485x485+0+0 8-bit sRGB 110KB 0.000u 0:00.000

$ identify swamp-new.svg 
swamp-new.svg SVG 485x485 485x485+0+0 8-bit sRGB 117KB 0.000u 0:00.000
```

**Comment by Penegal** [comment]
Maybe we should reach the ImageMagick devs to check if this is a known bug?

**Comment by matthijsmelissen** [comment]
@imagico Do you have any idea what could be going wrong here?

**Comment by imagico** [comment]
As said i can't reproduce this problem and it could be related to ImageMagick builts without RSVG support.

You can rasterize with Inkscape as well of course but in general an Inkscape dependency is probably more problematic.

**Comment by kocio-pl** [comment]
@imagico What operating system version and ImageMagick package version do you use?

**Comment by imagico** [comment]
See https://github.com/gravitystorm/openstreetmap-carto/pull/3051#issuecomment-371837679

It's the same with newer versions by the way (like Imagemagick 7.0.7/RSVG 2.42.3).

**Comment by kocio-pl** [comment]
I ask for more specific informations, because it seems I have the same app version, so maybe it's something about compilation or run time environment. Ubuntu is very popular and if it has some bugs, more people will hit that wall:

```bash
$ convert --version
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC Modules OpenMP 
Delegates (built-in): bzlib djvu fftw fontconfig freetype jbig jng jpeg lcms lqr ltdl lzma openexr pangocairo png tiff wmf x xml zlib
```

```bash
$ dpkg -s imagemagick
Package: imagemagick
Status: install ok installed
Priority: optional
Section: graphics
Installed-Size: 114
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Architecture: amd64
Multi-Arch: foreign
Version: 8:6.9.7.4+dfsg-16ubuntu6
Depends: imagemagick-6.q16 (>= 8:6.9.2.10+dfsg-2~)
```

```bash
$ convert --version | grep Version:
Version: ImageMagick 6.9.7-4 Q16 x86_64 20170114 http://www.imagemagick.org
```

**Comment by imagico** [comment]
As said my working hypothesis is that this is a problem specific to ImageMagick without RSVG.  So far no one has disproven that.

If you want to get RSVG support via package management you probably need some additional package for that (usually some `imagemagick*extra` stuff).

**Comment by kocio-pl** [comment]
There are no other `imagemagick*` packages available that I don't have installed. After installing `librsvg2-bin` package there is new utility - `rsvg-convert`, however it does not work with all the options, namely `-depth`, `-density` and `-negate`.

It's an external bug/issue, but I prefer to find a workaround for Ubuntu.

**Comment by kocio-pl** [comment]
Unfortunately `rsvg-convert` won't support these options, so we need some other toolchain, maybe using some manual tools like Inkscape for example:

https://gitlab.gnome.org/GNOME/librsvg/issues/329#note_307349

**Comment by federicomenaquintero** [comment]
I'm the maintainer of librsvg, so I'm happy to help with this.

If someone can walk me through the script mentioned in `wetland.md`, maybe I can come up with a way to do it with SVG only (e.g. using SVG filter effects for erode, lighten, negate, etc.), and then you can just render a single file with `rsvg-convert` or something like that?  Would that be useful?

**Comment by imagico** [comment]
> maybe I can come up with a way to do it with SVG only (e.g. using SVG filter effects for erode, lighten, negate, etc.)

Unlikely since i don't suppose you can do the vector equivalent of `-morphology hitandmiss` with that.

**Comment by kocio-pl** [comment]
@imagico Could you help with this issue and for example produce proper files? It seems that currently nobody else has the environment which works this way.

**Comment by imagico** [comment]
For info: There is meanwhile a fully scripted pattern preprocessing system in my style that can use either inkscape or imagemagick for rasterization and allows adjusting the rasterizing resolution.

https://github.com/gravitystorm/openstreetmap-carto/commit/00eb1a3963ad95e8b45df78a773bac8e9d1f565c

This does not however build SVG source files for the composite wetland patterns.  Have not yet found a good automated method for that (the files i use are essentially hand made).

But if the script works for you that would solve your SVG rasterization problems.

**Comment by PenegalECI** [comment]
@imagico: I could use a sample command line here; my Python knowledge is rather low.

**Comment by imagico** [comment]
You don't really need any python knowledge to see what commands are used for rasterizing the SVGs.  It is quite literally in

https://github.com/imagico/osm-carto-alternative-colors/blob/master/scripts/generate_patterns.py#L29-L53

My reason for mentioning this here is that you indicated problems doing this with imagemagick and here you have it demonstrated how to use inkscape as alternative.

You have four variants for both - either with transparent background or white background and either with or without resolution specified.

But as said creating the composite pattern using the procedure described in wetland.md is still the same.  If you want to use inkscape for rasterization you have to modify this of course - you need to rasterize once at native resolution and a second time at 8 times the linear resolution for the morphology operations.

**Comment by Penegal** [comment]
@imagico: if I understand correctly, your Inkscape calls only replace the `convert -depth 8 -density 90 wetland.svg wetland_tile.png` call with `inkscape -z --export-png=wetland_tile.png --export-dpi=90 --export-background=white wetland.svg` — this is the command that I understood, from your Python code, I should use —; if so, I still have the truncated `wetland_tile.png` pattern I got the last times. Besides, that doesn't prevent the erroneous final `wetland_pattern.png` to be generated once more.

If your configuration allows you to correctly generate the patterns, would you simply generate them and then you or I would include them in the PR and that's all? We wouldn't get the cause of these bugs, but they would have been circumvented and the new patterns could be put in production. This PR has been opened months ago, and you seem the only one to be able to generate the patterns correctly. Would you generate them?

**Comment by imagico** [comment]
Of course i can generate a pattern image for this but for the goal of adaptability and maintainability there should be a working process to create those to allow people adjusting the pattern - like for using different symbols or a different color.

I would gladly help you tracking down the problem you have but since i can't reproduce it i cannot really do much about it actively.

A useful starting point could be to run the pattern image generation on the alternative-colors style and see what the results are.  Do they differ between using Imagemagick or Inkscape?  Are all patterns produced incorrectly or just some?

Another starting point would be to open the pattern SVG in Inkscape interactively and then try to export it as PNG.  Does it correctly export the image then?  With the right extent and the right size?  The inkscape command should generate the same as you get when you interactively export the image from inkscape.

**Comment by Penegal** [comment]
Well, I think I found something explaining the downsizing of `wetland_tile.png`: `wetland.svg` has a density of 96 ppp; in Inkscape, when I try to change the density to 90 ppp, the size changes from 256*256 px to 240*240 px. I don't know how the SVG gives 96 ppp for density, but it seems that this difference explains the problem.

Regarding the `swamp.svg` downsizing, I tried to regenerate it using your online version of jsdotpattern, and, even if it is generated with a 512*512 px size specified in the SVG code, it get resized, but, if I try to export it using a 96 ppp density, the exported size miraculously increases to 512 px. Definitely a density-related bug here, but why? I'll try to get a more recent version of imagemagick, if I can install it without breaking my distro.

**Comment by Penegal** [comment]
Gah! Tried to remove density-related arguments for `patter_casing.png` generation:
pattern_casing

That would need messing with other arguments, which is way too much for my current imagemagick knowledge.

**Comment by Penegal** [comment]
Ok, I tried with the testing version of ImageMagick (6.9.10-23), and here is what I got: `pattern_casing.png` is still 481*481 px, which breaks subsequent operations:
image

If you look closely, you will see that room was made in the wetland pattern for the tree pairs, but the holes are slightly too little and too close of each others for the tree pairs to fit in. This version of ImageMagick correctly interprets the second-to-last `convert` command, but still lacks a correct understanding of the first `convert`, hence the 481*481 px `pattern_casing.png`.

**Comment by Penegal** [comment]
I also tried to upgrade `rsvg-convert` to 2.44.10-1, as it is called for SVG operations by ImageMagick, but that did not changed the problem.

**Comment by imagico** [comment]
As i have written above in https://github.com/gravitystorm/openstreetmap-carto/pull/3051#issuecomment-454434219 for the wetland pattern process you need both the native resolution version and one with eight times the linear resolution for the casing processing.

If rasterization for you without a specified resolution leads to an incorrect output resolution that is a bug in the program in the version used (presumably resulting in use of a different assumed resolution for converting SVG dimensionless units into real world units and converting back into pixel).  But since both imagemagick and inkscape allow specifying an output resolution you can compensate for that.

So you'd need to rasterize once at a resolution that matches the assumed resolution for converting between pixel and real world units and another time at eight times that resolution (which would be 768 ppi if the assumed native resolution is 96 ppi as you indicate) for the casing which is after processing scaled back to 12.5% which is the same size again.

**Comment by imagico** [comment]
I understand.  But please keep in mind that i cannot verify if what you do is working or not and if not why because the same commands for me produce different results.  

If i understand your description correctly every command that processes an SVG for you apparently will pecified to prneed the density soduce correct results.  That is the first, second and fifth in your sequence.  Presumably that is `-density 96` for the second and fifth and `-density 768` for the first.

If that does not work you should check if all the intermediate images are the correct size (that is 512x512 pixel for all except wetland_tile.png which is 256x256 pixel).

If that is not the case that would mean imagemagick does not show consistent results for you at all and you could try using inkscape for rasterization using something like

* `inkscape -z --export-png=wetland.png --export-dpi=96 --export-background=white wetland.svg`
* `inkscape -z --export-png=swamp.png --export-dpi=96 --export-background=white swamp.svg`
* `inkscape -z --export-png=swamp_hr.png --export-dpi=768 --export-background=white swamp.svg`

And then use wetland.png/swamp.png/swamp_hr.png in the process instead of using the SVGs.  You might need to use a different resolution value with inkscape than with imagemagick because the mismatch in assumed default resolutions might not be the same.  The sizes of the resulting images should be 256x256 pixel for wetland.png, 512x512 for swamp.png and 4096x4096 for swamp_hr.png.

**Comment by Penegal** [comment]
> If i understand your description correctly every command that processes an SVG for you apparently will pecified to prneed the density soduce correct results. That is the first, second and fifth in your sequence. Presumably that is `-density 96` for the second and fifth and `-density 768` for the first.

Using `-density 96` instead of `-size 512x512` for the fifth command generates a 1*1 px `pattern_col.png`; using `-density 96 -size 512x512` doesn't change the final result.

> If that does not work you should check if all the intermediate images are the correct size (that is 512x512 pixel for all except wetland_tile.png which is 256x256 pixel).

With `convert -depth 8 -density 96 wetland.svg wetland_tile.png`, `wetland_tile.png` is 259x259 px, but I can get it with 256*256 px with `inkscape -z --export-png=wetland_tile.png --export-dpi=96 --export-background=white wetland.svg`. Then, the only discrepancy with file sizes is that `patter_casing.png` is 513x513 px.

Comparing the different intermediate images, it seems that the main problem left is the first command, generating, `pattern_casing.png`, as it doesn't match `swamp.svg` and comparing them give the same offset that bothers me on the final `wetland_pattern.png`.

Now, here are the good news: it seems I finally got a good result by starting to generate a rasterized version of `swamp.svg`, then using it instead of the SVG. That gives the following chain of commands:
```
inkscape -z --export-png=swamp.png --export-dpi=96 --export-background=white swamp.svg
convert -scale 800% swamp.png -morphology Erode Disk:5.3 \( +clone -fill black -draw 'color 0,0 floodfill' -negate \) +swap -morphology Erode Disk:10.3 -compose Darken -composite -scale 12.5% -depth 8 pattern_casing.png
inkscape -z --export-png=wetland_tile.png --export-dpi=96 --export-background=white wetland.svg
montage wetland_tile.png wetland_tile.png wetland_tile.png wetland_tile.png -geometry 256x256+0+0 wetland_512.png
convert wetland_512.png \( pattern_casing.png -negate \) -compose Lighten -composite -threshold 50% \( +clone -negate -morphology hitandmiss peaks:1.9 \) -compose Lighten -composite +level 20%,100% wetland_pattern_bkg.png
convert -depth 8 -size 512x512 xc:"#93b685" \( swamp.png -negate \) -set colorspace RGB -alpha Off -compose CopyOpacity -composite pattern_col.png
convert -depth 8 -size 512x512 xc:"#4aa5fa" \( wetland_pattern_bkg.png -negate \) -set colorspace RGB -alpha Off -compose CopyOpacity -composite +compose pattern_col.png -compose Over -composite wetland_pattern.png
```

This sequence gives me the following result:
image

It seems that there is a bit of transparency on the pattern elements, but perhaps this is normal. Is that pattern OK?

**Comment by imagico** [comment]
> `convert -scale 800% swamp.png -morphology Erode Disk:5.3 \( +clone -fill black -draw 'color 0,0 floodfill' -negate \) +swap -morphology Erode Disk:10.3 -compose Darken -composite -scale 12.5% -depth 8 pattern_casing.png`

That will work in some way but blowing up the PNG image to 800% is pretty pointless.  As said to use the original process you'd need to rasterize the SVG twice - at native resolution and at eight times the native resolution.  So that would probably mean

* `inkscape -z --export-png=swamp_hr.png --export-dpi=768 --export-background=white swamp.svg`
* `convert swamp_hr.png -morphology Erode Disk:5.3 \( +clone -fill black -draw 'color 0,0 floodfill' -negate \) +swap -morphology Erode Disk:10.3 -compose Darken -composite -scale 12.5% -depth 8 pattern_casing.png`

> It seems that there is a bit of transparency on the pattern elements, but perhaps this is normal. Is that pattern OK?

I don't know.  That depends on how you want the pattern to look like in the map.  If you unintentially get semi-transparent symbols that is probably because the SVG you use is not black and white.  The one in your PR is but maybe you are working with a different one now.

**Comment by Penegal** [comment]
> That will work in some way but blowing up the PNG image to 800% is pretty pointless. As said to use the original process you'd need to rasterize the SVG twice - at native resolution and at eight times the native resolution. So that would probably mean
> 
>     * `inkscape -z --export-png=swamp_hr.png --export-dpi=768 --export-background=white swamp.svg`
> 
>     * `convert swamp_hr.png -morphology Erode Disk:5.3 \( +clone -fill black -draw 'color 0,0 floodfill' -negate \) +swap -morphology Erode Disk:10.3 -compose Darken -composite -scale 12.5% -depth 8 pattern_casing.png`

I included that in the commands sequence, and that gives me this sequence:
```
inkscape -z --export-png=swamp.png --export-dpi=96 --export-background=white swamp.svg
inkscape -z --export-png=swamp_hr.png --export-dpi=768 --export-background=white swamp.svg
convert swamp_hr.png -morphology Erode Disk:5.3 \( +clone -fill black -draw 'color 0,0 floodfill' -negate \) +swap -morphology Erode Disk:10.3 -compose Darken -composite -scale 12.5% -depth 8 pattern_casing.png
inkscape -z --export-png=wetland_tile.png --export-dpi=96 --export-background=white wetland.svg
montage wetland_tile.png wetland_tile.png wetland_tile.png wetland_tile.png -geometry 256x256+0+0 wetland_512.png
convert wetland_512.png \( pattern_casing.png -negate \) -compose Lighten -composite -threshold 50% \( +clone -negate -morphology hitandmiss peaks:1.9 \) -compose Lighten -composite +level 20%,100% wetland_pattern_bkg.png
convert -depth 8 -size 512x512 xc:"#93b685" \( swamp.png -negate \) -set colorspace RGB -alpha Off -compose CopyOpacity -composite pattern_col.png
convert -depth 8 -size 512x512 xc:"#4aa5fa" \( wetland_pattern_bkg.png -negate \) -set colorspace RGB -alpha Off -compose CopyOpacity -composite +compose pattern_col.png -compose Over -composite wetland_pattern.png
```

This sequence works for me; should I include it in `wetland.md`, as a replacement in the case the reader encounters the same problem as me, and then carry on to finishing this PR?

> I don't know. That depends on how you want the pattern to look like in the map. If you unintentially get semi-transparent symbols that is probably because the SVG you use is not black and white. The one in your PR is but maybe you are working with a different one now.

In fact, the current online version of the wetland patterns already are semi-transparent; that is noticeable, for example, by examining the blue dashes against the transparent grid background of Gimp. I assume this means the semi-transparency is normal and that I can carry on.

**Comment by imagico** [comment]
> This sequence works for me; should I include it in wetland.md, as a replacement in the case the reader encounters the same problem as me, and then carry on to finishing this PR?

You can but you should indicate that this won't work universally - for me the first command for example results in a 546x546 pixel image.

> In fact, the current online version of the wetland patterns already are semi-transparent; that is noticeable, for example, by examining the blue dashes against the transparent grid background of Gimp. I assume this means the semi-transparency is normal and that I can carry on.

The blue dash pattern transparency comes from a different source, that is done with the `+level 20%,100%`.  

The process gives you full control over color and opacity of the symbols.  swamp.png and wetland_pattern_bkg.png essentially serve as alpha masks for the final pattern image compositioning.

**Comment by Penegal** [comment]
Wow. I used the new pattern in Kosmtik to test it, but ran into a strange issue:
image

This is an altered screenshot: the upper left corner uses the new pattern as rendered by Kosmtik: as you can see, it seems somewhat faded. On the lower right, I altered the screenshot to directly superimpose the new pattern; as you can see, it renders as one should expect, without fading. I'm rather puzzled here, as the style doesn't seem to add transparency to the pattern. What could have happened?

I precise I am way behind upstream, as this work started one year ago, but I did not merge from upstream to prevent creating a huge commit which will essentially add noise in history; I can do it to test, though, but it will add a huge noise in git diffs.

**Comment by imagico** [comment]
You need an additional `+gamma - -strip` in the last command to get rid of wrong metadata.

But more importantly your pattern is not pixel aligned - if you produced it with jsdotpattern you need to use `rd,1` instead of `rd,0`.  But as indicated above it would be better to use one of the other symmetric wetland patterns (like reed or marsh) and just replace the symbol.  This way the pattern arrangement would be identical.

**Comment by Penegal** [comment]
Wow! You magician :heart_eyes: 
image

Seems good to merge, now.

**Comment by Penegal** [comment]
Is there a problem preventing this to be merged?

**Comment by imagico** [comment]
My comments on the change as it is now:

* since the change is meant to _Uniformize swamp rendering with forest/wood_ i am wondering about the symbol color.  It is different from the previous one and different from the forest symbol color.
* the tree pair symbol is for forest/wood used to indicate areas lacking a leaf_type tag.  But for swamp the same symbol is used universally.  I am not sure if this would work out nicely.  A mapper just tagging `natural=wood` and `wetland=swamp` will get consistent symbols but a mapper tagging more specifically with leaf_type will get different rendering for wood and swamp.

I am not opposed to the change as is and not using a different symbol for swamp but i am wondering about the overall strategy.

**Comment by Penegal** [comment]
>     * since the change is meant to _Uniformize swamp rendering with forest/wood_ i am wondering about the symbol color.  It is different from the previous one and different from the forest symbol color.
Different? I compared the final rendered colors of the tree icons in the new swamp symbol and the current forest symbols, and they are rendered the same: `93b685`. You can see, at a limit between the two symbols, that they have the same color:
image

>     * the tree pair symbol is for forest/wood used to indicate areas lacking a leaf_type tag.  But for swamp the same symbol is used universally.  I am not sure if this would work out nicely.  A mapper just tagging `natural=wood` and `wetland=swamp` will get consistent symbols but a mapper tagging more specifically with leaf_type will get different rendering for wood and swamp.
When I asked about updating this symbol, [SK53](https://github.com/gravitystorm/openstreetmap-carto/issues/1920#issuecomment-150289899) warned about boreal swamps which are mainly coniferous, hence keeping the two symbols. Or maybe you mean that the new swamp symbol should take `leaf_type` into account? Combining `leaf_type` with `wetland=swamp` is too rare to be accounted by Taginfo; if present, this combination has less than a thousand occurrences. I don't think it would be relevant to take such a rare combination into account.

**Comment by imagico** [comment]
Regarding color - i am sorry about that, it looked from your example like the color is different but that might just be because the wetland dashing around creates that impression.

Regarding the symbol - yes, the logical step if your goal is to uniformize swamp rendering with forest/wood would be to show leaf_type in the same fashion.  If the aim is consistency to normal woodland low use numbers are not a significant factor since despite low use volume this is an undisputed tagging.  But you don't have to do that in this PR.  I was just asking for the overall strategy here.

**Comment by imagico** [comment]
Looks good, thanks.

**Comment by Penegal** [comment]
More than 3 months since the merge, and it's still not online ? I thought the server problems were solved.

**Comment by matkoniecz** [comment]
See https://github.com/openstreetmap/chef/issues/235

Reviewing whatever v4.21.1 still has regression bugs would allow recommending it for release.

**Comment by Penegal** [comment]
@matkoniecz: Ok, thanks for the link!

**Comment by jeisenbe** [comment]
> Reviewing whatever v4.21.1 still has regression bugs would allow recommending it for release.

It seems the bugs have all been fixed. Should we consider releasing v4.21.1 or v4.22 soon?

**Pull request merged**
