### PR TITLE
Slightly lighten colour of house names and numbers

### LINKED ISSUE #320: Cartography of address labels : too much at level 17/18?
Have a look at:
http://www.openstreetmap.org/#map=17/37.87853/-122.27021&layers=N

The address labels are very prominent.  Could these be dialed down a bit, perhaps appearing in lighter font, or better yet not at all at zoom 16/17/18?  
The address labels are super important for searching of course, and even when finding a specific place, but at these zoom levels perhaps they demand more attention than they are worth.

### LINKED ISSUE #1120: Render building text lighter
Buildings names are currently rendered in `#444`. It might be nice to render them a bit lighter, especially after the new building color is rolled out.

### PR DESCRIPTION
**Pull request by math1985**
This resolves #320 and resolves #1120

### CODE REVIEW

**Comment by math1985** [comment]
Before: before

After: after

**Comment by nebulon42** [comment]
I don't see much difference. Are you sure that before/after should not be the other way round?

**Comment by math1985** [comment]
Something was wrong indeed with the PR, fixed both the PR and images now.

**Comment by mkoniecz** [comment]
I think that colour should be change only on z17 - with 18 and higher unaffected.

**Comment by Rovastar** [comment]
Looks good.

**Comment by nebulon42** [comment]
I think that this amplifies the low contrast issue with yellowish buildings on grey residential landuse.

**Comment by mkoniecz** [comment]
It also implements #1120

**Comment by math1985** [comment]
I would preview keeping the colour on z17 and z18 the same. @mkoniecz is this a dealbreaker for you?

**Comment by mkoniecz** [comment]
I admit that I missed that it is not affecting >= 19. I am not convinced that it is improving map, but it is not so bad as I thought.

**Comment by math1985** [comment]
I think it does affect >= 19?

**Comment by nebulon42** [comment]
@math1985 Now that building colours have been adjusted, could you please provide an updated preview?

**Comment by math1985** [comment]
Updated screenshot.

**Comment by pnorman** [comment]
image

How is it in rural areas? I couldn't find a rural building+address in my dataset.

**Comment by math1985** [comment]
> I couldn't find a rural building+address in my dataset.

I'm not sure if I understand what you mean. If it's a building, the background colour is the same independent of whether it's urban or rural right?

**Comment by pnorman** [comment]
> I'm not sure if I understand what you mean. If it's a building, the background colour is the same independent of whether it's urban or rural right?

Yes, but I want to see if it looks sensible on a building in isolation in a rural area.

**Comment by math1985** [comment]
screenshot from 2015-03-12 22 16 06

**Pull request merged**
