### PR TITLE
Issue #2660 Shop medical supply icon

### LINKED ISSUE #2660: Rendering shop=medical_supply with a special icon
The tag shop=medical_supply has > 3,400 instances. I suggest the following icon:
med

### PR DESCRIPTION
**Pull request by james2432**
Fixes #2660

From: https://www.openstreetmap.org/#map=19/45.55000/-73.65399 (node)
image

image

image

From https://www.openstreetmap.org/#map=17/45.42026/-75.62195 (way):

image

image

image

### CODE REVIEW

**Comment by kocio-pl** [comment]
Now we have a common problem when working with multiple similar issues - after merging #3123, which was changing the same lines in `project.mml`, you should resolve the conflicts to make this code mergable again. This is probably the same problem with all the other shop icon rendering - and it will repeat with each merge.

**Comment by james2432** [comment]
Done

**Comment by kocio-pl** [comment]
Thanks! That was quick. :smile:

**Comment by james2432** [comment]
On to the next! :yum:

**Pull request merged**
