### PR TITLE
Issue #2929 Add icon for shop=music 

### PR DESCRIPTION
**Pull request by james2432**
Related to #2929

### CODE REVIEW

**Comment by kocio-pl** [comment]
Nice! Could you provide real map rendering for a node and a way with names to make sure what's the final effect?

**Comment by james2432** [comment]
image

image

image

image

**Comment by kocio-pl** [comment]
It is a one example - way or a node? Please make a one shot also with the other one type. 

Adding links to the testing places helps to check the results, so it's good to add them too.

I would also left shop_other on the end of the list, as it represents special category "all the other shops".

It looks very good for me and I would merge this code soon.

**Comment by james2432** [comment]
Updated comment and code based on your comments

**Comment by kocio-pl** [comment]
Great. What about rendering different type of geometry and links to examples?

**Comment by james2432** [comment]
See my comment https://github.com/gravitystorm/openstreetmap-carto/pull/3123#issuecomment-373916820 That has been updated

**Comment by lakedistrictOSM** [comment]
Thanks for this!

**Comment by kocio-pl** [comment]
Thanks for making this icon a reality on the map!

**Pull request merged**
