### PR TITLE
reuse symbol of DIY shop for hardware shop

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes part of #1460.

### CODE REVIEW

**Comment by matkoniecz** [comment]
It is a bit different shop, but difference is probably not big enough to make a separate symbol.

**Comment by nebulon42** [comment]
Rebased. Yes, it is a bit different, but the definition is a bit fuzzy. I think it might also be a good idea to have closely related shops reuse the same icon to prevent icon explosion, which might be confusing.

**Comment by gravitystorm** [comment]
> I think it might also be a good idea to have closely related shops reuse the same icon to prevent icon explosion, which might be confusing.

On the other hand, reusing icons can mislead people into thinking that their is no difference between the tags. This is less likely to happen with an obviously generic icon (e.g. a dot) but more likely to happen with seemingly specific icons that are used for multiple different (even if similar) features.

**Comment by kocio-pl** [comment]
Yes, we have to be careful, but it's good to know there's also this possibility.

**Comment by nebulon42** [comment]
True, I was not suggesting to do this on a large scale. And of course there need not to be icons for everything.

**Pull request merged**
