### PR TITLE
Stop rendering highway=proposed

### PR DESCRIPTION
**Pull request by matkoniecz**
https://cloud.githubusercontent.com/assets/899988/8719491/65957a08-2bac-11e5-8e39-512656ab7346.png

https://cloud.githubusercontent.com/assets/899988/8719492/659a1770-2bac-11e5-8117-7156a0b89525.png

https://cloud.githubusercontent.com/assets/899988/8719493/65c30e96-2bac-11e5-813c-75c99472e439.png

### CODE REVIEW

**Comment by math1985** [comment]
I still support this.

**Comment by gravitystorm** [comment]
I'm happy with this too

**Comment by pnorman** [comment]
There's still MSS relating to proposed in roads.mss

**Comment by matkoniecz** [comment]
@pnorman Thanks for noticing, fixed.

**Comment by matkoniecz** [comment]
rebased

**Comment by kocio-pl** [comment]
Probably "resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1654" is missing.

**Comment by matkoniecz** [comment]
@kocio-pl 

no, it is still present - see https://github.com/matkoniecz/openstreetmap-carto/commit/e3c79b11275eabf4a30cb0fa9a84f36438b95dbd

It is no longer in the first line so github is no longer showing it in discussion view

**Comment by Gazer75** [comment]
Why this had to go I don't understand. It was perfectly fine with the transparent rendering imo.
Another reason to not use openstreetmap.org...

**Comment by PinkDuck** [comment]
I am disappointed this disappeared from render, I went to show someone the proposed route for a construction project that is now underway to find having to track down the relation instead for a less than pleasing visual.

**Pull request merged**
