### PR TITLE
Pixel aligning some icons 

### LINKED ISSUE #3362: Pixel aligning some icons
Some of icons which I have designed at the beginning of my activity here, was not pixel-aligned, but we have added them anyway. Now I fixed them and reuploaded to Gist. 
I also propose to make a line in `amenity=atm` icon thinner to make it less prominent.

_(Current icon on the left, fixed icon(s) on the right)_

* `historic=wayside_shrine`
historic wayside_shrine0 historic wayside_shrine 
Gist: https://gist.github.com/Tomasz-W/e237875a860653546d553cacd4d8afbd
* `amenity=bbq`
amenity bbq0 amenity bbq
Gist: https://gist.github.com/Tomasz-W/4ff000df11e004abf24d5e77f5b8db62
* `information=audioguide`
information audioguide0 information audioguide
Gist: https://gist.github.com/Tomasz-W/c1b01647b8979e88b14d3dee6fcb3138
* `information=board` [I prefer thin version]
information board0 information board3 information board2
Gist: https://gist.github.com/Tomasz-W/d6f962425fbc8ec05b54a696e7eaee66
* `information=map`
information map0 information map
Gist: https://gist.github.com/Tomasz-W/1e8f2e4a59069ddee99db53ac1a5c1dc
* `shop=ticket`
shop ticket0 shop ticket
Gist: https://gist.github.com/Tomasz-W/b18eee2375829d1fa2e97f40fd855968
* `tower:type=bell_tower`
tower_type bell_tower0 tower_type bell_tower
Gist: https://gist.github.com/Tomasz-W/18d5cac547924610245808723dd61319

* `amenity=atm`
amenity atm0 amenity atm
Gist: https://gist.github.com/Tomasz-W/bcb011d2e8785553241f63121adf307d

### PR DESCRIPTION
**Pull request by Adamant36**
This PR pixel aligns some icons needed it. Although I do not have any test renderings, because there was no change in code or anything. I did test things on my side though and it went fine. The new icons showed up on the map etc. So I assume everything works.  I can provide test renderings if need be though. Also, this PR closes #3362

### CODE REVIEW

**Comment by Tomasz-W** [comment]
Codes of bbq and bell tower icons are unnatural long, so I've made them again on another templates. Please change their files one more time.

https://gist.github.com/Tomasz-W/4ff000df11e004abf24d5e77f5b8db62
https://gist.github.com/Tomasz-W/18d5cac547924610245808723dd61319

**Comment by Adamant36** [comment]
I updated them. It should be good to go now.

**Comment by kocio-pl** [comment]
Nice! Please make a real world rendering of each replaced icon to make sure that it really works. It's always good to make rendering if it's not just a code fix.

**Comment by Adamant36** [comment]
Ok. I'll do that from now on.

**Comment by kocio-pl** [comment]
Sorry for not hinting it earlier - the project is quite active lately and I'm trying to follow the traffic...

**Comment by Adamant36** [comment]
wayside shrine
https://www.openstreetmap.org/#map=19/39.11562/-121.93709
wayside shrine
bbq
https://www.openstreetmap.org/#map=19/37.87619/-122.28861
bbq

information audioguide
(no examples in California to test)

information map
https://www.openstreetmap.org/#map=19/37.87064/-122.26484
information map

information board
https://www.openstreetmap.org/#map=19/39.11561/-121.93674
information board

shop ticket
https://www.openstreetmap.org/#map=19/37.86987/-122.24969
shop ticket

bell tower 
https://www.openstreetmap.org/#map=19/38.53991/-121.44074
bell tower

atm
https://www.openstreetmap.org/#map=19/38.52886/-121.47269
atm

tourism apartment 
(no examples in California to test)

tourism guest house
https://www.openstreetmap.org/#map=19/38.47639/-121.49539
guest house

tourism hostel
https://www.openstreetmap.org/#map=19/38.58277/-121.49215
hostel

hotel
https://www.openstreetmap.org/#map=19/38.58115/-121.48765
hotel

@Tomasz-W, there seems to be a problem with the new ticket icon not rendering the white line in the middle for some reason.

**Comment by kocio-pl** [comment]
> (no examples in California to test)

You can export small part of data directly from OSM.org website, from anywhere in the world.

**Comment by kocio-pl** [comment]
I see! You can make temporary database and just switch them, here is my dumb script:

```bash
#!/bin/bash
sudo service postgresql restart
sudo -u postgres -H -- psql -c "alter database gis rename to temp;"
sudo -u postgres -H -- psql -c "alter database gis2 rename to gis;"
sudo -u postgres -H -- psql -c "alter database temp rename to gis2;"
```

**Comment by Adamant36** [comment]
Sweet! I'll have to try that. Sounds better then having to set everything up again every time I need to load a new location, like I was doing for the more obscure icons. I just now realized that I can modify code and click reload in Kosmtik without shutting the whole thing down and restarting it every time. That will save me a lot of time in the future.

**Comment by Tomasz-W** [comment]
fixed shop=ticket icon 

https://gist.github.com/Tomasz-W/b18eee2375829d1fa2e97f40fd855968

**Comment by Adamant36** [comment]
Thanks. I updated it and it seems to be good now. 
fixed ticket icon

**Comment by kocio-pl** [comment]
Thanks, guys! 

@Tomasz-W I like how the shrine is less heavy now (that was something I was not sure if it'll work good) and the laying people silhouettes are more clear. It's unexpected for me that even icons designed by the person, who introduced pixel alignment, could be improved in this respect. Good investigating work!

@Adamant36 When making rendering you might crop the output to show only relevant objects, it's easier to see the merits of the change this way.

**Pull request merged**
