### PR TITLE
Adding amenity=shower icon

### LINKED ISSUE #3067: Add rendering for amenity=shower
Related to #3062 and #2856. May be useful especially for rendering camping, sport places or beach areas.

It can be designed probably quite easily - anybody wants to try?

This tag is quite popular (12 695 uses) and has its own wiki page:
https://wiki.openstreetmap.org/wiki/Tag:amenity%3Dshower

### PR DESCRIPTION
**Pull request by james2432**
Fixes #3067 

From: https://www.openstreetmap.org/node/4898075512#map=18/44.60609/-76.12866 (node)
image

From: https://www.openstreetmap.org/#map=19/45.72938/-68.83598(way)
image
Fake name added to test rendering:
image

### CODE REVIEW

**Comment by polarbearing** [comment]
Looks a bit like garden watering for me. could we try my new one in #3067 ? :-)

**Comment by kocio-pl** [comment]
I still like the current proposition more and it's easier for me to recognize too. When thinking about garden watering I think of this shape, which we use for gardening centre: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/garden_centre.svg

**Comment by james2432** [comment]
Re-touched the zoom aspect now is at zoom >=18

**Comment by kocio-pl** [comment]
What about name rendering for a node and a way? The code is here, so it should be tested.

**Comment by kocio-pl** [comment]
On the other hand stats tell that name is not really popular with showers:

https://taginfo.openstreetmap.org/tags/amenity=shower#combinations

**Comment by james2432** [comment]
should I take out name for showers? wiki says to add name and operator:

https://wiki.openstreetmap.org/wiki/Tag:amenity=shower

**Comment by kocio-pl** [comment]
I was mentioning the numbers just to show the practice, but it's up to us to decide. You can leave it (it's perfectly fine when it's defined explicitly on the wiki, and from z18 it shouldn't make a visual problem), just please make the testing renderings to make sure there are no bugs in the code.

**Comment by james2432** [comment]
updated screenshots with name

**Comment by kocio-pl** [comment]
I prefer real locations (with links) for both node and a way, because I try to test the code before merging as a good practice and it's easier to compare the results then.

**Comment by james2432** [comment]
https://www.openstreetmap.org/#map=19/45.19130/-81.55369
image

**Comment by kocio-pl** [comment]
It's a node (https://www.openstreetmap.org/node/3786627020), what about the way label?

**Comment by james2432** [comment]
the way label was tested with the fake name added but I can test with this later:

https://www.openstreetmap.org/way/536787545#map=19/47.57643/-122.13311

**Comment by dieterdreist** [comment]
great icon

**Comment by james2432** [comment]
image
Seems to work a.o.k.

**Comment by kocio-pl** [comment]
Thanks, it really does work as it should.

**Pull request merged**
