### PR TITLE
fix dy for leisure=water_park

### PR DESCRIPTION
**Pull request by mkoniecz**
leisure water_park name eeeeee eeeeee eeeeee ref 1 ele 8000 closed_way master - dy

### CODE REVIEW

**Comment by kocio-pl** [comment]
Hm, I can't recognize which one is "before" and which is "after" - seems like it was meant just for simple 1:1 comparison.

**Comment by mkoniecz** [comment]
@kocio-pl - yes, it is comparison not on real data, but with a single generated element. It is not mentioned anywhere, mainly because I am not sure how to name it. Internally I am using term "synthetic data" but I think that it is not making situation clear.

> can't recognize which one is "before" and which is "after"

I expected this problem. Have you noticed "before", "after" labels? Or is there something else causing this problem?

**Comment by kocio-pl** [comment]
It was just the labels.

**Comment by mkoniecz** [comment]
Diff in the new style. Is it better?
leisure water_park name eeeeee eeeeee eeeeee ref 1 ele 8000 closed_way master - dy

**Comment by kocio-pl** [comment]
I see no difference, just the bigger fonts. However the problem isn't serious, it's just a minor "hm?..." and if it couldn't be easily fixed, so be it.

**Comment by HolgerJeromin** [comment]
> Is it clear why first image is displayed only once?

Because it is not rendered in this zoom levels? I think printing this two times would be a bit clearer. Especially the label "after" would make more sense then. The labels are exact over an image where it is wrong. Perhaps centering the label "before" and "after" on the columns would be helpful, too.
I would perhaps name them "unit tests". Users with a programmers background will have the right idea.

**Pull request merged**
