### PR TITLE
Add 14px storage tank icon used by iD

### LINKED ISSUE #3927: Reuse iD editor storage tank icon
> If you think that something should be changed - please open a new issue.

_Originally posted by @matkoniecz in https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-539653830_

The current tall storage tank icon looks like a gasoline pump.

It would just be safer to use the storage tank icon from the iD editor. Thanks.

### PR DESCRIPTION
**Pull request by bhousel**
closes #3927 
I named it storage_tank2.svg, so it wouldn't collide with the existing icon, but you can move it if you want.

Anyway, there are a bunch more icons over in [bhousel/temaki](https://github.com/bhousel/temaki).  They are 15px to match what maki does, but redrawing them to pixel align to 14px is usually not a big deal. Enjoy!

### CODE REVIEW

**Comment by kocio-pl** [comment]
It's OK for me. 

Since you mean to replace it, it's better to rename it, we don't collect all the possible icons if not used here currently. However one has to check if this is not being used for different tagging and then decide how should it look like.

**Comment by jeisenbe** [comment]
Looking back at the previous discussion in the issues #2909 and #588, we did not really reach consensus about rendering `man_made=storage_tank` with an icon instead of similar to buildings when tagged on areas. See https://github.com/gravitystorm/openstreetmap-carto/issues/2909#issuecomment-340767093,  https://github.com/gravitystorm/openstreetmap-carto/issues/2909#issuecomment-390165339, and https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-45058778 plus following comments and https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-339616474 and https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-339624211 about rendering like buildings. 

Also see discussion about tagging on https://wiki.openstreetmap.org/wiki/Talk:Tag:man_made%3Dstorage_tank#building.3Dyes_.3F and elsewhere on that same Talk page.

It seems that a number of mappers feel that `man_made=storage_tank` and `man_made=silo` are sufficient, without a `building` tag, though many also add a `building=` tag.

Should we start rendering `man_made=storage_tank` and `=silo` like buildings? If so, it's probably not necessary to show an icon when they are mapped as areas.

Should silos and storage tanks have the same icon? This storage tank icon looks more like a tank, but less like a silo, than the current icon.

**Comment by bhousel** [comment]
I have no opinion about the rendering.

There is a silo icon too if you want it.. (they do look different from storage tanks)
preview page here:  https://bhousel.github.io/temaki/docs

**Comment by jeisenbe** [comment]
@bhousel - I'm guessing that you are quite busy with iD and probably do not have time to develop this PR further. Is that correct? If so, is it ok if we edit it for you, or is it better for us to make a different PR if further changes are required?

**Comment by jeisenbe** [comment]
Rendering comparison at z18. These storage tanks, like many (56%), are also tagged with `building=`

z18-storage-tanks-buildings-compare

**Comment by jeisenbe** [comment]
Comparison of silos:

z19-silos-compare
z18-silos-compare

**Comment by bhousel** [comment]
> I'm guessing that you are quite busy with iD and probably do not have time to develop this PR further. Is that correct? If so, is it ok if we edit it for you, or is it better for us to make a different PR if further changes are required?

1. I don't really work on iD anymore.
2. We discussed storage tanks here:  https://github.com/openstreetmap/iD/issues/4265 .  They should probably have a building tag when mapped as an area.
3. You can make whatever changes to the PR you want - "allow edits from maintainers" is checked, and I wasn't planning on doing any follow on work.

**Comment by imagico** [comment]
A few comments:

* i think neither the current symbol nor the newly proposed one is ideal but i also don't think the newly proposed one is worse so i would not mind a one-to-one replacement if otherwise seen positively
* in general when @nebulon42 re-designed many point symbols of this style only having profile views and no perspective views was part of his design paradigm.  This was not fully maintained later in all cases but that is the reason why we have many symbols like the current storage tank symbols.
* i think any more elaborate change in how things are rendered in this field should be preceded by an analysis of actual tag use (like combination with building tags, relationship to other semantically similar tags etc.).

**Comment by polarbearing** [comment]
I would not require a building tag to render the silo/storage. I can imagine various construction types, for some I'd be inclined as a mapper to add 'building' to some of them, and explicitly not on some others. 
For comparison, we discourage 'building' on man_made=bridge with a few notable exceptions.

**Comment by HolgerJeromin** [comment]
Both icons are pretty heavy with no real value. Who uses this map for searching for storage tanks?
Showing the outline would be ok imo, and why not with the bu

**Comment by jeisenbe** [comment]
So far @kocio-pl has said this new icon is "ok", which I believe means it's better than the current icon, @imagico does not mind the replacement though it's not entirely clear if he thinks it is an overall improvement, and @HolgerJeromin does not like the use of an icon, but has not commented if the new icon is an improvement on the old one. 

I think the new icon is more legible, but this is because it uses a perspective view, partially from above, rather than a straight-on, side view. As mentioned, this would be a departure from our usual icon design style, but it might be helpful to allow such variation.

Does anyone else have an opinion about the new icon?

Should we allow icons which are designed with a perspective view?

**Comment by Adamant36** [comment]
I say go for it. It's better then no icon. I thought there was a discussion somewhere a while back about if storage tanks count as buildings that was inconclusive. I can't seem to find it though, but I think whatever the case is, it's best to go with what is already established. Which in this case is an icon and the current one clearly needs changing. Maybe allowing for a different perspective will lead to improvements in other icons later on also.

**Comment by kocio-pl** [comment]
> So far @kocio-pl has said this new icon is "ok", which I believe means it's better than the current icon, 

I meant that it is also acceptable for me. To be precise, it has some downsides compared to a current icon - it uses perspective, which we try to avoid, so I would not point out which one is really better.

**Comment by jeisenbe** [comment]
That was silly of me. I tried to update this PR, but pushed my master branch instead of the changes, and this apparently closed the PR. And now that the PR is closed, I can no longer push changes to this branch. Is there any way to fix this remotely?

**Comment by imagico** [comment]
I am not sure but i think once there is a change on the branch in question you can reopen.

**Comment by jeisenbe** [comment]
@bhousel - mea culpa, could you please run `git push -f`?

**Comment by bhousel** [comment]
> mea culpa, could you please run `git push -f`?

it didn't seem to work, so I just opened another PR.

**Pull request closed without merging**
