### PR TITLE
Jewish symbols made lighter

### PR DESCRIPTION
**Pull request by kocio-pl**
Follow up to https://github.com/gravitystorm/openstreetmap-carto/pull/2714#issuecomment-320690830.

Mapnik seems to render SVG in its own way, which is beyond our control and sometimes makes details to vanish, as it is with our current star of David. We can however try a symbol with thinner lines. 

I took [star_of_david3.svg](https://github.com/imagico/jsdotpattern/blob/master/symbols/star_of_david3.svg) from jsdotpattern project. It's rather not pixel aligned, but general religion symbol looks now better, because holes are visible. Cemetery symbol (the same shape scaled down to 10x9 px) is still worse than PNG (no small holes inside), so I would probably not use it:

Before
ntu8hdz1
After
kj9hfe88

Before
hby7cmh7
After
mdlvrzew

### CODE REVIEW

**Comment by nebulon42** [comment]
Looks not bad to me. Could link or post an image with the symbol before? Would make it easier for me to compare.
Cemetery is not very visible but recognizable. How does it look currently?

**Comment by kocio-pl** [comment]
I have updated both images with before/after renderings.

I'm not sure now about cemetery. With new symbol the lightness is the same and while I can spot the holes with general symbol with normal size (100-120%), cemetery symbol holes are not visible at 100% - it needs a lot of zooming (for me it's >200%), which is not what typical user would do. So maybe cemetery symbol should be moved to SVG too.

**Comment by sommerluk** [comment]
The general jewish religion symbol „after“ looks much clearer to me than the „before“ version. It can be recognized as Star of David.

About the cemetery symbol: Honestly, both, the „before“ and the „after“ variant, I cannot reliably recognize them as Star of David. They are just to small. But the „after“ variant –  even though stronger – seems to me easier to guess as Star of David.

👍

**Comment by imagico** [comment]
Although i would assume this is clear but just in case it is not - this demonstrates the _incorrect but consistent_ case described in #2750.

**Comment by kocio-pl** [comment]
Sorry, I don't understand it - could you describe in short words what exactly is incorrect and what you think is consistent with this case? Any ideas what should be done to make it OK for you?

**Comment by imagico** [comment]
The results in your _After_ example above are are not a faithful rendition of the SVG file, you can easily see this by comparing these results with a rendering of the pattern with other programs (Inkscape or ImageMagick) or with Mapnik when using `polygon-gamma: 1;`.

_Incorrect but consistent_ refers to what i wrote in #2750:

> It affects patterns in landcover-area-symbols - if observations in kosmtik are representative patterns in the normal landcover layer will render incorrectly but consistently with polygon-gamma other than 1 and correctly otherwise (the latter being the current situation for the quarry pattern) polygon-pattern-gamma does not appear to have an effect on this.

I don't know a way to fix this - otherwise i would have mentioned this in #2750.

**Comment by kocio-pl** [comment]
It looks like people are in favour of this rendering not because it's rendered similar to a vector image, but because it works better (in a cartographic sense) than current PNG image for them - and for me too. 

Solving the problem with Mapnik might give us the ultimate solution to this problem, but this PR would still make a progress with readability and fixes problem with map scaling, so it's worth merging IMO.

**Pull request merged**
