### PR TITLE
update symbol of historic=memorial

### PR DESCRIPTION
**Pull request by nebulon42**
I know I have changed the memorial icon recently, but  this tries to fix two issues with the current symbol

* looks a lot like a tombstone
* large visual profile

by changing it into a plaque-like design and making it smaller. This shall also mitigate #1066 a bit.

preview (left=before, right=after)
memorial

### CODE REVIEW

**Comment by kocio-pl** [comment]
I'm not sure what to do now. 

Ultimately we should use this one for a plaque probably, as it should be really much less visible than currently, but look at the squares with statues in the centre - they loose their dominant function with this new rendering. I guess we need a common symbol for memorial and plain artwork statues, because they are similar (despite being tagged differently) and maybe some other for other types. But this will be effective once we have memorial types available, so it's a question of database reload (https://github.com/gravitystorm/openstreetmap-carto/issues/1504) and we don't know when it may be and there is no sign of progress in last month and even the action plan has no checked items.

This PR can't resolve the problem of different forms of memorial forms, it just tries to change default icon and for some it will be better, while being worse for the other.

**Comment by nebulon42** [comment]
Solving the memorial types problem was not intended anyway. This is meant as a pre-database reload PR. I cannot see depicting a statue as tombstone to be good either.

**Comment by kocio-pl** [comment]
But there are plenty of memorial places which [looks exactly like this](https://commons.wikimedia.org/wiki/File:Flight_810_Memorial.jpg) and rightly so, because they do the same: try to commemorate someone (or some event); the only real difference is a lack of tomb. I find them more typical for such a broad category and I'm reluctant to make this change, however I will not be satisfied until we have the right solution to make [such places](http://www.openstreetmap.org/relation/4772652) more readable, for example.

**Comment by dieterdreist** [comment]
2015-06-08 22:10 GMT+02:00 Michael Glanznig <notifications@github.com>:

> preview (left=before, right=after)
>
> <https://cloud.githubusercontent.com/assets/3531092/8044124/0009a6e4-0e2b-11e5-949c-d74709adcb98.png>
>


I am not sure what is the reason, but these 2 renderings are very
different, the new version has much fewer labels and different labels. You
should make exactly the same before/after renderings with the only
difference what you have changed. FWIW, I prefer the old symbol because the
new one cannot be understood.

**Comment by nebulon42** [comment]
@dieterdreist The differences are because of Kosmtik switching to Mapnik 3 recently. I'm not debugging this, because this has to be done anyway later. I think you are quite capable of sorting out what is part of this change and what not, just have a look at the diffs (Files changed).

>  I prefer the old symbol because the new one cannot be understood.
I guess you will have to explain this.

@kocio-pl The image you have linked does make up just a small amount of memorials. There are lots of others. Therefore, no single symbol will be suitable for such a broad category. Nevertheless, I think the new symbol is much more suitable as for the reasons I have mentioned in the first post.

**Comment by kocio-pl** [comment]
Memorials can be as small as the plaque (your new icon), similar in size and look to the tombs (your old icon) or big as a statue - or even bigger (monuments seem to be much bigger). So I prefer something in medium size (current one) to match, at least partially, both extremes (let's say with a "resemblance factor" for 3 sizes like 0,5+1+0,5=2) rather than mostly small ones (1+0,5+0=1,5). The context is clear enough for me to know it's not a tombstone.

**Comment by daganzdaanda** [comment]
If you want to move away from a too literal depiction, maybe the symbol for "memorial" here https://commons.wikimedia.org/wiki/Simple_map_icons works. IIRC, that "abstract human" thing is used on some German maps, too.
I did not know that the "(tomb)stone shape" is supposedly also used in Japan: https://commons.wikimedia.org/wiki/File:Japanese_Map_symbol_(Monument).svg (Check the category, it's very interesting)

**Comment by dieterdreist** [comment]
sent from a phone

> Am 14.06.2015 um 22:03 schrieb daganzdaanda <notifications@github.com>:
> 
> If you want to move away from a too literal depiction, maybe the symbol for "memorial" here https://commons.wikimedia.org/wiki/Simple_map_icons works. IIRC, that "abstract human" thing is used on some German maps, too.


yes, it is the German symbol for these, used for a very long time http://geoportal.geodaten.niedersachsen.de/legende/wms_pl25.gif

**Comment by math1985** [comment]
I think the old icon is more recognizable (even though not always literally correct), so I'd prefer to keep the old one. @nebulon42 Thanks for your efforts though!

**Pull request closed without merging**
