### PR TITLE
Made landuse=military areas less prominent

### PR DESCRIPTION
**Pull request by andrzej-r**
Ref #2670

Made landuse=military areas less prominent by:
- Removing the outline
- Changing the fill pattern to use a finer (but more dense) lines
- Changing the fill pattern to to use lower alpha value (more transparent)
- Increased the visibility threshold at zoom levels 8+ from 100/75px to 200px

### CODE REVIEW

**Comment by matkoniecz** [comment]
Can you add some before/after images?

**Comment by andrzej-r** [comment]
Zoom level 10
l10-orig
l10-modified

Zoom level 11
l11-orig
l11-modified

**Comment by polarbearing** [comment]
When removing the outline we cannot see the boundary of the feature, in particular when it is not identical to other underlying features. 
In #2290 and #2704 we experiment with line width=2 which is a bit thinner than the current 3 in military. Maybe we can use the same here. 
What happens when we fully remove the pink between the hatch lines?
Can we see some previews with larger areas and in higher zoom?

**Comment by polarbearing** [comment]
Example with your finer hatching and outline width 2, see left the proposed museum outline.
military_line_2_thin_hatching

**Comment by polarbearing** [comment]
No outline in z18. 
military_line_0_thin_hatching

**Comment by kocio-pl** [comment]
We were discussing making all the uniform services areas look the same (military, police and fire services). The proposition was to get rid of hatching and leave just a red area - with the red outline (by default, because we were not thinking about more changes). Recent [experiments with museum outline]( https://github.com/gravitystorm/openstreetmap-carto/issues/2704) show, that the outline should be specific in order to make a fence visible, if it's present. Could anybody show how the outline of a military area looks with a fence currently?

**Comment by polarbearing** [comment]
Military with fence is well visible since the grey contrasts against the pink: 
https://www.openstreetmap.org/#map=18/52.42578/13.57413
military_fenced

**Comment by andrzej-r** [comment]
I will upload additional screenshots in the evening. One interesting use case is near Farnborough, with eg several overlapping military areas. 

I am not too attached to this particular proposal. I just consider current rendering of military areas way too prominent. 

I didn't get rid of hatching because I thought that may be one change too much. Besides, IMHO military areas should *not* be treated like other land uses. Especially in certain countries. 

I was thinking about leaving 1px border (2px is still quite obnoxious, in my opinion) but then I realised removing the border entirely works just fine. We need some transparency in the fill/hatching pattern to display overlapping areas but that's all. No border or 1px border should also work better with fences. 

Fill pattern was made a bit more transparent because there are often quite many mapped objects inside these areas and the previous fill pattern was obscuring them.

Filtering settings were made more aggressive to prevent large numbers of small areas from dotting the map at medium zoom levels. It is analogous to the airport/airfield issue discussed in another ticket.

**Comment by polarbearing** [comment]
I agree with reducing military, just it needs to be in sync with our plans for police etc. We could use the outline without the hatching.

**Comment by kocio-pl** [comment]
General note: I'm happy that you both are really testing these things! That's what is needed in my opinion.

I don't see the fence on the military outline, but it looks like the problem no one really notice, since it was not reported as of now - so maybe it's not that important? However if there is a way to make the difference visible somehow, it's preferable.

**Comment by kocio-pl** [comment]
I think we could leave the hatching only for danger areas (see #2739 and #684). Currently they are shown with light "x" signs, which could be just dropped then, because addition of hatching would be enough.

**Comment by andrzej-r** [comment]
So, how about:
- no hatching
- 1px border
- ~10% opaque fill with the same colour as now (currently 14%, 8% in my proposal)
- 200px threshold at zoom 8+?

If that's OK, I will update the PR. Details can always be later refined to match police and fire services etc.

**Comment by andrzej-r** [comment]
Promised screenshot of a more complex use case at higher zoom level (15/51.3064/-0.6725):
l15

**Comment by polarbearing** [comment]
@kocio-pl - how do we distinguish the military from the other uniformed services when they have only the same outline?

**Comment by andrzej-r** [comment]
I am OK with using only 1px border for small areas (in pixels). For larger areas (in pixels) we need either tinting or hatching, as we may see only part of the border. In both cases the fill should be unobtrusive.

I don't consider a color shift a problem. In fact, IMHO, it would be good to have eg commercial areas tint building colors, but that's a topic for another discussion. 

Hatching or tinting is really an aesthetic matter, with hatching being a "low tech" substitute to tinting. It is just down to an arbitrary decision.

**Comment by kocio-pl** [comment]
> how do we distinguish the military from the other uniformed services when they have only the same outline?

The same as we distinguish schools from other societal amenities: they have no icon, while the rest have some.

**Comment by kocio-pl** [comment]
> If that's OK, I will update the PR. 

First please show how would it look like then, so we could judge the result.

**Comment by polarbearing** [comment]
I don't see hatching as "low tech". Removing/avoiding colour merging effects was a main goal in this style for quite a while (I wonder if that is documented?). The style has subtle differences in the same colour group that get lost when colours merge. 
Before making new PRs I would find it a good idea to agree on the style of outline. I am working on some for tourism features (#2290, #2704) and it would be good to apply the scheme in sync, e.g. the width in various zoom levels.

**Comment by kocio-pl** [comment]
In case anybody coming here from weeklyOSM 393 ( http://www.weeklyosm.eu/archives/9939 ) - this issue was closed by its author **without merging**, so it will certainly not affect next release of osm-carto.

**Comment by paulusr** [comment]
I'm here from weeklyOSM 393, just like to say that I was hoping this would go ahead as current style needs fixing.

**Comment by kocio-pl** [comment]
The problem is not neglected, just check #3045 and help us there to decide and test solutions.

**Comment by andrzej-r** [comment]
New proposal is in PR #3057.

**Pull request closed without merging**
