### PR TITLE
Add special icon for shop=trade, shop=wholesale

### LINKED ISSUE #3291: Add icon for shop=trade (and potentially shop=wholesale)
https://wiki.openstreetmap.org/wiki/Tag:shop=trade
6.7k uses

Probably something involving pallets or maybe a fork lift truck. Could share an icon with [shop=wholesale](https://wiki.openstreetmap.org/wiki/Tag:shop%3Dwholesale) (1.3k uses).

1 trade01png

### PR DESCRIPTION
**Pull request by Adamant36**
Adds icon for shop=trade, shop=wholesale closes #3291

Shop=trade (uses same updated icon as shop=wholesale)
https://www.openstreetmap.org/#map=19/37.77322/-122.41143 (way)
trade way
https://www.openstreetmap.org/#map=19/37.76920/-122.40372 (node)
trade node

Shop=wholesale
https://www.openstreetmap.org/#map=19/40.66082/-73.72151 (way)
wholesale way
https://www.openstreetmap.org/#map=19/40.73295/-73.86265 (node)
wholesale node

### CODE REVIEW

**Comment by meased** [comment]
Definitely needs pixel alignment.

**Comment by lakedistrictOSM** [comment]
There's also the pixel aligned icon that I designed, linked in the original issue. However Tomasz's asymmetric version is an improvement on his original.

I'd also like to see this icon used for cash and carry shops (shop=wholesale).

**Comment by Adamant36** [comment]
Asymmetrical version 1
shop asymmetrical version 1
Asymmetrical version 2
asymmetrical version 2
I think I prefer the first version

I'm more then willing to add it as the icon for shop=wholesale also. It seems like the tag has enough uses. As long as others agree.

**Comment by kocio-pl** [comment]
Could you also test symmetric pixel aligned version?

shop=wholesale makes sense for me too - not too many uses, but it's fast growing:
taghistory 29

**Comment by Adamant36** [comment]
@kocio-pl, I thought thats what I tested in the message above yours? Is that not what @Tomasz-W provided a few messages up or are talking about @lakedistrictOSM's icon in the original issue. I know nothing about how icons and pixel alignment work. 

I'll add shop=wholesale then once the icon gets worked out.

**Comment by kocio-pl** [comment]
Well, I thought @lakedistrictOSM wrote it because his icon has not been tested. Which one did you use in the original rendering test?

**Comment by Adamant36** [comment]
@kocio-pl the original rendering test was done with @Tomasz-W's original version. Here's a test of @lakedistrictOSM's versions. 
trade lakedistrict version

**Comment by kocio-pl** [comment]
I like @Tomasz-W versions because of these nice details on packages. Probably asymmetrical v2 is nice, because it shows more diversity between packages, but all the icons here are good enough. My preference list goes as follows:

1) asymmetrical v2
2) asymmetrical v1
3) symmetrical v1 (@Tomasz-W )
4) symmetrical v2 (@lakedistrictOSM )

but I have harder problems to solve and leave it just as a hint. Whatever you will decide this this icon is OK for me.

**Comment by Adamant36** [comment]
@kocio-pl OK. Thanks. 

@Tomasz-W and @lakedistrictOSM What do you guys think?

**Comment by Tomasz-W** [comment]
@Adamant36 It's always harder to rate effect of your own work, so I believe in @kocio-pl "ranking" ;) . I've made v2 version, because v1 to be pixel-aligned has to have a tape shape in weird position, so I think my v2 without it might be even better.

**Comment by polarbearing** [comment]
asymmetrical v2 works best for me too, and I agree to use the icon for wholesale as well.

**Comment by lakedistrictOSM** [comment]
They're all readable for me. The labels on Tomasz-W's designs are a nice touch.

**Comment by kocio-pl** [comment]
There's no policy for that. I guess if you enhance the title it should be enough, I just will wait a bit longer to not take anyone willing to comment by surprise.

**Comment by Adamant36** [comment]
@kocio-pl It should be good to go now. I left the icon name as trade for both of them because I couldn't come up with anything better.

**Comment by kocio-pl** [comment]
Thanks! My independent tests are also OK.

**Pull request merged**
