### PR TITLE
Adding shop=car_parts icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1537.

car_parts-large-after-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
I think that the plus and minus sign could be a bit thinner and the connectors on top maybe a bit wider.

**Comment by ximex** [comment]
i agree with @nebulon42

**Comment by kocio-pl** [comment]
Sounds reasonable and looks good too:
car_parts-z19-nebulon

What do you think?

**Comment by ximex** [comment]
much better

**Pull request merged**
