### PR TITLE
Add icon for shop=houseware

### LINKED ISSUE #3141: Add icon for shop=houseware
https://wiki.openstreetmap.org/wiki/Tag:shop=houseware
6.6k uses

Mentioned in #1406 and #2347.

Kitchenware is probably the easiest thing to depict as an icon although we need to be careful that it's not too similar to `amenity=restaurant` (spoon and fork), `amenity=cafe` (teacup and saucer), `amenity=bar` (wineglass), `amenity=pub` (pintglass), `shop=tea` (teapot) or `shop=butcher` (meat cleaver).

A sideview of a bowl on top of a plate might work, or a whisk/spoon/spatula with a bowl or pan.

### PR DESCRIPTION
**Pull request by Adamant36**
Closes #3141 Add icon for shop=houseware
From https://www.openstreetmap.org/#map=19/37.78274/-122.46479 (node)
houseware test
From https://www.openstreetmap.org/#map=19/37.76356/-122.48147 (way)
houseware way

### CODE REVIEW

**Comment by kocio-pl** [comment]
Please change the name of the commit to something more descriptive.

**Comment by kocio-pl** [comment]
BTW - please also check on both nodes and ways with names and give the links to these places - there's only one image now and I don't know which case is it because I have no link.

**Comment by Adamant36** [comment]
@kocio-pl For the future is there an easy way to do multiple pull requests for different issues at the same time or do I have to wait until the first pull request is merged before I can submit a new one? I couldn't seem to find a clear answer about it anywhere.

**Comment by matthijsmelissen** [comment]
You created a pull request from the master branch now, the normal workflow is to create a new branch for each pull request. Then you can create as much pull requests as you like.

**Comment by Adamant36** [comment]
OK cool. I'll look into that more once this merges.

**Comment by kocio-pl** [comment]
Thanks! It works also in my tests.

**Comment by Tomasz-W** [comment]
@Adamant36 Thank you for this PR! Maybe you are interested in write code for other icons? Please take a look at a task list in https://github.com/gravitystorm/openstreetmap-carto/issues/3105#issuecomment-371597884 :)

**Comment by Adamant36** [comment]
@Tomasz-W Your welcome. I just did another pr shop=ticket. Thank you for creating the icons so more things can display on the map :)

**Pull request merged**
