### PR TITLE
Add git workflow guidelines to contribute on this repo

### PR DESCRIPTION
**Pull request by Ircama**
**Add git workflow guidelines to contribute on this repo**

With this PR I would like to submit the first version of a new document for revision.
It provides step-by-step instructions for using *git* with OpenStreetMap Carto and suggests guidelines on how contributors should operate when collaborating through pull requests (PRs) via Git and GitHub.

### CODE REVIEW

**Comment by pnorman** [comment]
I would **much** rather point at external documentation. We are currently doing that in [workflow](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#workflow) with a link to [github's pull request guidance](https://help.github.com/articles/about-pull-requests/).

When we added the link it contained text about the fork & pull model but it's not there anymore. We could link to https://help.github.com/categories/collaborating-on-projects-using-issues-and-pull-requests/. The fork and pull model is defined in https://help.github.com/articles/about-collaborative-development-models/

The two relevant parts of that category seem to be https://help.github.com/articles/working-with-forks/ and https://help.github.com/articles/proposing-changes-to-a-project-with-pull-requests/. Would linking to those two work?

**Comment by kocio-pl** [comment]
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2291.

**Comment by math1985** [comment]
I agree nearly everything described in this pull request is the standard Github workflow, so I don't think this repository is the best place to describe this. It would indeed be great if we can link to some external places where contributors can find more information.

**Comment by Ircama** [comment]
> I agree nearly everything described in this pull request is the standard Github workflow

OK to move this document in some other place. Which are the most mismatching aspects in order to improve it?

**Comment by pnorman** [comment]
Closing and opening an issue for the stale link.

**Pull request closed without merging**
