### PR TITLE
Ditch and drain text is not offset 

### PR DESCRIPTION
**Pull request by Adamant36**
Solves issue #1651 ditch and drain text is not offset. I also unified the code some to make it easier to follow. This is my first time doing this. So if I did anything wrong or if there is anything else I need to do, feel free to let me know.

### CODE REVIEW

**Comment by kocio-pl** [comment]
Please post some before/after rendering (or a few, if it looks different in different places) so the readers can instantly get what is the problem and how it's fixed just by looking, OK?

**Comment by Adamant36** [comment]
OK. I'll make sure to do that from now on. Here's a few pictures of the before and after of a canal in two separate areas. Unfortunately, I wasn't able to find any named ditches or drains in the area I use for rendering, but I imagine they would look much the same. 
Z15
canal before 1
canal after 1
canal before
canal after
Z16
canal z16 before
canal z16 after

**Comment by kocio-pl** [comment]
Thanks for the images. Probably that rivers have the same problem and maybe should be rendered the same, because they're not different than canals IIRC - I mean waterway, not river area, of course. 

Could you test it on some rivers too (some without the surrounding area and some with it)?

**Comment by Adamant36** [comment]
Sure. I was actually thinking that. So I tested out a few different zoom levels and text spacing with both areas and no area. 
Areas zoom 13 text-dy: 10;
before with area z13
after with area z13
Areas zoom 14 text-dy: 10;
before with area z14
after with area z14
Also z15, z16, and z17 after with text-dy: 10;
area after z15
area after z16
area after z17

It seems like text-dy: 10; works good for z13 but not anything greater than that because the label is still in the water way. So I tried different spacing levels for the rest of them.
Areas z14 text-dy: 14; 
water area z14 dy-14
z14  text-dy: 14; thinner water area
water area z14 dy-14 thinner water area
Areas z15 text-dy: 14; 
water area z15 dy-14
Areas z15 text-dy: 14; alternative
water area z15 dy-14 alternative
Areas z15 text-dy: 18; 
water area z15 dy-18
Areas z15 text-dy: 18; alternative
water area z15 dy-18 alternative
Areas z16 text-dy: 18; 
water area z16 dy-18
Areas z16 text-dy: 18; 
water area z16 dy-18 alternative
text-dy: 18; seems to work OK for z15 but doesn't work at all well on z16

Line before Z13
line before 13
Line after z13 text-dy: 10;
line after z13 dy10
Line after z14 text-dy: 10;
line after 14
Line after z15 text-dy: 10;
line after 15
Line after z14 text-dy: 14;
line after z14 dy-14
Line after z15 text-dy: 18;
line after z15 dy-18

I think z13 is best with  text-dy: 10; z14 is best with text-dy: 14; and z15 is best with text-dy: 18; At zoom 16 and 17 though it seems like the text will be in the water area whatever the spacing is set to and it would probably make the text to far away from a line if it was increased any more than 18. Plus a lot seems to depend on the width of the river.

**Comment by kocio-pl** [comment]
I also think that this idea breaks on the rivers, so I'm thinking about rejecting this idea. We could also stick to the original idea and don't change the rivers (as an exception) or try with the halo.

**Comment by matthijsmelissen** [comment]
@Adamant36 Sorry for lack of response earlier, and thanks for your nice improvements! I definitely think this is an improvement, at least for ditch and drain (as in the original).

Another option would perhaps be to make the text darker?

@Adamant36 If you could change the PR in a way you're happy with I'll (probably) merge it.

**Comment by kocio-pl** [comment]
I think offset is OK for thin lines:
- stream
- ditch
- drain

Rivers are wide by definition, so it's better to not add an offset, because the water area should be added eventually. 

Canals can have different size, so I'm undecided.

Current code meets my feeling and canals have the offset here, so basically I'm OK with this PR.

**Comment by matthijsmelissen** [comment]
Lets go ahead and merge it then!

**Comment by matthijsmelissen** [comment]
Let’s go ahead and merge it then!

**Comment by kocio-pl** [comment]
I would, but the remote repo doesn't let me resolve conflict in `water.mss `, so - let's wait for @Adamant36... :smiley:

**Comment by matthijsmelissen** [comment]
You should just be able to do `git checkout master` followed by `git pull Adamant36 master` to resolve the merge conflict? You might need to add `git remote add Adamant36 https://github.com/Adamant36/openstreetmap-carto/` first.

**Comment by kocio-pl** [comment]
Thanks, I was trying just the web interface. However I'm still not certain about canal, so I won't hurry that much to fiddle with command line.

**Comment by Adamant36** [comment]
I agree with everything said. It looks good as is. River and canals though should probably should probably stay not offset due to the width issue. @kocio-pl, if there is  anything I need to do on my end to resolve the merge conflict just let me know.

**Comment by kocio-pl** [comment]
Yes, you should try to rebase, if you know what it means (basically applying current master changes to your code):

https://help.github.com/articles/using-git-rebase-on-the-command-line/
https://help.github.com/articles/resolving-merge-conflicts-after-a-git-rebase/

**Comment by Adamant36** [comment]
@kocio-pl, I think its good to go on my end now. That was some crazy stuff :)

**Comment by Adamant36** [comment]
There you go.

**Comment by kocio-pl** [comment]
Thanks for the code and especially for the careful testing! It really works better for thin waterway lines.

**Comment by Adamant36** [comment]
Your welcome. I was pretty worried for a while there that I had jumped the gun on the pull request and that it would never go through. So I appreciate you being patient with me and providing the extra help when I needed it. It made all the difference. Next time I'll be sure to test things more in the original issue before I turn it into a pull request.

**Pull request merged**
