### PR TITLE
move bakery icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 by moving bakery icon to SVG.
Icon: [nebulon42/osmic/bakery-16.svg](https://github.com/nebulon42/osmic/blob/master/shop/bakery-16.svg) (as used by HOT style already)

I think that a loaf of bread is more (universally) recognisable as a pretzel.

http://www.openstreetmap.org/#map=19/48.21113/16.36694
before
bakery_before

after
bakery

### CODE REVIEW

**Comment by math1985** [comment]
Yes, looks nice.

**Comment by dieterdreist** [comment]
+1 for the pretzel, as it is more catchy, the proposed bread icon could
also be read as a comb for instance.

**Comment by talllguy** [comment]
The bread does look like a comb, but I feel that bread is still more synonymous with bakeries. Perhaps the silhouette of a cross section of a loaf of bread would be better. :bread:

**Comment by althio** [comment]
> I think that a loaf of bread is more (universally) recognisable as a pretzel.

+1
The bread icon might be improved but it is already better than a pretzel at international level IMO.

**Comment by math1985** [comment]
The bread icon is recognizable (n=1).

**Comment by mkoniecz** [comment]
Overall I would support merging.

I asked three people, with following results:
- ?, but agreed that it looks like a bread. Claimed that guess was impossible due to color.
- comb
- bread

For me old icon is not better.

**Comment by daganzdaanda** [comment]
As I'm from Bavaria, I like the pretzel (it is used by many bakeries here) -- but I do think that in the rest of the world, a loaf of bread will probably be better.
The icon works for me, but if you still want to experiment, I'd suggest the outer two lines to get angled inwards a bit, so that they are not parallel anymore.

**Comment by Rovastar** [comment]
I do admit I thought comb when I first saw it.

But I am not really good at icons like this.  I just Google "bread icons" and get ideas from there.

**Comment by nebulon42** [comment]
Thanks for testing and comments. Overall, there seems to be support for the bread instead of the pretzel with icon improvements possible.

I could offer the following alternative: bakery-163

This adds more noise but resolves the comb issue?!

**Comment by mkoniecz** [comment]
For me it is much better.

**Comment by althio** [comment]
For me it is even better than first bread and far superior to pretzel.
Obviously I support merging.

**Comment by nebulon42** [comment]
updated with bread variant

**Comment by dymo** [comment]
In Denmark where I'm from, most bakeries have a pretzel in their logo - i don't know the origin of that tradition.

In Vietnam where I live, you usually have to look very hard to find a bread loaf in a bakery, so I don't think the bread icon would be recognizable here, but baguette, croissant or cake icons would work.

**Comment by nebulon42** [comment]
> In Denmark where I'm from, most bakeries have a pretzel in their logo - i don't know the origin of that tradition.

In Europe those originate from medieval guilds and their signs.

**Pull request merged**
