### PR TITLE
make display threshold of landuse=military and amenity=prison areas based on way_pixels

### PR DESCRIPTION
**Pull request by matkoniecz**
Small prison and military areas rendered later, huge military areas may be rendered earlier.

https://cloud.githubusercontent.com/assets/899988/9227266/f193eabe-4112-11e5-86a3-200bb75c27fb.png
https://cloud.githubusercontent.com/assets/899988/9227264/f193208e-4112-11e5-9053-0e56f19f07ba.png
https://cloud.githubusercontent.com/assets/899988/9227268/f19623ce-4112-11e5-8ae8-8deaaa55f5c4.png
https://cloud.githubusercontent.com/assets/899988/9227269/f19857a2-4112-11e5-8afa-0cc678f88787.png
https://cloud.githubusercontent.com/assets/899988/9227267/f1952384-4112-11e5-98f4-3730628c9e6b.png
https://cloud.githubusercontent.com/assets/899988/9227273/f1ade1bc-4112-11e5-8962-59b7421724ee.png
https://cloud.githubusercontent.com/assets/899988/9227270/f1ac6c2e-4112-11e5-8014-14137cd6d1f9.png
https://cloud.githubusercontent.com/assets/899988/9227272/f1ad65b6-4112-11e5-8c47-eb66a9f88cab.png
https://cloud.githubusercontent.com/assets/899988/9227274/f1af9d40-4112-11e5-9155-aa0f467fc20b.png
https://cloud.githubusercontent.com/assets/899988/9227271/f1ac74e4-4112-11e5-90db-aa9cec56d16c.png
https://cloud.githubusercontent.com/assets/899988/9227275/f1b18768-4112-11e5-9160-83f0ad027d42.png
https://cloud.githubusercontent.com/assets/899988/9227280/f1c85420-4112-11e5-92a1-71803e4a5108.png
https://cloud.githubusercontent.com/assets/899988/9227276/f1c5efdc-4112-11e5-8e4c-b944b9c5211c.png
https://cloud.githubusercontent.com/assets/899988/9227279/f1c7e2d8-4112-11e5-98ad-5ebb0159ef68.png
https://cloud.githubusercontent.com/assets/899988/9227277/f1c6fb7a-4112-11e5-9f53-ff9f35d0a0b5.png
https://cloud.githubusercontent.com/assets/899988/9227265/f1934bfe-4112-11e5-86da-9ab871b3cc5b.png (SW USA - only with PR applied. Current state: http://www.openstreetmap.org/#map=7/47.006/-117.312

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
does this fix #686 ?

**Comment by matkoniecz** [comment]
Yes, also #1648 as mentioned in commit descriptions ( https://github.com/gravitystorm/openstreetmap-carto/pull/1739/commits - available via "commits" tab at top of discussion).

**Comment by HolgerJeromin** [comment]
Sorry, i always forget to check the commit message :-) Thanks

**Comment by kocio-pl** [comment]
It's good change. For some examples I was unable to spot the difference, but at least I haven't seen any regression.

**Pull request merged**
