### PR TITLE
Start merging road areas into roads layers

### PR DESCRIPTION
**Pull request by pnorman**
cross-ref #2046 

This is how far I got before I had to travel, but should reviewable on its own.

### CODE REVIEW

**Comment by math1985** [comment]
Are the reordering in the .mss necessary and the whitespace changes necessary? If not, could you propose these as a separate PR?

**Comment by pnorman** [comment]
> Are the reordering in the .mss necessary and the whitespace changes necessary? If not, could you propose these as a separate PR?

They're needed since they belonged to the roads area layer, which is now gone. The only whitespace change is because they end up nested differently within the roads fill layer.

I think there's an opportunity to refactor that part of the MSS and simplify it, but haven't looked at it in enough detail yet.

**Comment by math1985** [comment]
Something is still wrong with this PR, areas now also render as linear roads. This causes them to be rendered too big (as the outline is rendered too).

I didn't know it was possible to just leave out the geometry field, by the way.

**Comment by matkoniecz** [comment]
> Something is still wrong with this PR, areas now also render as linear roads. This causes them to be rendered too big (as the outline is rendered too).

What results in following problems: https://cloud.githubusercontent.com/assets/899988/15871159/70ebd0a2-2cf3-11e6-9256-bbe85db6c0ef.png

**Comment by pnorman** [comment]
Closing as don't know when I'll have time to resume work on this.

**Pull request closed without merging**
