### PR TITLE
Creature features and text-polys to use in naming and shading places

### PR DESCRIPTION
**Pull request by stevenLAD**
Create features and text-polys to use in shading and naming places that
are defined as areas.

Replaces Pull 2800 which did not create features.

Subsequent Pulls in new branches will implement these features

### CODE REVIEW

**Comment by stevenLAD** [comment]
Currently only addresses Vilages and Hamlets where any conflicts with place points should be easily identifiable by contributors, but can be extended to other places if required / desired

**Comment by pnorman** [comment]
Closing since this doesn't implement anything and you've made #2802 and #2804

**Comment by stevenLAD** [comment]
I was told on my first pull to beak things down into small chunks using separate pull requests. With 2803 (this pull) I created objects, and then with 2804 I rendered the names and 2806 the areas, the intention being to allow use of names areas or both, and to not confuse the creation and the rendering. Clearer guidelines as to how Pull requests are to be structured needs to be available, as different people appear to have different ideas.

**Comment by pnorman** [comment]
#2804 contains the commits in this PR, so it replaces this.

The problem with #2797 is you were doing unrelated whitespace cleanups in the same PR as implementing something new. You should have one PR for whitespace cleanups and another for implementing something new.

**Comment by stevenLAD** [comment]
Thank you for the clarification. I have followed this practice since.

**Pull request closed without merging**
