### PR TITLE
transparent symbol for private recycling and playgrounds

### PR DESCRIPTION
**Pull request by mkoniecz**
implements part of #1012

Thanks to @nebulon42 for SVG icons.

The same method as for private parking, without considering access=public as synonymous to access=yes

### CODE REVIEW

**Comment by nebulon42** [comment]
Private parking also changes text colour, maybe this should be done for playground too?

**Comment by mkoniecz** [comment]
Good idea.

**Comment by math1985** [comment]
I'm not sure if we want to render an icon for private playgrounds and recycling centre at all? Also I don't know if people will understand the meaning of this use of transparency at all?

**Comment by polarbearing** [comment]
Why not, I think it is good to see if e.g. a school or a residential structure has a playground or not. 
And yes, they will understand as long as there is consistency (private parking, playing, museum, etc)

**Comment by mkoniecz** [comment]
New version, with different text style.

before/after

access private leisure playground name eeeeee eeeeee eeeeee ref 1 ele 8000 closed_way master - private_transparent
36 4224616 28 153194 access private leisure playground master - private_transparent
55 5835111 38 1394557 access private leisure playground master - private_transparent
31 3287897 120 6898142 access private leisure playground master - private_transparent
50 0210097 19 9001859 access private leisure playground master - private_transparent

**Comment by math1985** [comment]
I don't think the new text colour looks nice. Perhaps there is a better colour? I also wouldn't mind keeping the text the same.

**Comment by mkoniecz** [comment]
access private leisure playground name eeeeee eeeeee eeeeee ref 1 ele 8000 closed_way master - private_transparent

What about this one?

**Pull request merged**
