### PR TITLE
Add rendering for bicycle_parking

### LINKED ISSUE #591: Add rendering for amenity=bicycle_parking
Please add rendering for amenity=bicycle_parking, both nodes and areas. The icon could be the same as car parking but with a small bicycle underneath, like the JOSM "rendering".

If i remember correctly, these used to render. Areas like these look very empty with no bicycle parking rendering: http://www.openstreetmap.org/#map=19/55.86100/12.91229 .

Also, there are about 96 000 uses in the database.

### PR DESCRIPTION
**Pull request by math1985**
* Add bicycle_parking icon from z18 or (for areas) 750 pixels, whichever is
  earlier.
* Add yellow background for bicycle_parking (like regular parking).

Thanks to @nebulon42 for the icon.

This resolves #591 and part of #108.

### CODE REVIEW

**Comment by pnorman** [comment]
assigning to @gravitystorm for him to decide if we want to render bicycle_parking

**Comment by mkoniecz** [comment]
@math1985 This PR adds only .
amenity bicycle_parking name eeeeee eeeeee eeeeee ref 1 ele 8000 node master - math_bicycle-parking
svg file without any logic to render it.

**Comment by mkoniecz** [comment]
Also, why it is 18px sized icon? Is it icon with halo like ones from rejected #1341?

**Comment by math1985** [comment]
Pushed missing files.

The icon was [proposed](https://github.com/gravitystorm/openstreetmap-carto/issues/591#issuecomment-77688436) by @nebulon42. I doubt it works on 16px.

**Comment by HolgerJeromin** [comment]
ihmo the name of the feature is not rendered. Is this intentional?

**Comment by math1985** [comment]
> ihmo the name of the feature is not rendered. Is this intentional?

Yes, it's not rendered for regular parkings either.

**Comment by HolgerJeromin** [comment]
Yes, it is: http://www.openstreetmap.org/way/8089509

**Comment by math1985** [comment]
You're right, I added the label now.

**Comment by mkoniecz** [comment]
I think that also transparency for private ones should be added.

**Comment by nebulon42** [comment]
Before https://github.com/nebulon42/osmic/commit/135010e64ff3a9e3ce067519da91ee02482eea6a all icons are versions without halos. If you don't want them just use those.

**Comment by math1985** [comment]
Closed in favour of #1364.

**Pull request closed without merging**
