### PR TITLE
Add icon for shop=ticket 

### PR DESCRIPTION
**Pull request by Adamant36**
This pull request adds an icon for shop=ticket and closes issue #3115
https://www.openstreetmap.org/#map=19/37.73301/-122.50486 (node)
ticket node
https://www.openstreetmap.org/#map=19/37.76897/-122.47026 (way)
ticket way

### CODE REVIEW

**Comment by kocio-pl** [comment]
Thanks! 

Could you please show just the area around the object? It's hard for me to find them and it should be easy to make the selection with the Kosmtik export.

**Comment by Adamant36** [comment]
Sure. Its hard for me to find them to. I didn't know you could do it that way. I've been taking screen captures and cropping them. If you could update your list of code needed for icons in issue #3105 for this issue when its merged, along with the one for Guidepost and Map Icons, I would appreciate it. 

Thanks

**Comment by Tomasz-W** [comment]
Hmm, the icon looks a little bit "empty". I made inverted versions for compare.

shop ticket 2
shop ticket 3

@Adamant36 Can you try them?

Gist link: https://gist.github.com/Tomasz-W/b18eee2375829d1fa2e97f40fd855968

**Comment by kocio-pl** [comment]
It's always better to export images, because for example Chrome has some problems with handling colors. However even when making a screenshot just crop it more accurately and it would be OK.

**Comment by Adamant36** [comment]
Ticket 2 (way)
ticket 2 way
Ticket 2 (node)
ticket 2 node
Ticket 3 (way)
ticket 3 way

**Comment by Tomasz-W** [comment]
I vote for "2"

**Comment by Adamant36** [comment]
Good. Thats the way I was leaning to. I'll update the pr as soon as I get the branch thing resolved.

**Comment by lakedistrictOSM** [comment]
Another vote for 2.

**Comment by Adamant36** [comment]
So I was trying to update the ticket.svg file and I screwed up and readded it as an .png. So now there's two of them. Is there a way to delete ticket.png and get the correct ticket file added that's not a total hassle?

**Comment by sommerluk** [comment]
Delete the file `ticket.png`, than do `git add ticket.png`.

**Comment by Adamant36** [comment]
@kocio-pl It looks like this one is good to go. Id appreciate it if you could merge it before I fix whatever is wrong with interior decoration so I wont risk screwing it up again. Sorry about the problems. Lesson learned on using branches I guess.

**Comment by kocio-pl** [comment]
Thanks, works as expected!

**Comment by kocio-pl** [comment]
Please remember to add closing statement in the proper way, so it will close corresponding issue automatically:

https://help.github.com/articles/closing-issues-using-keywords/

**Pull request merged**
