### PR TITLE
Render shared cycleway+footways different from cycleways

### PR DESCRIPTION
**Pull request by tvainika**
Add 'segregated' tag to .style file to allow using it in styles.

Add different rendering to non-segregated shared cycleway and footway
by alternating red and blue just like separate cycleway and footway
are rendered.

Add longer cycleway dashes to segregated cycleway and footway.

This resolves issue #1321.

Compared to my original proposal in #1321, this has only three different renderings: Current for cycleways without foot=yes/designated tag, and then two different dash patterns for segregated cases yes or no (default). In case of not segregated, rendering is like alternating footway and cycleway. In case of segregated cycleway and footway, it has a bit longer dashes for cycleway, because such segregation is usually considered more suitable for bicycling.

### CODE REVIEW

**Comment by mkoniecz** [comment]
Please add before/after images.

**Comment by tvainika** [comment]
Here is before/after images.

Let me know what you think. I actually started thinking myself if this segregated=yes case needs still polishing if you compare it to non-combined cycleway.

cycleway_before
cycleway_after

**Comment by math1985** [comment]
This requires a database reload. See also #1243.

**Comment by tvainika** [comment]
Let me know if you think it would be worth doing without separate case for segregated=yes tag: Combined cycleway and footway rendered by alternating blue and red dots can be done without a database reload. (Just first part of the changes made to roads.mss.) That would resolve my original issue partially.

**Comment by kocio-pl** [comment]
I think red-blue-red-blue pattern is not too visible, maybe it should be less interleaved (like 3xred-3xblue-3xred-3xblue or something)?

**Comment by tvainika** [comment]
Current non-combined cycleway is 1×blue+3×space repeated, non-combined footway is same pattern in red.

If combined cycleway and footway uses something like 3×blue(-3×space)-3×red(-3×space) pattern, should also non-combined cycleways and footways be modified?

**Comment by math1985** [comment]
I think the blue/red mixed combined looks too busy. In addition, I don't think rendering shared cycleways different from cycleway-only is really necessary.

All cycleway-only roads I know are either of two categories: either there is a footway immediately next to it, or pedestrians are officially not allowed to use the cycleway but everyone does so anyway. In neither case, it's not really useful for pedestrians to know that they can't use the cycleway. Is this different in Finland (or anywhere else)?

So I will reject this proposal. But thank you anyway for the effort @tvainika!

**Comment by mkoniecz** [comment]
> either there is a footway immediately next to it, or pedestrians are officially not allowed to use the cycleway but everyone does so anyway

In Poland in the second case law allows pedestrians to use cycleways.

**Pull request closed without merging**
