### PR TITLE
WIP Improve low-zoom levels

### LINKED ISSUE #2688: Improve low zoom levels
Most of our work goes to high zoom levels, but it's time to look how we could improve also lower levels. [Mid zoom work](https://github.com/gravitystorm/openstreetmap-carto/issues/2194) seems to be pretty advanced now, with PR mostly ready to be merged (#2654). Faded out landuse colors could be used also for low zoom IMO (and new water color can have some impact), but that's just a general idea and there can be other things which need to be taken into account (like performance problems or issues related to using external and pre-rendered data).

What we have now in low zoom levels is better rendering of cities/capitals (z4+) and new road colors (z5+), but for example z0-z3 is still underused. Discussion on improving low zoom levels has been [already started here](https://github.com/gravitystorm/openstreetmap-carto/pull/2654#issuecomment-314688048).

Some related resources:
- http://fred.dev.openstreetmap.org/lowzoom/
- https://lists.openstreetmap.org/pipermail/talk/2012-March/062286.html
- https://wiki.openstreetmap.org/wiki/User:Kocio/low_zoom_rework (my old summary from 2015)
- https://github.com/gmgeo/osm-carto-lowzoom (tool for dropping tags from extracts which are not visible on low zooms)

Some issues that are close to the subject:
- https://github.com/gravitystorm/openstreetmap-carto/issues/2278
- https://github.com/gravitystorm/openstreetmap-carto/issues/2507
- https://github.com/gravitystorm/openstreetmap-carto/issues/2293
- https://github.com/gravitystorm/openstreetmap-carto/issues/1448
- https://github.com/gravitystorm/openstreetmap-carto/issues/1770
- https://github.com/gravitystorm/openstreetmap-carto/issues/1935

### PR DESCRIPTION
**Pull request by matthijsmelissen**
This is a big pull request (might be split up later) to keep track of proposed changes on the low zoom levels.

This pull request does the following:
* Change admin borders to thick non-transparent dark-green lines
* Generalize (simplify) admin borders
* Make placenames slightly darker
* Render country/state labels dark green (color or borders)
* Renders maritime borders blue
* Render motorways on z6 and z7 slightly lighter

This PR also includes #3065 (give oceans outline and simplify shapefiles on z0-7), #3056 (improve country/state label rendering) and #2972 (add halo to roads on z6 and 7).

On a technical level, admin borders are now rendered from the individual lines rather than polygons. This is necessary because drawing admin borders from polygons means we always render two borders on top of each other (both sides of the border), which means borders are always rendered unnecessarily thick. It also gives problems with the generalization algorithm. However note that admin_level's on the individual lines are missing in some countries (most notably Poland), so this still requires some work on the data side.

Resolves #2688. Supersedes #2950 (different approach).

### CODE REVIEW

**Comment by matthijsmelissen** [comment]
Before:
screen shot 2018-02-16 at 01 33 07
After:
screen shot 2018-02-16 at 01 33 17

Before:
screen shot 2018-02-16 at 01 32 37
After:
screen shot 2018-02-16 at 01 32 25

**Comment by matthijsmelissen** [comment]
And to illustrate, difference between polygon boundaries and line boundaries.

Polygon (old) / line (new):
screen shot 2018-02-16 at 01 47 10screen shot 2018-02-16 at 01 48 50

Specifying a thinner line in the polygon case doesn't help in making the polygon even thinner.)

**Comment by matthijsmelissen** [comment]
@rrzefox Would it be possible to deploy this one instead?

**Comment by matthijsmelissen** [comment]
To clarify, the approach in this PR replaces the PR you just deployed. Sorry for the confusion!

**Comment by rrzefox** [comment]
Yeah I gathered that, but I hadn't read this PR as "ready to be deployed" yet (too many "WIP" in changeset descriptions and even in the title).

This has however now been deployed and Z0-8 rerendered.

**Comment by matthijsmelissen** [comment]
Thanks. Quite a big change, I really need to get used to it myself.

URL to compare: http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#7.00/37.519/16.197

**Comment by kocio-pl** [comment]
This might be good for checking the borders tagging - and maybe making them more standard to avoid problems like here:

http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#13.00/16.4752/-90.5431

or here (3 different renderings of the same border - black, blue and none):

http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#14.00/44.4144/-75.8381

**Comment by kocio-pl** [comment]
Korean border (Joint Security Area) looks strange now:
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#8.00/38.269/-592.085

**Comment by Tomasz-W** [comment]
If this PR includes changing borders on all zoom levels (it's name is "low-zoom levels", but @matthijsmelissen visualisation includes all zoom levels, so I don't know), I've got some remarks:
* dark dashed line could be confesed as some kind of highway=track on higher zoom levels
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#15.00/51.6109/-706.8934
* how would look the borders from highways added to relation? (I can't find an working example, but here's sample place in Poland to show you what I mean)
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#18.00/52.26675/-703.20169

**Comment by andrzej-r** [comment]
I quite like the visual aspect of these changes but there are problems. 

- this PR is changing too many things at once. We should have one ticket for discussing/coordinating changes and several PRs implementing specific ideas. 
- proposed rendering of borders and names IMHO looks very good. But screenshots above show a number of technical (mapping?) issues. How do we go about that? Fix mapping issues first? Deploy first and fix errors later (wouldn't recommend that)? Some mitigation techniques? 
- as I mentioned in #3056 I really don't like the idea of using different size labels for regions of the same type. Filtering is fine but rendering style should not misrepresent data.

**Comment by kocio-pl** [comment]
Another interesting place to test rendering countries - Vatican:

http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#13.00/41.8987/12.4623
http://bl.ocks.org/matthijsmelissen/raw/af7a602c222dbf1ff1a2c0d84ed755b7/#16.00/41.9029/12.4529

**Comment by daganzdaanda** [comment]
Hmmm, difficult, and yes, too much in one change really ;) 
Apart from the big issue whether it's even possible to switch to lines from polygons for boundaries, here are my 2c.

* I do like the treatment of naval boundaries. 
* I don't like how close the colours of the labels for countries and cities are now.
* I like a lot that there are less dashed borders, much calmer. Also, it's no problem for me that the style of a border can change from solid to dashed when zoomed in. 
* Very unsure about introducing generalisation. It opens a can of worms philosophically ;)
* I really don't mind pink for borders, I think it's used in many maps (e.g. school atlases in Germany). But I agree it's a bit of a issue between motorways and pink borders. The thin dark-green lines mostly look good, but they can be mistaken for railways.
* Making motorways thinner while leaving the casing / halo makes them look more pink on z6+7

**Comment by Zverik** [comment]
I see a lot of gaps in borders. Poland loses all of its regions. Since, I assume, these borders are mapped properly with relations, could it be this PR relies on a secondary, often overlooked mapping practice, like tagging border ways with `boundary=administrative`?

**Comment by imagico** [comment]
> I see a lot of gaps in borders. Poland loses all of its regions. Since, I assume, these borders are mapped properly with relations, could it be this PR relies on a secondary, often overlooked mapping practice, like tagging border ways with boundary=administrative?

Correct.

Historically this style has for a long time rendered administrative boundaries both based on way tags and based on boundary relations.  This was changed in #1989 to relations only which provides meaningful feedback for mappers that they have correctly mapped the boundary relation - see also https://github.com/gravitystorm/openstreetmap-carto/pull/2950#issuecomment-345839634.

This PR would change mapper feedback to communicate to mappers about way tagging only and not about boundary relations.  The mapper would essentially directly draw boundary lines.  Boundary relations would be used for labels only - which would generate additional confusion for mappers.

If you'd transfer tags from relations to ways you would need to decide if you do this based on tags (i.e. still require boundary=administrative to be tagged on ways) or do this based on relation membership only.  In any case you would still loose mapper feedback regarding the validity of the multipolygon geometry.

**Comment by hikemaniac** [comment]
In general this PR looks good. In my opinion the country and region borders become more recognizable and distinguishable. Also the maritime borders look great. The thinner roads with a halo fit perfectly as well. However, on zoom 8 and bigger I have a hard time to see the borders:
borders unclear
Maybe we can highlight them in some way, though I personally have no good ideas about how to fix this.

**Comment by dieterdreist** [comment]
2018-02-25 10:33 GMT+01:00 hikemaniac <notifications@github.com>:

> In general this PR looks good. In my opinion the country and region
> borders become more recognizable and distinguishable.
>


I don't share the enthusiasm, with the changed colors and line width the
borders come very close to railways, the small width makes it IMHO more
difficult to distinguish borders from other features, because they are
closer now.

**Comment by matthijsmelissen** [comment]
> with the changed colors and line width the
borders come very close to railways, the small width makes it IMHO more
difficult to distinguish borders from other features, because they are
closer now.

Does your criticism apply to all zoom levels or only the mid/higher ones?

**Comment by Tomasz-W** [comment]
I think this issue should be split into few parts, and in the part with borders colour change, we should start from changing current borders color to dark-green, and discuss about certain problems one by one. It's big topic by itself, so with another things (labels change, highways visibility) the disscusion it messed up too much.

**Comment by matthijsmelissen** [comment]
I'm still playing with this. Example of what I have now:

screen shot 2018-03-04 at 23 09 08

I'll cut this up into smaller PR's.

**Comment by kocio-pl** [comment]
If I see it right, the land color has been changed for something yellow, or this is a kind of bug?

**Comment by matthijsmelissen** [comment]
> If I see it right, the land color has been changed for something yellow, or this is a kind of bug?

Yes, that's something I've been experimenting yet (for z0-7). It increases the contrast between land/water and land/roads, and to me makes the map more pleasant to look at. Not sure yet whether I'll keep it though.

**Comment by matthijsmelissen** [comment]
I remember somebody had a link that shows the admin ways that do not have an admin_level tag. Could somebody repost that link?

**Comment by Tomasz-W** [comment]
I don't like yellow background idea. For me, @imagico low-zoom proposition is way more better direction.

http://maps.imagico.de/#map=3/38.411/2.988&lang=en&r=osmlz&o=146&ui=2

**Comment by matthijsmelissen** [comment]
> For me, @imagico low-zoom proposition is way more better direction.

Which of the layers? Note that the Green Marble layer is not osm-data, so we probably don't want to use it here.

**Comment by Tomasz-W** [comment]
> Which of the layers?

The ones set in link (OSM-Carto style landcover, OSM-Carto style water areas).

**Comment by matthijsmelissen** [comment]
> I like Green Marble, because it's giving an effect like everything is complete :)

I agree that it looks nice, but of course the question is whether we want to give the impression on openstreetmap.org that everything is complete :).

**Comment by kocio-pl** [comment]
This is more realistic version which shows only the data we already have:

http://maps.imagico.de/#map=3/38.411/2.988&lang=en&r=osmlz&o=56&ui=2

This model however doesn't use desaturation we use on midzoom, so the colors would be softer (that would probably help Japan for example). IIRC Green Marble was used by Christoph only to show how the final effect could look like:

http://blog.imagico.de/on-basic-small-scale-landcover-rendering/

The bare land will be still visible on low zoom levels for quite a long time and I like the current color (yellow/green doesn't work for me).

**Comment by polarbearing** [comment]
> On a technical level, admin borders are now rendered from the individual lines rather than polygons.

I am strongly against this move as it completely breaks the data model of boundary relations.
I was surprised to find a major change in how to handle border data - woken up by the tagging discussion - camouflaged in a PR that is named for some visual improvements. As said by others before, these moves need to be discussed separately.

**Comment by matthijsmelissen** [comment]
> I was surprised to find a major change in how to handle border data - woken up by the tagging discussion - camouflaged in a PR that is named for some visual improvements. As said by others before, these moves need to be discussed separately.

The relevant PR is #3102 (the current one is a meta-PR to group a couple of related changes).

**Comment by matthijsmelissen** [comment]
> I was surprised to find a major change in how to handle border data - woken up by the tagging discussion - camouflaged in a PR that is named for some visual improvements. As said by others before, these moves need to be discussed separately.


The relevant PR is #3102 (the current one is a meta-PR to group a couple of related changes). It was certainly not my intention to camouflage this change (and I think in #3102 I have been quite explicit about it).

**Comment by DaveF63** [comment]
>.On a technical level, admin borders are now rendered from the individual lines rather than polygons. This is necessary because drawing admin borders from polygons means we always render two borders on top of each other (both sides of the border), which means borders are always rendered unnecessarily thick.

As this requires adding duplicated data, this is manipulating data to suit one renderer & is unacceptable. Relations can be tested to see if there are duplicate `admin_level` tags as part of the border & rendering can be adjusted to suit.

**Comment by matthijsmelissen** [comment]
Some more ideas for border rendering (first is current):

screen shot 2018-04-12 at 02 21 40
screen shot 2018-04-12 at 02 21 14
screen shot 2018-04-12 at 02 20 59
screen shot 2018-04-12 at 02 24 17

**Comment by matthijsmelissen** [comment]
Some more ideas for border rendering (first is current):

screen shot 2018-04-12 at 02 20 59
screen shot 2018-04-12 at 02 21 14
screen shot 2018-04-12 at 02 21 40
screen shot 2018-04-12 at 02 24 17

**Comment by dieterdreist** [comment]
I prefer the first from your first post and the third from the second post.
Also the last is OK, although I prefer less thick and more contrast. The
variants with the thinner borders blur into the map and make it less
readable.

**Comment by Tomasz-W** [comment]
Proposition from https://github.com/gravitystorm/openstreetmap-carto/pull/3074#issuecomment-366109563 was perfect for me. Bold, well-readable country names and and well-visible borders in gray, which was distinguishing them from pink roads.

**Comment by kocio-pl** [comment]
It would help me if you add numbers to the proposed versions.

**Comment by matthijsmelissen** [comment]
Done!

**Comment by kocio-pl** [comment]
I like 3 and 5 is also acceptable, however I'm not used to it.

**Comment by matthijsmelissen** [comment]
I'm a bit stuck with improving the low-zoom levels further. In my opinion zoom levels 5/6/7 are still rather ugly, however I find it hard to really improve them.

Is anyone willing to write a PR with suggestions?

**Comment by kocio-pl** [comment]
I'm stuck with #2946, but I lack the proposition how to solve it, mainly from @matkoniecz.

Another thing for low zoom that depends on the problem beyond me is showing rivers using waterway relation properties - see https://github.com/openstreetmap/osm2pgsql/issues/230#issuecomment-385311069.

I'm not sure what else could I do at the moment.

**Comment by matthijsmelissen** [comment]
Some of the issues in this PR have been addressed already; others will hopefully be addressed in separate PRs. I am therefore going to close this meta-PR.

**Pull request closed without merging**
