### PR TITLE
move prison icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Icon: [prison-16.svg](https://github.com/nebulon42/osmic/blob/master/administration/prison-16.svg)

before
prison_before

after
prison_after

### CODE REVIEW

**Comment by polarbearing** [comment]
Nice improvement, the old one looked a bit like an owl in a cage.

**Comment by math1985** [comment]
The icon is improved a lot, but perhaps still not recognizable enough. Any chance of basing an icon on something like [1](http://zizaza.com/cache/small_wm/iconset/582181/582214/PNG/256/nasty/simple_prison_nasty_line_icon_png_prison_png_prison_icon.png) or [2](http://t1.gstatic.com/images?q=tbn:ANd9GcQym0gbmT_5FsrMjM09K3LvqONGNeJJpEaKq0pxr2AVEpNei2HhopLsQA)?

**Comment by nebulon42** [comment]
@math1985 I think it will be hard to have the hands recognisable. Your second suggestion is quite similar to my proposal, though hands are absent. Could you explicate where you see lack of recognisability?

I see increasing the space between bars and the person as one possible improvement, but I'm not sure if that is necessary.

**Comment by kocio-pl** [comment]
What I like in current version is that the person behind the bars is lighter, so it's easier for me to recognize both objects are different - example 2 from @math1985 also goes this way (but it's too much abstract for me).

**Comment by daganzdaanda** [comment]
I like the new one already, it's much better than the owl! 

I kind of feel that the bars could be a little further from the head, and maybe then the body could be wider. Or maybe three bars, one of them in the middle in front of the person, could actually work? 
Maybe the window outline could also be stronger?

**Comment by Rovastar** [comment]
I like the new one already, it's much better than the owl! 

Owl!! Surely it is a "jailbird". ;)

**Comment by nebulon42** [comment]
I have tried some variations like increased space and a thicker frame, but nothing looked good. So I have to leave the proposal as it is.

**Comment by pnorman** [comment]
:shipit:

**Comment by math1985** [comment]
Is the change in tourism_viewpoint intentional? Might be better in a separate PR (or add least add it to the PR description).

**Comment by nebulon42** [comment]
@math1985 This is caused by the collapsed view of the code, if you expand it to full then you see that the change is made near the prison rule.

**Comment by math1985** [comment]
Oops, thanks.

**Pull request merged**
