### PR TITLE
Add more swimming icons

### LINKED ISSUE #2018: render water sport facilities (non waterpark)
We should render `leisure=sports_centre` + `sport=swimming` same as the current `leisure=water_park` to prevent tagging for the renderer (for not fun orientated water stuff).
All keys are available in the database.

The sports_centre + swimming combination is [quite often](http://overpass-turbo.eu/s/dFz) used (Taginfo says 3272) even now.

### PR DESCRIPTION
**Pull request by dryo**
Partially fixes #2018 

Changes proposed in this pull request:
- add icons for leisure=sports_centre + sport=swimming and leisure=swimming_area

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Have you tested this?
I am pretty sure this is missing a sql change

**Comment by dryo** [comment]
Hi @HolgerJeromin 
Thanks for your appreciation and hint. I forgot to input the SQL changes. Did that now.
Unfortunately I currently don't have the resources to test. Maybe someone else with more equipment at hand has time for that?

**Comment by Adamant36** [comment]
@dryo, I just tested it. It looks like you didn't add the code for them to rendered with their names. 
For instance, this sports centre should say "Richmond Swim Center" under the icon. 
sports centre no name
Here's the location of the place https://www.openstreetmap.org/#map=19/37.92399/-122.32714

At least the icon showed up. So, you know at least that works. I'll retest it and swimming areas once the extra code is added.

**Comment by dryo** [comment]
@Adamant36 A big thank you for testing! My main goal was to have icons but I see your point especially when it comes to sports centres. I added the code that should display the name label the same way it was with water parks.
If you have the time to test again I'd be very happy!

**Comment by Adamant36** [comment]
Your welcome. Thanks for doing it. I'm pretty happy you did, because it lays the groundwork for the other sports icons to be added, which I've been meaning to do at some point. 
**Sports Center** 
https://www.openstreetmap.org/#map=18/37.92395/-122.32794 (node)
sports center node
https://www.openstreetmap.org/#map=19/37.89536/-122.29191 (way)
sports center way
**Swimming Area**
https://www.openstreetmap.org/#map=17/37.80839/-122.42381 (node)
swimming area node
https://www.openstreetmap.org/#map=19/37.89572/-122.25025 (way)
swimming area way
**Thoughts**
So, it seems like names are rendering now. Two side notes, one the swimming area way is also tagged as a bay and it seems to over ride the blue water rendering. Two, the swimming area way is only rendering as a point , instead of an area with a fill color. The bay thing isn't that important, but I still wanted to mention it. The fill color thing for swimming area ways might be worth not rendering and leaving as is. Since it could look weird to have a green area in the middle of blue water. It might be worth testing anyway though, which I'm willing to do if need be. @kocio-pl, whats your opinion on it?

**Comment by dryo** [comment]
@Adamant36 Thanks for testing (again)! It seems to work as expected.

First side note:
If I understand it correctly you meant to write "point" instead of "way" and with "blue water rendering" you meant that the name of the bay is now green and no longer blue. I guess you were referring to "Aquatic Park Cove". I don't see this as a problem, however let's hear some opinions about that.

Second side note:
This PRs intention was not to fill swimming areas with color. See discussion on #1490 for that.  This pull request was only for #2018 leaving out the request for another icon for water parks because IMO there seemed no common support for this idea.

@HolgerJeromin @Tomasz-W @kocio-pl I'd see this PR as ready to merge. Your opinions please ;)

**Comment by Adamant36** [comment]
@dryo, your welcome. Yeah, thats what I meant. Sorry for the confusion. I wasnt thinking that those things were problems, but I still wanted to bring them up anyway just in case. I agree with you that its ready to merge. Thanks for writing the code. If you want me to test anything else for you in the future, feel free to ping me.

**Comment by HolgerJeromin** [comment]
swimming area combined with bay is not optimal / wrong tagging IMO. So I am fine with this side effect.

**Comment by Tomasz-W** [comment]
There is 5-10°C  in Poland now, so I'm not going to swim outdoor soon, but I would be happy with merging icon for both tags anyway ;) ;) I'm OK with no-fill/ outline for swimming areas.

**Comment by kocio-pl** [comment]
Thanks for testing and discussing it. It looks good to me and I think it should be merged.

I like especially spotting `leisure=swimming_area` - together with beach and beach resort it makes interesting new type of objects we show:

taghistory 53

**Comment by kocio-pl** [comment]
@dryo Thanks for this code! My testing showed that it's working as expected.

Since this is your first contribution, maybe you're interested in fixing some other warm up issues (see #3298)? If you will need some help or guidance, just drop a line.

**Comment by HolgerJeromin** [comment]
> My testing showed that it's working as expected.

You tested that this does not change sports centres without sport=swimming. Did you?

**Comment by kocio-pl** [comment]
Checked - it doesn't change standard sport centers rendering.

**Pull request merged**
