### PR TITLE
add icon for leisure=fishing

### LINKED ISSUE #3390: Add rendering for leisure=fishing
"Fish & Pay" (`leisure=fishing`) is a leisure facility for fishing as entertainment. People normally pay an entrance fee or by catch weight. It's similar to `landuse=recreation_ground` but with man-made or natural pounds.

I suggest using the same pattern for `landuse_recreation_ground` and [this](https://commons.wikimedia.org/wiki/File:MUTCD_RS-063.svg) as icon.

Links:
* Wiki: https://wiki.openstreetmap.org/wiki/Tag:leisure%3Dfishing
* Taginfo: https://taginfo.openstreetmap.org/tags/leisure=fishing
* Tag count: 5 026, more than beach_resort, outdoor_seating and bird_hide.
* Examples: [w607102421](https://www.openstreetmap.org/way/607102421) and  [w544102360](https://www.openstreetmap.org/way/544102360)
* Search: https://www.google.com/search?q=Fish+%26+Pay

### PR DESCRIPTION
**Pull request by Adamant36**
This PR adds an icon for leisure=fishing. Which is used to tag fishing spots. It currently has 5,132. It is different then the fishing=yes tag in the fact that it is used to tag individual fishing spots. Whereas, the later is used to tag places, like lakes, with a fishing designation. I think adding the icon would allow for some cool places to show up on the map that would not otherwise, along with their names. Which helps in navigation.The usage numbers have also been climbing a lot since the tag was created and will only increase now that it is a default for iD editor. 
taghistory
https://www.openstreetmap.org/#map=19/38.01555/-122.36589 (node)
node
https://www.openstreetmap.org/#map=19/34.74313/-118.20191 (way)
way
Closes #3390

### CODE REVIEW

**Comment by Tomasz-W** [comment]
@Adamant36 Can you try with 2nd version of icon (updated hook proportions):

leisure fishing fish hook above

Gist link: https://gist.github.com/Tomasz-W/58cdeee87a3e4f767d699955bd1caa35

**Comment by Adamant36** [comment]
Yeah sure. I like the second one better. I actually thought that one was it.

**Comment by Tomasz-W** [comment]
First version reminded me "U" shape, so I've made right hook part 1px lower.

**Comment by Adamant36** [comment]
Updated icon
https://www.openstreetmap.org/#map=19/41.91723/-71.75816 (node)
fishing node z18
https://www.openstreetmap.org/#map=19/42.80120/-71.57149 (way)
fishing way z17

@kocio-pl, I think its good to go if you want to test and merge it.

**Comment by kocio-pl** [comment]
Thanks, guys! It looks and works as expected.

**Pull request merged**
