### PR TITLE
Adding shop=hifi icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1418.

hifi-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
The situation for `shop=hifi` on the wiki is a bit unclear at this moment, maybe we should defer this a bit? Iconwise it works. How would it look like with the inner circle being larger?

**Comment by kocio-pl** [comment]
I don't remember any particular output from discussion on the mailing list and this icon seems to me as a no-brainer if we count recognizability. What are the issues you think should be resolved before we might start rendering it?

I will try with bigger circle.

**Comment by nebulon42** [comment]
It says on the wiki "proposed to be merged with electronics".

**Comment by kocio-pl** [comment]
I just asked on tagging list what to do with it.

**Comment by nebulon42** [comment]
Thanks. I know I'm really picky, but now the inner circle feels too big. What about having it larger than before but not as large as in 2) leaving a bit of white space for the "ring"? I think that would be perfect.

**Comment by kocio-pl** [comment]
No problem, we're just playing after all. =} 

3) hifi-14-3 

It may be really the best if this tagging will be held.

**Comment by kocio-pl** [comment]
Wiki page is now clean, since nobody on the list objected, and the icon is updated to version 3), so it's ready for merging.

**Pull request merged**
