### PR TITLE
add icons for popular shop types

### LINKED ISSUE #1415: Add special rendering for shop=jewelry
We should start rendering shop=jewelry, probably with this icon from osmfr-cartocss fork:

https://github.com/cquest/osmfr-cartocss/blob/master/symbols/jewelry.svg

[It was proposed in meta-issue #1402]

### PR DESCRIPTION
**Pull request by nebulon42**
Resolves #1415, #1412, #1408 and part of #1460.

alcohol ~~(distinction to beverages unclear #1407)~~
alcohol

electronics
electronics

furniture ~~(distinction to interior_design unclear #1406)~~ (interior_decoration not considered for now)
furniture

gift
gift

jewelry, jewellery
jewelry

mobile_phone
mobile_phone

optician
optician

### CODE REVIEW

**Comment by math1985** [comment]
For Jewelry, I also like an icon like this:

http://wiki.openstreetmap.org/wiki/File:Shop-jewelry.svg

Simpler than the ring, and the simpler the better on this scale, I guess.

**Comment by nebulon42** [comment]
I had a try with the diamond, but the inverse version of what you linked here did not work out. I'm not sure regarding the linked version, it's rather noisy for me. I seriously considered the diamond, but then moved towards the ring in the end.

**Comment by math1985** [comment]
Ok, good that you had a look at it at least!

**Comment by matkoniecz** [comment]
> alcohol (distinction to beverages unclear #1407)

Wiki has "shop=alcohol Shop selling alcoholic drinks" and "shop=beverages Shop focused on selling alcoholic and non-alcoholic beverages.".

**Comment by matkoniecz** [comment]
Maybe shop=beverages may have something else rather than wine glass? Second bottle? Can?

**Comment by dieterdreist** [comment]
> Am 21.04.2015 um 07:10 schrieb Mateusz Konieczny <notifications@github.com>:
> 
> alcohol (distinction to beverages unclear #1407)
> 
> Wiki has "shop=alcohol Shop selling alcoholic drinks" and "shop=beverages Shop focused on selling alcoholic and non-alcoholic beverages.".
> 


it's mainly a cultural distinction, in countries with restricted sale of alcohol (e.g. USA, Iran) there are special alcohol shops, while in other countries you will get alcohol also in "normal" beverage shops, but also in these countries there will typically be shops that sell alcohol only, often just of some particular  kind (typically high quality), like wine or whiskey.

**Comment by nebulon42** [comment]
Ok, so beverages should be distinct. I will work on that later. Any further comments on these icons?

**Comment by imagico** [comment]
optician, mobile_phone and gift seem fine to me.

furniture i would make the 'line' less prominent - right now it appears to be a two part object

jewelry seems too abstract to be easily recognizable - could also resemble some kind of doll/puppet or some technical stuff.

electronics seems ambiguous - could also mean a kind of public viewing location.

**Comment by dieterdreist** [comment]
2015-04-20 23:34 GMT+02:00 nebulon42 <notifications@github.com>:

> alcohol (distinction to beverages unclear)
> [image: alcohol]
> <https://cloud.githubusercontent.com/assets/3531092/7240957/8fa5b1f4-e7b5-11e4-8e7d-9788b4f90a45.png>
>

There is also the tag shop=wine (used 1933 times currently), that might be
more suitable for those places specialized in wine, and your icon seems to
fit perfectly for wine.
Used not only in Europe: http://taginfo.osm.org/tags/shop=wine#map

**Comment by math1985** [comment]
The optician icon is 3d, while the other icons look more 'flat'. I think that was also a design principle. I don't oppose the proposed icon, but it does stand out a bit. I wonder if there would be a way to create a icon without 3d-effect? If not, I'm find with going fo the proposed icon.

**Comment by matkoniecz** [comment]
> There is also the tag shop=wine (used 1933 times currently), that might be
more suitable for those places specialized in wine, and your icon seems to
fit perfectly for wine.

I think that different icons for shop=alcohol and shop=wine would be an overkill, the same may be used for both.

**Comment by nebulon42** [comment]
I also would use the same icon for alcohol and wine shop. But that should be done afterwards if desirable.

Optician is 3D: true, but glasses without sidepieces look not that good e.g. optician-16 vs. optician
I'm also not satisfied with fake perspective here: optician-16

furniture: I'm not sure on the gap width but slightly more inclined towards the larger one. furniture 16 vs. furniture-16 (0.25px less wide)

For jewelry I have nothing else in store as the diamond did not work.

I think that TV might equal public viewing is a bit far fetched, but electronics shop is itself ambiguous so it's quite hard to settle onto a specific depiction.

**Comment by math1985** [comment]
Thanks!

**Pull request merged**
