### PR TITLE
Move shelter icon to SVG

### PR DESCRIPTION
**Pull request by kocio-pl**
Implements part of #1165.

Simple vector replacement of a raster shelter icon:

pd1siftw

### CODE REVIEW

**Comment by pnorman** [comment]
We use `name.size.ext` more than `name-size.ext`, so let's move to that at the same time.

**Comment by kocio-pl** [comment]
IIRC all my icons was made like this - probably looking at some @nebulon42 files, I guess. I was never sure, because we have both formats mixed, but I had more serious problems, so never touched it. If we decide to make them all the same, it probably deserves its own cosmetic patch.

**Comment by kocio-pl** [comment]
Just a cosmetic change so the icon looks better when enlarged (probably not visible on osm-carto):
oixnkvog

**Comment by nebulon42** [comment]
While you're at it, I would suggest removing the rain as it just adds unnecessary clutter IMO.

**Comment by imagico** [comment]
I think the rain is important to indicate the function, otherwise it is just some kind of building.

**Comment by HolgerJeromin** [comment]
I would keep the rain, too.

**Comment by kocio-pl** [comment]
I was thinking about it too and came to the conclusion that otherwise it's not clear what type of building/roof is this. I like it more with rain.

**Comment by pnorman** [comment]
I like the rain, even though the clarity isn't perfect, mis-interpreting it is still likely to get the idea of sheltering across.

**Pull request merged**
