### PR TITLE
Add a Code of Conduct

### PR DESCRIPTION
**Pull request by pnorman**
This adds a code of conduct, based on the Go code of conduct. The goal of a code of conduct is to make explicit inappropriate behavior and mechanisms for dealing with it.

In selecting the Go code of conduct as a starting point, I looked at about 25 options, looking for those which covered the problems we have had and would work with a small scale project, or could be made to work by eliminating content instead of substantial rewrites.[1]

I was initially expecting to do something based on the [Debian code of conduct](https://www.debian.org/code_of_conduct) but I found it less useful than the Values section of the Go document. It is much easier to remove unnecessary sections than expand a document.

## Modifications
Most of the modifications are because the Go process does not [scale down to small projects](https://github.com/golang/proposal/blob/master/design/13073-code-of-conduct.md#open-issues). We have four maintainers and one discussion venue - Github. Go has orders of magnitude more people involved and has IRC channels, mailing lists, mutiple GitHub projects, a subreddit, and in-person events.

## To Do
* [ ] Add links to the document
* [ ] Link to it from CONTRIBUTING.md

## References

[Go CoC proposal rationale](https://github.com/golang/proposal/blob/master/design/13073-code-of-conduct.md#rationale)
[Go CoC blog post/talk](https://blog.golang.org/open-source#TOC_7.)

[1]: Debian, FreeBSD, Go, Joomla, and Puppet met the initial filtering.

### CODE REVIEW

**Comment by jojo4u** [comment]
I read the text and welcome this addition.

**Comment by math1985** [comment]
Looks fine to me. I can merge this or wait for the todo-items to be resolved.

**Comment by pnorman** [comment]
> I can merge this or wait for the todo-items to be resolved.

I'm okay either way, but because this is a policy matter instead of a normal PR I'd like feedback or a go-ahead from @gravitystorm and @matkoniecz

**Comment by gravitystorm** [comment]
I'm broadly in favour of this. I can see two small things:

* To be in line with other OpenStreetMap policies, I favour "indefinite" bans rather than "permanent" bans. 
* We will need to publish email addresses for the maintainers

**Comment by pnorman** [comment]
> To be in line with other OpenStreetMap policies, I favour "indefinite" bans rather than "permanent" bans.

We changed to permanent in the DWG ban policy.

**Comment by pnorman** [comment]
> We will need to publish email addresses for the maintainers

Should we set up an alias? We don't often need to communicate privately, only every other month or so, but it would be nice to just send to one email.

**Pull request merged**
