### PR TITLE
Render marina labels like other landuse labels, including font size

### LINKED ISSUE #1827: Scale marina label according to size of object
http://www.openstreetmap.org/way/149850735#map=16/41.7382/12.2467
selection_001

### PR DESCRIPTION
**Pull request by math1985**
This resolves #1827

### CODE REVIEW

**Comment by math1985** [comment]
Does anybody know why my Travis builds are failing?

**Comment by HolgerJeromin** [comment]
Strange git error. As a repo owner you could try (in travis webinterface) to retry the build.
travis/pr passed. So a final merge will be ok.

**Comment by math1985** [comment]
> As a repo owner you could try (in travis webinterface) to retry the build.

Still the same unfortunately.

**Comment by pnorman** [comment]
You can ignore the push error. Did you perhaps push it to the wrong repo first?

**Comment by HolgerJeromin** [comment]
Travis tries to fetch branch marina-label from this repo and not yours. Most other PR i checked had only the PR check and not the push check.
Your #1907 had the same problem. 
Probably safe to ignore, but still strange. you could report on https://github.com/travis-ci/travis-ci

**Comment by math1985** [comment]
> Did you perhaps push it to the wrong repo first?

Yes I think that's the problem, something went wrong with my push. Thanks for checking.

**Pull request merged**
