### PR TITLE
move toilets icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165, second try after #1178.
Icon based on input of https://github.com/gravitystorm/openstreetmap-carto/pull/1178#issuecomment-74868529 by @daganzdaanda

Please note that the symbol is now smaller (16px instead of 20px).

before
toilets_before

after
toilets_after

### CODE REVIEW

**Comment by mkoniecz** [comment]
My initial impression: recognizable, nice that it is smaller. Recognizable also by the first available tester.

**Comment by kocio-pl** [comment]
Great: +1.

**Comment by mboeringa** [comment]
+1

**Comment by polarbearing** [comment]
cool, very recognisable. No confusion with flowers anymore.

**Comment by daganzdaanda** [comment]
Yep, that looks very good!

**Comment by mkoniecz** [comment]
Thanks!

**Comment by nebulon42** [comment]
Great, that toilets are in. :)

**Pull request merged**
