### PR TITLE
Adding shop=sports icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1530.

New icon alone and in comparison with shop=clothes:
sports-alone
sports-clothes

### CODE REVIEW

**Comment by RobJN** [comment]
Doesn't say "sport" to me - still says clothes. Why not try a ball or similar.

**Comment by matkoniecz** [comment]
For me it is good icon for shop=sport_clothes, not shop=sport.

**Comment by kocio-pl** [comment]
Another idea:
2) sports-14-13

**Comment by kocio-pl** [comment]
@RobJN Ball was hard to be drawn in such a small space, but I also don't like to use attributes of any kind of sport because I think we may start adding icons for different sport objects. You can read more about problems with creating right sport icon [in the corresponding issue](https://github.com/gravitystorm/openstreetmap-carto/issues/1530).

**Comment by mboeringa** [comment]
I am fine with the original "cloth" type proposal with shorts. Shorts are quite strongly associated with "sport". The second icon has a conflict with the archaeological site icon, and is less signifying.

> For me it is good icon for shop=sport_clothes, not shop=sport.

What's the supposed difference? I doubt people could differentiate, all shops related to sport, except maybe those specialized ones selling trophies, sell clothes... And the official tag seems **shop=sports** ;) (http://wiki.openstreetmap.org/wiki/Key:shop), shop=sport_clothes is not even listed on the Wiki...

**Comment by kocio-pl** [comment]
@mboeringa It was in fact derived from archaeological site icon and I was thinking about making it even more slim ([like this one](http://www.kajasport.pl/pol_pl_Puchar-T-7090-6213_2.jpg)), but first I wanted to know if this metaphor is acceptable at all. BTW: archaeological icon is amenity-brown, while sports will be shop-violet, so I don't think it could be misleading.

Maybe single item is too hard to use as an icon - we can resort to multiple objects, [as I have already proposed in #1530](https://github.com/gravitystorm/openstreetmap-carto/issues/1530#issuecomment-105257929), but I want to test every possible way to have something more clear.

**Comment by kocio-pl** [comment]
Slimmed down version with more typical foot:
sports-cup-tall

**Comment by math1985** [comment]
Would something like sport-icon work?

**Comment by kocio-pl** [comment]
One of my draft was a football ball, but it was unrecognizable, given the available pixel resolution, so I guess this one would be even worse, because the were patches and there are thin lines.

However I don't like the idea of showing any particular sport discipline as a general symbol, because I foresee they might be needed in the future for different sport facilities (like pitches for example) and strongly prefer something neutral in this regard. It would be better to have one piece like this one, but if not, the collection of different symbols is acceptable for me (just less clean).

**Comment by kocio-pl** [comment]
I have just checked that leisure=sports_centre has no icon, so I'd like to reserve collection of symbols for it, because that will encourage people to tag it more precise (with sport=*).

**Comment by mboeringa** [comment]
> Slimmed down version with more typical foot:

If you want to stick with the "cup" metaphor, that is indeed an improvement. It looks more like a winning cup instead of an ancient amphora, and I think it now has enough distinction combined with the different colour.

**Comment by kocio-pl** [comment]
Yes, I think it's decent enough now and I like it this way.

**Comment by matkoniecz** [comment]
The problem is that it is meaning is not obvious - what is problematic enough for me to not merge it but not enough to reject it (as icon is fitting this shop type).

Unfortunately I have no idea for a better icon and cup icon is the best one from already proposed.

**Comment by kocio-pl** [comment]
I have already wrote down all my arguments regarding "obviousness" and why it's overrated and inconsistent (see [here](https://github.com/gravitystorm/openstreetmap-carto/issues/660#issuecomment-135059905) for example), but nobody have even tried to discuss with them (which is a big surprise for me!). I guess it means it's probably just a matter of personal feelings - and I see no way to really discuss them... :no_mouth:

**Comment by imagico** [comment]
> what is problematic enough for me to not merge it but not enough to reject it.

I think it helps to look at the balance in terms of solving problems adding problems. Here:

Solved:
* it would solve the problem that a certain type of shop is not indicated with a specific symbol and thereby adds useful semantic information to the map.

Added:
* it adds an additional type of icon making the map as a whole more difficult to read.
* it adds ambiguity and confusion by use of a symbol that is no clearly associated by most people with the type of feature it illustrates (people don't go to a sports shop to buy cups, at least not AFAIK).

Which weights more is a matter of opinion of course.

**Comment by mrwojo** [comment]
The icon looks specifically like [shop=trophy](http://wiki.openstreetmap.org/wiki/Tag:shop%3Dtrophy). (That tag is underrepresented in OSM. There's far more than 48 of those in the real world.)

**Comment by kocio-pl** [comment]
@imagico I would describe it in a different way, with more specific gains than just one big "more informations" on the positive side. For me it involves wider context  (like "makes high zoom levels more usable"), because I also care for consistency (what about other equally not clear icons/lines/patterns we already have - should we remove vineyard pattern or any road colors, because they are not clear just by looking at them?) and the relations with the rest of ecosystem (they're very popular, so it's probably important for the people to see them different than a standard shop). But you're right - in the end kind of +/- list might help when in doubt.

There's also multiple-objects version available. I just like it less and I think it could be used for something different, but it's still not being used and those items are what you can really see in such a shop.

@mrwojo There are basket shops, which would be more relevant for current "convenience" icon, yet I think the look is much less important factor than popularity - and lack of better alternatives probably. Which is exactly the same as in this case (trophy shops are less popular than general sports shops anyway).

**Comment by kocio-pl** [comment]
Interesting example from MapQuest Open: [shop=sports+sport=skying](http://www.openstreetmap.org/node/2182480589#map=13/52.2392/20.9746&layers=Q) is visible from z=13 and before I have checked it, I thought it's a grit bin. However under the closer inspection it looks like a side effect of trying to show [snow sports pitch](http://www.openstreetmap.org/way/284300930) without checking if it's a pitch at all.

**Comment by math1985** [comment]
Unfortunately I don't think the current symbol is recognizable enough - test person also thinks it sells trophies rather than sport articles.

If anybody has a good idea, please let us know!

**Pull request closed without merging**
