### PR TITLE
change cinema icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 and moves cinema icon to SVG.
Icon is here: [nebulon42/osmic/cinema-16.svg](https://github.com/nebulon42/osmic/blob/master/amenity/cinema-16.svg)

http://www.openstreetmap.org/#map=18/48.21658/16.36108
before
cinema_before

after
cinema_after

### CODE REVIEW

**Comment by math1985** [comment]
The icon is recognizable according to my test with sample size 1.

**Comment by dieterdreist** [comment]
2015-01-08 23:50 GMT+01:00 math1985 <notifications@github.com>:

> The icon is recognizable according to my test with sample size 1.
>


while the current icon for cinemas is not ideal, the proposed one isn't
recognizable either IMHO
https://github.com/nebulon42/openstreetmap-carto/blob/svg-cinema/symbols/cinema.16.svg

**Comment by althio** [comment]
Sorry I don't buy this one. Without the prior knowledge that we are on
cinema icon I don't think I would recognise it.
The most problematic part is the top white and black stripes.
The bottom part could also be mistaken for a box with a hole.
I will have a look around for other ideas of icons too.

**Comment by kocio-pl** [comment]
Maybe someting like the screen (rectangle, probably with rounded corners) with 3 simple people silhouettes on the bottom edge?

**Comment by althio** [comment]
These are not definite icon proposals but food for thought.

camera image image image image

film image image image image

roll image image


clap image image

ticket image image


> Maybe someting like the screen (rectangle, probably with rounded corners) with 3 simple people silhouettes on the bottom edge?

I find this, almost the same idea with seatings but no people. It is not perfect at small scale but I like your general idea.
screen icon_37-48 icon_37-20

**Comment by HolgerJeromin** [comment]
IMO ticket and roll does not work in the small size.
The icon requirements from nebulon42 are against perspective. I think screen does not work, as the perspective is not easy to detect.
Perhaps the icon film could be reworked to have one full and two half frames like the old icon.

**Comment by althio** [comment]
> IMO ticket and roll does not work in the small size.

roll: EDITED to add a more representative size for small scale, previous was too small.

> The icon requirements from nebulon42 are against perspective. I think screen does not work, as the perspective is not easy to detect.

If you follow @kocio-pl suggestion (screen with 3 simple people silhouettes on the bottom edge) you may be able to squash eveything without perspective effect. Sorry I didn't draw every ~~icon proposal~~ icon idea myself with perfect design, but please try to imagine what every icon could be with some improvements.

Please do not hesitate to share also what you like.

Among these ideas (meaning these kind of icons possibly redrawed with some improvements), my personal ranking would be:
camera, roll, screen, film, clap, ticket.

**Comment by mkoniecz** [comment]
At least for me something similar to old icon would be more recognizable - in list made by @althio film icons are working - image?

For me this icon is not really working. I also asked three people, with following results:
- cinema
- factory
- obviously train station, it is a steam train

**Comment by daganzdaanda** [comment]
I like the second of  the camera icons that @althio found: camera
It's flat, almost square, and pretty unique. It may benefit from aligning points to the pixel grid.

**Comment by mboeringa** [comment]
I think the "screen" looks way to much like a symbol for a computer screen with keyboard. Ticket and clap are not doing to well either in small size in terms of signifying what they represent.

I am kind of neutral to the remaining three, that do carry the clear significance to film (although isn't it funny how we still use the symbols of a gone by era for some symobilizations in the present - think of road signs with a steam locomotive! ... maybe a DSLR would be a more suitable symbol ;-), a lot of movies and commercials are shot with it nowadays)

> Perhaps the icon film could be reworked to have one full and two half frames like the old icon.

I agree this added something to the old version, suggesting the continuity of the film roll.

**Comment by nebulon42** [comment]
It would be possible to use the film as icon:
bildschirmfoto vom 2015-01-11 14 25 17

I don't like the large "holes" in it, but obviously transparency works too:
bildschirmfoto vom 2015-01-11 15 52 54

**Comment by mboeringa** [comment]
> It would be possible to use the film as icon:

I think it looks quite good, it certainly is an option this one.

**Comment by mkoniecz** [comment]
> It would be possible to use the film as icon:

Both work well for me.

**Comment by math1985** [comment]
If you update this with this with the film icon I can merge this.

I think transparency is not a good idea, it would look strange on colourful backgrounds.

**Comment by nebulon42** [comment]
I have updated the icon (without transparency). However, the transparency would only affect the "holes" so I think it would not look much stranger than with "holes".

**Pull request merged**
