### PR TITLE
Make weir, dam, and lock_gate slightly larger on z>18

### LINKED ISSUE #1403: High-zoom weir rendering
We should probably scale z18 and z19 weir icons up to the width of the river.

z18
image

z19
image

### PR DESCRIPTION
**Pull request by math1985**
This resolves #1403.

### CODE REVIEW

**Comment by math1985** [comment]
This is ready for review.

**Comment by pnorman** [comment]
Merged. I had a hard time finding a suitable weir... most around here are on streams or rivers mapped as an area.

**Comment by math1985** [comment]
> I had a hard time finding a suitable weir..

You could make use of https://github.com/math1985/openstreetmap-test-data together with something like
``
sed -i s/action=\'modify\'\ //g ~/openstreetmap-test-data/rendertest.osm
osm2pgsql -s -d gis -C 512 ~/openstreetmap-test-data/rendertest.osm
``
.

**Comment by pnorman** [comment]
For single feature test data I generally just construct it out of existing data with psql on the command line.

**Comment by pnorman** [comment]
I wonder if we need turning circle like logic for weirs on streams/etc

**Pull request merged**
