### PR TITLE
Render brand=* additionally to name=*

### PR DESCRIPTION
**Pull request by floscher**
This is supposed to solve parts of #698.
I've picked some amenities, for which it makes the most sense to render brand. These are:
* amenity=fuel (Shell, Esso, Agip, Total, BP, …)
* amenity=bank (Sparkasse, Volksbank, Commerzbank, …)
* amenity=fast_food (Mc Donald's, Burger King, Subway, …)
* shop=supermarket (Aldi, Lidl, Rewe, Coop, …)
* shop=department_store (Ikea, Woolworth, Galeria Kaufhof, …)

Depending on what tags are present (only name, only brand or both), one of the following variants is rendered:
* [name]
* [brand]
* [name] + "\n(" + [brand] + ")"

Currently this will result in many amenities (especially petrol stations) showing up as "Brand xy\n(Brand xy)", because many of them have the same value for the brand- and name-key. I even had difficulties to find a petrol station, that has different values for name and brand. But this is in my eyes a tagging-mistake (tagging for the renderer), which will hopefully be corrected as soon as brand renders in this style (see also [the comment by Rovastar to issue #698](https://github.com/gravitystorm/openstreetmap-carto/issues/698#issuecomment-49944999)).

### CODE REVIEW

**Comment by pnorman** [comment]
Stale PR, and the issue related to it is closed.

**Comment by nighto** [comment]
In my humble opinion (and I know this is polemic), the tag name=* for those POIs is much more official_name=* then name=*. But this is subject to the tagging list, not here, so feel free to ignore.

**Comment by BalooUriza** [comment]
On Thu, Sep 17, 2015 at 10:44 AM, Arlindo Pereira <notifications@github.com>
wrote:

> In my humble opinion (and I know this is polemic), the tag name=* for
> those POIs is much more official_name=* then name=*. But this is subject to
> the tagging list, not here, so feel free to ignore.
>
Gas stations and convenience stores that have franchises tend to be
problematic for this.  The sign out front often has something like
"Cherokee", "Phillips 66" or "Conoco" but the name on the front of the
station/store/restaurant there might be something like "Pawnee Nation
Casino", "Batman's Good Food" or "Three Flags Drive-Thru Tobacco".

**Comment by Stemby** [comment]
Please, could you look at [this](http://wiki.openstreetmap.org/wiki/Talk:Tag:amenity%3Dbank#name.3D.2A_and_brand.3D.2A) discussion?

Thank you!

**Pull request closed without merging**
