### PR TITLE
concat name with ele

### PR DESCRIPTION
**Pull request by nebulon42**
Attempts to solve #1104. Name and ele are concatenated (solution by @mkoniecz), if ele is null only name is displayed and vice versa.
Drawbacks: we lose the ability to style ele differently from name and to render ele earlier or later than name.

http://www.openstreetmap.org/#map=15/46.9552/13.3305
before
ele_before

after
ele_after

### CODE REVIEW

**Comment by math1985** [comment]
I think this also renders ele for objects that were previously not rendered with ele, right? Is that desirable?

**Comment by nebulon42** [comment]
Ah, yes, didn't think about that, sorry. Probably not.

**Comment by nebulon42** [comment]
This update should ensure that ele is only rendered for peak, volcano, saddle, alpine_hut and shelter (as before).

**Comment by math1985** [comment]
Thanks!

**Pull request merged**
