### PR TITLE
Change scrub color and pattern

### LINKED ISSUE #2098: Stream is barely visible on scrub
Stream is barely visible on scrub.

The waterway=stream is barely visible on the natural=scrub, especially when combined with intermittent=yes. Screenshot from http://www.openstreetmap.org/#map=19/5.34678/-3.98195
screenshot

Not sure what would be a good solution for this, if any…

### PR DESCRIPTION
**Pull request by jeisenbe**
**Fixes #2098** - "[Intermittent] Stream is Barely Visible on Scrub"
Related to #2069, However does not yet change the color of golf courses, which use the same color as current scrub but without a pattern. This should be addressed soon, perhaps by changing golf to use the leisure color.

**Changes proposed in this pull request:**
_The current scrub color is:       #b5e3b5 = Lch(86,29,143), hsla(120,45%,80%,1)_
1. Change scrub color to:         #c8d7ab = Lch(84,24,122), hsla(67,41%,78%,1)

_The current scrub pattern uses:   #8ece8f = Lch(77,41,143)
2. Change scrub pattern to use:    #b0be93 = Lch(75,24,122)

3. Update scrub.md so that it links to the new pattern from http://www.imagico.de/map/jsdotpattern.php

Test rendering with links to the example places:
http://www.openstreetmap.org/#map=15/20.7490/-156.8960
**Hawaii z15**
Before
hawaii-z15-before
After
hawaii-z15-scrub-only

**Hawaii z16** http://www.openstreetmap.org/#map=16/20.7490/-156.8960
Before
hawaii-z16-before
After
hawaii-z16-scrub-only

Test area z15
Before
test1-before=
After
test-scrub-only-z15

### CODE REVIEW

**Comment by jeisenbe** [comment]
Here are some lower zoom levels to compare with farmland and heath:

**Goodwick, Wales** 
http://www.openstreetmap.org/#map=13/52.0101/-4.9899
z12 Before
goodwick-z12-master
After
goodwick-z12-scrub-only

z13 Before
goodwick-z13-master
After
z13-goodwick-scrub-only

z14 Before
goodwick-z14-master
After
z14-goodwick-scrub-only


**Graig Isaf, Wales**
With bog and marsh: http://www.openstreetmap.org/#map=7/52.81443/-4.01972
Before
bog-marsh-master
After
bog-marsh-scrub-only

**Comment by jeisenbe** [comment]
Some areas with detailed landcover mapping in the Azores Islands, including scrub, forest, heath, grass, marsh, intermittent lake and intermittent streams.

**Caldeira, Azores Islands**
http://www.openstreetmap.org/#map=16/38.5847/-28.7164
Before
caldeira-master
After 
caldeira-scrub-only-

**Estrada da Caldeira, Azores**
http://www.openstreetmap.org/#map=17/38.57280/-28.69047
Before
estrada-master
After
estrada-scrub-only

**Sicosta, Azores**
Villages with allotments, farmyards, orchards. 
http://www.openstreetmap.org/#map=17/38.55036/-28.65888
Before
sicosta-master
After
sicosta-scrub-only

**Comment by Tomasz-W** [comment]
@jeisenbe The original proposition was c8d**6**ab so why it has changed to c8d**7**ab here?

PS. Please do not put certain colour values in PRs names as we often change them during PR discussion and it might be confusing.

**Comment by kocio-pl** [comment]
Yes, the names of tickets should be short and succint in general, the rest should be inside.

**Comment by jeisenbe** [comment]
It was always #c8d7ab in the test images that I was showing on issue #2098, but perhaps I mistyped the code in the comments? #c8d7ab is #d1e0b4 is 3% darker, by Lch. 

There is no perceptible difference between c8d6ab and c8d7ab. 
The chroma or saturation is only 1 or 2% different, by hsla or Lch, otherwise they are identical:

c8d6ab-vs-c8d7ab

Sorry about the title, I'll shorten it.

**Comment by kocio-pl** [comment]
I will certainly need to adjust to this new brownish-green rendering of scrub, but it is still green and it really solves the water rendering problem. We have some more green areas changes ahead and let's see how they play together.

Thanks for the coding work and analysis for all the people involved in this!

**Comment by Adamant36** [comment]
@jeisenbe, I happened to notice that the new scrub pattern disappears one zoom level lower then forest. Could it perhaps be tweaked so they both disappear at the same level? (I can't remember if it did the same thing before the change or not, but I thought it might be due to the new density or something).

**Comment by jeisenbe** [comment]
This is the same as before; the forest/wood pattern already appeared sooner

**Comment by Adamant36** [comment]
Bummer. Maybe I'll do an issue to see if there's any will to change it then.

**Comment by jeisenbe** [comment]
We just decided to render the allotments pattern at z13, so it could make
sense to start showing the scrub patterns, orchards, vineyard and wetlands
at z13.

But it may not work with patterns that are much wider-spaced, like scrub.
The allotments pattern is only 4x4 pixels, while scrub needs about 20x20
pixels to repeat IIRC

**Comment by Adamant36** [comment]
I say if it works we do it. I don't see why it wouldn't on larger areas.

**Comment by Tomasz-W** [comment]
I was going to notice this problem. It can be annoying with large scrub areas like here:

https://www.openstreetmap.org//#map=13/34.2229/-117.8636

please fix it.

**Comment by Adamant36** [comment]
Wow, that's a huge scrub area. There's no reason the pattern shouldn't still display at z13 with a place like that.

**Comment by Tomasz-W** [comment]
@jeisenbe https://github.com/gravitystorm/openstreetmap-carto/issues/3593

**Pull request merged**
