### PR TITLE
show ref for aeroway=gate and ele for peaks/volcano/saddle/alpine_hut without names

### LINKED ISSUE #1797: Labels for [aeroway=gate; ref=*] and [natural=peak, ele=4] are not rendered since 2.31
It is rendered for ```[aeroway=gate; ref=*; name=*]``` due to ```AND name IS NOT NULL``` clause in SQL query for text-point and text-poly
aeroway gate ref 4 node v2 30 0 - v2 31 0 200px
.

### PR DESCRIPTION
**Pull request by matkoniecz**
fixes #1797

tourism alpine_hut ele 4 node master - peak 200px
natural volcano ele 4 node master - peak 200px
natural saddle ele 4 node master - peak 200px
natural peak ele 4 node master - peak 200px
aeroway gate ref 4 node master - peak 200px

### CODE REVIEW

**Comment by imagico** [comment]
:-1: for showing ele on natural=volcano - see #1790

**Comment by matkoniecz** [comment]
> :-1: for showing ele on natural=volcano - see #1790

Elevation is already rendered for volcanoes with names, there is .mss code for showing ele, it merely fixes mismatch between cartocss and SQL.

**Comment by imagico** [comment]
I know, i would still prefer fixing this for volcanoes by not rendering ele at all.

**Comment by jojo4u** [comment]
I agree that this mismatch should be fixed indepedently of the decission to render ele.

**Comment by pnorman** [comment]
not rendering ele at all for volcanos or other changes to the volcano rendering can be raised in other issues, but this fixes a bug.

Do we need to change any indexes as a result of this?

**Comment by matkoniecz** [comment]
```
polygon:
  # The polygon table is by far the largest, and generally the slowest
  name:
where: name IS NOT NULL
```

may be affected.

**Pull request merged**
