### PR TITLE
Update some icons

### LINKED ISSUE #3349: waterway=stream with location=underground should render differently
At the moment streams render the same no matter if their location is set to be underground. While it is useful to know the flow of water it would mislead you on where the water is accessible.

On topographic maps they make the distinction with a dashed/dotted line. I believe mimicking this with a similar style would be sufficient in allowing map readers to recognize where it's an above ground stream and where it is underground and inaccessible.

### LINKED ISSUE #3449: Update some icons
There are disussions about updating some of icons, but as they are going on in closed tickets. I'm opening new one for doing it properly.

* `amenity=restaurant`(https://github.com/gravitystorm/openstreetmap-carto/pull/3430):
 (fork + spoon)
amenity restaurant (fork + knife)

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amenity/restaurant.svg)

* `man=made=storage_tank/ silo`(https://github.com/gravitystorm/openstreetmap-carto/issues/588):

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/man_made/storage_tank.svg)

* `amenity=arts_centre` (https://github.com/gravitystorm/openstreetmap-carto/pull/3401):
 (palette + note v1)
 (palette + note v2)
amenity arts_centre4 (note + paint brush)

(current one: https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/shop/art.svg)

### PR DESCRIPTION
**Pull request by Adamant36**
Closes #3449 - This PR updates some icons to better looking ones. The arts centre icon gets a musical note, the spoon and fork trade places in the restaurant icon, and the storage tank icon gets thinner.

arts centre 
https://www.openstreetmap.org/#map=19/41.40658/-75.65854
arts centre

restaurant 
https://www.openstreetmap.org/#map=19/41.40792/-75.66059
restaurant

storage tank
https://www.openstreetmap.org/#map=19/41.40650/-75.66848
storage tank

@kocio-pl, do you happen to know why it would reference your PR in the first commit when I wasn't involved in it and it had nothing to do with this PR?

### CODE REVIEW

**Comment by kocio-pl** [comment]
No, I don't know why.

**Comment by Adamant36** [comment]
Hhhhmmm, weird.

**Comment by Adamant36** [comment]
New slipway icon
https://www.openstreetmap.org/#map=19/41.25098/-75.88442
slipway

@kocio-pl, it should be good to go now.

**Comment by Tomasz-W** [comment]
@Adamant36 Another small thing to fix: I just found that `leisure=amusement_arcade` icon is in generic 'symbols' folder instead of 'leisure' subfolder https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/amusement_arcade.svg

**Comment by kocio-pl** [comment]
@Tomasz-W Maybe you would like to learn some basics about git? It would allow you to make at least such trivial fixes. When dealing with software projects, some level of technical skills makes people more effective as community members in general. I really recommend this.

**Comment by Adamant36** [comment]
@Tomasz-W, I moved it. 
(just to show it works)
arcade

I plan to move the other icons at some point soon largely based on the feedback from the other similar PR. That aside, I agree with @kocio-pl that it might be worth your time to learn some basics of the coding and how things work. Then you could test your own icons etc. Its really not that difficult if your only dealing with basic things like icons and if you have any problems its not we can't help you solve them.

**Comment by Tomasz-W** [comment]
@Adamant36 Are you willing to include new slipway icon here?

Gist link: https://gist.github.com/Tomasz-W/c453ba8bc0ab15404d40098a947879e2

**Comment by Adamant36** [comment]
@Tomasz-W, its already there. I tested it above. Unless its different somehow, but it looks the same.

**Comment by Tomasz-W** [comment]
@Adamant36 Sorry, too many issues in my head, I got lost for a moment 😄

**Comment by Adamant36** [comment]
No worries. Its been really busy around here lately.

**Pull request merged**
