### PR TITLE
sort linestring_values in lua

### PR DESCRIPTION
**Pull request by HolgerJeromin**
Sorted list could perhaps prvent something like #3084

### CODE REVIEW

**Comment by kocio-pl** [comment]
Is it really useful patch? We could merge it then before release, but this is more coding related than I can evaluate - ping @matthijsmelissen @pnorman @matkoniecz.

**Comment by matthijsmelissen** [comment]
@kocio-pl Do you look at the change made in #3100? Really not that hard to understand :) 

The natural definition occured twice, the second overwrote the first.

**Comment by kocio-pl** [comment]
Thanks! Yes, I did :smile: , I just didn't know how is it useful from a practical point of view.

**Comment by matthijsmelissen** [comment]
The point is simply, if we keep the right order it’s easiier to spot duplicates :)

**Pull request merged**
