### PR TITLE
Clean up some svg images

### PR DESCRIPTION
**Pull request by pitdicker**
When rendering my local area with Mapnik I get a bunch of errors (apparently not fatal). The first bunch:
```
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-style> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-variant> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-weight> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-stretch> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-size> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <font-family> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <text-decoration> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <letter-spacing> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <word-spacing> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <writing-mode> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <direction> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <dominant-baseline> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <baseline-shift> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <text-anchor> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <clip-rule> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <overflow> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <color-interpolation> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <color-interpolation-filters> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <color-rendering> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <image-rendering> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <shape-rendering> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <text-rendering> attribute is not supported"
Mapnik LOG> 2020-09-11 21:09:25: SVG PARSING ERROR:"SVG support error: <enable-background> attribute is not supported"
```

The problem is that the svg files in `symbols/` contain a lot of junk.

For this PR I have cleaned up the 8 most offending svg files, those containg a `style="font-style: …` declaration:

- symbols/amenity/bureau_de_change.svg
- symbols/amenity/public_transport_tickets.svg
- symbols/corners.svg
- symbols/leisure/miniature_golf.svg
- symbols/rect.svg
- symbols/rectdiag.svg
- symbols/shop/marketplace.svg
- symbols/shop/ticket.svg

No icons have changed appearance, but all unnecessary tags, groups, transformations and metadata are removed, and they now make consistent use of `viewBox`.

B.t.w. I would be willing to clean up more/all of svg files.

### CODE REVIEW

**Comment by polarbearing** [comment]
Without having checked the details, I appreciate the cleaning. 
The junk is most likely being caused by the variety of tools used by different icon authors without manual cleaning. 

What is your process, did you clean them manually like in a text editor, or with some tool, that could potentially be integrated/automated in the handling?

**Comment by pitdicker** [comment]
> The junk is most likely being caused by the variety of tools used by different icon authors without manual cleaning.

Yes, plenty of tools that can work on SVG but leave stuff around.

I used Inkscape's ungroup and the transformations sidebar to apply transformations to the individual paths, scour with almost all the options, and looking over the result in a text editor.

With just scour you can already have enough automation to remove metadata and shrink the file size, but it does not understand enough of svg to remove the problematic tags and inline css that caused the warnings here.

**Comment by kocio-pl** [comment]
> B.t.w. I would be willing to clean up more/all of svg files.

Which ones else require cleaning?

**Comment by pitdicker** [comment]
Sorry for the slow reply... 
These are the only svg's that gave me warnings.

Others don't require anything, but about I guess about 50% of their size is metadata and other invisible stuff that can be removed.

I have been looking into svg pattern files and https://github.com/gravitystorm/openstreetmap-carto/issues/2045. With a little smarter script you can generate small and less problematic SVG patterns. Would an AWK script be acceptable? I know little Python, no javascript, and I don't think you'll accept C or Rust ;-).

**Comment by pnorman** [comment]
I'd like to add a CI check on the SVG files that check for elements that don't meet [our style guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines) but the first step is cleaning up what we already have.

So 👍 in principle, but I haven't reviewed these particular changes for time reasons.

**Review by pnorman — APPROVED** [review]

**Pull request merged**
