### PR TITLE
render amenity=doctors

### PR DESCRIPTION
**Pull request by poempelfox**
Symbol is from SJJB icon set (http://www.sjjb.co.uk/mapicons/), license CC-0.
Solves issue #89 .
Tried to make a usable .svg symbol instead of the .png, but failed miserably.
amenity-doctors-rendered

### CODE REVIEW

**Comment by althio** [comment]
@nebulon42 +1
I think I like the bag icon better. Do you have a small version or an example on a map ready?

**Comment by HolgerJeromin** [comment]
@althio http://www.openstreetmap.org/#map=20/50.77013/6.04000&layers=HN

**Comment by math1985** [comment]
@nebulon42 Where can I find the Nori icon set?

**Comment by nebulon42** [comment]
@math1985 The icon is here: https://github.com/nebulon42/osmic/blob/master/health/doctor-16.svg
Shall I make another PR for it?

**Comment by math1985** [comment]
> Shall I make another PR for it?

Please!

**Comment by daganzdaanda** [comment]
I do like the bag, but I think the Aesculap thing is not impossible. Here's a try:
proposal_doctors
I think the snake doesn't need to have so many turns. This is probably the minimum. And it should not look like a $, so I made the first turn wider. The eye could be left out, but I like it ;)
Wikipedia tells me unicode has a codepoint u+2695 ⚕ STAFF OF AESCULAPIUS... maybe there's a good solution in a font somewhere.

**Comment by nebulon42** [comment]
I agree that the snake might be improved, but it is still a fairly complex icon for such small sizes.

**Comment by althio** [comment]
That is a very good attempt with the staff and snake, but I still think
that the bag with cross is easier to recognise AND easier to associate with
doctors universally without any required prior knowledge.

**Comment by kocio-pl** [comment]
I also vote for bag.

**Comment by dieterdreist** [comment]
2015-01-11 14:00 GMT+01:00 althio <notifications@github.com>:

> That is a very good attempt with the staff and snake, but I still think
> that the bag with cross is easier to recognise AND easier to associate with
> doctors universally without any required prior knowledge.
>




AFAIK the cross is only used in regions with christian influence...

**Comment by math1985** [comment]
The bag seems more popular, but thanks anyway @poempelfox!

Resolved by #1201.

**Pull request closed without merging**
