### PR TITLE
Glacier labels color and thresholds

### LINKED ISSUE #1016: Glacier label colour
After #941 

from https://github.com/gravitystorm/openstreetmap-carto/pull/941#issuecomment-56933642

"The glacier label color is somewhat greenish making it probably hard to distinguish from other greenish labels frequently around in areas of temperate region glaciers as well as water linework which is also similar in color. Color should IMO be closer to the glacier outline color - the previously used magenta tint was very good to read and distinguish. Correct me if i am wrong but i suppose darken() is performed in sRGB or sRGB derived hsl and not in perceptual color space which might account for color distortions."

This problem is happening also on zoom levels not affected by the national park overlay.

IMHO previous label style was clearly a better one in this case.

### PR DESCRIPTION
**Pull request by imagico**
fixes #1016

* changes the glacier label color to `mix(darken(@glacier, 40%), darken(@glacier-line, 30%), 50%)`.
* ~~changes the airport label color and icon to a violet tone to be better distinguishable from both glacier and waterbody labels.~~
* changes the size threshold for showing labels to be closer to as it was before.  There are still significantly less labels at z=10 but better than before (where at z=10 almost no mountain glaciers showed up).
* adds an additional rule for showing very large glaciers (>10000 pixel) already at z=8.  Due to the size distribution of actual glaciers this only affects larger icefields and icecaps, only a handful of them outside the polar circles (a few in Iceland, two in Norway, two in Patagonia and a few mostly unnamed ones in Alaska/Canada).  

glacier labels color
glacier labels at z=10

### CODE REVIEW

**Comment by mkoniecz** [comment]
@Imagico - can you consider making a separate request for label color? I would merge it (there is no opposition to it, IMHO it is clearly better).

I am unsure about zoom levels - I am not opposing but I do not feel confident enough to merge this change.

**Comment by imagico** [comment]
For the size limits this change is a compromise between the original glacier labeling and how it is handled after the general labeling change in #941.  I respect the opinion from @math1985 that he prefers the version with less labels but no arguments in that direction have been made so far.

With the current labeling settings labels formally start at z=10 but effectively no glacier labels are shown in the Alps, Caucasus, the contiguous US and the Andes north of Patagonia and only a handful for the Himalayas (mostly where mapping is not very detailed) at that scale.

And I do not remember any complaints about too many glacier labels before - and there were significantly more than even with this change.

If there are arguments for less labels i would be eager to hear, otherwise i think this change in thresholds is an improvement and would like to see it in the map.

**Comment by math1985** [comment]
I have merged this as is. As far as I'm concerned we can consider fine-tuning later. Thanks @imagico!

**Comment by imagico** [comment]
Thanks - and as said, if there are situations were less labels would be better i would be happy to look at them.

**Pull request merged**
