### PR TITLE
Add 14px storage tank icon used by iD

### LINKED ISSUE #3927: Reuse iD editor storage tank icon
> If you think that something should be changed - please open a new issue.

_Originally posted by @matkoniecz in https://github.com/gravitystorm/openstreetmap-carto/issues/588#issuecomment-539653830_

The current tall storage tank icon looks like a gasoline pump.

It would just be safer to use the storage tank icon from the iD editor. Thanks.

### PR DESCRIPTION
**Pull request by bhousel**
closes #3927
replaces #3928

### CODE REVIEW

**Comment by jeisenbe** [comment]
Rendering examples:

z18-storage-tanks-buildings-compare

z19-silos-compare

**Comment by kocio-pl** [comment]
Maybe making the gap a bit bigger would make the shape more obvious?

**Comment by meased** [comment]
1. I disagree that the current icon looks like a gas pump.
2. The new icon is not pixel aligned.
3. The new icon is just a cylinder and could be mistaken for a lot more objects than the current icon (it reminds me of a hard drive).
4. Is an icon even needed for these features?
    - Whether it is "proper" or not, there is clearly a user expectation that these features will render like buildings. Why is that not enough?

**Comment by jeisenbe** [comment]
Ok, now there's @jidanni and @adamant36 in favor but some specific critical comments by @kocio-pl and @meased about lack of pixel-alignment and the size of the gap between the top and the side. 

@bhousel - do you have time and interest in trying to address those concerns?

There have been a couple of comments about rendering this feature with building fill - this could be done in another PR, though it would only work for those mapped as areas (as with buildings).

**Comment by bhousel** [comment]
> @bhousel - do you have time and interest in trying to address those concerns?

Not really, sorry.  I just sent the thing originally because I had the program open and could throw something together in a few minutes.

As a maintainer you should just pick something. It probably doesn't really matter which icon you use.  They'll all look pretty janky until this project is generating retina tiles, and you can't please everyone who shows up to your GitHub to complain.  Arguing over which storage tank icon is best is not a great use of anyone's time.

**Comment by jeisenbe** [comment]
This PR would need to rebased now for v5.0.0, so I am going to close it as stale.

**Pull request closed without merging**
