### PR TITLE
move embassy icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements #1165 by changing the icon for `amenity=embassy` to SVG.
Icon: [nebulon42/osmic/embassy-16.svg](https://github.com/nebulon42/osmic/blob/master/amenity/embassy-16.svg)

before
embassy_before

after
embassy_after

### CODE REVIEW

**Comment by mkoniecz** [comment]
Please, test it with tall name like "ÉÉÉÉÉÉ ÉÉÉÉÉÉ ÉÉÉÉÉÉ" (text-dy is too low).

**Comment by nebulon42** [comment]
The text would have worked, but I nevertheless increased `text-dy` by 1.

**Comment by mkoniecz** [comment]
Weird, according to my test it was failing.

**Comment by nebulon42** [comment]
With your tool? I changed the text to ÈÈÈÈÈ, but I don't know, which value do you suggest?

z19
embassy_text

**Comment by pnorman** [comment]
I'd give it one more pixel over what you have in the image - because the text isn't uniformly tall, it looks to not be hitting the tallest point.

**Comment by nebulon42** [comment]
Right, I did that already, but didn't update the preview.

**Comment by nebulon42** [comment]
I have updated the icon to a lighter version that looks better and is more similar to the old version.

**Comment by math1985** [comment]
The latest preview does not match with the icon in the repository. Which one is the correct version?

**Comment by nebulon42** [comment]
> Which one is the correct version?

The one in the inital post should match with the repository and the file in this PR.

**Comment by math1985** [comment]
The preview in https://github.com/gravitystorm/openstreetmap-carto/pull/1235#issuecomment-70380791 is different from the file in the repository though. Can I ignore this preview?

**Comment by nebulon42** [comment]
Yes, this was the first version, which has been superseded. The comment was intended to show to @mkoniecz that I tested with this particular name.

I probably should not update the first comment anymore to avoid confusion about updates.

**Comment by math1985** [comment]
> The comment was intended to show to @mkoniecz that I tested with this particular name.

I actually like the updated first post. In any case I merged this now.

**Comment by mkoniecz** [comment]
> I actually like the updated first post.

I also prefer first post to contain current state (or at least - link to post with a current state), not what was initially submitted.

**Pull request merged**
