### PR TITLE
Fix #996 by adding intermittent water bodies support

### LINKED ISSUE #996: Special rendering for intermittent water areas
@imagico proposed in #805 to render specially intermittent water areas.

intermittent tag is in the dabase, seasonal needs style file change.

quote from https://github.com/gravitystorm/openstreetmap-carto/issues/805#issuecomment-50901241

This should be extended to water areas, for example the current appearance of Australia is quite irritating:

http://www.openstreetmap.org/#map=6/-24.377/129.749

since nearly all of the water areas you can see there are intermittent.

Both intermittent=yes and seasonal=\* should be considered.

Current use according to taginfo:
- waterway=\* + intermittent=yes: 672000 times (most of this is NHD imports)
- waterway=\* + seasonal=*: 1200 times
- natural=water + intermittent=yes: 45000 times
- natural=water + seasonal=*: <1000 times

### PR DESCRIPTION
**Pull request by Penegal**
This adds support for rendering intermittent water bodies, hence it fixes #996.

Rendering examples:
https://www.openstreetmap.org/way/391188151
image
https://www.openstreetmap.org/way/394053640
image
https://www.openstreetmap.org/way/466317471
image
https://www.openstreetmap.org/way/507366289
image

### CODE REVIEW

**Comment by kocio-pl** [comment]
Here are the keywords for automatically closing tickets:

https://help.github.com/articles/closing-issues-using-keywords/

Could you post some images with the rendering of the actual code from this PR?

**Comment by Penegal** [comment]
@kocio-pl: Edited.

**Comment by kocio-pl** [comment]
Thanks! The links to rendered locations are useful for testing - could you post them too?

It looks great and intuitive for me, some more examples:

[Intermittent pond in the forest near the river](https://www.openstreetmap.org/way/497662523#map=19/52.16843/21.13375)
al3d54wf

[Intermittent water in the small park ](https://www.openstreetmap.org/way/542298114#map=19/52.12824/21.05654)
zais5eo3

[Seasonal pond with a name in the park](https://www.openstreetmap.org/way/98345824#map=18/52.16753/21.02205)
xhwxnnwd

**Comment by Penegal** [comment]
Edited.

**Comment by kocio-pl** [comment]
South Australia example on z6 - I don't know if the tagging is complete, but at least some of the biggest lakes there are clearly intermittent:
xictib09

Whole continent view on z5 (click to see the full size):
v7qapvzy

**Comment by sommerluk** [comment]
Given that the pattern is quite simple and maybe pixel-aligned, is there a chance to have this as SVG pattern avoiding #2750 problems?

**Comment by kocio-pl** [comment]
Currently we're not sure why such problems exist at all and how to fix/avoid them with vector patterns (looks to me like a Mapnik issue), so raster version is the only safe bet for now.

**Comment by Penegal** [comment]
What does miss for this to be merged? Approval? Testing?

**Comment by kocio-pl** [comment]
I just wait one day more to gave a chance for anybody to post additional comments/improvements, because it's now more visible than just an old issue, but that's all.

**Comment by Penegal** [comment]
OK, just wanted to be sure.

**Comment by kocio-pl** [comment]
Thanks for the work! I like the result, especially because it tunes a look on low zoom (probably not only in Australia).

**Comment by turnsole80** [comment]
I've updated the tagging on some of the lakes in Australia, so it should look even better now :)

**Comment by kocio-pl** [comment]
Thanks a lot! I've been thinking lately about asking the Aussie community about it.

There can be similar examples across the globe, if anybody knows one, please tag them too.

**Comment by kocio-pl** [comment]
Another interesting thing to test: #1167.

**Comment by Gazer75** [comment]
There is a small issue with this. It will not display over a dam polygon.
https://www.openstreetmap.org/relation/8248594

**Comment by Gazer75** [comment]
Why not? When the doors are open the water flows over in that area.

**Comment by kocio-pl** [comment]
The main reason is that there are so much combinations with layers and they are expensive (in terms of performance and maintenance), that we must have a strong reasons to add/split more of them. And it would mean that intermittent water should have its own layer. And that would be always above the whole class of things, not only dams...

We would need some generic solution like global render layers - that would mean that layer=1 is always above layer=-1. Yet we have only per-layer rendering priority (road with layer=1 over road with layer=-1) not the global one (building with layer=1 over road with layer=-1). I'm not even sure if this is doable with our framework, but even if it is, it would be huge code rewrite probably.

For a notable example of layering problem without global rendering layers see https://github.com/gravitystorm/openstreetmap-carto/issues/688#issuecomment-232675998.

**Pull request merged**
