### PR TITLE
Adding shop=tyres rendering

### PR DESCRIPTION
**Pull request by kocio-pl**
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2619

shop=tyres is the last of very popular shop types - above 10k uses - which have no special icon (the other one is shop=boutique, but [it was rejected 2 years ago](https://github.com/gravitystorm/openstreetmap-carto/pull/1719)). This icon was designed by @MaestroGlanz and I find it good enough for this style:

slrr2van

### CODE REVIEW

**Comment by kocio-pl** [comment]
Any comments/reviews about it?

**Comment by daganzdaanda** [comment]
I cleaned the icon a bit and made it 12px tall to leave 1 px margin in a 14 px icon. Was that the way the other icons were sized?? It seems very tiny... https://gist.github.com/daganzdaanda/d0e644e0fa1844597f800d0aedddc372

**Comment by pnorman** [comment]
It kind of looks like there's a perspective to the icon, although that could also be a tyre on the left and a rim on the right.

**Comment by kocio-pl** [comment]
@daganzdaanda No, most of the icons are using 14px matrix, so you don't have to resize it.

**Comment by kocio-pl** [comment]
At 14px original proposition (1) looks more readable for me than the new one (2), so I left this code unchanged:
1) tyres
2) tyres2

I think in this case it's hard to avoid perspective at all. We've used it also for optic and book icon for the same reason.

**Comment by kocio-pl** [comment]
I have trouble deciding about merging this code. "A pull request should have at least one review before it is merged" (https://github.com/gravitystorm/openstreetmap-carto/issues/2436#issuecomment-291008629) - but do we need formal review ([like this one](https://github.com/gravitystorm/openstreetmap-carto/pull/2703#pullrequestreview-51651599)) or any comment indicating that other developer have seen it ([like this](https://github.com/gravitystorm/openstreetmap-carto/pull/2662#issuecomment-314222362))?

The problem is lack of review or reaction is common situation with our PRs, so decision making process is still not quite effective.

**Comment by nebulon42** [comment]
For me this means a formal review.

**Comment by kocio-pl** [comment]
I doubt there's any difference in how both of them apply style guidelines, but reworked icon is also acceptable for me:

aeco qrc

**Pull request merged**
