### PR TITLE
Refactor water-features

### LINKED ISSUE #403: Render weir on top of waterways
I think weirs should be rendered on top of waterways. It looks very strange when there are gaps in weirs at the point where the waterway intersects. At the moment it seems to be random whether the waterway or the weir is rendered on top.

Example how it should not be:
screenshot from 2014-09-16 20 37 34
http://www.openstreetmap.org/#map=19/49.00742/8.49113

Example how it should be:

screenshot from 2014-09-16 20 37 44
http://www.openstreetmap.org/#map=19/49.00329/8.47812

### LINKED ISSUE #474: Render labels for man_made=pier
Piers in big marinas are like streets in towns. They have names (numbers or letters)
It's important to know their names to find the right pier. These names of piers had been rendered before, but have been removed lately. 

Please render the names of piers again. 

See her for examples: http://www.openstreetmap.org/#map=17/44.05425/15.29923&layers=N
http://www.openstreetmap.org/#map=17/43.71978/15.89723&layers=N

### LINKED ISSUE #893: man_made=groyne is not rendered if it's a closed way
similar to #892

No closed groynes are rendered. Propotion closed: 4972, none-closed:11291.

### PR DESCRIPTION
**Pull request by math1985**
Dam, weir, lock:
* Add rendering for dam areas (supercedes and closes #227, based on code by
  @chrisfleming), dam and weir nodes, and lock_gate line
* Render weir in right layer (resolves #403)
* Change rendering of weir so it renders with small dashes
* Use marker instead of image for lock_gate node
* Add labels for dam nodes, dam areas, weir, and lock_gate
* Improve labels for dam lines and lock lines
* Remove labels for undocumented and less common waterway=lock

Groyne, breakwater:
* Render groyne/breakwater area the same color as groyne/breakwater way
  (resolves #893)
* Add label for groyne, breakwater, and pier (resolves #474)

Other:
* In general rewrite and clean up code

### CODE REVIEW

**Comment by RicoZ-OSM** [comment]
How about waterfall icons?

https://github.com/gravitystorm/openstreetmap-carto/issues/336

**Comment by math1985** [comment]
Waterfalls are out of the scope of this pull request. I'd be happy to look at it though given a good icon.

**Comment by vincentdephily** [comment]
I like this :)

Locks have been discussed already, but I wonder about dams and weirs (on a line) too. Circles look weird, could you try using the same rendering as on areas (as if the linear river feature was really just a thin area feature) ? If that's too small to be legible, render the dam/weir slightly larger than the river ?

**Comment by math1985** [comment]
I'm also not happy with the circles, but I don't know how to change them. We cannot use the orientation of the water feature to rotate the symbol, I think.

I'm not sure exactly what you mean with your proposal, what do you mean with 'could you try using the same rendering as on areas (as if the linear river feature was really just a thin area feature) ?'?

**Comment by math1985** [comment]
Rebased and dropped rendering of names of waterway=lock_gate and lock=yes name.

**Comment by math1985** [comment]
Rebased.

**Comment by math1985** [comment]
This would also be nice to have in the next release.

**Comment by math1985** [comment]
Rebased.

**Comment by pnorman** [comment]
I attempted a review, but locks are not common here so I'm not the best person to do so.

**Comment by mkoniecz** [comment]
>  locks are not common here so I'm not the best person to do so

The same is true for me, in addition my knowledge about such water-features is limited.

**Comment by systemed** [comment]
Happy to take a look if you post some screenshots here.

**Comment by math1985** [comment]
> Happy to take a look if you post some screenshots here.

Screenshots are in the first post.

**Comment by systemed** [comment]
Oh, I thought you meant there was something new to see rather than the stuff I've already extensively commented on.

**Comment by math1985** [comment]
@systemed I think I forgot to come back to you, sorry for that. We only render the `waterway=lock_gate` tag in the current proposal (both on nodes and lines). We cannot render lock names, because we don't have lock_name in the database (we will render lock_name after the next database reload). We also cannot render < symbols because we cannot rotate symbols based on the way they are connected to. I tried rendering locks lighter/darker, but I couldn't get the layer ordering right (the fact that rivers can be both tagged as area and line, combined with the fact that rivers as line have a round linecap makes layer ordering very complex - I didn't see a way to prevent the round line cap from rendering on top of the water area on the other side of the lock). So I think this is the best we can do for now.

**Comment by mboeringa** [comment]
I should say: go for it. It may not be perfect, but you have well argued the proposal, and it generally looks an enhancement to the current rendering.

**Comment by math1985** [comment]
Rebased.

@gravitystorm Could you review this?

**Comment by mkoniecz** [comment]
> Rebased.
@math1985 Are you sure that you pushed new version? 

Github claims that

>  We can’t automatically merge this pull request. 

and that commits are from "27 Sep 2014".

**Comment by math1985** [comment]
Sorry, forgot to push. Now it should be fine.

**Comment by vincentdephily** [comment]
Sorry for the naive question, but why can't we rotate the < symbol ? Can it not be handled in the same maner that oneway arrows are ?

**Comment by dieterdreist** [comment]
2015-03-09 20:23 GMT+01:00 math1985 <notifications@github.com>:

> We cannot render lock names, because we don't have lock_name in the
> database



is there any particular reason for this strange tag rather than a simple
"name"?

**Comment by systemed** [comment]
Yes, 'name' is used for the name of the waterway, just as 'bridge_name' is often used for the name of a bridge while 'name' is used for the name of the road.

**Comment by dieterdreist** [comment]
2015-03-10 10:34 GMT+01:00 Richard Fairhurst <notifications@github.com>:

> Yes, 'name' is used for the name of the waterway, just as 'bridge_name' is
> often used for the name of a bridge while 'name' is used for the name of
> the road.



I don't see this conflict: lock_gates according to the wiki should be
tagged on nodes, and according to taginfo they mostly are:
http://taginfo.osm.org/tags/waterway=lock_gate
Not sure if those tagged on ways are mainly on the waterway or on a
dedicated way for the lock gate (i.e. orthogonal to the waterway).

FWIW, I also don't like the idea of "bridge_name" for highways, I think it
is sufficient for the highway to know it is on a bridge, while the name of
the bridge and other details of the bridge would be better suited for the
bridge object itself rather than the ways running over it (maybe the
movable property has a point in being attached to the highway, for easier
use of the data in routing etc.).

**Comment by systemed** [comment]
lock_name is used on the waterway way through the lock, not on the gates.

**Comment by dieterdreist** [comment]
2015-03-10 12:15 GMT+01:00 Richard Fairhurst <notifications@github.com>:

> lock_name is used on the waterway way through the lock, not on the gates.



wouldn't it make more sense to map the lock as an area and have a "name"
tag on it?

**Comment by systemed** [comment]
You need to have the lock as a way for routing purposes, as it's a significant time penalty and often has properties such as opening hours, charges, and equipment required for passage (e.g. keys). That doesn't preclude having it as an area as well.

But discussing tagging theory, as opposed to practice, should be on the tagging@ list and not the osm-carto issue tracker.

**Comment by mkoniecz** [comment]
@math1985 Well, as experts are unavailable I will review it. Math, can you rebase it?

**Comment by pnorman** [comment]
My reluctance to review it is not many of the features modified are present locally - there's only [one](https://www.youtube.com/watch?v=Z1YFxZCgYoU&t=207) in western canada.

**Comment by math1985** [comment]
Rebased.

**Comment by mkoniecz** [comment]
@math1985 Github claims that

>  We can’t automatically merge this pull request.

**Comment by math1985** [comment]
That's caused by a new merge conflict.

Rebased again.

**Comment by matkoniecz** [comment]
I started reviewing. Sample size is still low, but in 7 examples of tag usage two had major tagging problems (entire lake tagged as dam, circular dam without area=no).

**Comment by mboeringa** [comment]
> I started reviewing. Sample size is still low, but in 7 examples of tag usage two had major tagging problems (entire lake tagged as dam, circular dam without area=no).

I think it is good that these problems no show up, so they can be fixed, because this sounds like a bad tagging practice.

**Comment by matkoniecz** [comment]
Yes, obviously it is a good thing that more tagging errors will be visible.

**Comment by matkoniecz** [comment]
There is one funny case - road on top of linear dam is nearly completely blocking rendering. But it is probably WONTFIX (I am not even making a new ticket for this one). https://www.openstreetmap.org/way/266343562#map=16/46.1778/33.6243

The one solution that I see is to render linear dams wider, but I am not convinced that it is a good idea.

Also, as rendering for nameless linear dams is not changed, this case is not affected by this PR.

**Comment by matkoniecz** [comment]
@math1985 According to wiki[1] waterway=lock_gate should be used only on nodes. This seems to be sort-of followed. But this PR add rendering of waterway=lock_gate on ways.

[1] http://wiki.openstreetmap.org/wiki/Tag:waterway=lock%20gate

**Comment by math1985** [comment]
5% of the lock gates are ways. Intuitively I think it also makes sense to tag lock gates as way when the river is tagged as area (the wiki documentation likely dates from the time there were no river areas yet).

However, I also don't mind following the wiki documentation, and dropping the ways from rendering.

**Comment by matkoniecz** [comment]
Either PR or wiki should be changed. Unfortunately I have no opinion about what would be preferable.

**Comment by dieterdreist** [comment]
2015-03-15 19:50 GMT+01:00 Mateusz Konieczny <notifications@github.com>:

> Either PR or wiki should be changed. Unfortunately I have no opinion about
> what would be preferable
>


I would change the wiki to allow for ways, but only after "approval" on the
tagging mailing list.

**Comment by matkoniecz** [comment]
@dieterdreist 

I posted message on @tagging.

**Comment by math1985** [comment]
Rebased and squashed.

**Comment by matkoniecz** [comment]
@math1985 Have you considered adding `text-halo-fill: rgba(255,255,255,0.6);` to new labels? Or is it not working well in that case?

**Comment by matkoniecz** [comment]
@dieterdreist

> I would change the wiki to allow for ways, but only after "approval" on the tagging mailing list.

I think that there was a clear approval.

**Comment by pnorman** [comment]
Reviewed last night, okay with it.

**Comment by matkoniecz** [comment]
And I finished my review - and I am also OK with it, though it may be a good idea to apply #1273 also to labels introduced in this PR.

**Pull request merged**
