### PR TITLE
Add rendering for arcades

### LINKED ISSUE #3371: Render leisure=amusement_arcade
[1082 uses](https://taginfo.openstreetmap.org/tags/leisure=amusement_arcade#map)

https://wiki.openstreetmap.org/wiki/Tag:leisure%3Damusement_arcade

Generally a fairly large venue that is not currently rendered.

Rendering ideas (I suppose it would probably be green):

- Just a dot + text
- Space invader monster (vary it to avoid copyright issues?)
spaceinvader

### PR DESCRIPTION
**Pull request by meased**
Fixes #3371

Adds rendering for `leisure=amusement_arcade`.

https://www.openstreetmap.org/#map=18/45.99303/-123.92720
arcade_fl_17
arcade_fl

https://www.openstreetmap.org/#map=18/45.51235/-122.61292
arcade_qw

https://www.openstreetmap.org/#map=18/45.43464/-122.57540
arcade_db

### CODE REVIEW

**Comment by polarbearing** [comment]
Seems you contradict your last statement in #3371 where you were favouring a mechanical device over a video character?

**Comment by meased** [comment]
> Seems you contradict your last statement

Not at all. My point was that the icon should indicate that the venue is an arcade, regardless of whether it is mechanical or video. At the moment, the video character seems to be the best option with the best artwork, if a better icon can be made, great!

I did attempt to make a pinball icon. It was awful... You're welcome to take a stab at it.

**Comment by Adamant36** [comment]
It might be worth letting @Tomasz-W have a stab at it. He could probably come up with something good. If nothing else a front view of a generic arcade cabinet or something. There's some examples on Noun Project. As it is, this looks to out of place/loud. It doesn't work to have such an abstract icon mixed  in with real world ones like that, in my opinion.

**Comment by meased** [comment]
Here was my scratch:
arcade_scratch

**Comment by Tomasz-W** [comment]
My icon proposals:

1) leisure amusement_arcade
2) leisure amusement_arcade

Gist link: https://gist.github.com/Tomasz-W/6715fe9f45db8b21dcf560b8f4035a35

**Comment by meased** [comment]
Updated to the pinball icon as it seems to be well received and was my next favorite.

fl_18_v2
fl_17_v2
qw_18_v2
qw_19_v2
db_18_v2

**Comment by kocio-pl** [comment]
I have a hard time recognizing it, looks to me like kind of tennis maybe.

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. Sep 2018, at 08:52, kocio-pl <notifications@github.com> wrote:
> 
> I have a hard time recognizing it, looks to me like kind of tennis maybe.


+1, I agree

**Comment by kocio-pl** [comment]
For me it's lack of symmetry. Maybe pinball table shape would be more recognizable.

**Comment by meased** [comment]
> put the ball a bit further right

It's all the way to the right.

> Maybe pinball table shape would be more recognizable

14x14 is very small and it seems complexity is sort of what defines a pinball table.

**Comment by dieterdreist** [comment]
sent from a phone

> On 8. Sep 2018, at 17:48, meased <notifications@github.com> wrote:
> 
> 14x14 is very small and it seems complexity is sort of what defines a pinball table.


yes, of course not the actual table, but a lateral view (silhouette) might work even at 14x14


cheers,
Martin

**Comment by Tomasz-W** [comment]
Pinball table icon:

leisure amusement_arcade 3

**Comment by kocio-pl** [comment]
This looks rather like a furniture for me, I meant something like view from the top:

https://cdn.shopify.com/s/files/1/0696/2897/products/Baseball_Pinball_3.png?v=1494963466

**Comment by Tomasz-W** [comment]
>  something like view from the top

it's too complicated to make an 14x14 icon presenting it

**Comment by polarbearing** [comment]
> It's all the way to the right.

Indeed, I see when putting a ruler on the right side. Interesting optical illusion. The ball looks a bit more centred without the ruler. 

Still find the flipper/ball icon more recognisable than the table side. 
I had experimented myself with a top view of the table earlier. Having a frame already takes so much pixelspace that it is hard to have anything recognisable within.

**Comment by kocio-pl** [comment]
Thanks for checking it, @polarbearing.

I would go with original "monster" or spaceship icon. They are much more readable than flipper/ball icon and without the knowledge about arcade games there are no shapes that could work.

**Comment by polarbearing** [comment]
Still like the flipper more. The monster is highly specific to a particular video game, and it gives the venue a prominence it does not deserve. . But I fear the laymen test would fail for both.

**Comment by meased** [comment]
I'll try a test with a spaceship later, see how that goes.

**Comment by meased** [comment]
Trying a spaceship icon:

arcade_ship_fl17
arcade_ship_fl18
arcade_ship_qw18
arcade_ship_qw19

**Comment by Tomasz-W** [comment]
I think it looks like some kind of tower. As some people wenen't satisfied with pinball design, I would go with "space invider" design or add _leirure-green_ generic dot for this feature (which may be the best solution, because we still aren't sure if electronic icon is a good for something which could be non-electronic)

**Comment by Adamant36** [comment]
I vote for green dot. A lot of arcades aren't exclusively for arcade or pinball machines. Plus, most of them have the name "arcade" in them anyway. Maybe leaving them as a green dot would spur people on to add the names to more of them if nothing else.

**Comment by kocio-pl** [comment]
> I think it looks like some kind of tower. 

Yes, more or less.

> As some people wenen't satisfied with pinball design, I would go with "space invider" design or add leirure-green generic dot for this feature (which may be the best solution, because we still aren't sure if electronic icon is a good for something which could be non-electronic)

I would still go with invader. 

Dots are poor way of communicating with a map user - if she's not able to recognize arcade, that's the same as with dots of course, but if she can, it have more precise information about the object. We use dots only as a placeholder or to deal with clutter (shops) - and this is not this case. I also think green dot is too general, because leisure is much broader category than a shop or an office.

**Comment by meased** [comment]
Trying a modification to the invader:
- Lower portion is now reminiscent of a pacman ghost (combining pacman and space invader themes).
- Height reduced to lower the amount of "ink" used.

fl_newinv_18

**Comment by kocio-pl** [comment]
I like this version, especially making it a bit smaller.

**Comment by dieterdreist** [comment]
2018-09-16 22:03 GMT+02:00 kocio-pl <notifications@github.com>:

> I like this version, especially making it a bit smaller.
>

me too, it looks like the bastard of pac man's opponent and a space
invaders ;-)

**Comment by meased** [comment]
Updated with master. More testing (same areas as above):

fl17
fl18
fl19

qw_17
qw_18
qw_19

db17
db18
db19

**Comment by kocio-pl** [comment]
Thanks! My testing also shows it's OK.

This one was fun. :smile:

**Pull request merged**
