### PR TITLE
Add fitness_centre with the same rendering as sports_centre

### PR DESCRIPTION
**Pull request by boothym**
#2375 - at least gets the fitness_centre name rendered, we can get an icon added later.

I don't have a way to test this PR, but I assume it will work ok as I've just copied the parts where sports_centre is mentioned in the code.

### CODE REVIEW

**Comment by imagico** [comment]
We generally require changes to be tested and not be done blindly.  The inner workings of the style and interactions between different parts can be complicated and even experienced contributors will not usually submit changes without testing.

If you need help with setting up a testing environment there are usually people here who can give suitable tips and suggestions.

Regarding the change itself - there are less than 100 features with `leisure=fitness_centre` without a building tag and most of these seem to be errors of some sort (missing building tag or misuse of the tag for a spa or similar) so not a good idea to add area rendering for this IMO.

**Comment by boothym** [comment]
Well it's there for anyone who wants to test it, as unfortunately I don't have the time or inclination to do it at the moment. 

Not sure where you are getting your numbers from, as there are over 200 instances of `leisure=fitness_centre` without a building tag (ie nodes) in the UK alone?

The reason for the change is to have the same rendering as `leisure=sports_centre`, especially for nodes where the name is displayed for sports centre, but not shown for fitness centre. There are many incorrectly tagged gyms which would not be rendered if they were changed to fitness centre.

**Comment by boothym** [comment]
If you want an example of why this change is needed, see: http://www.openstreetmap.org/node/208364293/history

This gym was correctly updated from leisure=sports_centre to fitness_centre, but now its name is no longer rendered on the map.

**Comment by imagico** [comment]
Note i was talking about area features and area rendering here.

Rendering tagged nodes with label only is a different matter.  This is a problem too but likely not any worse if this is extended to fitness centres.  Right now sports_centre is widely used for name dropping, just look at the number of nodes with this tag in the database that have a generic name indicating the type of sport or site rather than the specific name of the feature in question.  

Examples:

https://www.openstreetmap.org/node/2379021641
https://www.openstreetmap.org/node/286688123
https://www.openstreetmap.org/node/4452411798
https://www.openstreetmap.org/node/519628832
https://www.openstreetmap.org/node/250386927
https://www.openstreetmap.org/node/1231870683
https://www.openstreetmap.org/node/1860280192

**Comment by dieterdreist** [comment]
2017-01-13 11:15 GMT+01:00 Christoph Hormann <notifications@github.com>:

> Rendering tagged nodes with label only is a different matter. This is a
> problem too but likely not any worse if this is extended to fitness
> centres. Right now sports_centre is widely used for name dropping, just
> look at the number of nodes with this tag in the database that have a
> generic name indicating the type of sport or site rather than the specific
> name of the feature in question.



that's a fine line, some/most of them could be considered names (e.g.
"Reithalle", "Sporthalle") while the first on (a node with
name="Volleyball") clearly isn't. A generic name can also be the specific
name, especially in smaller settlements where there's just one of a kind
and no need to distinguish (I don't know the objects you have posted here
and cannot say if this is the case here)

**Comment by imagico** [comment]
No, the difference here is generic type of sport vs. generic type of site.  Neither is correct as a name, a name tag is always for the individual name of the feature in question which differentiates it from similar features nearby.  Having the type of site as name would be like placing a node `amenity=place_of_worship` with `name=church` - which is wrong.

In this particular case the name of the sports centre would be _Reitverein St. Hubertus_ which is in the description tag here.

The fact that in conversation locals might identify the feature by its type (like "wir gehen zur Reithalle") does not change this - we also tend to say "wir gehen zum Bäcker/Supermarkt/..." which does not mean that "Bäcker" is a correct name tag for shop=bakery.

There are of course cases where in terms of map usability it might be beneficial to render localized values for tags like `sport=*` or `shop=*` instead of or in addition to generic icons and names but that is technically challenging due to the variety of languages in the map.

**Comment by dieterdreist** [comment]
2017-01-13 11:45 GMT+01:00 Christoph Hormann <notifications@github.com>:

> No, the difference here is generic type of sport vs. generic type of site.
>


yes


> Neither is correct as a name, a name tag is always for the individual name
> of the feature in question which differentiates it from similar features
> nearby.
>

as I have written, the individual name can be the same as the generic type
of site. Even more as we focus on "ground truth", i.e. the name the local
people use

**Comment by boothym** [comment]
@imagico I'm not sure why you are bringing up examples of sports_centre - this PR is about getting fitness_centre rendered. 

Regarding names of sports on pitches, I've suggested sport icons https://github.com/gravitystorm/openstreetmap-carto/issues/844#issuecomment-250768588

**Comment by pnorman** [comment]
While the cartography needs discussing, it's also important that this PR be tested.

**Comment by kocio-pl** [comment]
I think of leisure=fitness_centre rather as leisure, not sport, so prefer to use the same color as some other leisure features.

Testing rendering seems to work both for nodes and area:
xipu563f
udfvbov7

If you want to test anything more, I need the location.

**Comment by boothym** [comment]
Looks fine to me for nodes, which is what I was concerned about. Not really bothered about areas as fitness centres are normally nodes are with a building tag. Though it would be nice if the same text was used on buildings, instead of the normal text.

**Comment by math1985** [comment]
Thanks @boothym! And sorry for slow review.

**Comment by boothym** [comment]
Thanks, I wondered if something had happened to all the reviewers! :)

Just a question about buildings tagged with leisure=fitness_centre or tourism=attraction. Why aren't named buildings with these tags styled in the same way as nodes?

**Pull request merged**
