### PR TITLE
Special rendering for intermittent waterways - fixes #805

### LINKED ISSUE #805: Special rendering for intermittent waterways
There is an approved proposal for key intermittent=yes applicable to waterways:

 http://wiki.openstreetmap.org/wiki/Proposed_features/Intermittent_river

Please add rendering of intermittent waterways as dashed blue line.

See also https://trac.openstreetmap.org/ticket/3681.

### PR DESCRIPTION
**Pull request by mkoniecz**
Note: there are still some issues.

- <s>(1) - in a rare situation - intermittent waterway with bridge=*, connecting with not intermittent waterway ordering of rendering may be wrong, leading to a small glitch. It is fixable by ordering waterways in SQL querry - but is it worth additional complexity and performance hit to solve something that never appears in data? Or in the worst case - is really rare? (based on math1985's comment)</s>
- <s>(2) - is it possible to maintain consistent dashes across (meta)tiles? See the first image. (thanks @pnorman!) </s>
- <s>(3) - is it necessary to modify rendering of wadis? And (changed) derelict canals? Both use dashes,  but wider and  rounded ones. See examples at http://www.openstreetmap.org/way/81918899 and http://www.openstreetmap.org/way/220089162#map=16/31.0738/34.5945 (wadi rendering is changed, for derelict canals I opened #1003)</s>
- <s>(4) - is it a good idea to assume that ditch is intermittent ? (no)</s>

glitch

Examples of a new rendering on an example of http://overpass-turbo.eu/s/5ec (+some minor modifications of OSM data)

Minor waterways:

z19
z16
z14
z13
tunnel
bridge

Major waterways:
z19
z16
z14
z13
bridge
bridge2
tunnel17
selection_005

### CODE REVIEW

**Comment by math1985** [comment]
@mkoniecz Could you rebase this?

**Comment by math1985** [comment]
@mkoniecz Can you rebase this?

**Comment by mkoniecz** [comment]
Yes, I will do it tomorrow.

**Comment by mkoniecz** [comment]
Rebased, now I am testing whatever everything works properly.

**Comment by mkoniecz** [comment]
Probably too late for this release, but according to my tests everything works properly.

**Pull request merged**
