### PR TITLE
move emergency phone to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
sos_before

after
sos_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
Less visible (that may be what we want - to see such items but not eclipse more typical elements), but for me as good as current.

**Comment by daganzdaanda** [comment]
I like how clear the SOS reads. As with "phone", I think the gap isn't really necessary. 
Should we define a common colour for all "emergency" icons?

**Comment by nebulon42** [comment]
> Should we define a common colour for all "emergency" icons?

That should be discussed seperately. But could be an idea to pursue.

**Comment by nebulon42** [comment]
Rebased and ready for review/merge I think.

**Comment by matkoniecz** [comment]
Thanks for the new icon!

**Pull request merged**
