### PR TITLE
move toilets icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 by changing the icon for `amenity=toilets` to SVG (as requested by @mkoniecz in #1012). 

Symbol ([toilets-16.svg](https://github.com/nebulon42/osmic/blob/master/amenity/toilets-16.svg))
toilets-16

http://www.openstreetmap.org/#map=19/46.79772/13.49504
before:
toilets_before

after:
toilets_after

A very similar symbol is also used by the HOT style, it is heavily inspired by Maki's [toilets-18.svg](https://github.com/mapbox/maki/blob/mb-pages/src/toilets-18.svg).

### CODE REVIEW

**Comment by daganzdaanda** [comment]
I like the icons @nebulon42 proposes, the second is even better than the first IMO.

The old icon is 20px and was probably scaled down from something bigger, it is not sharp at 20px. If we want all icons to be 16px, there is not much room for the arms... I tried a number of versions:

https://gist.github.com/daganzdaanda/fae414f277eae88e3efb

toilets-16-versions
toilets-16-versions-x3

First line: 
the 2 proposals from here, then adding a vertical divider
2nd line:
The current png, scaled from 20px to 16px, and two tries at rebuilding them in svg
Next 4 lines:
various tests
Last line: 
variation of the proposed icons with divider

**Comment by mboeringa** [comment]
I think adding the dividing line back in like you did, like in the last line of icons, does make the original proposal of @nebulon42 much more acceptable and recognizable. I have far less the feeling that it is some kind of "flower arrangement". That is a big change in experience based on a minor adjustment.

**Comment by nebulon42** [comment]
Thanks for working on this! What stopped me from adding the divider line is my requirement for 1px padding around the edges of the icon, which limits the space for filled pixels to 15x15. This is for inverse (shield) versions, so that those can be 16px with no icon content touching the border. You see there are lots of things to keep in mind.

Great that you tried some arm variations so it is clearly visible that these are too blurry at such a small size.

@daganzdaanda What is your favourite?

**Comment by mboeringa** [comment]
> What stopped me from adding the divider line is my requirement for 1px padding around the edges of the icon, which limits the space for filled pixels to 15x15.

If that is a requirement, the lower left one (7th row, first icon) might be an option @nebulon42. That icon is very close to your original version, but just 14x14 pixels for the image area.

I like the balanced feeling between white and black space in that icon too.

**Comment by kocio-pl** [comment]
For me 7.1 too is the best (the same reason - great balance between visibility and regonizability), then 1.3 (better visibility, but worse proportions of a male figure) and 1.1 (very good visibility, but no line decreases recognizability - there are many places where simple people figures could be used).

**Comment by nebulon42** [comment]
Here is a new propsal based on the input by @daganzdaanda: toilets-16

**Comment by kocio-pl** [comment]
I think it's very good.

**Comment by mboeringa** [comment]
I think it's good to go!

**Comment by nebulon42** [comment]
Somehow I cannot re-open this PR so I will create a new one.

**Comment by daganzdaanda** [comment]
I noticed that the pixel area that you use is really just 14x14. That is really a challenge! Thanks for explaining the rationale behind that decision.

**Pull request closed without merging**
