### PR TITLE
Unpaved no access

### LINKED ISSUE #110: Render paved/unpaved
Would be nice if unpaved (surface=unpaved/gravel/ground/etc etc) roads were rendered a bit differently from paved (paved/asphalt/cobblestone/etc). Perhaps brown casing?

### PR DESCRIPTION
**Pull request by sommerluk**
Fixes #110

Closes #3399 (alternative version)

Changes proposed in this pull request:
- Render paved/unpaved differently: Unpaved roads with a pattern

This PR is an alternative version of #3399 that does not render access on roads any more, to simplify the overall rendering of roads. (It does not change, however, the access rendering for tracks, footways and so on, which follows a completely different approach than access rendering on roads.)

### CODE REVIEW

**Comment by kocio-pl** [comment]
Are there any opinions about this code? If I understand it right, it removes the only thing that has been disputed lately, so I guess it could be merged soon.

**Comment by kocio-pl** [comment]
Since I'm again able to run development environment on my computer with new Ubuntu, there are test images of unpaved roads in the wild:

residential [ https://www.openstreetmap.org/#map=19/52.23962/20.93215 ]

Screenshot_2020-09-25 OpenStreetMap Carto — Kosmtik

tertiary [ https://www.openstreetmap.org/way/204584341#map=18/52.09157/21.37662 ]

Screenshot_2020-09-25 OpenStreetMap Carto — Kosmtik(1)

**Comment by kocio-pl** [comment]
primary [ https://www.openstreetmap.org/#map=18/11.15067/119.39736 ]

Screenshot_2020-09-25 OpenStreetMap Carto — Kosmtik(3)

secondary [ https://www.openstreetmap.org/#map=16/14.2736/120.7760 ]

Screenshot_2020-09-25 OpenStreetMap Carto — Kosmtik(4)

**Review by pnorman — CHANGES_REQUESTED** [review]
I do not find residential, tertiary or primary easily distinguishable, and find secondary marginal.

I also don't feel that this cartography fits with the rest of the style.

I haven't done a line-by-line review of the MSS but am concerned about adding this much code and complexity to a difficult part of the codebase.

**Comment by kocio-pl** [comment]
> I do not find residential, tertiary or primary easily distinguishable, and find secondary marginal.

I also have the hard time seeing the difference, but fixing this problem would be quite simple.

> I also don't feel that this cartography fits with the rest of the style.

I'm surprised to hear that. In my opinion pattern rendering on areas is well-established and consistent with the whole style.

> I haven't done a line-by-line review of the MSS but am concerned about adding this much code and complexity to a difficult part of the codebase.

That is a valid concern. On the other hand there is high demand for this feedback, which could help mitigate roads mistagging - see https://github.com/gravitystorm/openstreetmap-carto/issues/110#issuecomment-23166250.

**Comment by sommerluk** [comment]
Rebased to current master.

**Comment by sommerluk** [comment]
I would really like to move that forward.

Regarding the MSS file: Of course, this PR adds code, but the code is not complex. Remember that Mapnik has kindly implemented pattern renderings on line strings because of our request, so that now we have straightforward code.

Regarding the pattern being distinguishable, I could provide a version with more contrast, if desired. Should I do so?

**Comment by imagico** [comment]
> I would really like to move that forward.

I very much support that, either this or #3399.

> Regarding the pattern being distinguishable, I could provide a version with more contrast, if desired. Should I do so?

I think this as now is a good balance between clear readability and not being too bold to illustrate a secondary distinction and not messing too much with the overall balance of the map.

**Comment by sommerluk** [comment]
Closing this in favour of #3399, to centralize discussion and not have too many open PR:

**Pull request closed without merging**
