### PR TITLE
move butcher icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165. Supercedes #1379.

before
butcher_before

after
butcher_after

### CODE REVIEW

**Comment by daganzdaanda** [comment]
Good icon!
And a smart idea, since you're trying to get more filled areas in the icons and that did not work so well with the meat cleaver.

**Comment by dieterdreist** [comment]
2015-05-09 19:38 GMT+02:00 nebulon42 <notifications@github.com>:

> Implements part of #1165
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1165>.
> Supercedes #1379
> <https://github.com/gravitystorm/openstreetmap-carto/pull/1379>.
>
> before
> [image: butcher_before]
> <https://cloud.githubusercontent.com/assets/3531092/7551265/eb54015a-f682-11e4-83f8-6d729f905cf5.png>
>
> after
> [image: butcher_after]
> <https://cloud.githubusercontent.com/assets/3531092/7551267/ee62d484-f682-11e4-9a6b-7942adb520dc.png>
>


I prefer the old one, of all icons in use I always found this one of the
better ones, really easy to understand and nice graphics. The new one is a
kind of blob that is less understandable IMHO.

**Comment by kocio-pl** [comment]
Both are good and readable for me.

**Comment by nebulon42** [comment]
Rebased.

**Comment by matkoniecz** [comment]
Random person: both icons are not obvious and not really readable.

Me: I prefer current one, probably because I am used to it.

**Comment by math1985** [comment]
Random person does not recognize new icon and thinks first icon is better.

**Comment by nebulon42** [comment]
I think I will not be able to come up with a redesign. Maybe the current one is better, but I cannot move that to SVG because of the large "hole" representing the blade. If you feel this is not mergeable, please close this PR.

**Comment by math1985** [comment]
Still hoping that somebody comes up with a better idea!

**Pull request closed without merging**
