### PR TITLE
Adding icon for amenity=university and amenity=college [WIP]

### PR DESCRIPTION
**Pull request by kocio-pl**
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/120 (partial solution).

Code based on amenity=hospital, but using current university/college label color.

Area, z15
Before
x10fsg0u
After
7gqkxtaj

Area, z16
Before
fvpjydrj
After
fbp9hjni

Area, z17
Before
evlp4xpi
After
dksxozgx

Node, z16
Before
dkmzlijr
After
trxnlh7l

Node, z17
Before
ws6roiqe
After
wg3nt5xd

Node, z18
Before
ertddgfy
After
hywvs2qx

### CODE REVIEW

**Comment by Circeus** [comment]
PLEASE not. Having a scaling name for these is one of the best thing about them, and anything with an icon has a name that can't scale anymore according (IIRC) pixel_area. In fact, I personally wish we could reasonably get rid of the hospital icon so hospital names could scale too.

**Comment by math1985** [comment]
> anything with an icon has a name that can't scale anymore according (IIRC) pixel_area

That's not a technical limitation, so if we want scaling labels in combination with icons we can define rules that allow this. Currently, caravan sites already do have a scaling label in combination with an icon.

See also #1355. @Circeus, I would be very interested in hearing your feedback on that issue.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 23 set 2016, alle ore 12:33, Matthijs Melissen <notifications@github.com> ha scritto:
> 
> That's not a technical limitation, so if we want scaling labels in combination with icons we can define rules that allow this. Currently, caravan sites already do have a scaling label in combination with an icon.


but it's a limitation designwise, either we scale the icon along with the text (would be a big change) or it will lead to strange looks (tiny icon compared to text).
Maybe having 2 or even three icon sizes could eventually look ok, it surely would increase code complexity (offsets etc) quite a bit

**Comment by kocio-pl** [comment]
We should probably have a general rule for such cases - see for example similar problem with prison: https://github.com/gravitystorm/openstreetmap-carto/issues/1022

**Comment by RobJN** [comment]
Do you need an icon for a university given that the name will usually include "university" in it?

**Comment by polarbearing** [comment]
@RobJN - is there any research that supports your assumption? OSM defines the use of the university tag for third level institutions, and I know many of them not carrying 'university' in their name. The [MIT](http://web.mit.edu/) is probably the most prominent on the technology sector.

**Comment by math1985** [comment]
> Do you need an icon for a university given that the name will usually include "university" in it?

Not saying we would, but we could show the university icon on lower zoom levels, before the name can be displayed, to indicate the campus location inside the city.

**Comment by RobJN** [comment]
No evidence just my hunch for the UK. Just seems like there was a lot of
attempt to clean up the map render and now loads of icons are being added.
Just wondered whether this was directed by a strategy. I'm sure you agree
that there is a balance between usefulness of icons and clutter.

**Comment by kocio-pl** [comment]
Can we reach some agreement with this PR? If not, I'm gonna close this PR without merging in a few days.

**Comment by polarbearing** [comment]
In favour of merging.

**Comment by kdudzik** [comment]
I don't like this change. Icons suggest nodes or small areas. We could enable this icon for nodes only but enabling it also for areas makes the campuses look worse IMHO.

**Comment by kocio-pl** [comment]
> We could enable this icon for nodes only but enabling it also for areas makes the campuses look worse IMHO.

That would be inconsistent with how we deal with hospitals. Do you think that universities are different in that regard?

**Comment by math1985** [comment]
What about first trying to render the name (in italics), and if it doesn't fit render the icon (without label)?

**Comment by polarbearing** [comment]
> math1985>  name (in italics), and if it doesn't fit render the icon (without label)

hm is that consistent behaviour someone would expect? Would that mean that in lower zoom I see an icon, when I zoom in the name?

> kdudzik>  Icons suggest nodes or small areas. 

First time I hear about such rule. 

>  kdudzik> We could enable this icon for nodes only but enabling it also for areas makes the campuses look worse IMHO.

Why? Maybe you have a campus that is tagged incorrectly, i.e. amenity nodes/buildings within the campus amenity?

Nodes and areas should not be treated differently in rendering, often a node is a first step in mapping before it is expanded to an area.

**Comment by kdudzik** [comment]
@kocio-pl I don't think hospitals are any different - they should be handled the same way, true.

@polarbearing I don't know any rule, that's just my subjective opinion. I'm not quite convinced to it, but I would prefer it to the current proposal.
Maybe @math1985's idea could work.
In my opinion a small icon with a small caption (or even without a caption) in the middle of a large area (which it represents) looks just weird.

**Comment by kocio-pl** [comment]
I think we should first rethink how do we render [similar objects](https://github.com/gravitystorm/openstreetmap-carto/pull/2361#issuecomment-249383602) and then go back to this problem. Thanks for the feedback!

**Comment by Tomasz-W** [comment]
Further discussion in https://github.com/gravitystorm/openstreetmap-carto/issues/3284

**Pull request closed without merging**
