### PR TITLE
move archaeological site to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
archaeological_site_before

after
archaeological_site_after

### CODE REVIEW

**Comment by mboeringa** [comment]
Way better! The old icon looked like some fire pit for a camp site...

**Comment by kocio-pl** [comment]
The old one was quite good, but this one is more crisp. I like previous icon's idea to "stick out" of the ground, but this is not needed IMO.

**Comment by mboeringa** [comment]
> I like previous icon's idea to "stick out" of the ground, but this is not needed IMO.

I always have had a hard time recognizing it as such, as the tilted "amphora" isn't recognizable enough in the original. My first impression was always something different when seeing the icon...

**Comment by daganzdaanda** [comment]
> I like previous icon's idea to "stick out" of the ground

So THAT is what that was supposed to be! I never understood that icon! The new one is a million times better for me.

**Pull request merged**
