### PR TITLE
fix oneway arrow colour for highway=path/footway and bicycle/horse=designated

### LINKED ISSUE #2054: Wrong colour for oneway arrow on path with bicycle=designated
oneway-path
https://www.openstreetmap.org/way/367094309

It's a bicycle=designated and foot=designated highway=path with oneway=yes. The arrow is red, the path blue.

### PR DESCRIPTION
**Pull request by nebulon42**
Fixes #2054.
Thanks @daganzdaanda for reporting.

before
designated_before

after
designated_after

### CODE REVIEW

**Comment by matkoniecz** [comment]
From reading code the same should happen for [highway=path; horse=designated; oneway=yes].

**Comment by matkoniecz** [comment]
And it really happens, see https://www.openstreetmap.org/#map=19/52.80319/13.69840 

selection_005

(via http://overpass-turbo.eu/s/eyz )

**Comment by nebulon42** [comment]
Thanks, I have not tested this, but updated the code. I have chosen the sequence so that it reflects the colouring of the line again.

**Comment by matkoniecz** [comment]
Thanks for the fix!

**Pull request merged**
