### PR TITLE
move fuel icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Icon: [nebulon42/osmic/fuel-16.svg](https://github.com/nebulon42/osmic/blob/master/transport/fuel-16.svg)

before
fuel_before

after
fuel_after

### CODE REVIEW

**Comment by mkoniecz** [comment]
For me new icon is more recognizable.

**Comment by mboeringa** [comment]
Looks fine

**Comment by kocio-pl** [comment]
Great - larger and easier to recognize!

**Comment by math1985** [comment]
Tester prefers new icon.

**Comment by polarbearing** [comment]
Even more applause - thanks @nebulon42

**Comment by nebulon42** [comment]
no applause necessary, thanks.

**Comment by sb12** [comment]
@nebulon42 I like the new icon and just thought about an issue ( #989  ) we discussed a few months ago.

Do you think you could adapt the icon similar to http://en.wikipedia.org/wiki/File:Free_EV_charge_station_sign_evinfra.svg , so we could show charging stations on the map as well?

**Comment by nebulon42** [comment]
I have added an issue for this icon request, so I don't forget. See https://github.com/nebulon42/osmic/issues/11

**Pull request merged**
