### PR TITLE
remove rendering on areas for natural=peak, volcano, saddle, cave_entrance

### PR DESCRIPTION
**Pull request by matkoniecz**
It makes code less confusing.

### CODE REVIEW

**Comment by dieterdreist** [comment]
in the case of a vulcano it would seem to make more sense mapping it as an area

**Comment by math1985** [comment]
> in the case of a vulcano it would seem to make more sense mapping it as an area

According to the wiki, it may only be used on notes.

**Comment by math1985** [comment]
This removes spring icons but not labels.

**Comment by matkoniecz** [comment]
Spring is no longer affected.

**Comment by dieterdreist** [comment]
2015-03-22 19:14 GMT+01:00 math1985 <notifications@github.com>:

> in the case of a vulcano it would seem to make more sense mapping it as an
> area
>
> According to the wiki, it may only be used on notes.
>

we could change this, according to taginfo, a small number (around 5%) is
already tagged on ways depite the misleading wiki page.

**Comment by dieterdreist** [comment]
btw.: just discovered: this was recommended to be mapped on areas or nodes,
and just one year ago changed (unilaterally I guess) to nodes only:
http://wiki.openstreetmap.org/w/index.php?title=Tag%3Anatural%3Dvolcano&diff=996213&oldid=995784

**Pull request merged**
