### PR TITLE
[WIP] Render salt ponds.

### LINKED ISSUE #545: Add rendering for landuse=salt_pond
The following landcover types are currently not rendered:
- ~~landuse=harbour, see also https://trac.openstreetmap.org/ticket/3612~~ rejected in https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-277207366 and https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-341894371
- landuse=salt_pond, see also https://trac.openstreetmap.org/ticket/4470
- ~~natural=dune~~, see also https://trac.openstreetmap.org/ticket/3815
- ~~natural=fell~~ rejected in https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-98479426 and https://github.com/gravitystorm/openstreetmap-carto/issues/545#issuecomment-341895192 , see also https://trac.openstreetmap.org/ticket/3033
- ~~and natural=scree~~ (done), see also https://trac.openstreetmap.org/ticket/3033
- ~~natural=reef, see also https://trac.openstreetmap.org/ticket/4416~~ done

It would be nice to have these tags rendered.

### PR DESCRIPTION
**Pull request by StyXman**
Fixes #545.

Changes proposed in this pull request:
- Render salt ponds with a flat old pink color. This reflects the fact that salt ponds tend to be colorful. Also the white salt dots recently introduced could be added.

Test rendering with links to the example places:

https://www.openstreetmap.org/way/694107134

Before
Screenshot_20190924_231526

After
Screenshot_20190924_230907

This is closely related to #3901.

### CODE REVIEW

**Comment by jeisenbe** [comment]
The location shown for testing may not be ideal, because there seems to be overlap between the `wetland=saltmarsh` and `landuse=salt_pond` areas.

The pink/purple color is somewhat similar to industrial and commercial areas. While salt ponds have some similarities to quarries and industry, we had discussed trying a shade of blue, since these features are intermittently covered with water, and adding a pattern in addition, in #545.

Perhaps we could try the triangular pattern that @imagico has used in his map style? See https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/salt_pond.svg and https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/salt_pond.png

**Comment by imagico** [comment]
Generally a good idea but the color does not work for me either.

**Comment by StyXman** [comment]
> The location shown for testing may not be ideal, because there seems to be overlap between the `wetland=saltmarsh` and `landuse=salt_pond` areas.

So I'm looking for freestanding `salt_pond`s?

**Comment by StyXman** [comment]
I'm going to have an issue here:

https://www.openstreetmap.org/way/108543652#map=14/47.4039/-2.4703



As you can see, the `salt_pond` contains a lot of `basin`s. Whatever we choose here, it's going to be on top of everything else, like the pink blobs in the sshot above.

**Comment by jeisenbe** [comment]
https://www.openstreetmap.org/way/108543652 is not mapped according to the usual way that is documented at [Tag:landuse=salt_pond](https://wiki.openstreetmap.org/wiki/Tag:landuse%3Dsalt_pond) - only the (intermittent) water areas should get this tag. Fortunately, most of the salt ponds in your screenshot are mapped correctly - all those east of Kercabellec have the tag `landuse=salt_pond` just on each pond, e.g. https://www.openstreetmap.org/way/142063430 and https://www.openstreetmap.org/way/142063459 - and rendering these similar to other water areas should help give feedback in support of consistent mapping.

**Comment by jeisenbe** [comment]
> Whatever we choose here, it's going to be on top of everything else, like the pink blobs in the shot above.

That's only true if we render `landuse=salt_pond` with priority over `natural=water`. While I think that is the correct option, you could also render areas as water if double-tagged with `landuse=salt_pond` + `natural=water` - this is very common. In that case, we would need to use a pattern, like [salt_pond.png](https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/salt_pond.png), rendered on top of water areas, so that the landuse is still visible.

**Comment by jeisenbe** [comment]
Example with ocean-color and salt_pond.png pattern for landuse=salt_pond:

z16-salt-pond-pattern-oceancolor

z14-salt_pond-corse

Next to the facebook offices, in East Palo Alto:
- Unfortunately, there is an overlapping `natural=wetland area`, perhaps because the landuse=salt_pond doesn't render, though the geometry is different.
- Note also that the wetland overlaps the coastline on the north side.
https://www.openstreetmap.org/relation/7352305#map=15/37.4903/-122.1583
z15-salt_pond-palo-alto

Salt ponds in South Australia:
- These are also tagged with natural=water
https://www.openstreetmap.org/#map=14/-34.8186/138.5977
z13 after
z13-dry-creek-salt_pond

z14 after
z14-dry-creek-after-salt_pond

**Comment by jeisenbe** [comment]
@StyXman what do you think about the option with the [pattern](https://github.com/imagico/osm-carto-alternative-colors/blob/alternative-colors/symbols/patterns/salt_pond.png)
) shown in https://github.com/gravitystorm/openstreetmap-carto/pull/3905#issuecomment-542032628 ?

**Comment by jeisenbe** [comment]
This needs rebasing for v5.0.0 - should I do this myself and take over this PR so that @StyXman gets credit for starting this, or would it be clearer I close this PR and open a new one with the designs in https://github.com/gravitystorm/openstreetmap-carto/pull/3905#issuecomment-542032628 ?

**Comment by pnorman** [comment]
> This needs rebasing for v5.0.0 - should I do this myself and take over this PR so that @StyXman gets credit for starting this, or would it be clearer I close this PR and open a new one with the designs in [#3905 (comment)](https://github.com/gravitystorm/openstreetmap-carto/pull/3905#issuecomment-542032628) ?

Do a new PR because you're not going to be reusing any of the commits here

**Comment by StyXman** [comment]
@jeisenbe thanks for thinking in terms of credit. I don't care much about it, really. Currently I have no time to work on these :(

**Pull request closed without merging**
