### PR TITLE
move telephone icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
phone_before

after
phone_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
I guess the arch should be more visible to make the shape easier to recognize, but overall impression is good.

**Comment by mboeringa** [comment]
What if you drop the small gap between handle and speaker/microphone, have you tried that? I don't think it is actually necessary, and makes it slightly less recognizable (also in the "emergency" variant).

I know the gap is there in the original one, but it is so small, so as to be virtually invisible on coarse low dpi screens...

**Comment by daganzdaanda** [comment]
Agree about the gap not being necessary. Otherwise, good icon.

**Comment by math1985** [comment]
@nebulon42 Have you looked into dropping the gap?

**Comment by nebulon42** [comment]
I like the gap better. I have also to make sure that my icons still look good at bigger sizes, even if that is not a concern for this style. It's a concern that I have to have.

Without gap: telephone-141 telephone-142

I can offer a less wide gap though and have updated the branch:
telephone

**Comment by daganzdaanda** [comment]
I'm fine with the smaller gap, actually it's better than the full version.

**Comment by kocio-pl** [comment]
+1

**Comment by matkoniecz** [comment]
Yes, smaller gap works really well.

**Comment by mboeringa** [comment]
Looks acceptable now.

**Comment by nebulon42** [comment]
Rebased. Since the smaller gap is accepted this should be ready for review/merge now.

**Comment by matkoniecz** [comment]
Thanks for the new icon!

**Pull request merged**
