### PR TITLE
make railway=tram with service tags less visible, fixes #1531

### LINKED ISSUE #1531: use service tag during rendering railway=tram
railway=rail with service=yard/siding/spur is rendered as less prominent. The same may be done with railway=tram, currently tram depots with many tracks are rendered as black areas - see http://www.openstreetmap.org/#map=15/50.0327/19.9334 for an example

selection_002

### PR DESCRIPTION
**Pull request by matkoniecz**
https://cloud.githubusercontent.com/assets/899988/8819185/0190789e-304a-11e5-9798-6297adcdfb1e.png
https://cloud.githubusercontent.com/assets/899988/8819186/01922432-304a-11e5-856b-be4f75f7890f.png
https://cloud.githubusercontent.com/assets/899988/8819187/0192c112-304a-11e5-9a3a-03405a5901c7.png
https://cloud.githubusercontent.com/assets/899988/8819184/019083c0-304a-11e5-8dd5-b956ab57ddb3.png

(note - single track in Jerusalem, where missing service tag is visible is now fixed - http://www.openstreetmap.org/way/217849915#map=19/31.80890/35.23993 )

### CODE REVIEW

**Comment by kocio-pl** [comment]
I think z14 is better to start show them than z16 (although not as strong as we have now, that's sure - your proposition of lighter color is good probably). At this zoom level it's interesting to know what type of industrial area is it exactly, because it's not competing for user's attention anymore. Even in big city typical "quarter" (between suburb and neighbourhood) doesn't have more important industrial structures, so it makes sense to show they are dominant here.

**Comment by matkoniecz** [comment]
The problem with showing it earlier is formation of blob with merging tracks (even with really narrow lines).

Also, z14 is IMHO too early - at least structures that I found seem to not be important enough to be prominently displayed so early (and dark blob will be prominent, at least I have no good ideas how to avoid this). 

z15 would make sense and that was planned zoom level of appearance but I failed to find display that would not be bad.

Overall, I think that z16 is reasonable.

**Comment by kocio-pl** [comment]
I think a lighter "blob" doesn't hurt, because one doesn't have to see the separate tracks, just the impression that there are a lot of them. Could you show one such example at z14 and z15 (probably one of those you have just rendered here)?

**Comment by matkoniecz** [comment]
> example at z14 and z15

https://cloud.githubusercontent.com/assets/899988/8823030/028f46ce-306a-11e5-8a3d-dc0a35580d8e.png
https://cloud.githubusercontent.com/assets/899988/8823029/028d4568-306a-11e5-96f4-df91a975d8fc.png

**Comment by kocio-pl** [comment]
At z14 Crich is too dark and Cracow is good, but maybe still too distracting for someone tracking the roads (clustering makes color stronger). At z15 both are really good for me and doesn't disturb me, so I prefer starting to show them from that level.

**Comment by matkoniecz** [comment]
After reviewing next batch of z15 locations I am reconsidering lack of rendering on z15.

https://cloud.githubusercontent.com/assets/899988/8825835/443e62c2-3082-11e5-9170-91d8d1836007.png

https://cloud.githubusercontent.com/assets/899988/8825836/44417070-3082-11e5-8485-5112fe304327.png

(https://cloud.githubusercontent.com/assets/899988/8825837/4447880c-3082-11e5-8ff6-6c2a1d2e1b5c.png

https://cloud.githubusercontent.com/assets/899988/8825839/444a5654-3082-11e5-9bbe-3728de0e58c7.png

https://cloud.githubusercontent.com/assets/899988/8825838/44483900-3082-11e5-9d9b-f1909b097369.png

https://cloud.githubusercontent.com/assets/899988/8825840/444c27fe-3082-11e5-804f-41793f609c32.png

https://cloud.githubusercontent.com/assets/899988/8825841/4457c244-3082-11e5-94dd-5eee4bd7fa5e.png

https://cloud.githubusercontent.com/assets/899988/8825842/445a822c-3082-11e5-9114-57783832c810.png

I will update PR to update rendering at z15.

**Comment by kocio-pl** [comment]
I have no problems with this new batch of examples. You're quick, BTW! :smile:

**Comment by ximex** [comment]
z15 looks good. z14 is to early. gread job :+1:

**Comment by matkoniecz** [comment]
After looking at these examples again I am convinced that showing it at z15 is a good idea.

**Comment by math1985** [comment]
Looks good!

The zoom level for the labels needs also to be adapted - see Crich z15.

**Comment by matkoniecz** [comment]
Crich at z15 is tricky (I had the same reaction) - this place is mapped as [railway=tram; service=yard; highway=pedestrian; name=foobar]. Pedestrian and its name is rendered at z15.

Names of railway tracks is currently not rendered anywhere.

**Comment by ppawel** [comment]
I love these changes!

**Comment by math1985** [comment]
> this place has ways mapped as [railway=tram; service=yard; highway=pedestrian; name=foobar].

Sorry, I missed that it was also tagged as highway.

**Pull request merged**
