### PR TITLE
move hostel icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements #1165.
Symbol is now smaller.

before
hostel_before

after
hostel_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
Almost the same remarks as in https://github.com/gravitystorm/openstreetmap-carto/pull/1389#issuecomment-80988986, but I think in this case the barrier is not too too high.

**Comment by dieterdreist** [comment]
> Am 15.03.2015 um 13:31 schrieb nebulon42 <notifications@github.com>:
> 
> Symbol is now smaller.


I find this hard to read because it is very dense, maybe enlarge the distance of the sleepers or make the bed thinner

**Comment by nebulon42** [comment]
Yes, it is dense because it is hard to fit a bunk bed into 14x14px.
Maybe this would be an improvement: hostel-183

**Comment by kocio-pl** [comment]
Maybe, but it's hard to compare - could you show how would it look like on the map?

**Comment by neiljp** [comment]
Is the stand/support on the bottom bunk really necessary? Would removing it help with improving the shape/visibility? Maybe more space between bunks? bigger pillows/heads?

Similarly 'should' there be a vertical line on the right-hand side? Conversely, is removing the left-hand one valid? Does it leave the design 'intact'?

**Comment by mboeringa** [comment]
Here is a small attempt at modification, not a lot that can be done in 14x14 pixels...

hostel_icon
:

**Comment by kocio-pl** [comment]
For me it's acceptable.

**Comment by nebulon42** [comment]
The person is a bit short, but not bad. @mboeringa If that is a SVG, could you please provide it as Gist?

**Comment by mboeringa** [comment]
> The person is a bit short, but not bad. @mboeringa If that is a SVG, could you please provide it as Gist?

Sorry, this was just quick and dirty in MS Paint, to see if anything sensibly could be changed. If you download the PNG and zoom in to 800% in MS Paint, you can see what pixels I changed compared to the original rasterized version you supplied in your first post.

**Comment by nebulon42** [comment]
Updated after input of @mboeringa.

**Comment by mboeringa** [comment]
@nebulon42 ,

In my version, I lowered the "bedding" by 1 pixel from 3 to 2, as this looked a bit more natural in my eyes by creating more "space" between the lower figure and the top bed. Is there a technical hurdle to implement this in your SVG version?

Also, the "heads" appears higher, looking like they float. Here is a side-by-side comparison, left my pixel manipulated version, right @nebulon42's SVG version:
hostel_icon
hostel_icon_enlarged

**Comment by nebulon42** [comment]
Yes, looks better.

**Comment by nebulon42** [comment]
From my side this is now ready.

**Comment by mboeringa** [comment]
Updated version in the original post looks fine to me too.

**Comment by math1985** [comment]
Looks fine to me, but waiting for #1389 for consistency reasons.

**Comment by matkoniecz** [comment]
From looking at icon itself it seemed to not be an improvement - but from looking at how map changes it is in fact improvement. I support merging both #1389 and #1390. Note, I still think that edit proposed in https://github.com/gravitystorm/openstreetmap-carto/pull/1389#issuecomment-85626745 would be a good idea.

**Pull request merged**
