### PR TITLE
model aerialways with dashed lines instead of using line patterns

### PR DESCRIPTION
**Pull request by nebulon42**
By getting rid of the patterns it is easier to customise. Of course, the possibilities of `line-dasharray` are limited, but for those simple patterns it should be sufficient.

It's just an idea I had.

preview (right = after)
aerialways

### CODE REVIEW

**Comment by kocio-pl** [comment]
I was staring at both images and couldn't spot the difference. ={ Could you explain the change in simple words?

**Comment by mboeringa** [comment]
> I was staring at both images and couldn't spot the difference. ={ Could you explain the change in simple words?

I think the whole point of @nebulon42's proposal was to show you can create exactly the same symbols using an apparently easier coding / styling method...

**Comment by pnorman** [comment]
you need `line-clip:false` any line with dashes both to avoid rendering problems at meta-tile boundaries

**Comment by pnorman** [comment]
Just for an example, so that people understand what I mean
without line-clip
image

with line-clip
image

**Comment by nebulon42** [comment]
Thanks for the hint. There is no visual difference with/without `line-clip: false` at metatile borders in my Kosmtik setup. Could this be due to changed behaviour in soon-to-be Mapnik 3?

**Comment by math1985** [comment]
Cool idea, well done!

**Comment by pnorman** [comment]
> Thanks for the hint. There is no visual difference with/without line-clip: false at metatile borders in my Kosmtik setup. Could this be due to changed behaviour in soon-to-be Mapnik 3?

Defaults may have changed, but also it requires some luck to hit a visually obvious case of the problem. The first few MT bounds I checked at didn't have anything I could clearly point at.

**Comment by math1985** [comment]
Also, Kosmtik handles some things related to metatiles differently from the production server, as we have seen before.

**Comment by gravitystorm** [comment]
> Could this be due to changed behaviour in soon-to-be Mapnik 3?

Yes, the defaults for clipping have changed from `true` to `false` in mapnik 3 -  see https://github.com/mapnik/mapnik/issues/2146

**Pull request merged**
