### PR TITLE
Adding landuse=aquaculture pattern

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1774.

The idea is to have kind of "underwater orchard" with regular blue dots pattern with a boundary line in the same color (water-text):

aquaculture-dot-6699cc-14

### CODE REVIEW

**Comment by pnorman** [comment]
When I look at it, it's not obvious to me what it represents.

**Comment by kocio-pl** [comment]
Can you think about anything that could be clear aquaculture visual representation for you? I'm ready to test it.

**Comment by pnorman** [comment]
> Can you think about anything that could be clear aquaculture visual representation for you?

No.

**Comment by polarbearing** [comment]
> When I look at it, it's not obvious to me what it represents.

This was discussed in #1774 and preferred over more picturesque versions. You cannot expect that every feature is obvious from the first glance, and at the same time not too obtrusive. 

We have the query tool on the website so it is easy to check what it is in detail.

**Comment by matkoniecz** [comment]
> Can you think about anything that could be clear aquaculture visual representation for you?

Unfortunately no. And current rendering IMHO rather fits more generic restricted area (fish pattern also was problematic, though for different reasons).

**Comment by kocio-pl** [comment]
I'm not aware of dots being used for restricted area - we have hatching exactly for this and we use it very conservatively (only 2 object IIRC - and still we render them [a bit different](https://github.com/gravitystorm/openstreetmap-carto/issues/1285)), so I think allotments could be more suspected about being restricted. And if you still feel dots look like restricting something, the orchard (or maybe vineyard too) is - by design - very common in that regard to the current aquaculture draft, so they maybe should be removed to make this style consistent about using patterns?

What I'm trying to say is we may have different feelings, but we should not keep forgetting about already existing features and treat them as given and obvious. Archaeological sites and quarries were good examples of problematic visual representation.

**Comment by imagico** [comment]
The pattern seems to work fine for me but the outline does not - outlines without an area fill usually do not work well, especially when shown at strongly varying scales.

Apart from that z10 is too early for such a pattern, you will usually only have individual dots visible at this scale which is not helpful.

**Comment by kocio-pl** [comment]
@imagico 
> outlines without an area fill usually do not work well, especially when shown at strongly varying scales.

Could you give some examples of such problems? I don't feel it might be a problem at all, so kind of proof (or even just a hint) would be helpful as a reality check.

> Apart from that z10 is too early for such a pattern, you will usually only have individual dots visible at this scale which is not helpful.

It depends on the size probably and I guess sea aquacultures can be quite big (according to FAO [global fish production in such farms almost doubles wild captures](https://en.wikipedia.org/wiki/File:Global_total_fish_harvest.svg) and it's a hint how big areas may be involved). Smaller areas can be dynamically hidden as in case of military areas (way_area comes to the rescue).

What zoom level do you think would be better to start with?

**Comment by imagico** [comment]
> Could you give some examples of such problems?

Not off hand - this is simply very rare in maps because it does not work well.  If you disagree i would suggest you look for examples where it works.

**Comment by kocio-pl** [comment]
Sure, I will check them later. Also if you will find some counterexamples or some documents regarding outlines without the area fill, drop a line here.

**Comment by pnorman** [comment]
It needs to be possible to gain an understanding of the map without a legend.

How are other maps representing aquaculture and are there any standard ways to do so?

**Comment by math1985** [comment]
I agree the proposed rendering isn't really clear, and map users also won't be able to learn easily what it means.

The general tendency seems to be that this PR is not good (enough) for merging, and it's not really clear how it can be improved, so I guess closing the PR is the only thing I can do now.

I'd be happy to look at a new effort if new ideas come up, of course.

**Pull request closed without merging**
