### PR TITLE
added historic aircraft rendering

### LINKED ISSUE #3518: Render historic=* POI's
Tags historic=tank and historic=locomotive are currently not rendered, even though they are significant local landmarks that are also of public interest in the map. Could they, along with other missing historic=* POI's, be rendered either with some kind of generic historic POI icon or a more specific icon?

### PR DESCRIPTION
**Pull request by alexriabtsev**
Fixes #3518 (partly)

Changes proposed in this pull request:
- added rendering for historic_aircraft

Test rendering with links to the example places:

Before

After

### CODE REVIEW

**Comment by kocio-pl** [comment]
I'm happy to see you making the code and I'd like to test it, but there are some things to clean before that:
- first of all, the code involves `historic=airfield` (with just a few such objects...), not `historic=aircraft` :-)
- I would rename the icon to `aircraft.svg` for sure, we don't have to stick with original name, it should fit the code of OSM Carto
- there is unused `airfield-15.svg`, it should be just removed
- the before/after images are missing
- there are added spaces after few lines with `CASE WHEN tunnel IN ('yes', 'culvert')`, which should not be touched at all
- z16 seems way too early to show single aircrafts, for such a small objects z18 should work much better

**Comment by alexriabtsev** [comment]
I didn't get BEFORE/AFTER image but fixed everything else

**Comment by jeisenbe** [comment]
This PR would add a brown icon shaped like a propellor plane, seen from above. 

I’m concerned that this could be confused with an airstrip, airfield or aerodrome - commonly these have a similar icon. Most of our icons which represent man-made objects are shown from the side.

Also, adding this feature would suggest that we might also need to render similar icons for other `historic=` objects which are about as common, such as `historic=wreck`, `historic=cannon`, `historic=locomotive` (See https://wiki.openstreetmap.org/wiki/Key:historic). Later this could lead to adding `historic=tank`, `historic=ship`, `historic=vehicle` and others, if we do not have a clear criteria. 

See the open issues #3635 “Too many icons” and #3880 "Symbol and label prioritization” for the general discussion that needs consensus.

**Comment by HolgerJeromin** [comment]
Just to have the icon in the comments:
image

**Comment by alexriabtsev** [comment]
> This PR would add a brown icon shaped like a propellor plane, seen from above.
> 
> I’m concerned that this could be confused with an airstrip, airfield or aerodrome - commonly these have a similar icon. Most of our icons which represent man-made objects are shown from the side.
> 

this icon was proposed in the original discussion. There is no problem to change svg in the folder when the community agrees on the different one.

> Also, adding this feature would suggest that we might also need to render similar icons for other `historic=` objects which are about as common, such as `historic=wreck`, `historic=cannon`, `historic=locomotive` (See https://wiki.openstreetmap.org/wiki/Key:historic). Later this could lead to adding `historic=tank`, `historic=ship`, `historic=vehicle` and others, if we do not have a clear criteria.

the idea was/is to visualize  one of the most wide-spread tag (see original issue). And yes, I would agree that this shouldn't be the only historic  tag to be visualized.

**Comment by alexriabtsev** [comment]
@kocio-pl if you don't mind add 'hacktoberfest-accepted' label for PR when accepted, please.

**Comment by kocio-pl** [comment]
Since we use completely different color for transportation objects, I don't see how this could be misinterpreted as airstrip or airfield (let alone aerodrome, which has different, more contemporary shape). This shape is OK for me, since looks more "historic" than aerodrome and it fits [our guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines), but I see no problem if someone proposes replacement. 

One missing thing to fix however should be to rescale it to 14x14 px (it looks in the code it's still 15 px square). Another question is what problem do you have with making images, do you need some help with it?

I don't get what is this tag for? I probably misunderstood you and added it now, so let me know, please, so I don't flip it back and forth...

**Comment by alexriabtsev** [comment]
> Since we use completely different color for transportation objects, I don't see how this could be misinterpreted as airstrip or airfield (let alone aerodrome, which has different, more contemporary shape). This shape is OK for me, since looks more "historic" than aerodrome and it fits [our guidelines](https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#map-icon-guidelines), but I see no problem if someone proposes replacement.
> 
> One missing thing to fix however should be to rescale it to 14x14 px (it looks in the code it's still 15 px square). Another question is what problem do you have with making images, do you need some help with it?
> 
> I don't get what is this tag for? I probably misunderstood you and added it now, so let me know, please, so I don't flip it back and forth...

thanks for your reply @kocio-pl! I would appreciate help with images as I'm not designer guy at all 👍 I can replace the image if I get the correct one.

Hacktoberfest is every year movement in open-source community. You can read more at https://hacktoberfest.digitalocean.com/

**Comment by kocio-pl** [comment]
They say about "valid pull requests", so I guess the tag is OK.

I'm not sure if I understand you, but this is not about graphics, but rather basic testing. Are you able to open Docker containers and view the proper area in Kosmtik? Then a simple screenshot should work. Rescaling icon might be probably easily done in Inkscape, but I guess editing SVG by hand might work too.

**Review by imagico — CHANGES_REQUESTED** [review]
Thanks for submitting a pull request.  There are some technical issues with it - as pointed out by @kocio-pl but this is not the main problem.

I see the following issues currently speaking against accepting this here.  Some of them have already been mentioned by @jeisenbe, many of them also reflect general problems mentioned previously in the discussion in #3635.  Specifically:

* the symbol you chose is not an intuitive representation for what it is supposed to represent, namely a non-functional aircraft.  Accordingly there is a high risk of map users mistaking the rendering for representing something related to functional aircraft.  The choice of color for the symbol does not solve this because the color systematics for symbols in this style are not very intuitive either.
* no overall concept of common base design for symbology of historic artefacts has been presented, instead this is built on an ad hoc local  'good enough' concept of symbology design - which is exactly the problem that has led us to #3635 in the first place.
* our symbol and label prioritization is essentially broken (#3880) and adding more baggage to it without actually fixing it will only aggravate the problem.
* we currently have no consensus on the future of point symbols in this style as shown in #3635 and discussion on this confirms this lack of consensus is still ongoing.  We need to resolve this and develop common goals and a common vision for the future of POI symbol display and just adding more of them does not help in that regard.

This is all obviously not your fault in developing this.  Generally speaking choosing a POI symbol addition for the first PR is rarely a good idea because at the current state of this style this is a very difficult thing to do well.

**Comment by imagico** [comment]
@kocio-pl - please document labels with a meaning that is not intuitively clear to everyone.

**Comment by kocio-pl** [comment]
What do you mean, is there any documentation for tags?

**Comment by imagico** [comment]
All labels can have a description: https://github.com/gravitystorm/openstreetmap-carto/labels

**Comment by kocio-pl** [comment]
While waiting for @alexriabtsev regarding icon rescaling and test rendering (please post a comment if you need some help), just some quick comments:

1. No icon is perfect, this is symbolic by definition. Let's look at you own recently merged icon design as an example: 

https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/office/consulate.svg

What does it represent? Is this some `office=government`? Some secretary of town hall maybe? It's not clear at all. Historic aircraft icon is far more solid in that respect, that it shows an actual physical object, not the abstract institution.

2. Prioritizing things is about tuning things, not a goal in itself. Moreover #3880 is just an general idea which has no guidelines what is more important and why, let alone having the code, so it might take next months or years before it launches - if ever. That is not a convincing reason for everybody else to hold on, especially when the code for this one is almost ready.

3. #3635 is similar - the fact, that some people have some general ideas written, is still just a draft as 400+ other open tickets, not even a guideline. I have also just found out that you are unconsistent in how do you treat your own PR (#4168) and what others try to do - it introduces a new icon and there's not even a mention about this ticket. Could you please explain that?

**Comment by imagico** [comment]
Please keep the discussion here on topic.  If you want to discuss consensus based decision making we have #3951, if you want to discuss strategy for POI symbols rendering we have #3635.  If you need clarification on what #3880 is about just ask there.  And if you want to bring up a topic that is not part of any of those topics and that is not of concern to this PR please open a new issue.

**Comment by kocio-pl** [comment]
I just replied to the topics you have introduced and as shortly as you, so I guess it makes sense here. If you think only 1. is relevant, please don't start any other topics to begin with.

**Comment by alexriabtsev** [comment]
> While waiting for @alexriabtsev regarding icon rescaling and test rendering (please post a comment if you need some help), just some quick comments:
 yeah, I would appreciate help! thanks in advance!

**Comment by kocio-pl** [comment]
What help do you need exactly? Please let me know.

Resizing image in Inkscape should be easy, probably this could help you:

https://designbundles.net/design-school/how-to-resize-an-image-in-inkscape

I also believe changing numbers from 15 to 14 in SVG in text editor might work, but I just have not tested it.

When it comes to testing environment, we have instructions, and I believe Docker installation should be the easiest:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md

**Comment by alexriabtsev** [comment]
OK, I resized svg

**Comment by kocio-pl** [comment]
Great! What about test rendering? Do you need some more support?

**Comment by alexriabtsev** [comment]
image
I guess everything is fine?

**Comment by kocio-pl** [comment]
This is only about basic code consistency. What we need now is to make visual test how that change really works, so you need to import relevant area with historic aircrafts (you can easily export that data from small area - use https://www.openstreetmap.org/export or some country data where you can find them) and look here:

https://github.com/gravitystorm/openstreetmap-carto/blob/master/DOCKER.md#test-rendering

**Comment by alexriabtsev** [comment]
OK, I'll try to. Never done this before

**Comment by pnorman** [comment]
Closing as abandoned - we never got a test rendering.

**Comment by aceman444** [comment]
That is sad.

**Pull request closed without merging**
