### PR TITLE
Do not render link roads until z11

### PR DESCRIPTION
**Pull request by math1985**
This improves rendering on mid zoom levels by smoothing up the highways.

### CODE REVIEW

**Comment by matkoniecz** [comment]
I worry a bit about big T shaped junctions causing problems like https://github.com/hotosm/HDM-CartoCSS/issues/236

Is it possible that in some places on Z10 motorways or trunks will appear disjointed after hiding link roads?

**Comment by math1985** [comment]
There will be tiny gaps, like you can see on HOT: http://www.openstreetmap.org/?#map=10/50.0077/20.1551&layers=H
I think the gaps are so small on z10 that they are preferable over the strange bumps on the roads we have now: http://www.openstreetmap.org/?#map=10/51.5087/4.5133

**Comment by math1985** [comment]
Can somebody please review this? I really dislike the effect the link roads currently produce.

screen shot 2017-08-27 at 10 50 01

**Comment by pnorman** [comment]
I'd prefer z10, but am okay with trying z11.

**Pull request merged**
