### PR TITLE
render amenity=place_of_worship as a primary tag

### LINKED ISSUE #1193: amenity=place_of_worship without building=* is now not rendered as area
amenity place_of_worship closed_way

### PR DESCRIPTION
**Pull request by mkoniecz**
fixes #1193 (fixes a bug in SQL query)

how it was (old PoW style) --> after this PR (how it was supposed to be now)
amenity place_of_worship closed_way bay - powfix

how it is (current PoW style) --> after this PR (how it was supposed to be now)
amenity place_of_worship closed_way master - powfix

and for PoW on building:

old -> new
amenity place_of_worship building closed_way bay - powfix

current -> new
amenity place_of_worship building closed_way master - powfix

### CODE REVIEW

**Comment by polarbearing** [comment]
Thanks @mkoniecz. Your helper tool is nice to check the colours, however it would be good to see the following cases in context and with a typical building shape:

- PoW alone as non-building area
- PoW non-building area with a PoW-building and a non-PoW-building on top

It would also bee good to have a plan how a landuse=religious could look like being rendered behind those cases, as the support for it seems to be increasing.

**Comment by mkoniecz** [comment]
@polarbearing - it is a good idea, in fact I am planning to make good test data representing full range of what is rendered by the style. It is obvious that testing with real-world data is too inefficent, before this release nobody checked amenity=place_of_worship as a primary tag - despite the fact that rendering of this case was supposed to be improved.

But this is purely a hotfix - rendering rules were not changed and rendering style is already tested (or at least it was supposed to be tested) before merging PR with building colour change.

**Comment by math1985** [comment]
> before this release nobody checked amenity=place_of_worship as a primary tag

I did, but I assumed the current behaviour was @pnorman's intention.

See also #532, but no decision has been taken on whether it makes sense to have this file in the repository or not.

**Comment by math1985** [comment]
> I did, but I assumed the current behaviour was @pnorman's intention.

POW without building tag is in fact part of my test suite, which I now added to #532.

**Comment by nirvn** [comment]
@math1985 this is quite a significant regression for many parts of the world. Could the fix be committed to the main openstreetmap tiles now?

**Comment by math1985** [comment]
That's up to @gravitystorm.

**Pull request merged**
