### PR TITLE
add icon for shop=pet, remove shop=pets

### PR DESCRIPTION
**Pull request by nebulon42**
Adds an icon for `shop=pet` and also removes SQL logic for `shop=pets` that somehow was in too (`shop=pets` has no wiki page and 18 usages on taginfo).

before
no icon rendered

after
pet_shop

### CODE REVIEW

**Comment by kocio-pl** [comment]
Yummy - go for it! =}

**Comment by math1985** [comment]
I support merging, but waiting for #1311.

**Comment by matkoniecz** [comment]
@nebulon42 

> shop=pets that somehow was in too 

It used to be more popular then http://josm.openstreetmap.de/ticket/10594 happened :)

Shop values used more than 100 times were added to list of values displayed as purple dot, with some obvious exceptions. Since this time tagging changed a bit.

**Comment by nebulon42** [comment]
I see, so should I remove it or leave it in?

**Comment by matkoniecz** [comment]
Keep this change, there is no reason to render it now.

**Comment by nebulon42** [comment]
Just in case: Rebased.

**Comment by math1985** [comment]
Merged (just before your rebase).

**Comment by nebulon42** [comment]
That means that you took care of the rebase? Fine to delete the branch?

**Comment by math1985** [comment]
> That means that you took care of the rebase? Fine to delete the branch?

Yes. The branch can be deleted.

**Comment by nebulon42** [comment]
It seems that we have lost the SQL for `shop=books` somehow. It is again displayed as `other` in master now.

**Comment by math1985** [comment]
> It seems that we have lost the SQL for shop=books somehow.

Fixed.

**Comment by kocio-pl** [comment]
A variation of this could be used for amenity=veterinary (14k on taginfo, so very useful). The simplest form would be color changing from "shop" to "medical", but maybe also adding a circle around (like in hospital) would be more clear?

**Comment by nebulon42** [comment]
I also thought about this, but I am not a big fan of reusing identical icons and also not a too big fan of the circle. I tried a few variations for veterinary already, but none worked so far. There is https://github.com/nebulon42/osmic/issues/16 so maybe it is useful to discuss possible variations there.

**Pull request closed without merging**
