### PR TITLE
[WIP] Switch to ST_PointOnSurface

### LINKED ISSUE #1644: Switch to ST_PointOnSurface?
In vector tiles, polygons cannot be used for labeling, as polygons are clipped to the vector tile bounds.

This is a particular problem for non-PostGIS datasources, but for PostGIS ones, the standard solution is to use ST_PointOnSurface. #349 found that it was not really better or worse than Mapnik label placement.

https://github.com/gravitystorm/openstreetmap-carto/issues/349#issuecomment-36590153 raised the possibility of performance concerns. I am not sure, but there are a couple of ways this can be addressed
1. Appropriate use of `!bbox!`. `(SELECT ST_PointOnSurface(way) AS way FROM planet_osm_polygon) AS p` does not work because the geometry filtering condition used is `ST_PointOnSurface(way) && !bbox!`.
   
   The appropriate way to write the query is
   
   ``` sql
   (SELECT
   ST_PointOnSurface(way)
   FROM planet_osm_polygon
   WHERE way && !bbox!
     AND name IS NOT NULL
   ) AS p
   ```
   
   This will then use indexes to limit the data fetched, with a second filtering taking place in the outer select added by Mapnik. A functional index on `ST_PointOnSurface(way) WHERE name IS NOT NULL` could also help.
   
   I don't know if @mrwojo did this when testing. If not, it could easily explain any performance differences.
2. Where this is both a point and a polygon layer, these can be combined into one query with `UNION ALL`

### PR DESCRIPTION
**Pull request by matthijsmelissen**
Resolves #1644.

This is a necessary step towards vector rendering (see #1644).

This is a second trial of #3228, based on the word by @pnorman in #3233.

This is a first step, once we have this than we can probably merge the point and poly layers (for example amenity-points and amenity-points-poly).

### CODE REVIEW

**Comment by matthijsmelissen** [comment]
@pnorman Would you be able to review this?

**Comment by imagico** [comment]
The comments from #1644 regarding label placement quality still apply.

**Comment by jeisenbe** [comment]
I’ve read through the comments on #1644, where @imagico concluded with:

“My main point here is that ultimately ST_PointOnSurface() is going to be a
dead end regarding quality label placement but Mapnik likely is as well so
it really does not matter.”

Is this still correct?

**Comment by imagico** [comment]
Can we close this since most of it is superseded by #3712 and the rest would probably be easier to implement with new PRs?

**Pull request closed without merging**
