### PR TITLE
Fix 'integer out of range' error on z0

### LINKED ISSUE #1289: integer out of range
Whlie trying to render zoom level 0 using v2.27.0, I get this error:

```RuntimeError: ERROR:  integer out of range```

On Postgres' logs I can see the failing query:

```sql
SELECT ST_AsBinary("way") AS geom,"feature" FROM (SELECT
    way, name, way_pixels,
    COALESCE(landuse, "natural") AS feature
  FROM (SELECT
      way, COALESCE(name, '') AS name,
      ('landuse_' || (CASE WHEN landuse IN ('forest') THEN landuse ELSE NULL END)) AS landuse,
      ('natural_' || (CASE WHEN "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock') THEN "natural" ELSE NULL END)) AS "natural",
      way_area/(156543*156543) AS way_pixels
    FROM planet_osm_polygon
    WHERE (landuse IN ('forest')
      OR "natural" IN ('wood', 'sand', 'scree', 'shingle', 'bare_rock'))
      AND way_area/(156543*156543) > 0.01
      AND building IS NULL
    ORDER BY z_order, way_area DESC
  ) AS features
) AS landcover_low_zoom WHERE "way" && ST_SetSRID('BOX3D(-20037508 -20037508,20037508 20037508)'::box3d, 900913)
```

The problem being that `156543*156543` (24505710849, ~23Gi) is too big for a PG integer. I'm still using PG 9.3, but I don  know if this is part of the problem.

### PR DESCRIPTION
**Pull request by math1985**
This resolves #1289

### CODE REVIEW

**Comment by pnorman** [comment]
Looks good to me, from my phone. The `NULLIF` isn't for z0 but is for some queries which request with a pixel size of 0.

**Comment by math1985** [comment]
@pnorman or @gravitystorm Can you merge this?

**Comment by math1985** [comment]
Rebased.

**Comment by pnorman** [comment]
I'm having node-mapnik issues so can't test.

**Pull request merged**
