### PR TITLE
Add icon for amenity=bench and amenity=waste_basket

### LINKED ISSUE #194: Add rendering for amenity=bench
I think "amenity=bench" should be rendered, specially those that are mapped as ways, since that often means long stone benches that also act as a barrier.

Bench icons could start showing at level 20, while bench ways should start at 18.
Maybe a brownish color for both symbols and lines, or use the "color" tag if available (is that possible?) or even a color depending on the material (stone=grey, wood=brown, etc).

### LINKED ISSUE #418: Add rendering for amenity=waste_basket
Popular tag is not rendered on the map.
Please add this tag.

http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dwaste_basket

### PR DESCRIPTION
**Pull request by math1985**
* Add icon for amenity=bench from z18 (resolves #194)
* Add icon for amenity=waste_basket from z19 (resolves #418)

These icons are taken from the SJJB repository, so they are still not aligned to the pixels.

Preview:
screenshot from 2015-01-30 21 30 06

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
At least the bench should be included direct as SVG.

**Comment by floscher** [comment]
> At least the bench should be included direct as SVG.

:+1:, I've opened pull request math1985/openstreetmap-carto#5 for this.

**Comment by nebulon42** [comment]
As with #1240 for picnic table I'm not sure if the bench should be slightly thicker? With 1.5px thickness it would look like that (more blurry of course):
bench_thicker
([bench-16.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/bench-16.svg))

**Comment by pnorman** [comment]
I prefer 1.5 pixels

**Comment by nebulon42** [comment]
This would be my proposal for waste basket ([waste-basket-16.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/waste-basket-16.svg)):
waste_basket

**Comment by math1985** [comment]
I merged in the svg bench icon.

I don't particularly like the bin icon - not sure what to do about it, maybe it would look better with a straight bottom?

**Comment by nebulon42** [comment]
Maybe this: waste-basket-16

**Comment by mkoniecz** [comment]
@nebulon42 - I like this icon.

**Comment by math1985** [comment]
Yes, looks better to me. Thanks!

**Comment by nebulon42** [comment]
I have updated the corresponding icon: [waste-basket-16.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/waste-basket-16.svg)

**Comment by math1985** [comment]
I updated the PR with both svg icons.

**Comment by nebulon42** [comment]
To me bench.16.svg is still displayed as 1px version. Did you mean to keep that?

**Comment by math1985** [comment]
>  Did you mean to keep that?

No I forgot that one, it should be updated now.

**Comment by HolgerJeromin** [comment]
A bench is larger than a basket. They are often near. It looks strange if the basket has more visual weight.

**Comment by nebulon42** [comment]
Normally, I'd like to use every pixel of the restricted 16px frame for the icon, but I agree in a way. I have reduced the profile of the waste basket a bit: waste-basket-16

I like the low profile of the bench. An option would be to add a back-rest to it as is done in the Humanitarian style, but I'm not too fond of that.

**Comment by daganzdaanda** [comment]
The new waste basket looks good to me.
I'm happy that benches will appear on the map soon!
But let's not forget that some benches are tagged on lines. (See also https://github.com/gravitystorm/openstreetmap-carto/issues/194#issuecomment-25430056 ) I would like to see those, too, but I have no good idea. Just a fat grey line, maybe with the symbol in the middle?

**Comment by HolgerJeromin** [comment]
Yes. I would show the Icon for benches as ways, too. But showing the dimension seems not easy possible, so drop this information.

**Comment by math1985** [comment]
How should we do that? Does it make sense to add an extra query specifically for linear benches?

**Comment by math1985** [comment]
Added new bin icon and updated preview.

**Comment by mkoniecz** [comment]
Maybe bin icon can be even smaller?

**Comment by math1985** [comment]
I'd prefer to leave the icon as is.

**Comment by mkoniecz** [comment]
I propose moving these two icons to .amenity-low-priority to avoid blocking more important icons and labels.

**Comment by althio** [comment]
The guidance https://github.com/gravitystorm/openstreetmap-carto/pull/1282#issuecomment-74496085 about icon size and weight is IMO very applicable here. As mentioned earlier https://github.com/gravitystorm/openstreetmap-carto/pull/1249#issuecomment-71399247 weight of bin vs bench is strange.

We do not have practical guidelines yet, just general guidance.
This present issue on bench / bin can be a useful practical case to determine size / weight / priority / tiers of icons. First in a 'fight' bench vs bin, and also as in bench&bin vs other icons.

This is very related to @mkoniecz last comment
> moving these two icons to .amenity-low-priority to avoid blocking more important icons and labels

**Comment by daganzdaanda** [comment]
> moving these two icons to .amenity-low-priority 
definitely!

**Comment by math1985** [comment]
Rebased.

**Comment by mkoniecz** [comment]
@math1985 Can you move these two icons to .amenity-low-priority to avoid blocking more important icons and labels?

**Comment by math1985** [comment]
Sorry I forgot, done now.

**Comment by mkoniecz** [comment]
It is hard to find place with fully mapped benches and waste baskets, but in such places rendering of these objects is too prominent. I would propose pushing benches to z19 and waste baskets to z20.

http://www.openstreetmap.org/#map=19/50.07081/19.91222

selection_002
selection_003


Also, is it possible to ensure than benches have priority over waste baskets?

http://www.openstreetmap.org/#map=19/50.06866/19.98983

selection_004
selection_005

**Comment by pnorman** [comment]
tile.osm.org doesn't render z20. I'd be against any changes for zoom level 20, except if [continuing a size progression](https://github.com/gravitystorm/openstreetmap-carto/pull/978/files#diff-5d9237083037cf1d6d91c329a0ff61adR1971). These changes would only be visible to those running their own deployment of osm-carto.

We've used z17 for the cutoff at which everything renders for other features, and I'd prefer to do so for benches and bins. If we feel benches/bins are too strong, perhaps reducing the size? Saying z19 only feels like a cartographic cop-out.

**Comment by mkoniecz** [comment]
> tile.osm.org doesn't render z20

Right, I forgot. Than I repeat my

> Maybe bin icon can be even smaller?

**Comment by nebulon42** [comment]
I made a smaller version of waste basket: https://github.com/nebulon42/osmic/blob/master/outdoor/waste-basket-10.svg

**Comment by math1985** [comment]
Rebased, and made the following changes:

* Render waste_basket smaller
* Render bench only from z19
* Give bench priority over waste_basket

This is again ready for review.

**Comment by matkoniecz** [comment]
I would support merging. @math1985 - would it be OK for me to squash 3 commits from this PR into one before merging? It is case of "improve previous commit" rather than separation of independent changes.

**Comment by math1985** [comment]
Yes, please squash. In general I think it's clearer if the reviewer squashes rather than the author of the PR, as it makes it easier for the reviewer to see what has changed.

**Comment by matkoniecz** [comment]
Merge done via cli in https://github.com/gravitystorm/openstreetmap-carto/commit/376a1b4a230a12faff5eb6979f7822da3029a13f

**Pull request closed without merging**
