### PR TITLE
Add name to dock

### PR DESCRIPTION
**Pull request by boothym**
#2557 renders a name on waterway=dock 

I haven't tested this PR so I'd be grateful if someone could render this for me. It's a straightforward change so hopefully there's no issues with it.

### CODE REVIEW

**Comment by math1985** [comment]
Thanks for your pull request! However, waterway=dock is not in https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L2050 so this won't work.

Setting up rendering yourself is really the best way to create pull requests. If there anything we can help you with setting it up, let us know.

**Comment by boothym** [comment]
The reason I created this PR without testing is because the issue hadn't been responded to for a couple of months, so I thought I'd give it a try myself. 
At the moment I don't have the time or inclination to learn how to set up a renderer. I was hoping someone else who knows what they are doing would be kind enough to render it at some point.

>However, waterway=dock is not in https://github.com/gravitystorm/openstreetmap-carto/blob/master/project.mml#L2050 so this won't work.

Is there an example in the code I can copy to help me add waterway=dock correctly to that file? I looked at basin and dam but not exactly sure how what each section does...

**Comment by nebulon42** [comment]
Your honesty is much appreciated but I find your stance problematic. We value every contribution and I myself have also submitted some quick changes to other projects before testing them as a first-time edit. But we have contribution guidelines (https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#pull-requests) and since this is your second PR regular contributors should try to follow them. If you say "I don't have the time or inclination to learn how to set up a renderer" I'm tempted to answer "I don't have the time or inclination to merge your PR."

You can expect any help you need, but you should not expect others to do work for you that you don't want to do. The time you have to invest to find out how to adjust the code with trial-and-error and without being able to inspect the result would be larger then setting up a small database and have Kosmtik up and running. Have a look at https://ircama.github.io/osm-carto-tutorials/. It should get you started.

Regarding your question @math1985 has already pointed you to the particular query. Have a look at which waterway values are handled by this query (both in the SELECT and in the WHERE part) to figure out where you have to add the lock part.

**Comment by imagico** [comment]
I support the point made by @nebulon42 here, your enthusiasm is great @boothym but you cannot get others to address your issue with priority by creating an untested pull request.  Adding one or two lines of code to the style is not what takes time with implementing such a change.

If you would like to see issues fixed other developers no not give high priority to you need to invest the time to set up a testing environment.  As said previously if you have specific problems with doing that just ask.

If you can't or do not want to do that you can still productively participate in development here by finding and analyzing problems, evaluating the suitability of tags to be used in rendering, designing icons and patters and similar stuff.  You can also improve tag documentation on the wiki which is often an issue.  But you will depend on the priorities set by others here regarding what is actually implemented.

**Comment by boothym** [comment]
>but you cannot get others to address your issue with priority by creating an untested pull request

Not looking for priority - as I said before, no one had responded for a couple of months so I gave it a go myself for what I thought was a fairly straightforward issue, no harm done. And I'm hardly going to start making PRs for big changes.

>The time you have to invest to find out how to adjust the code with trial-and-error and without being able to inspect the result would be larger than setting up a small database and have Kosmtik up and running. 

Just wondering, do you have a rough idea of how long it would take to get a renderer set up?

Anyway, I've made some changes so I'll leave the PR up in case anyone wishes to render it. If you don't want it here then feel free to delete.

**Comment by imagico** [comment]
> Just wondering, do you have a rough idea of how long it would take to get a renderer set up?

No, i have not done this in some time and even if i did this would not be indicative for someone doing this the first time. Depends on you background, the system you work on and other stuff.

Anyway - in my opinon, if you are interested in rendering of OSM data, no matter if specifically in the context of openstreetmap-carto or more generally, this is well invested time since you learn about and get to know a lot of important tools in that context.

**Comment by SomeoneElseOSM** [comment]
> Just wondering, do you have a rough idea of how long it would take to get a renderer set up?

When testing https://switch2osm.org/manually-building-a-tile-server-16-04-2-lts/ or similar in a new VM I normally allow a couple of hours (mostly for Natural Earth and software downloads).  If it's the first time through, I'd allow a couple more hours.
https://wiki.openstreetmap.org/wiki/User:SomeoneElse/Ubuntu_1604_tileserver_load might also be useful as it also mentions virtual machines.

**Comment by pnorman** [comment]
Closing as I gather @boothym doesn't intend to test and finish this off.

**Pull request closed without merging**
