### PR TITLE
Split up roads.mss, refactor road colour script

### PR DESCRIPTION
**Pull request by jdhoek**
The generated colour values now reside in road-colors-generated.mss, and
have been removed from roads.mms. road-colors-generated.mms is generated
by the colour script, and should not be edited manually. To regenerate
it, edit road-colors.yaml and run:

```
./scripts/generate_road_colours.py > road-colors-generated.mss
```

The original output of the colour script provided some info about the
amount of loss caused by converting from CIE lch to RGB. To get this
output, call the script with the `-v` flag (for verbose).

### CODE REVIEW

**Comment by jdhoek** [comment]
This replaces the refactoring part of #2220.

Related to #2085.

**Comment by pnorman** [comment]
:+1: in principle, but I haven't done a code review yet

**Comment by pnorman** [comment]
I opened https://github.com/jdhoek/openstreetmap-carto/pull/1 with some changes and support for road shields

Can tertiary not be special-cased in `generate_shields.py` and generated from `generate_road_colours.py`? If there's no way to easily do so it's okay as it is, but then we should add a comment to generate_road_colours.py about where the rgb hex values for it come from

**Comment by jdhoek** [comment]
@pnorman Great, I'll have a look.

**Comment by HolgerJeromin** [comment]
We could check the status of road-colors.yaml (that it generates the same file as the checked in version)  with Travis. But this could be done later.

**Comment by jdhoek** [comment]
With the help of @pnorman `generate_shields.py` now uses the settings from `road-colors.yaml` as well. For both generating files: their output is unchanged.

**Comment by pnorman** [comment]
> `generate_shields.py` now uses the settings from `road-colors.yaml` as well.

Thanks. I thought about doing this but didn't want to get into that script as well.

**Comment by jdhoek** [comment]
Turned out to be a minor change in that script, so it seemed beneficial. I did alter the spacing to align with Python standards and `generate_road_colours.py`, [but only a handful of lines were actually altered](https://github.com/gravitystorm/openstreetmap-carto/pull/2220/commits/d13cb8892f7a2565a5026f986b7e9e9fe5880ab4?w=1).

**Comment by math1985** [comment]
Great work!

**Pull request merged**
