### PR TITLE
use variables in font definitions

### PR DESCRIPTION
**Pull request by nebulon42**
Carto is now capable of expanding them.
Requires carto >= 0.17.2, carto 0.18 is our requirement.

cc @sommerluk

### CODE REVIEW

**Comment by pnorman** [comment]
This is incompatible with our 3.x requirements, but because there are no cartographic changes that's okay.

**Comment by sommerluk** [comment]
Looks good. Thanks for the patch!

**Comment by kocio-pl** [comment]
Are we ready to merge this patch now?

**Comment by nebulon42** [comment]
Yes, this would be against the feature freeze if it would have cartographic changes. But without we just won't backport it to the 3.x series.

**Pull request merged**
