### PR TITLE
Adding amenity=ferry_terminal icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/869.

Rendered like bus stop - z=16:
ferry-z16

z>=17 (with osmic icon):
ferry-z17-osmic

### CODE REVIEW

**Comment by kocio-pl** [comment]
Edited version, based on osmic with top inspired by MapQuet Open icon (both are too solid and look rather like bollard for me):
ferry-z17-my-turkawka
ferry-z17-my-pliszka

**Comment by imagico** [comment]
I don't think there is a gain from adding a large specific for this purpose.  The meaning is perfectly clear with just a generic square symbol which uses less space and adds less clutter to the map.

**Comment by matkoniecz** [comment]
Yes, especially that symbol is not really recognisable. Generic square seems much better.

**Comment by kocio-pl** [comment]
Hm, you may be right. However I'd like to hear if there are some counterexamples, where just the dot with label would be suboptimal choice maybe?

**Comment by math1985** [comment]
At larger terminals, such as [here](http://www.openstreetmap.org/#map=16/51.9740/4.1302), it might not always be immediately clear which building is the ferry terminal.

**Comment by kocio-pl** [comment]
So maybe we should show this icon just for areas?

**Comment by ximex** [comment]
the icon itself looks good.

**Comment by math1985** [comment]
Is is not possible to come up with a simpler symbol for 'ship'? The 'terminal' concept will be clear enough from the ship, I think.

**Comment by kocio-pl** [comment]
Any ideas are welcome. How should it look like? 

I can also split this PR into generic blue square part, which is not controversial, and we can add the icon later, once there is one drawn and approved.

**Comment by matkoniecz** [comment]
I think that splitting is a good idea.

**Comment by pnorman** [comment]
Not sure how well it works - it can't always be distinguished from a bus stop

image

Remember, the marked points are not on the water's edge.

See for example, [Tsawwassen](http://www.openstreetmap.org/node/660826491). Now, this should probably be an area, but the centroid of the area isn't going to be at the coastline either.

[Sidney International](http://www.openstreetmap.org/way/136695687) is an area, as are [Swartz Bay](http://www.openstreetmap.org/way/131450912) and [Langdale](http://www.openstreetmap.org/way/299739618).

A ferry icon is useful at lower zooms to show where the terminal is, but at high zooms its pretty eident where the road meets the water. If we wanted an icon there, we should do it based on where the lines touch, not ferry terminals, which are different.

**Comment by kocio-pl** [comment]
I guess the best choice for terminal icon could be [something like what we will shortly use for the ford](https://github.com/gravitystorm/openstreetmap-carto/pull/1625): just the water and the arrows for showing there is a way over them. However the question is if we want to distinguish those icons, and if yes - in what way should they be different?

**Comment by kocio-pl** [comment]
What about simpler shape like this:
ferry-arrows

**Comment by matkoniecz** [comment]
How it works for examples from https://github.com/gravitystorm/openstreetmap-carto/pull/1673#issuecomment-125102218 ?

**Comment by kocio-pl** [comment]
Sidney:
ferry-arrows-sidney

Swartz Bay:
ferry-swartz

Langdale:
ferry-langdale

Tsawwassen node is overcrowded with tags (ferry_terminal+locality+traffic_signals), so not suitable for testing this icon.

**Comment by kocio-pl** [comment]
Maybe we should use the aeroway color for ferry terminal areas too. I guess this might be even used for all the transport terminals (like bus stations).

**Comment by sabas** [comment]
Rendering the area could be useful.
Should the single berthing points inside the terminal be tagged differently?
Sample area http://overpass-turbo.eu/s/aW6

**Comment by jojo4u** [comment]
@sabas From what I understand on a complex facility amenity=ferry_terminal should be the whole area (buildings, parking spaces), waterway=mooring, mooring=ferry should the the point where highway and ferry meet. This extends the meaning ferry_terminal a bit but in 2007 there was not so much hindsight (http://wiki.openstreetmap.org/wiki/Talk:Proposed_features/Ferry_Terminal)

**Comment by jojo4u** [comment]
@kocio-pl I improved Tsawwassen.
The other examples suffer from "too much highway=service", something I already fixed on Tsawwassen and will be on Swartz Bay (https://www.openstreetmap.org/note/393069)

**Comment by kocio-pl** [comment]
First I will have to learn how to tag the airport, then find out what parts ferry terminal consists of, and in the end try to find some analogies. It would be also good to study bus and railway station - or maybe also other transportation stations, to be as universal as possible. However I'm not into transportation too much and try to do few other things, so the help would be welcome. 

I just thought it would be dead easy task... =}

**Comment by matkoniecz** [comment]
Unfortunately in current state it is not ready for merge and it seems unlikely to change in the near future - so I will close it for now. 

Updated/new PRs solving this problem are welcomed!

> I just thought it would be dead easy task... =}

Almost everything is harder than it seems before starting it.

**Comment by kocio-pl** [comment]
Sure, currently I plan to start with defining airport/heliport/ferry(port) as a similar big areas.

**Pull request closed without merging**
