### PR TITLE
Travis carto update

### PR DESCRIPTION
**Pull request by nebulon42**
update carto version used for Travis and target Mapnik 2.3.0 API version specifically

### CODE REVIEW

**Comment by yohanboniface** [comment]
Upgrading carto makes sense, but not sure why targetting 2.3.0 specifically?

**Comment by nebulon42** [comment]
Normally I would use whatever is running on the tile servers. Which is 3.0.11? But because of https://github.com/gravitystorm/openstreetmap-carto/pull/2374#issue-179183022 I thought the maintainers wanted to keep Mapnik 2 compatibility.

**Comment by yohanboniface** [comment]
ah, sure makes sense!

**Comment by kocio-pl** [comment]
You mean Mapnik probably. [Carto version on the servers is currently 0.16.3](https://github.com/openstreetmap/chef/issues/39#issuecomment-249408667) - the same as in this patch.

**Comment by pnorman** [comment]
We still have to maintain 2.1 compatibility and older Carto versions too. If we want to test more recent versions we should do it in addition.

**Comment by nebulon42** [comment]
I don't remember why, could you remind me?

**Comment by kocio-pl** [comment]
I guess this is https://github.com/gravitystorm/openstreetmap-carto/issues/2198.

**Comment by nebulon42** [comment]
Ah, so it's about Tilemill again. I think this software will haunt us forever. :)

**Comment by kocio-pl** [comment]
It's rather our policy problem, since git version is already OK, but @gravitystorm [doesn't feel it's enough](https://github.com/gravitystorm/openstreetmap-carto/issues/2080#issuecomment-249803296) and I don't know if TileMill team would make a release just to satisfy this requirement.

**Comment by pnorman** [comment]
> We still have to maintain 2.1 compatibility and older Carto versions too. If we want to test more recent versions we should do it in addition.

**Pull request closed without merging**
