### PR TITLE
Drop derelict_canal rendering

### LINKED ISSUE #1003: dry canals are displayed as blue dashes
Pernamently dry derelict canal ( http://wiki.openstreetmap.org/wiki/Tag:waterway%3Dderelict_canal ) is currently displayed as blue, transparent dashes. I thing that it would be better to use some symbol that is not blue - but I have no good suggestions.

example of a current rendering: http://www.openstreetmap.org/?mlat=49.20021&mlon=16.22416#map=17/49.20021/16.22416

selection_003

### PR DESCRIPTION
**Pull request by sommerluk**
Resolves #1003

### CODE REVIEW

**Comment by kocio-pl** [comment]
Do you think it's better to just drop it now than count on wiki changes that could clarify it? There were some changes recently:

https://wiki.openstreetmap.org/wiki/Tag:waterway%3Dderelict_canal

**Comment by sommerluk** [comment]
I think indeed that dropping now it is the best solution.

**Comment by kocio-pl** [comment]
I think that you're right - it can look in many ways: filled with water, intermittent water, ditch, ditch filled with plants etc., so there's no reasonable way of rendering it. Even proposed tags with prefixes still are unclear in this regard, so we need some more precise tagging to visualize it.

**Comment by kocio-pl** [comment]
Thanks, testing looks OK.

**Pull request merged**
