### PR TITLE
Adding special shop=bag icon and removing rendering of shop=bags

### PR DESCRIPTION
**Pull request by kocio-pl**
Adding special icon for shop=bag (taken from osmic repository):

bag-19

and removing rendering of shop=bags, which is considered an error on Wiki and is much less used (~100 uses).

### CODE REVIEW

**Comment by HolgerJeromin** [comment]
Is the file naming ok? luggage.svg for bag, while not rendering shop=luggage? :-)

**Comment by kocio-pl** [comment]
I just thought the name could be preserved, but I have nothing against re-naming it accordingly.

**Comment by math1985** [comment]
Looks good, would you mind rebasing this?

**Comment by kocio-pl** [comment]
Done, should be OK.

**Comment by kocio-pl** [comment]
...and again (due to some other patch merged in the meantime).

**Comment by kocio-pl** [comment]
..and once more, this time caused by merging another my own patch. My next PR will be YAML code cleaning, I swear! =}

**Comment by kocio-pl** [comment]
Looks like there was some problem with MML - gitk told me:

```
    Merge branch 'bag' of https://github.com/kocio-pl/openstreetmap-carto
    
    Conflicts:
    	project.mml

--------------------------------- project.mml ---------------------------------
index 381e556,b18fa73..f6598b0
Binary files differ
```

Is this a real issue (like not yaml2mml script did not run) or just kind of artifact?

**Comment by kocio-pl** [comment]
Also the previous merge:

```
    Merge branch 'lowzoomcities10' of https://github.com/sommerluk/openstreetmap-carto
    
    Conflicts:
    	project.mml

--------------------------------- project.mml ---------------------------------
index 2eb7e75,dc20f4f..381e556
Binary files differ
```

**Comment by math1985** [comment]
> Is this a real issue (like yaml2mml script did not run) or just kind of artifact?

Not sure, I can't reproduce it now. Maybe something wrong somehow on my side.

**Comment by pnorman** [comment]
You can fix conflicts in project.mml by rerunning yaml2mml and `git add project.mml`. Make sure to fix any conflicts in the yaml first.

**Comment by matkoniecz** [comment]
> Is this a real issue (like yaml2mml script did not run) or just kind of artifact?

AFAIK it is a comment inserted by git during rebasing/merging where it was necessary to manually remove conflicts.

**Comment by math1985** [comment]
Yes, but in this case I see no reason for the conflict to occur in the first place.

**Pull request merged**
