### PR TITLE
Use ST_PointOnSurface for bridge names

### PR DESCRIPTION
**Pull request by pnorman**
I didn't identify any labels likely to appear on the same objects, so we shouldn't run into issues like the other cases where moving one label (e.g. shop) but not the other (e.g. addr) results in duplicates.

### CODE REVIEW

**Comment by jeisenbe** [comment]
Should the geometry still be `polygon` even though we are producing a point for labeling with `ST_PointOnSurface`, because the original geometry was a polygon?

**Comment by pnorman** [comment]
> Should the geometry still be `polygon` even though we are producing a point for labeling with `ST_PointOnSurface`, because the original geometry was a polygon?

I'll change that, although it doesn't matter that much.

**Comment by jeisenbe** [comment]
Should we also change the geometry to point for all the other layers which now use ST_PointOnSurface?

**Comment by jeisenbe** [comment]
@pnorman is this PR ready to merge?

**Comment by jeisenbe** [comment]
@pnorman there is now a merge conflict that needs resolving

**Comment by jeisenbe** [comment]
@pnorman do you have time to fix the merge conflict?

**Comment by pnorman** [comment]
Not in the next few days

**Comment by jeisenbe** [comment]
@pnorman will you have to work on this in the next month? If you are busy, I'm willing to fix the merge conflict for you, if that is acceptable.

**Comment by pnorman** [comment]
> @pnorman will you have to work on this in the next month? If you are busy, I'm willing to fix the merge conflict for you, if that is acceptable.

If you have time you're welcome to fix it.

**Pull request merged**
