### PR TITLE
preview.png update instructions for a new release

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/2362.

### CODE REVIEW

**Comment by pnorman** [comment]
We normally just use the rendering from osm.org and update as needed. I don't often have a DB with this area loaded up, so as written this would be a barrier for me doing releases.

**Comment by kocio-pl** [comment]
That's the ultimate solution (current and accurate illustration of the style), so I like to have it. But since it's not crucial part of the release process, we can also hint how to do that the way you're doing it now. The most important thing here is to make this checklist more complete, not to force anything.

**Comment by kocio-pl** [comment]
How about now? You can propose your wording if you have one.

**Comment by math1985** [comment]
Thanks!

**Pull request merged**
