### PR TITLE
fix text-dy for nightclub

### PR DESCRIPTION
**Pull request by matkoniecz**
amenity nightclub name eeeeee eeeeee ref 1 ele 8000 operator ee ee ee operator brand ee ee ee brand node v2 30 0 - dy_again 200px

### CODE REVIEW

**Comment by nebulon42** [comment]
Note that the nightclub icon seems to be the only one where a halo has sneaked in. Maybe this should be cleaned up too.

**Comment by matkoniecz** [comment]
@nebulon42 Good idea. Changed and added to this PR (as after removing halo text-dy needed to be changed anyway).

**Comment by nebulon42** [comment]
Great. Is this just something I'm seeing or why have I authored the second commit?

**Comment by matkoniecz** [comment]
@nebulon42 I set you as author as second commit as it was your idea, your icon and I am nearly sure that nothing is broken by this change (and in case that something is wrong - I am still recorded as commiter) - so I decided that giving you credit is preferable.

In case that you prefer to change it I may set myself as the author.

**Comment by math1985** [comment]
> In case that you prefer to change it I may set myself as the author.

Yes, I think it'd be less confusing to list yourself as auhor, and acknowledge @nebulon42 in the PR or commit description.

**Comment by matkoniecz** [comment]
@math1985 Changed.

**Comment by nebulon42** [comment]
I'm fine with either way or not mentioning me at all. :) I was just confused, didn't know that this is possible.

**Comment by matkoniecz** [comment]
> I was just confused, didn't know that this is possible.

```git commit --author=<author>``` allows to set arbitrary person as author of the commit - see http://git-scm.com/docs/git-commit

**Comment by pnorman** [comment]
It's best to only set an author if you're somehow applying patches from them or something involving picking their changes from other commits.

**Pull request merged**
