### PR TITLE
Use >= rather than >

### PR DESCRIPTION
**Pull request by math1985**
This brings the code in line with the coding standard

### CODE REVIEW

**Comment by pnorman** [comment]
I suppose the one question is was it intended to be `>= 16` or `>= 17`.

**Comment by math1985** [comment]
Considering the other POI zoom levels, I think probably ''>= 16'' was intended.

Updated.

**Comment by pnorman** [comment]
Should the [text zoom](https://github.com/gravitystorm/openstreetmap-carto/blob/ece00c1243b4894c8211a2ac6faf62c936b6b876/amenity-points.mss#L688) be adjusted too?

**Comment by math1985** [comment]
> Should the text zoom be adjusted too?

No, we don't render labels for the other POI on z16 either.

**Pull request merged**
