### PR TITLE
Adding shop=computer icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1416 .

computer-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
I promised to notify you when I have created a similar icon: https://github.com/nebulon42/osmic/blob/master/shop/computer-14.svg

**Comment by kocio-pl** [comment]
Thanks. =} Could you make a rendering to compare it easier? The concept is basically the same, so details matter, I guess.

**Comment by nebulon42** [comment]
Here:
computer

**Comment by kocio-pl** [comment]
It's less clear at this scale, but might work (probably I should copy your screen anyway). I guess more opinions would be needed to make the decision.

**Comment by nebulon42** [comment]
Yes, that is to be expected because I added more detail.

**Comment by kocio-pl** [comment]
I think that's rather because of the bottom part, where I have used more of perspective for the keyboard. I like your details here very much (clever!), we just have so limited space here that keeping the whole design nice at higher resolutions bites the readability at lower ones. This is a borderline case for me - I'm not sure if it's recognizable enough.

**Comment by nebulon42** [comment]
For me it's still acceptable, but you are right about bigger vs smaller sizes. I have to make sure that my icons look okay at nearly all sizes, because uses might differ. They are intended for 14px, but in the font they could be used at virtually every size. Icons that are intended for osm-carto only, don't have this requirement.

**Pull request merged**
