### PR TITLE
path/footway/cycleway - render missing surface separately, more prominent rendering for unpaved ways

### LINKED ISSUE #1765: unpaved footways on rocky areas are poorly visible
http://www.openstreetmap.org/?mlat=47.56673&mlon=12.32377#map=19/47.56673/12.32377

>But there are minor issues due to low contrast on certain background textures (i.e. scree, bare_rock) 

@geowOSM - it is better to open new issues for new issues rather than comment om closed pull requests. Commenting in open PRs is a good idea as somebody is currently working on proposal and feedback is valuable. But comments in closed PR are likely to be lost.

### PR DESCRIPTION
**Pull request by matkoniecz**
It changes rendering for highway=path/footway/cycleway.

Now there are three [buckets](https://github.com/gravitystorm/openstreetmap-carto/issues/1698#issuecomment-134938213)*:

- highway=path/cycleway/footway tagged as paved
- valid surface tag is missing
- highway=path/cycleway/footway tagged as unpaved

There are contradictory goals that I tried to satisfy:

- make unpaved footways more prominent
- fit third stage - between paved and unpaved for missing surface
- avoid making paved footways more prominent
- keep each footway type recognisable
- keep footway style less prominent than highway=tracks
- make footways visible across different landcovers
- and many additional that in this case were not highly problematic

I think that it is works fairly well (or at least better than currently and previously used style).

Footways are still too dominant in fully mapped cities, important walking routes are not visible enough, paved/unknown/unpaved are not different enough etc. But it is near limits of useing the same style used across the world (yes, there is currently no available method to display [highway=path, surface=unpaved] differently depending whatever it is an unimportant path in crowded park or the main route across the mountains).

*Yes, this link leads to comment that is worth reading.

Examples for cities:
https://cloud.githubusercontent.com/assets/899988/9492585/18a7c242-4bf9-11e5-948c-2b9460eb48fe.png
https://cloud.githubusercontent.com/assets/899988/9492587/18aae9ea-4bf9-11e5-9455-bd627c5529da.png
https://cloud.githubusercontent.com/assets/899988/9492588/18ab11fe-4bf9-11e5-99ac-59786f54a2ab.png
https://cloud.githubusercontent.com/assets/899988/9492586/18aab8c6-4bf9-11e5-850a-227b50635331.png

Outside cities:
https://cloud.githubusercontent.com/assets/899988/9492602/404eaa72-4bf9-11e5-9189-bab5509794c3.png
https://cloud.githubusercontent.com/assets/899988/9492603/40520c4e-4bf9-11e5-8628-30ab33d54d93.png
https://cloud.githubusercontent.com/assets/899988/9492604/4079d972-4bf9-11e5-96ab-398d551f8619.png
https://cloud.githubusercontent.com/assets/899988/9492605/40fb4bd8-4bf9-11e5-8280-324af165b9c1.png

fixes #1765 and #1766

BTW, for people interested in adding surface tags in their area - here is a helpful overpass query (zoom in before using "Run" button): http://overpass-turbo.eu/s/b88 This query return ways without surface tags and ones tagged with tags not documented as valid surface valies for highway=footway/path/cycleway (in nearly fully mapped regions one may start mapping also surface for other highway types).

### CODE REVIEW

**Comment by pnorman** [comment]
Should we address the big difference in strength of footway and cycleway colour in this PR? The original colour was defined as "salmon" so I don't think much thought was given to it at the time.

**Comment by matkoniecz** [comment]
> Should we address the big difference in strength of footway and cycleway colour in this PR?

It is already addressed by making cycleway less wide. I calibrated it with goal of making cycleways slightly more prominent than footways.

Widths are conveniently displayed at beginning of https://github.com/matkoniecz/openstreetmap-carto/commit/5a4089f7f50299757eaa4e93c3591a0dbe47f027

**Comment by matkoniecz** [comment]
Finding new colour should be probably done together with #1781 that itself is blocked by road redesign.

**Comment by imagico** [comment]
First thanks for working on this.

I think this suggestion is an improvement on both the semantics (i.e. having a third class) and for readability compared to the current state.

IMO however

* while it improves #1765 it does not really fix it, in particular the look of unpaved ways is still very different or dark background (forest) compared to bright background due to the very sparse dashing and therefore dominant casing color.
* I don't see much improvement in the extreme difference in heaviness of cycleways vs. footways.
* The 'undecided' line signature is very difficult to identify, it mostly looks like noise/rendering artefacts.  You have to look really closely to spot those within either paved or unpaved ways around.

My assessment regarding your goals:

* make unpaved footways more prominent: *improved, but not great*
* fit third stage - between paved and unpaved for missing surface: *check*
* avoid making paved footways more prominent *yes, but i don't consider this an important goal as long as prominence stays within reason and does not negatively affect readability of other features*
* keep each footway type recognisable: *no, even when looking hard i frequently have doubts*
* keep footway style less prominent than highway=tracks: *yes but IMO far more than necessary, footway could be at least as prominent as cycleway until this becomes an issue and a paved footway may IMO be more prominent than a grade5 track*
* make footways visible across different landcovers: *improved, but not optimal*

In total i would be for merging this to address #1766 but would consider further improvements to be highly desirable.

Is there a particular reason why you don't want to use a solid line for paved?  It would directly match the styling used for tracks so it should be fairly intuitive for the map user.

**Comment by matkoniecz** [comment]
> In total i would be for merging this to address #1766 but would consider further improvements to be highly desirable.

I agree. In that case (unlike say #1736) I ended work not because I was happy about results but because I run out of ideas and time. It results in improvements - so I submitted PR, but hopefully somebody will find way to further improve situation.

> Is there a particular reason why you don't want to use a solid line for paved?

I tried it in the past and the best ones were described at https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35351 I also tried again to use solid red line and results were worse than what is in this PR. There were for example big problems with "keep footway style less prominent than highway=tracks", "avoid making paved footways more prominent".

Idea of solid lines for footways seems great until I start trying to really use it - typically the worst problems are in area with heavy footway density (cities with mapped footways).

**Comment by matkoniecz** [comment]
> while it improves #1765 it does not really fix it

Is it about all zoom levels? Or is it now affecting only some of them?

**Comment by imagico** [comment]
> I tried it in the past and the best ones were described at https://www.openstreetmap.org/user/Mateusz%20Konieczny/diary/35351 I also tried again to use solid red line and results were worse than what is in this PR. There were for example big problems with "keep footway style less prominent than highway=tracks", "avoid making paved footways more prominent".

I must say i did not check it a lot but the styling i tried which apart from the color is not unlike the purple variant in your diary entry seems to work pretty decently, see here:

z16 footway styling in urban context

Note this could of course use some lightening on the solid lines and in particular stairs but also note how it is not really stronger than the unmodified cycleways.

> Is it about all zoom levels? Or is it now affecting only some of them?

z<=14 is a different story of course - with different problems (#1748), for z15+ it seems so improve a bit with higher zoom levels.  But all the differences are really small, both between the different zoom levels and different line types.   You put a lot of work in here through fine tuning widths but I really think the color is largely to blame.

**Comment by matkoniecz** [comment]
Additional examples.

Reykjavik: https://cloud.githubusercontent.com/assets/899988/9502448/aa612c9a-4c31-11e5-8cb6-0037011a523a.png
Bruck an der Leitha: https://cloud.githubusercontent.com/assets/899988/9502451/aa64eace-4c31-11e5-9eb8-9ef3ba663f4f.png
Presov: https://cloud.githubusercontent.com/assets/899988/9502450/aa63ad62-4c31-11e5-98aa-59a8b35043fb.png
Kraków: https://cloud.githubusercontent.com/assets/899988/9502449/aa623e1e-4c31-11e5-8a86-d63b1a591d33.png

**Comment by matkoniecz** [comment]
> Note this could of course use some lightening on the solid lines and in particular stairs but also note how it is not really stronger than the unmodified cycleways.

Problems appear on lower zoom levels - either footways are too strong (especially compared too tracks) or invisible on some landuses or there is a jarring jump from dots to solid line.

Though it is likely that I really missed something that would work or I am disliking more than others sudden changes in rendering on changing zoom levels (I think that I am the only person complaining about too significant changes as zoom level changes).

**Comment by imagico** [comment]
> Problems appear on lower zoom levels - either footways are too strong (especially compared too tracks) or invisible on some landuses or there is a jarring jump from dots to solid line.

I don't see this - could you give an example?

**Comment by matkoniecz** [comment]
> I don't see this - could you give an example?

I have no code to immediately reproduce (I checked some possibilities and immediately discarded all attempts, without saving as separate branches). I was testing in http://www.openstreetmap.org/#map=15/50.0565/19.8624 for track prominence and used http://www.openstreetmap.org/#map=15/50.0875/20.0114 for problem of fully mapped footways. z14, z15 was the most problematic.

> invisible on some landuses

It typically failed either at http://www.openstreetmap.org/#map=19/50.09125/19.90067 or http://www.openstreetmap.org/#map=18/50.05925/19.91189 made obvious that there is too much of casing and on natural=bare_rock it will fail completely.

**Comment by matkoniecz** [comment]
On doing it again to recreate irritating issues I noticed that I was using the same width for all types.

It seems that tweaking widths separately may give better results - so maybe there will be an alternative with solid line.

**Comment by matkoniecz** [comment]
I probably really should expect this problem.

Solid line for paved footways results in solid line for paved cycleways.

Cycleways that are blue, resulting in game "is it a ditch or a cycleway"?
 
selection_002

Code (maybe someone has idea how to solve this - footways are better than in this PR but not so good to justify lack of consistency with cycleways): https://github.com/matkoniecz/openstreetmap-carto/commits/solid

Therefore I keep this PR as my proposal.

**Comment by imagico** [comment]
Yes, that is probably the major reason why the cycleway blue was so heavy in the first place.  But i am not so sure if it is that much of a problem, after all we also have dashed waterways and the cycleway blue is very different from the waterway blue and could be even moved somewhat towards violet, something like #5020ff.

**Comment by pnorman** [comment]
I'm inclined to merge as-is, considering it's an improvement. Still need to do some more local review.

**Comment by HolgerJeromin** [comment]
should we release a new version to avoid more outdated discussion?

**Comment by gravitystorm** [comment]
I hope to release later today, after #1791

**Comment by jojo4u** [comment]
I have trouble assessing the three buckets since the styles are not described and the examples are not annotated.

**Pull request merged**
