### PR TITLE
render historic=monument like historic=memorial, fixes #758

### LINKED ISSUE #758: Add rendering for historic=monument
An icon and name should do (as with its cousin historic=memorial). There's already a CC0 icon for it at http://www.sjjb.co.uk/mapicons/ which is the icon osm.org's browse page uses for this tag.

historic=monument has about 30k uses.

This may reveal some latent weirdness in tagging... like how every stone in Stonehenge is marked historic=monument.

### PR DESCRIPTION
**Pull request by matkoniecz**
historic monument name eeeeee eeeeee eeeeee ref 1 ele 8000 operator operator ee ee ee brand brand ee ee ee ee closed_way master - monument

two before/after on real data:

https://cloud.githubusercontent.com/assets/899988/6992697/a068e192-dada-11e4-87b7-89030d04179d.png

https://cloud.githubusercontent.com/assets/899988/6992698/a093a300-dada-11e4-95d3-f3d715944c5f.png

### CODE REVIEW

**Comment by nebulon42** [comment]
Why not use [this icon](https://gist.github.com/nebulon42/fe40eb4691a802dbeec8) for monuments? monument-16

**Comment by matkoniecz** [comment]
@nebulon42 Because I forgot to check your repository :)

I really like this new proposed icon, I think that I will change my PR.

**Comment by kocio-pl** [comment]
@nebulon42 How do you put this PNG file on cloud.github.com? I'd like to attach icon previews too.

**Comment by nebulon42** [comment]
@matkoniecz The gist I have linked within "this icon" does not contain a halo.

@kocio-pl I just drag the PNG onto the comment input field.

**Comment by kocio-pl** [comment]
OK, I see. And how do you convert your SVG icon to PNG?

**Comment by nebulon42** [comment]
In Inkscape use File > Export bitmap or use the Export icon just left of the Undo icon.

**Comment by math1985** [comment]
> I really like this new proposed icon, I think that I will change my PR.

@matkoniecz Could you update the PR accordingly and rebase?

**Comment by matkoniecz** [comment]
Closing it for now to avoid polluting pull request list.

**Pull request closed without merging**
