### PR TITLE
Adding shop symbol: hearing_aids

### PR DESCRIPTION
**Pull request by sommerbe**
Icon source: own work.
Rasterisation: tested with density=96,150,300,600 using ImageMagick convert

Changes proposed in this pull request:
- shops of type "hearing_aids" are rendered with a unique icon, similar to optician.

### CODE REVIEW

**Comment by imagico** [comment]
Thanks for the pull request.

This needs a sample rendering for evaluation of the symbol's suitability.

Tag in question is `shop=hearing_aids`:

https://wiki.openstreetmap.org/wiki/Tag%3Ashop%3Dhearing_aids

Has 8.7k uses, not that much considering how widespread these are in countries with aging populations like in Europe and East Asia.  But the tag describes a well delineated type of shop and it is consistently used in that meaning (despite the wiki doing an extremely poor job at a culture independent definition through copy&paste from English Wikipedia).

So in principle i am in support for adding this - subject to evaluation of the symbol.

**Comment by pnorman** [comment]
SVG looks technically okay, but we need a test rendering to evaluate how the symbol works. I support this in principle.

**Comment by sommerbe** [comment]
Please find attached two renderings using kosmtik of the symbol in question, of two different maps, before and after this suggested change, respectively. 

**Map 0**: after (above), before (below). See [OSM](https://www.openstreetmap.org/node/7655813854).
hearing_aids-after-map0
hearing_aids-before-map0

**Map 1**: after (above), before (below). See [OSM](https://www.openstreetmap.org/way/631561738).
hearing_aids-after-map1
hearing_aids-before-map1

**Comment by sommerbe** [comment]
The above/previous renderings refer to the modified icon, committed with 298e9510d99a92d17836491647e9144130a3f848

**Comment by imagico** [comment]
Thanks for the sample renderings.

I think there is some room for improvement in recognizability here.  The 14x14 pixel space provides quite a bit more room for a more explicit depiction than just a abstract shape vaguely resembling an ear.

A simple image search could provide some inspiration:

https://duckduckgo.com/?q=hearing+aid+symbol&t=h_&iar=images&iax=images&ia=images

I in particular think that a sound wave visualization (you could take that from our communication tower symbols) would be helpful.

**Comment by sommerbe** [comment]
Thank you for your feedback. Thinking about it, I agree with a) "a more explicit depiction", b) using the entire icon space and c) a wave visualization (for which I indeed used your communication tower symbol) which I think fits nicely given the development of in-the-ear hearing aids featuring bluetooth etc.

For this new icon, I wanted to resemble the principal shape/curves of the human ear while being a bit more organic/explicit than I found with many such symbols on the web. To be honest, I think depicting human shapes isn't that easy given that humans are particular critical towards recognizing humans, as far as I know.

Below is the rendering of this new icon (no 20). Scale x1 (above), Scale x2 (below).

hearing_aids-20
hearing_aids-20-scale2


 What do you think? In case we all agree, then I push this change.

**Comment by imagico** [comment]
I like that you are trying a new take on the subject with a more organic and less abstract shape.  But i am not sure if this is substantially better recognizable.  Part is that the waves are going in the wrong direction (a hearing aid would be receiving sound waves on the outside, not sending them).

For comparison here a sketch combining some design ideas that can be found in the image search linked to above.  This depicts a traditional above-the-ear hearing aid.  I am not sure this is necessarily better recognizable as an ear, but it attempts to illustrate the actual hearing aid and this way aims to avoid the generic _something with ears_ association.

variant 1
variant 2

I would encourage you to try tuning your design - maybe see how it looks like with the wave pattern flipped.

**Comment by sommerbe** [comment]
Here are two sketches with above-the-ear hearing aid, in following your suggestion related to the wave propagation direction, from front (above, no 25), from back (below, no 28).

hearing_aids-25
hearing_aids-28

I am under the impression that the latter sketch depicting the radio waves coming from behind fits better since these are closer to the receiver. With the receiver being more spatially apart from the human ear, compared to your suggested sketches, I find it easier to recognize the receiver.

But one may argue as to whether the human ear is better recognizable.

**Comment by HolgerJeromin** [comment]
Interesting you argue with radio waves.
For me they are sound waves. :-)

Something with sound and the ear. Fits too IMO.

**Comment by sommerbe** [comment]
Of course they are sound waves. Just a typo.

**Comment by imagico** [comment]
I think this is going in the right direction.  No strong preference w.r.t. the direction of waves from me.  If you choose the version from the left it might make sense to move them down a bit.

Regarding the gap between receiver and ear - yes, the hearing aid as a distinct thing is more clearly identifiable with it.  But it might be less clearly readable as a hearing aid since practically such devices will always sit directly on the ear without a gap.

**Comment by dch0ph** [comment]
Agree with with @sommerbe that waves coming from behind is more recognisable. Big improvement on first design!

**Comment by sommerbe** [comment]
Thank you.

Here are a few more drafts:

1.  **no gap** between receiver and ear, while sound waves are coming from behind (no 30),
hearing_aids-30

2. sound waves coming from the front are **centered**, with a gap between receiver and ear (no 31),
hearing_aids-31

3. sound waves coming from the front are centered, **without** a gap between receiver and ear (no 32),
hearing_aids-32

4. instead of depicting a hearing aid, a strike through line crosses the ear, with sound waves coming from the front (no 35),
hearing_aids-35

5. a strike through line without sound waves (no 38).
hearing_aids-38

The more abstract symbols having a strike through line (no 35, 38) might however be ambiguous. They could resemble one of: hearing aid shop, otologist. And maybe other professionals. But I wanted to try these out, just as an experiment.

**Comment by imagico** [comment]
I don't think the _line through ear_ is likely going to work.

Apart from that i think there are a lot of good options presented, i would like to see some input from others on the design and the intuitive readability.

**Comment by imagico** [comment]
Since there are no further comments i would suggest you, @sommerbe, to pick which of the last shown variants with a hearing aid depicted (with or without gap, waves from front or back) you would like to suggest and update the PR for a full review.

**Comment by sommerbe** [comment]
The symbol in question has been pushed for full review, using https://github.com/gravitystorm/openstreetmap-carto/pull/4909/commits/db87c75a3faafb561da719f3f5750ec4f72fcab1

The rendering using kosmtik is as follows.

Scale 1x:
hearing_aids-43

Scale 2x:
hearing_aids-43x2

Thank you for considering this suggestion for full review.

**Review by imagico — APPROVED** [review]
Got around to test this now, looks good.  And i think the symbol in this form is a good choice.

heading_aids

**Pull request merged**
