### PR TITLE
move motel icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Symbol is now smaller.

before
motel_before

after
motel_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
Hard to recognize and at first look it's rather luggage on the top or repair station. 

Maybe you could try something non-obvious: get half left from the hotel (with a head) and half right from the car icon?

**Comment by dieterdreist** [comment]
2015-03-19 23:58 GMT+01:00 nebulon42 <notifications@github.com>:

> Implements part of #1165
> <https://github.com/gravitystorm/openstreetmap-carto/issues/1165>.
> Symbol is now smaller.
>

for this feature it would make more sense to use a bigger symbol, IMHO.
"Before" looks better for this reason.

**Comment by nebulon42** [comment]
I managed to squeeze the whole bed in. Updated.

**Comment by nebulon42** [comment]
What is blocking this PR?

**Comment by math1985** [comment]
Sorry, didn't have time to review it.

**Comment by nebulon42** [comment]
Thanks!

**Pull request merged**
