### PR TITLE
Drop rendering for landuse=field

### LINKED ISSUE #589: landuse=field/natural=field
image

The middle-left brown-green transparent area is a [``landuse=field``](http://www.openstreetmap.org/way/23890170). It's a strong image with an opacity of 0.2

The [wiki documentation](http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dfield) says

> Although this landuse is rendered by Mapnik, it is not an officially recognised OpenStreetMap tag. Please use landuse=farm instead.
> There is no such thing as an "Officially recognised OpenStreetMap (sic) tag". People are free to use an tag.

It's not obvious from the rendering what it's supposed to be. The docs are no more helpful. JOSM doesn't have a preset for it.

There are 15k of them. 56% are last edited by MichaelCollinson, 21% are from Warofdreams, and only 23% last touched by other users.

https://www.openstreetmap.org/#map=15/53.9470/-1.8155 is an area with a bunch. There's no ``landuse=farm`` or ``landuse=farmland`` there.

There are also some ``landuse=field`` ``type=land_parcel`` relations, which I believe are discarded by osm2pgsql.

Do we really want to be encouraging such eccentric undocumented tagging by rendering this? If so, what do we want it to render like, because the current rendering is strange, to say the least, and it's not obvious from the colour what it means.

natural=field has 172 uses, and should probably be removed regardless of landuse=field.

### PR DESCRIPTION
**Pull request by math1985**
This is duplicate with landuse=farmland and landuse=grass.

This resolves #589.

### CODE REVIEW

**Comment by math1985** [comment]
@mkoniecz Do you have any time to review this (and the other two drop rendering PRs)?

**Comment by mkoniecz** [comment]
Yes, can you rebase it (and the other two)?

**Comment by math1985** [comment]
Sorry, didn't notice it has gotten out of date. Will do.

**Comment by math1985** [comment]
Rebased and created a new pull request for all three, so they don't conflict with each other: #1200.

**Pull request closed without merging**
