### PR TITLE
Issue #3087 Adding shop=dairy

### LINKED ISSUE #3087: Add rendering for shop=dairy
https://wiki.openstreetmap.org/wiki/Tag:shop%3Ddairy

### PR DESCRIPTION
**Pull request by james2432**
Fixes #3087 

From: https://www.openstreetmap.org/#map=19/45.26998/-74.13695 (way)
image

image

From: https://www.openstreetmap.org/#map=19/46.55076/-75.48622 (node)
image

image

### CODE REVIEW

**Comment by kocio-pl** [comment]
There are several key words to automatically close related issues:

https://help.github.com/articles/closing-issues-using-keywords/

**Comment by james2432** [comment]
I was aware of the keywords, didn't want to assume anything though

**Comment by kocio-pl** [comment]
Thanks. It's a standard procedure to close the issues like that - of course if the code really resolves the problem, but this is typically true for "add key=value" issues.

**Comment by james2432** [comment]
Merge issues fixed

**Comment by kocio-pl** [comment]
Thanks, it works as advertised.

**Pull request merged**
