### PR TITLE
move mast icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Mast icon has been inspired by https://github.com/gravitystorm/openstreetmap-carto/pull/1304#issuecomment-73604300. (Thanks @daganzdaanda)

Please note that the icon is now smaller (16px instead of 20px).
This PR also deletes a duplicate mast definition.

before
mast_before

after
mast_after

### CODE REVIEW

**Comment by math1985** [comment]
If we don't implement non-communication masts, I think this also works just as well, or better, without foot.

What do others think?

**Comment by dieterdreist** [comment]
2015-02-24 22:41 GMT+01:00 math1985 <notifications@github.com>:

> If we don't implement non-communication masts, I think this also works
> just as well, or better, without foot.



I clearly prefer the foot.

**Comment by daganzdaanda** [comment]
Of course I like it :)

**Comment by HolgerJeromin** [comment]
i like it. 
would like different rendering for communication type, too. But this alone is an improvement.

**Comment by nebulon42** [comment]
I would like to keep the foot if possible.

**Pull request merged**
