### PR TITLE
Fix ordering regressions

### LINKED ISSUE #2779: Railway yard tracks are rendered above main line tracks
Not sure if this has been fixed already, but [yard tracks are being layered above main line tracks](https://www.openstreetmap.org/#map=14/22.4189/114.0662).

### PR DESCRIPTION
**Pull request by kreed**
Fixes #2779 and #2781

### CODE REVIEW

**Comment by math1985** [comment]
Thanks for this PR! I haven't tested it yet but looks good.

**Comment by HolgerJeromin** [comment]
Do we want to push a bugfix release?

**Comment by kocio-pl** [comment]
Since we already meet [minimum 2 weeks period](https://github.com/gravitystorm/openstreetmap-carto/blob/master/README.md#versioning) for minor version and there are more small changes, not only bugfixes, I would make it v4.3.0 with release time witihin 2-3 days.

**Comment by pnorman** [comment]
Pushing a bugfix release would be applying these commits to 4.2.0 and tagging 4.2.1 and should be independent of if we want to tag 4.3.0 yet.

I don't mind doing this, but given the limited scope of the problem, don't see it as necessary.

**Pull request merged**
