### PR TITLE
Switch scrub pattern to SVG

### PR DESCRIPTION
**Pull request by kocio-pl**
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2045.

Warsaw, z18
Before
srnso4r7
After
5ip vekk

### CODE REVIEW

**Comment by imagico** [comment]
What's with the offset in the samples?

**Comment by kocio-pl** [comment]
I don't know. It was just simple script operation, so it might be this (Inkscape including) or it's a Mapnik issue.

**Comment by kocio-pl** [comment]
I hope symbol shift is not an obstacle for you to merge it?

**Comment by imagico** [comment]
I have not tested if a similar problem as with plant_nursery occurs here as well.  In general i would assume that whatever mapnik does exactly, if it breaks periodicity in one case it likely also breaks it in other cases.  But since the potential damage is not that big i don't think this is a big deal if it just happens for one pattern.  I would however be against moving to SVG patterns at large without the ability to control how mapnik renders them at least on the same level as with PNGs.

**Comment by kocio-pl** [comment]
I understand it as "OK, but let's think how to resolve general problem before we start with others". Sure, https://github.com/gravitystorm/openstreetmap-carto/pull/2685 is waiting for the solution to be merged.

**Pull request merged**
