### PR TITLE
Amenity=clinic icon rendering

### PR DESCRIPTION
**Pull request by kocio-pl**
This PR is my almost first try, so please double check it and give me a note what else should I do.

### CODE REVIEW

**Comment by matkoniecz** [comment]
see https://travis-ci.org/gravitystorm/openstreetmap-carto/builds/57394940

> project.yaml and project.mml are not in sync!
You should only modify project.yaml, not project.mml and run scripts/yaml2mml.py before committing.
Read https://github.com/gravitystorm/openstreetmap-carto/blob/master/CONTRIBUTING.md#editing-layers for further information.

**Comment by kocio-pl** [comment]
Sure, I'm just running the script. Thanks for the assistance!

**Comment by matkoniecz** [comment]
Also, It would be a good idea to include before/after images.

**Comment by kocio-pl** [comment]
OK. I was not fully aware that this PR will be ready for inclusion, I was just trying to learn how to prepare it, check the differences and let others look into the code to know if I didn't make some obvious mistakes - GitHub interface did not made it clear enough for me. My testing environment is not ready yet, so I guess this PR is not complete and few more days may be needed until I manage to run it and use your helper script.

**Comment by matkoniecz** [comment]
One more thing - it is a good idea to commit frequently but later commits may be merged - so for example here 5 commits may be merged into one "add amenity=clinic icon".

It is more complex but http://gitready.com/advanced/2009/02/10/squashing-commits-with-rebase.html with http://stackoverflow.com/questions/2563632/how-can-i-merge-two-commits-into-one hopefully will explain how it may be done (additional info for "Only do this on commits that haven’t been pushed an external repository." note - it is OK to do this for pull requests).

Note, rebasing is a bit tricky, so it may be left for later (it is possible also to squash commits during merging them to trunk).

> your helper script

For start I strongly recommend making before/after comparisons with just TileMill. My helper script is not allowing to do anything new, it just allows to do it in less tedious way. I finally released it as a gem and added documentation. For people starting with making changing to style it is better to setup "only" osm2pgsql, TileMill and map style. I remember it well that start was quite complex, adding specialized tools would not be the best idea for first days.

**Comment by math1985** [comment]
@kocio-pl Is this ready to be merged?

A before-after screenshot would indeed be helpful

**Comment by kocio-pl** [comment]
Nope, I still work on my development environment - probably with Docker, because even Ubuntu version change from 14.04 to 14.10 breaks some tools, so no shortcut for me. =} I already started writing Dockerfile and it may take some more time before I finish it (I'm just a novice with Docker and some other duties need my attention), but after that it will be available for others. I will let you know when this PR is ready - I plan to do this with before-after pictures.

**Comment by matkoniecz** [comment]
> I will let you know when this PR is ready

Can you open new PR once this will happen?

**Comment by kocio-pl** [comment]
Sure.

**Comment by kocio-pl** [comment]
I took another try with https://github.com/gravitystorm/openstreetmap-carto/pull/1565

**Pull request closed without merging**
