### PR TITLE
Add icon for shop=paint

### LINKED ISSUE #3288: Add  special icon for shop=paint
https://wiki.openstreetmap.org/wiki/Tag:shop=paint
7.6k uses

Icon could be a paint brush or a roller?
https://thenounproject.com/search/?q=paintbrush&i=105797
https://thenounproject.com/search/?q=paintbrush&i=466004
https://thenounproject.com/search/?q=paintbrush&i=273917

### PR DESCRIPTION
**Pull request by Adamant36**
Adds icon for shop=paint which closes #3288 
https://www.openstreetmap.org/#map=19/37.77712/-122.40170 (Way)
paint way
https://www.openstreetmap.org/#map=19/37.76481/-122.41495 (Node)
paint node

### CODE REVIEW

**Comment by Tomasz-W** [comment]
Thanks for another PR! :)
PS. Auto-close keyword in first post is broken because of "issue" word between "closes" and issue link.

**Comment by Adamant36** [comment]
Yep :) I wish there were more coders around helping you out. They must be off enjoying their summers or something. 

Thanks for the heads up on the closing thing. I keep doing that.

**Comment by Tomasz-W** [comment]
Speaking about summer, it would be good to have some features on map before it ends and the weather gets cold. I mean features like https://github.com/gravitystorm/openstreetmap-carto/issues/3069 or https://github.com/gravitystorm/openstreetmap-carto/issues/3241. So if it's not a problem for you, and you don't have other plans, I think these tags (and other leisure/ sport tags later) should have a prority to add rendering for.

**Comment by meased** [comment]
The handle is not pixel aligned (half a pixel off). Also, the file should be saved as an optimized SVG (there's a file type selector at the bottom of the Inkscape save dialog).

Otherwise looks good!

**Comment by Adamant36** [comment]
@Tomasz-W, sure I can do that. I was actually thinking about that already. It seemed like #3069 wasn't settled yet though. With the positioning thing and what not. So you think its good to go? And would I be updating the car repair icon to match it also?

@meased Thanks for the heads up. I thought it looked a little off.

**Comment by Tomasz-W** [comment]
Updated icon: https://gist.github.com/Tomasz-W/245e2151c51541d6265f540bc490eafe

@meased I'm using "clean SVG" format which is also allowed.

**Comment by Adamant36** [comment]
Updated.

**Comment by kocio-pl** [comment]
Thanks, it works good. You might try using git branches in the future instead of just using master.

**Comment by Adamant36** [comment]
I did that before and it led to a bunch of problems. I might try it again though once I get better at using Git.

**Pull request merged**
