### PR TITLE
Allotments pattern

### LINKED ISSUE #1994: landuse=allotments and highway=service
"highway = service" not visible against the background of "landuse = allotments"
mapnik: http://nadoloni.com/c/39.76004,47.46909,14/l/mapnik
mapsurfer: http://nadoloni.com/c/39.76004,47.46909,14/l/ms
http://www.openstreetmap.org/#map=14/47.4672/39.7545

### PR DESCRIPTION
**Pull request by imagico**
This changes the allotments pattern from transparent lines to a orchard-like grid dot pattern.

Closes #1994.

At the same time it slightly brightens the allotments and farmyard base color bringing farmyard on the same level as industrial etc (which seems fine in combination with the lighter farmland now).  This way buildings and other stuff on allotments areas are better visible.

Sample (from [here](http://www.openstreetmap.org/#map=16/48.0205/7.7907)):

allotments pattern

### CODE REVIEW

**Comment by kocio-pl** [comment]
Seems nice to me, service roads should be visible now, tracks and pedestrian are OK too, but footways are even less visible than currently (sample from [here](http://www.openstreetmap.org/#map=17/52.19295/21.03874)):
fbdyxlvp

**Comment by imagico** [comment]
IMO footways are not any worse with this change but this depends of course on the background color and orientation in the old styling.  In general footway visibility is a generic problem not specific to this base color, see also #1793

**Comment by mboeringa** [comment]
Have you possibly tried to reverse these two colors? I think the reversed colouring (beige/brown dots, yellowish background), may actually look better (and will almost certainly solve footpath visibility).

**Comment by kocio-pl** [comment]
Another idea: maybe space between the dots could be wider? That would make the pattern less busy.

**Comment by math1985** [comment]
@imagico Let me know what you think of the comments above. If it doesn't work out I'm fine merging the current version.

**Comment by imagico** [comment]
Since this is not intended to be a fundamental change of allotments rendering completely different colors are outside the scope here.  If there is something wrong with the current rendering or the one proposed here in addition to #1994 that should probably be discussed separately.

A coarser pattern would equally be a bigger change and similarly i see no good reason for that at the moment.  Coarse patterns have their own specific issues, especially with fine grained geometries.  If the pattern is considered too strong even though it is definitely weaker than the old one it could be reduced in contrast of course but i would need to see cases where it is actually too strong to consider that.

**Comment by math1985** [comment]
Fine, I merged the PR.

**Comment by imagico** [comment]
Thanks.

**Comment by kocio-pl** [comment]
> If the pattern is considered too strong even though it is definitely weaker than the old one it could be reduced in contrast of course but i would need to see cases where it is actually too strong to consider that.

The whole problem is not about being strong/weak, but about unfortunate interferences with way patterns. This PR resolves the interference with thin lines (service roads), but introduces interference with dots (footways). Contrast change may still help somehow, but one has to test it to know.

I believe footways are more common on allotments than service roads. They were on the edge of visibility already and new version makes them hardly visible plus I see unpleasant visual artifacts, however I don't care that much for details on such areas, so I plan leave it this way for now.

**Comment by imagico** [comment]
> The whole problem is not about being strong/weak, but about unfortunate interferences with way patterns. This PR resolves the interference with thin lines (service roads), but introduces interference with dots (footways).

As said i don't see that.  Footway visibility is a problem in general, was one with the old allotments rendering and still is with the new one but there are plenty of situations where it is far worse (like on bare_rock).  So the way to go here is IMO to improve footway rendering, not to tweak area rendering at the cost of map clarity in other aspects.

I considered various options when designing this PR - including no pattern and a dark pattern.  But this one seemed to be the most suitable.

> plus I see unpleasant visual artifacts on z15:

I can see no artefacts in that sample - would need to explain.

**Comment by kocio-pl** [comment]
> So the way to go here is IMO to improve footway rendering 

That would be the best for me. However I remember that this proved to be really hard (especially https://github.com/gravitystorm/openstreetmap-carto/pull/1359) and we found no solution, so I doubt we can resolve it. If you have some hint, it would be useful.

> I can see no artefacts in that sample - would need to explain.

I don't know how to explain, that's why I posted an image - if you don't see it, it's not a problem for you. I see annoying irregular pattern of light brown dots.

**Comment by imagico** [comment]
For reference - here are the options i considered/tested - overall i regard all of them inferior to the one proposed here, for different reasons and in different situation.  But if you prefer any of them or something completely different feel free to evaluate it further.

weaker pattern
single pixel bright
single pixel dark

**Comment by kocio-pl** [comment]
Thanks for sharing. Could you also provide a code for those attempts (so I can test it with footpaths) or just render it with footpaths examples yourself?

**Comment by imagico** [comment]
There is no code, pattern variations are here:

[variant 1](http://www.imagico.de/files/allotments_2.png)
[variant 2](http://www.imagico.de/files/allotments_3.png)
[variant 3](http://www.imagico.de/files/allotments_4.png)

**Comment by mboeringa** [comment]
Variant 3, with the dark brown spots on the beige background, actually looks more "natural" to me than the original proposal. With its darker "pattern" over a lighter background, it is also more consistent with most other pattern usage in OpenStreetmap-carto, like the forest visible in the example images.

So, as to @imagico 's wishes for "consistency" (https://github.com/gravitystorm/openstreetmap-carto/issues/2270), it might actually be better

**Pull request merged**
