### PR TITLE
move picnic table icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.
Icon: [nebulon42/osmic/table-16.svg](https://github.com/nebulon42/osmic/blob/master/outdoor/table-16.svg)

before
table_before

after
picnic

### CODE REVIEW

**Comment by mkoniecz** [comment]
My problem with this icon that it looks like information board (at least for me). New ones also have this problem.

**Comment by nebulon42** [comment]
You mean like a scaffold for a board (as in painting)? This is a very common symbol for a picnic table, I'm not able to think about something else. But if you have some hints, maybe there is something better.

**Comment by mkoniecz** [comment]
I know. I tried some variations - but it made problem even worse.

**Comment by althio** [comment]
Based on this picture:
https://commons.m.wikimedia.org/wiki/File:Picnic_table.jpg

I think the bench could be represented with extra height and the tabletop with reduced height.
Rough idea:image2

With extra features like glass and bottle?
Rough idea 2:image4

**Comment by pnorman** [comment]
I prefer the simpler bench to those more complex ones - either the existing one or the new one.

**Comment by math1985** [comment]
Tester thinks icon symbolizes a bench in the park. Good enough I think.

**Comment by nebulon42** [comment]
By saying "simple" do you refer to the thicker or the thinner version?

**Comment by math1985** [comment]
The thinner one without bottles.

**Comment by althio** [comment]
Thanks for your feedback. That was mostly illustrative hints to @nebulon42 because sometimes explaining by words is more difficult. Eventually if he thinks he can integrate a few concepts in his own design he will certainly do better than my attempts.

As for preference, I am OK with either. However I think the after-thick from @nebulon42 has a better shape but is a bit too thick, while after-lighter has the correct weight but shape of legs and benches feel less natural.

Another attempt based on the lighter version: picnic-lighter-width-bench3-narrower

**Comment by nebulon42** [comment]
@althio Thanks for the concrete suggestions, much appreciated.

I'm still undecided on thick vs. thin. I think that thin is too thin, but thick is a bit too thick. A solution would be to use 1,5px wide elements, but this would increase blurriness.

**Comment by pnorman** [comment]
> A solution would be to use 1,5px wide elements, but this would increase blurriness.

It's not too serious an issue if the unaligned side is on the interior.

**Comment by nebulon42** [comment]
Thanks @pnorman for the suggestion, you were right. I'm now quite happy with the result, see preview above.

**Comment by althio** [comment]
@nebulon42 I am happy also with your new suggestion, 1.5 is a nice middle ground.
Last nitpick -- feel free to ignore -- horizontally maybe the benches should extend more or the table extend less.

**Pull request merged**
