### PR TITLE
Render natural=shrubbery

### LINKED ISSUE #4473: Please render natural=shrubbery
Since hedges do not render as areas, cf. https://github.com/gravitystorm/openstreetmap-carto/pull/3844, a limited but highly prolific number of people use natural=scrub to map, what are in my understanding mostly hedge-like features: barriers to keep pedestrians from taking shortcuts. See https://wiki.openstreetmap.org/wiki/Tag:natural=shrubbery for complete description and account of other use cases.

As of now, this custom is regionally limited, the Netherlande being a prime spot of exploding use: https://wiki.openstreetmap.org/wiki/File:ScrubByNumbersNLvsAT.png shows a comparison with use in Austria. In Austria, like in most of the world, such "shrubberies" are not mapped at all, not the least maybe, because there exists (not until recently) no valid tagging for them.

As the trend to map micro features is expected to continue ever stronger, there will be demand for a tag to correctly map those "shrubberies". As the people doing such mappings are very sensitive to rendering, it is to be expected that they will not use the concise tag, but the one that renders.

Therefore my plea to render natural=shrubbery. Give the authors of the shrubbery proposals a chance of having created a successful tag. Apart from preventing the information loss by dilution of millions of currently concise mappings of actual scrub, I think also the cartographers work will be a little easier, if a tag, that starts rendering at z7 or so will not be used on perhaps even more millions of features, that range from closet sized to the size of a medium flat.

### PR DESCRIPTION
**Pull request by jdhoek**
Render `natural=shrubbery`. The three `shrubbery:density` values
(`sparse`, `medium`, and `dense`) are reflected in the pattern.

The pattern is modelled on the pattern used for `natural=scrub` (same distribution of symbols). Colours used match `natural=scrub` too, except when the `shrubbery:density=dense`, then the same colour as `barrier=hedge` is used to reflect that in both cases the vegetation is generally speaking impassable.

Fixes #4473

# Before

(Here `barrier=hedge` with `area=yes` is tagged. In the 'after' screenshots `natural=shrubbery` with `shrubbery:density=dense` replaces it.)

Screenshot from 2022-04-07 19-02-53

# After

Showing both `shrubbery:density=dense` and `shrubbery:density=medium`:

Screenshot from 2022-04-07 18-50-04

Screenshot from 2022-04-07 18-50-16

In the following screenshot some of the `natural=shrubbery` is tagged with `shrubbery:density=sparse` and no `shrubbery:density` tag for comparison:

Screenshot from 2022-04-07 18-51-38

### CODE REVIEW

**Review by imagico — CHANGES_REQUESTED** [review]
The general thing first:  As indicated in https://github.com/gravitystorm/openstreetmap-carto/issues/4473#issuecomment-1092083729 the situation from last September that has led to the consensus to close that issue has not substantially changed.  I don't want to prejudice the possibility that this assessment could change but so far no argument is in sight that is likely to result in that.

Independent of that there are a few other issues with your PR:

* your patterns are PNG only - we usually want patterns to be designed as SVGs so they can be rendered at different resolutions in good quality.
* the pattern design does not allow for an intuitive distinction towards the other features we render with the same base color (natural=scrub and natural=wood).  Since most of the features with this tag are small a coarse pattern is not a good idea, the only pattern that you could really consider for this would be a relatively fine structure pattern similar to for example leisure=garden and natural=beach.
* you overload the progression of wood/forest and scrub colors which indicate a difference in height of vegetation in this style with a completely different use to indicate some kind of density of  vegetation.  That is not a good idea.  You will have heath-height shrubbery in the same color as a rainforest with >50m high trees.
* Interpretation of `shrubbery:density` is highly questionable - it is [ostentatiously non-verifiable](https://wiki.openstreetmap.org/wiki/Verifiability#Objective_criteria) and there is no indication that its very limited application in the database follows any consistent verifiable principles beyond the domains of the individual mappers who use it (which is just 40 by the way).  The only hint at what the different density values mean is [the wiki page](https://wiki.openstreetmap.org/wiki/Key:shrubbery:density) and that is full of weasel words ('generally', 'might', 'effectively') and is available in English language only - hence no one who does not speak English has a chance to apply these tags in any consistent way.

**Comment by kocio-pl** [comment]
Different color for dense shrubbery sounds to me like interesting approach. My questions:

1. What do you think about different way of depicting density - pattern of symbols consisting of 1, 2 or 3 elements? 
2. How could we render this tag when density is not tagged?

**Comment by jdhoek** [comment]
> [imagico](https://github.com/imagico) we usually want patterns to be designed as SVGs so they can be rendered at different resolutions in good quality.

I was following the literal example of `natural=scrub`. I'll change the symbols to SVG.

> [kocio-pl](https://github.com/kocio-pl): Different color for dense shrubbery sounds to me like interesting approach.

Thanks. I did it mainly to stay near to `barrier=hedge`, which dense shrubbery shares the impassable property with. It may also help offer a migration path for mappers who've used or encounter the now broken `barrier=hedge` with `area=yes`.

> [imagico](https://github.com/imagico) you overload the progression of wood/forest and scrub colors which indicate a difference in height of vegetation in this style with a completely different use to indicate some kind of density of vegetation. That is not a good idea. You will have heath-height shrubbery in the same color as a rainforest with >50m high trees.

Any colours or hues you wish to suggest?

> [kocio-pl](https://github.com/kocio-pl) What do you think about different way of depicting density - pattern of symbols consisting of 1, 2 or 3 elements?

It does that — two, three, or four lobes on the symbol getting 'denser' — I'll see if I can create a screenshot more clearly showcasing it.

> [kocio-pl](https://github.com/kocio-pl) How could we render this tag when density is not tagged?

Currently I leave out the symbols but keep the same fill colour. That seems to work OK visually and rewards mappers for using `shrubbery:density`.

**Comment by imagico** [comment]
> Any colours or hues you wish to suggest?

No, the number of vegetation related green colors in this style is already at the limit of what can realistically be intuitively understood.  And in its current _generic urban greenery_ use the tag does not in any way fit into the schema we have for vegetation related green colors.

If you'd want to support the _generic urban greenery_ use the most suitable option would be a design somewhat similar to `leisure=garden` - but that would possibly result in something extremely generic (`natural=shrubbery`) being rendered similar to something much more precise (`leisure=garden`) - which is questionable as well.  And as said in https://github.com/gravitystorm/openstreetmap-carto/issues/4473#issuecomment-1092140354 supporting _generic urban greenery_ use of the tag would be fundamentally against the goals of this style.  If use of `natural=shrubbery` showed a trend towards something more specific this design idea could possibly be tuned to support this specifically - but at the moment that is unfortunately a hypothetical discussion because no such trend is really visible.

**Comment by jdhoek** [comment]
I've changed the image patterns to SVG as requested.

-----

@kocio-pl Here is a sample of the three `shrubbery:density` values (`dense`, `medium`, `sparse`) and one `natural=shrubbery` without on the top row. I've included `natural=wood` and `natural=scrub` on the lower row for comparison, and surrounded the swatches with `landuse=grass`. I've tweaked the colours a bit as well, but kept the progression towards a slightly darker variant as the density increases.

Screenshot from 2022-04-12 21-37-54

# Samples

The example below includes some patches of shrubbery that were already tagged as `natural=scrub`. Like many other mappers I am not changing these existing patches to `natural=shrubbery` without rendering in Carto, because these areas have a significant effect on the map and how it is used (with newly mapped areas there is no degradation of the existing map). This is not strictly necessary, but I consider it a courtesy to my fellow mappers.

I'm quite satisfied with how the rendering turns out here.

## Now

Screenshot from 2022-04-13 18-14-55

## With this PR

Screenshot from 2022-04-13 18-15-34

**Comment by imagico** [comment]
I have seen the request for review but as indicated i continue to stand behind the decision to close #4473.  It was @kocio-pl who re-opened the issue and suggested to work on a PR so i think it would probably be more productive if he provides feedback how he thinks this can be developed in a way that can achieve consensus approval from the maintainers.  It seems unlikely from my perspective but as said i don't want to prejudice the possibility.

**Comment by jdhoek** [comment]
> I have seen the request for review but as indicated i continue to stand behind the decision to close https://github.com/gravitystorm/openstreetmap-carto/issues/4473.

As a mere contributor I cannot select who the reviewer is, nor can I request specific reviewers via this UI. I have not specifically requested you to reassess your review. A maintainer will probably have to click some buttons to change who the reviewer is.

**Comment by imagico** [comment]
Sorry, my mistake then.  I always thought you can request a review from a specific person.

**Comment by jeisenbe** [comment]
@kocio-pl do you want to review or comment on this? 
Everyone, please remember that anyone can review a PR, not only maintainers.

**Comment by jeisenbe** [comment]
See my comments in https://github.com/gravitystorm/openstreetmap-carto/issues/4473#issuecomment-1147083873 - I think it is probably still too soon to render this new tag, until it clearly overtakes `natural=scrub` for mapping bushes in urban gardens.

**Comment by pnorman** [comment]
Closing - see https://github.com/gravitystorm/openstreetmap-carto/blob/8312c0dc091c1508306fafaa5b55a447e7da5b09/openstreetmap-carto.lua#L380-L382 and reasons above.

**Comment by jdhoek** [comment]
@pnorman What is the relevance of that code snippet for this PR?

If it's 'too soon' to render this tag, then why close the PR? Is something wrong with the PR itself?

**Comment by pnorman** [comment]
Code snippet was a  mispaste, corrected it above.

The reason for closing this PR is we're declining rendering this tag.

**Comment by jdhoek** [comment]
@pnorman Could you give an indication of the number of uses needed to consider rendering?

**Comment by BubbaJuice** [comment]
@jeisenbe How can we measure its use in urban gardens in comparison to `natural=scrub`?

**Comment by OttoROSM** [comment]
Can this please be rendered. The map now looks broken/imcomplete and is not reflecting the map data for people to recognise their surroundings.

**Comment by rene78** [comment]
Can we reopen this PR? Looks like most people - including me - are in favor to render the tag.

**Comment by daishu0000** [comment]
This tag has 68k uses now, I think it's time to reopen this PR.

**Comment by pelderson** [comment]
Closing in on 100K

**Pull request closed without merging**
