### PR TITLE
Adding shop=beverages icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/1592.

beverages-z19

### CODE REVIEW

**Comment by nebulon42** [comment]
Just more thoughts: Maybe make also the bottle different and maybe have a thicker straw?

**Comment by kocio-pl** [comment]
I started with it =} : 
2) beverages-14-0 and 3) beverages-14-straw-1 and 3) was too light for me, so maybe 2) would be good.
For more clear comparison - now it is 1) beverages-14-2. What's your opinion?

**Comment by nebulon42** [comment]
1) seems to be the thickest, would even thicker be possible?

**Comment by kocio-pl** [comment]
Sorry, I misunderstood you of course - thicker, not thinner!... =}}} IMO that would be hard, because straw should be long and thin (and again we have no sufficient vertical space), but I will experiment with your idea. 

Or maybe lemon - however there are also alcohols you drink with a straw and/or with a lemon, so I guess glass cup alone may be as good as with these attributes. It's enough to be visually different and eye pleasing if possible.

**Comment by Rovastar** [comment]
This is one of the tags that I never understood. 
I imagine most shops selling alcohol also sell some non-alcoholic drinks like Coke etc. BUt of course this is not the place to discuss this only obviously to encourage the usage....

**Comment by dieterdreist** [comment]
2015-05-29 3:13 GMT+02:00 Rovastar <notifications@github.com>:

> This is one of the tags that I never understood.
> I imagine most shops selling alcohol also sell some non-alcoholic drinks
> like Coke etc. BUt of course this is not the place to discuss this only
> obviously to encourage the usage....
>

I believe the "alcohol" shop typology is something mainly found in
countries like Iran or the US, i.e. it is context dependent whether people
will use the beverages shop (access to alcohol is "easy", it can also be
found in supermarkets etc.) or the alcohol shop (alcohol is strictly
regulated and special shops exist).

**Comment by kocio-pl** [comment]
4) beverages-14-7
5) beverages-14-8

For me neither the tallest bottle nor the thicker straw work at all.

**Pull request merged**
