### PR TITLE
Adding icon for tourism=apartment

### PR DESCRIPTION
**Pull request by kocio-pl**
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/401.

Rendering with chalet icon, as they are similar, but from z18 instead of z17, so it's less visible than shops and chalets.

z18
jz7crnvp

### CODE REVIEW

**Comment by nebulon42** [comment]
Great that you attempt to get tourism apartments rendered. However, I'm not too happy with the chalet icon. I would suggest to remove the mountain somehow. A chalet is basically an apartment at some remote area. So the mountain thing should be obvious from the context. Both categories can still share the same icon. For the sake of simplicity this could also happen later.

**Comment by kocio-pl** [comment]
So it would mean redesigning chalet icon anyway, because [it's still not vectorized](https://github.com/gravitystorm/openstreetmap-carto/issues/1165) and blue house seems to be not clear for me for both those tags. Do you have some idea what could it be instead?

**Comment by nebulon42** [comment]
No good one I have to admit. I did not have good ideas regarding accommodation that's why I left them till the end. Maybe this should be tackled later (TM). :-)

**Comment by kocio-pl** [comment]
Another reuse, it's better for me now:
xmg7sk t

**Comment by pnorman** [comment]
Closing as https://github.com/gravitystorm/openstreetmap-carto/issues/401#issuecomment-250432575 closed the parent issue.

Thanks for your work - Is there anything we can pull out for chalet?

**Pull request closed without merging**
