### PR TITLE
Adding rendering for amenity=ferry_terminal

### PR DESCRIPTION
**Pull request by kocio-pl**
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/2094.
Resolves https://github.com/gravitystorm/openstreetmap-carto/issues/869.

Looks like airport area rendering is rather for large area and ferry terminal is more like a railway station, so I took it. Labels are however the same like in the airport, but rendered later.

I also made some cleaning in color variables.

Examples:

Warsaw, z15 (nodes only, compared to some other labels)
p7dbtip8

Victoria (nodes and typical area)
z14 (not rendered)
bjher_1n
z15
pkcactt9
z16
x5e7i lb
z17
g0l1qrzl
z18
cc36kprk
z19
faamqado

### CODE REVIEW

**Comment by kocio-pl** [comment]
Another possibility - labels the same as the bus stop - doesn't work for me:
cxyhw1qv

BTW: are there really so large railway stations which should be rendered from z10? If not, maybe we can adjust SQL to optimize query for some higher zoom levels?

**Comment by pnorman** [comment]
Can review when I get home.

**Comment by kocio-pl** [comment]
As the station color seems to be designed for buildings, it can be made lighter (here or in separate PR). We could also go with airport area color, but it's too pale for this usage IMO:

z17
gj9efxea

z18
q1snoghk

z19
qs l225q

**Comment by math1985** [comment]
@kocio-pl Could you rebase this? I have the impression something went wrong, looking at the diff (or I'm misunderstanding the diff algorithm again).

**Comment by kocio-pl** [comment]
After some time away from this PR I've changed my mind and like to use the lighter version for a background, because current station color seems to be designed with station building in mind, not for the area (merging https://github.com/gravitystorm/openstreetmap-carto/pull/2443 will have some implications there).

I don't need to find it from a distance (ferry lines are good hint), it's enough to see its shape to understand how the space is used. Also using the same color for airport, ferry and station area (and possibly other transportation areas) would be more consistent.

I will fix the code soon.

**Comment by kocio-pl** [comment]
The code is updated and ready to be merged. 

General notes:
- The area is now rendered as the aerodrome (not as the railway station), the rest remains the same
- There was variable sections cleaning done

**Comment by nebulon42** [comment]
I think it is not a good thing to mix cleanups with changes. It makes diffs harder to read. Since there were some changes I don't get the changes at first glance. Could you please show a proper before after comparison?

**Comment by pnorman** [comment]
I think it's more worthwile to render an icon for a ferry terminal than a fill. These are features that people are often looking for, and an icon is better for that.

**Comment by kocio-pl** [comment]
The fill and the icon play a different role, just like in the airport: icon make it easier to find on the big picture, while the fill is important when zoomed in to know which roads and buildings belong here. This is related to https://github.com/gravitystorm/openstreetmap-carto/issues/2094.

Unfortunately we have no such icon available, because none of my propositions was approved by the community (https://github.com/gravitystorm/openstreetmap-carto/pull/1673), but if we have one, I would like to show it too.

**Comment by kocio-pl** [comment]
Code is cleaned now and here are basic before/after renderings (I won't make it extensive, because most of previous are correct except those with red background):

Warsaw, z15
Before:
e_ndw nu
After:
zvjyqtxs

Victoria, z18
Before:
4xbciwk5
After:
qw5 eoil

**Comment by kocio-pl** [comment]
Code is updated now and ready to be merged.

**Comment by math1985** [comment]
I agree this feature would need an icon for it to be useful (sorry for slow review).

**Comment by kocio-pl** [comment]
Any hints about the icon design? Maybe the discussion in the https://github.com/gravitystorm/openstreetmap-carto/pull/1673 could be useful here.

I think the icon should be visible only to some zoom level (like the airport, but later, since typical ferry terminal is smaller). It wouldn't be visible on z18 then, so the rendering above would be the same.

**Comment by kocio-pl** [comment]
This is how original icon works in reality (but it's black here):
https://maps.wikimedia.org/#18/52.23707/21.03863

I also think we could try with something more symbolic and easier to recognize, like the anchor:
https://openclipart.org/detail/10145/aussersihl-coat-of-arms

What do you think?

**Comment by math1985** [comment]
To me, the anchor doesn't really remind me of a ferry terminal. Not sure what others think.

**Comment by math1985** [comment]
To me, the anchor doesn't really remind me of a ferry terminal. Not sure what others think.

**Comment by kocio-pl** [comment]
I would be happy to at least have some hint what could work for the others, since my ideas was not accepted till now and I ran out of them. However first anchor is still good for me.

**Comment by dieterdreist** [comment]
2017-03-22 13:47 GMT+01:00 kocio-pl <notifications@github.com>:

> I would be happy to at least have some hint what could work for the
> others, since my ideas was not accepted till now and I ran out of them.
> However first anchor is still good for me.
>


IMHO it could be a car on a ship or inside a ship. An anchor is far too
generic.

**Comment by math1985** [comment]
Not all ferries carry cars. Maybe a generic icon of a ship?

**Comment by dieterdreist** [comment]
2017-03-22 15:24 GMT+01:00 Matthijs Melissen <notifications@github.com>:

> Not all ferries carry cars. Maybe a generic icon of a ship?




not all ships are ferries ;-)

After a quick look I think that current ferry tagging is immature, it won't
allow us to distinguish between huge ferry terminals and small passenger
ferry stops on a river like here:
http://www.openstreetmap.org/node/1051302891
Also the term "terminal" is indicating an endpoint, for intermediate stops
it isn't right.

there's also a new proposal for these kind of features (currently not used
for this style):
https://wiki.openstreetmap.org/wiki/Proposed_features/Seaway

**Comment by pnorman** [comment]
As this has cartography changes, this PR is currently held up by the [feature freeze until 4.0.0 has been released](https://github.com/gravitystorm/openstreetmap-carto/pull/2533#issuecomment-295931948).

**Comment by math1985** [comment]
@kocio-pl What is the status of this PR?

**Comment by kocio-pl** [comment]
I took some time to let the idea establish a bit in my head. Now I plan to eventually update it with 1. anchor icon, because:
- it's generic enough and much easier to recognize than our previous attempts to depict ships,
- having icon here conforms our style for transport amenities (blue icons for bus/tram stops or the airports) and having consistent system is enough to give user a hint what is the context of the anchor (transport),
- it's probably not going to be used for any other water-related feature (like marina).

**Comment by kocio-pl** [comment]
@dieterdreist I think that current tagging is just generic, I wouldn't call it immature - this problem applies to many old features (like healthcare amenities or public transport). However your `seaway=*` proposition looks quite interesting to me, but it's not yet practically used (6 uses now) nor even proposed for discussion (it's still a draft), so we can re-examine it later.

**Comment by kocio-pl** [comment]
Current rendering (with icon):

Warsaw, z15
Before
sfhncvqu
After
yi8iztue

Sidney (USA)
z15
Before
rz_0nkmo
After
vo2mmc f


z18
Before
h0wm1cah
After
3szsjaex

**Comment by kocio-pl** [comment]
Are there any other issues not discussed before?

**Comment by pnorman** [comment]
It's worth checking an inner harbor dense with small ferry terminals. http://www.openstreetmap.org/#map=15/49.2726/-123.1264 has some

**Comment by kocio-pl** [comment]
Vancouver, z15  (click to see unscaled images):
jzcaxgp5

**Comment by kocio-pl** [comment]
I feel this code is ready to be merged, but I don't know how long should I wait and what for, because it's quite old, but formal requirement (using icon) is fulfilled for just a few days. On the other hand nobody was opposing. Our decision rules are hard to apply to long and evolving solutions.

**Comment by vadp** [comment]
I've noticed that Mapnik started rendering amenity=ferry_terminal with an anchor symbol anchor symbol. 

At nautical maps a similar symbol denotes an [anchorage](http://wiki.openstreetmap.org/wiki/Seamarks/INT-1_Section_N#Anchorages.2C_Anchorage_Areas), so this usage of an anchor for the amenity=ferry_terminal is quite misleading.

**Comment by kocio-pl** [comment]
It's not a nautical map and none of the ship icon was clear enough for osm-carto community (even if they are used on some other styles). I also noticed using the anchor symbol in some other general map, but unfortunately I don't remember which one.

**Comment by imagico** [comment]
@vadp - you should best open a new issue for this.

Not only in nautical maps by the way, see for example chapter 2, symbol 226 in http://www.lib.berkeley.edu/EART/pdf/soviet.pdf - likewise for some pre-digital German TK100/TK200 (don't have a digitized sample at the moment).

**Comment by dieterdreist** [comment]
I agree an anchor is not a good symbol for a ferry

**Comment by vadp** [comment]
> I agree an anchor is not a good symbol for a ferry

@dieterdreist I've opened #2785 for this issue.

**Pull request merged**
