### PR TITLE
move library icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165 by moving the icon for `amenity=library` to SVG.
Icon: [nebulon42/osmic/library-16.svg](https://github.com/nebulon42/osmic/blob/master/amenity/library-16.svg)

before
library_before

after
library_after

### CODE REVIEW

**Comment by kocio-pl** [comment]
I don't like horizontal space - now it looks more like an arrow down or a gift than a book.

**Comment by nebulon42** [comment]
I can't follow you regarding the gift I have to say.

**Comment by kocio-pl** [comment]
Well, the lower part of the package with the gift. =} 

Anyway, I can't follow the horizontal space in the book icon - what does it represent?

**Comment by nebulon42** [comment]
It is intended to represent the pages, the thickness of the book.

**Comment by kocio-pl** [comment]
Hm, I was not sure, since I expect it to be on top. And I guess the cover is too short (vertical cover line should be longer than horizontal - this one is too square).

**Comment by nebulon42** [comment]
> I was not sure, since I expect it to be on top

That seems to be a problem with this icon. The book is meant to show the inside but some are seeing the back cover (me too sometimes). I will try to adjust the fake perspective.

**Comment by althio** [comment]
If you want to give a try to another idea and get rid of perspective how about several books on a shelf.
Found on the web as example:

**Comment by nebulon42** [comment]
Yes, tried it already but didn't work so well.

**Comment by nebulon42** [comment]
Slightly adjusted: library-162

**Comment by kocio-pl** [comment]
I still consider it strange because of a square aspect ratio (if I understand correctly those small parts on the bottom are the thickness/z axis, so they don' count for height) - rectangles with one dimension longer are more common: [https://commons.wikimedia.org/wiki/File:Comparison_paper_sizes.svg]

**Comment by nebulon42** [comment]
I have updated the icon and removed the z-axis part.

**Comment by HolgerJeromin** [comment]
I think most names of the poi will clarify the icon for those people who don't recognize it.

**Comment by mkoniecz** [comment]
Unfortunately at least for me the new icon is not recognizable and current one is.

**Comment by nebulon42** [comment]
> Unfortunately at least for me the new icon is not recognizable and current one is.

I have experimented quite a bit with different options before the last update and I'm afraid I will not be able to come up with a different/better version.

**Comment by vholten** [comment]
These are some variations:
book icons
book icons preview
(Inspired by [this icon](http://commons.wikimedia.org/wiki/File:Book-of-myst.png))

**Comment by kocio-pl** [comment]
Both are much better for me!

**Comment by nebulon42** [comment]
@vholten Are your previews output by TileMill or did you do some image editing?

**Comment by vholten** [comment]
@nebulon42 The previous previews were done by image editing (downsampling the icons to 16 pixel width). 
This is how it looks in TileMill using SVG:
book icons tilemill

**Comment by nebulon42** [comment]
Looks a bit blurry at the edges, but not bad. Maybe it helps to have the parts at the left/right side in solid colour as it is done for the lower part? I suggest that you create another Pull Request for it.

**Comment by mkoniecz** [comment]
@vholten It looks really well, better than the current one.

**Comment by althio** [comment]
@vholten I like them too.
I would prefer the left and right edges really vertical with no apparent perspective.

**Comment by vholten** [comment]
OK, I will try some variations and create a new pull request.

**Comment by math1985** [comment]
For what it's worth, tester recognizes the image proposed in this PR but prefers the current image.

**Comment by nebulon42** [comment]
Thanks, but let's wait for @vholten's PR.

**Comment by nebulon42** [comment]
I tried to recreate @vholten's proposal and it looks like this:
library_new

@math1985: Here I tried to use transparency (0.1) for the fill. What do you think?

As the outlines are a bit thin and the fill (pages) are quite big I think the icon is not prominent enough compared to the others, especially at lower zoom levels:
library_low_zoom

**Comment by nebulon42** [comment]
Please give feedback on the new icon so we can move this forward, thanks.

**Comment by math1985** [comment]
> Please give feedback on the new icon so we can move this forward, thanks.

I'm very busy at the moment, but will get back to it as soon as I have time.

**Comment by kocio-pl** [comment]
I like this icon - it's a bit less visible then current one, but then I think libraries are now too visible. New icon is satisfying recognizable for me.

**Comment by math1985** [comment]
I also like the new icon. It's more recognizable then the 'arrow', and as far as I'm concerned still prominent enough.

We could also consider swapping your proposed library and book shop icon. A (messy) stack of books reminds me more of a library than a book shop.

**Comment by lest69** [comment]
I also like the new icon. I think it's visible enough, especially when combined with the label.

I'm not so sure about swapping the icon with book shop. In my experience, the open book is a fairly universal symbol for representing libraries. Regardless, the colour of the icon and label is different for the two, so it should be relatively easy to determine which is the amenity and which is the shop.

**Comment by mkoniecz** [comment]
>  In my experience, the open book is a fairly universal symbol for representing libraries.

Situation in Poland is the same - IMHO this symbol or similar is more likely to represent library.

**Comment by nebulon42** [comment]
I have to delay this a bit because this involves transparency and I have to address https://github.com/nebulon42/osmic/issues/3 first to see if the transparency is still needed. We then will have to decide if we want to have icon halos in here too (#1189).

**Comment by mkoniecz** [comment]
@nebulon42 Is there anything blocking this PR? This icon is a nice improvement, is there anything that needs to be done before reviewing and hopefully merging it?

**Comment by nebulon42** [comment]
@matkoniecz After careful consideration I cannot use the last proposed variant, because of the large inner holes that lead to difficulties with legibility on noisy background.
Example: noise_library

I therefore have reverted the library icon in my repository and will go on proposing my version as depicted in the preview in the first post. You can still find the other icon [here](https://github.com/nebulon42/osmic/blob/b20bf75298c6a268ceacc247bccea1d5b902030d/amenity/library-16.svg) if you choose to go ahead with that version.

**Comment by matkoniecz** [comment]
@nebulon42 Yes, it is not working in cases like this example.

**Comment by kocio-pl** [comment]
Do the pages have to be completely translucent or fully brown, or there could be a shade?

**Comment by nebulon42** [comment]
Technically a transparent fill (say 10/15/20%) could work. But translucent fills clash with halos, so I cannot add that. (Although halos are not considered in this repository.)

**Comment by lest69** [comment]
Rather than transparency, is it possible to use a lighter, but still solid, shade? Or can it only have on/off for each pixel? I'm not completely familiar with how this all works, but I envision something like having the pages coloured by the primary colour -50% saturation, for example.

**Comment by nebulon42** [comment]
@lest69 When using `marker-fill` as we do it is not possible to use more than one colour.

Please tell me if you consider to merge this, otherwise I will close it.

**Comment by math1985** [comment]
I'm fine with merging the current proposal, what do the others think?

**Comment by kocio-pl** [comment]
For me it's just passable - visually not better than current icon (too strong), but not worse.

**Comment by pnorman** [comment]
I'd rather keep the current one or use something similar to what was proposed in the PR comments. I don't like the one in the PR itself.

**Comment by nebulon42** [comment]
I'm closing this, because we are re-iterating the same discussion over and over again.

**Pull request closed without merging**
