### PR TITLE
Cleanup SVGs for places

### PR DESCRIPTION
**Pull request by pnorman**
There should be no visual changes here.

### CODE REVIEW

**Comment by nebulon42** [comment]
Unnecessary in my opinion as it makes SVGs harder to edit (by hand). Any export with Inkscape will re-introduce the clutter again.

**Comment by pnorman** [comment]
> Unnecessary in my opinion as it makes SVGs harder to edit (by hand)

How?

**Comment by nebulon42** [comment]
Sorry, that was unclear. I meant that it makes them harder to edit because you have to do it by hand as exporting with Inkscape will re-add the clutter. Correct me if I'm wrong and the additional clutter can be avoided with Inkscape.

**Comment by pnorman** [comment]
> Sorry, that was unclear. I meant that it makes them harder to edit because you have to do it by hand as exporting with Inkscape will re-add the clutter. Correct me if I'm wrong and the additional clutter can be avoided with Inkscape.

It might add some of the XML namespace tags and perhaps RDF meta-data, but the coordinate precision stuff should stay. I don't know for sure, since I don't use Inkscape.

But based on the feedback, I think I'll change them to a circle in a circle.

**Comment by dieterdreist** [comment]
sent from a phone

> On 6 Dec 2016, at 23:01, Paul Norman <notifications@github.com> wrote:
> 
> It might add some of the XML namespace tags and perhaps RDF meta-data, but the coordinate precision stuff should stay. I don't know for sure, since I don't use Inkscape.


inkscape can save as "plain svg" and there's also an xml editor for fine tuning integrated.

**Comment by pnorman** [comment]
> It might add some of the XML namespace tags and perhaps RDF meta-data, but the coordinate precision stuff should stay.

As well as the replacing of the group + transform with just a plain path in one of the SVGs. I'm slightly surprised the former worked, given Mapnik's limitations.

**Comment by kocio-pl** [comment]
I see nothing wrong with this code cleaning - the worst thing that can happen is that the clutter will be back, which doesn't scare me too much.

**Pull request merged**
