### PR TITLE
 Change leisure=water_park rendering to tourism outline

### LINKED ISSUE #1490: Water parks areas should be rendered
Issue #370 was closed by pull #725, where leisure=water_park got an icon. I think it should also get a fill. 
Possible colours:
- like landuse=meadow (since there are often meadows along the pools)
- something like sports_centre (maybe rethink that strong green at the same time...)

### PR DESCRIPTION
**Pull request by jeisenbe**
Fixes #1490

## Changes proposed in this pull request:
- Change leisure=water_park text labels to match tourism=theme_park and tourism=zoo
- Add tourism outline for leisure=water_park, matching theme parks and zoos
- Rename leisure/water_park.svg icon to leisure/swiming_area.svg, do not use for leisure=water_park

## Explanation:
- Water parks are "amusement parks with features such as water slides". This tag should not be used for simple swimming pools, according to the [leisure=water_park wiki page](https://wiki.openstreetmap.org/wiki/Tag:leisure=water_park). 
- According to the wiki, water parks should be mapped as an area; [taginfo confirms](https://taginfo.openstreetmap.org/tags/?key=leisure&value=water_park) that over 75% are mapped in this way.
- However, the current rendering is identical to the rendering of `leisure=swimming_area` and `leisure=sports_centre` + `sport=swimming`. This causes confusion and does not support mappers in consistent tag usage.
- Water parks are closely related to `tourism=theme_park`, and can reasonably be rendered in the same style, as another type of amusement park. 

## Test rendering with links to the example places:

**Wild Wild Wet, Singapore** - a proper water park, part of a retail mall
https://www.openstreetmap.org/#map=17/1.37794/103.95416
Before z16
z16-wild-wild-wet-before
z17
z17-wild-wild-wet-before

After z16
z16-wild-wild-wet-after
z17-wild-wild-wet-after

**Water Works, Science Centre, Singapore**
https://www.openstreetmap.org/#map=1.33345/103.73657
This is a small water-play / science area in the outdoor courtyard of the Science Centre; it has a extra admission fee (much to my children's disappointment). The water area is very shallow. The feature to the north is tagged "theme_park"
before z18
18-water-works-before
after z18
z18-water-works-after

### CODE REVIEW

**Comment by jeisenbe** [comment]
Here's a better example of a proper water park, in Hawaii. However, it's also tagged tourism=theme_park, so the rendering will not change (but it will be possible to remove this tag):

z15
z15-wet-wild-hawaii-before

z17
z17-wet-wild-hawaii-before

(Apparently if you want to name a water park, it should include the words "Wet" and "Wild")

**Comment by jeisenbe** [comment]
Does anyone have time to look at this PR? While it doesn't eliminate an icon, it does change waterparks from using the "swimming" icon to using just an outline and text label, identical to the rendering for theme parks and zoos, which I believe will improve the map and be less confusing.

**Comment by Adamant36** [comment]
@imagico or @matkoniecz, any chance one of you could deal with this? I'd really like to see it added so it's one less thing people wrongly tag for rendering. As it currently is, there are a ton of them miss-tagged as leisure=park and landuse=recreation_ground. I think adding an outline would remedy that and having it be the tourism outline makes sense.

**Comment by imagico** [comment]
Quick comment - which however is not a complete reviews, i have not looked at actual use of the tag.

* I am generally critical of the use of the double outline style rendering - very bold, very noisy while transporting very little information, due to transparency looks different on different backgrounds.
* Rendering water parks identical to zoos and theme parks but very different from other swimming facilities seems a strange idea to me (especially since the delineation between a sports oriented public swimming facility and an amusement oriented one does not seem that obvious to me).

As a general reminder - reviewing PRs is not a privilege of maintainers here - everyone can do that.

**Comment by jeisenbe** [comment]
> "I am generally critical of the use of the double outline style rendering - very bold, very noisy while transporting very little information, due to transparency looks different on different backgrounds."

I agree that it isn't ideal. The main alternatives would be to use:
1) A solid-color outline
2) A solid-color fill
3) Transparent fill (but I don't think this alternative would address the problems that you mentioned)

But this could be adjusted for zoos, theme parks and water parks at the same time, after this PR is closed or merged. 

Perhaps there should be an new issue opened to address this? Would you be willing to do that, so that your concerns with the current rendering are clearly described?

> "Rendering water parks identical to zoos and theme parks but very different from other swimming facilities seems a strange idea to me (especially since the delineation between a sports oriented public swimming facility and an amusement oriented one does not seem that obvious to me)"

In the USA there is a strong division between "Water Parks", which are are type of Theme Park with water-slides and water-rides instead of roller coasters, and swimming pools or water sports centers. Water parks are open seasonally (except in the southernmost parts of the USA) and have expensive paid admission with wristbands and the whole bit, like a theme park. 

Most other swimming facilities are owned by the local government or are part of a fitness club or YMCA.

However, I've seen that in Luxembourg (where I was looking around for test-rendeirng locations) there are a number of places tagged as `leisure=water_park` which look like swimming pools to me. I think these are mistagged, based on the wiki page definition: 

"Water parks are amusement parks with features water slides, recreational pools (e.g. wave pools) or lazy rivers.
"Do not use this tag for swimming facilities, i.e. outdoor or indoor facilities that are mainly focussed on swimming as a sport. Tag them with leisure=sports_centre + sport=swimming instead."

I wonder if our current rendering, identical to the icon for `leisure=swimming_area` and `leisure=sports_centre` + `sport=swimming`, is causing the confusion. 

It's possible that a small, northern country like Luxembourg doesn't have single feature that should actually be tagged as a `leisure=water_park` (unless summers there are hotter than in Germany?):

z17 Piscine de Beaufort ("Beaufort Pool") - a swimming pool, but tagged leisure=water_park
z17-beaufort-before

z17 Centre Aquatique AquaSud - a swimming sports center?
z17-oberkorn-before

z18 Piscine Scolaire - "School pool" - come on, why did they tag this leisure=water_park?
z18-school-pool-before

There are 2000 nodes and 8000 ways, so I don't think I can review all of them, but perhaps this is a problem in some non-English speaking countries. 

However, I also see that the wiki page used to be less specific about the difference between a leisure=water_park and a swimming related sports centre. From 2010 to 2017 the page started like this:

2010 to 2017: "Water parks are amusement areas with features like water slides, recreational swimming pools and dressing rooms." 

So I can see why places where "Water Park" was not already defined might have found and used this tag in ways that don't match with American English usage. I see that this word is "mainly US" usage according to the [Cambridge dictionary:](https://dictionary.cambridge.org/dictionary/english/water-park) "mainly US - a large area containing several different pools, usually with equipment and activities for swimmers, that visitors pay to use" 
And [oxforddictionaries](https://en.oxforddictionaries.com/definition/us/water_park) has it as North American English: "A large outdoor area with swimming pools, water slides, and similar attractions."

Nonetheless, I don't think we are doing mappers any favors by rendering these like a sports-oriented swimming pool, with the current icon. The current wiki definition is certainly correct in describing how this term is used in English, and provides a reasonable distinction between water parks and regular pools or swimming sports centers.

**Comment by Adamant36** [comment]
"z18 Piscine Scolaire - "School pool" - come on, why did they tag this leisure=water_park?"

Might be an indoor water slide or to. There's a community pool at our local park that has a few water slides, changing rooms etc. I tagged it as a sports center. I think tagging it as a water park based on a few slides would have been wrong. To me a water park is a larger, usually privately owned, facility that has more then just a swimming pool and what swimming pools it does have aren't the main attraction. I can see where the usage of the tag on something or not could turn into the same arguing that occurs with leisure=park due to the ambiguity. The same thing happens with leisure=playground to some degree. Generally, I'm not solid on using the clarity of the tag or not as a reason to render or not. As I think most tags suffer from a lack of clarity to some degree. 

The ones tagged as leisure=park are probably just because "water park" has the word "park" in it and its Pokemon Go friendly. From my experince park miss tagging had more to do with our inability as a community to come up with a concise definition of what constitutes a park, causing people to run ramped with the tag unchecked, then it does anything to do with problems of the alternatives. Or put more simply, water park miss tagging as parks is on the park tag, not the water park tag.

**Comment by imagico** [comment]
@jeisenbe - note i was not defending the status quo in rendering, i was just commenting on your suggestion for a new rendering.

Regarding the meaning of leisure=water_park - i understand what you have in mind when thinking of a water park but don't really see how mappers are support to determine if something qualifies as such or is something else in various situations where there is water and pools involved and there is also some amusement infrastructure like water slides and in any case i don't see how there is a stronger similarity between zoos and theme parks and water parks than between water parks and other recreational/sports/health water facilities.

By the way - what you understand as water parks exists in Europe as well but in Central Europe mostly and in Northern Europe probably exclusively as an indoor facility. In German this is often called an _Erlebnisbad_ but differentiation from other types of bathing/swimming facilities is completely gradual.

**Comment by jeisenbe** [comment]
As an alternative to the tourism outline, we could render these with a fill color and text label without an icon, the same as generic leisure=sports_centre features?

**Comment by Adamant36** [comment]
I was thinking that.

**Comment by jeisenbe** [comment]
Closing in favor of trying rendering with solid fill color, similar to leisure=sports_centre.

**Pull request closed without merging**
