### PR TITLE
Adding amenity=social_facility icon

### PR DESCRIPTION
**Pull request by kocio-pl**
Implements part of https://github.com/gravitystorm/openstreetmap-carto/issues/108.

I think we should render amenity=social_facility [the same as amenity=community_centre](https://github.com/gravitystorm/openstreetmap-carto/pull/1744) in general. Once we have social_facility=* key available, we can create also some more specific icons (for shelters or food-related places, for example).

social_facility-19

### CODE REVIEW

**Comment by matkoniecz** [comment]
I think that for this two amenities just label would be better.

**Comment by kocio-pl** [comment]
Hm, since [more than 93% such objects have a name](http://taginfo.openstreetmap.org/tags/amenity=social_facility#combinations) it is perfectly acceptable solution, however I also know the place which is a mix of few different social facilities [in one building with the enclosing area](http://www.openstreetmap.org/way/39230878), so it would be still not visible. 

Your proposition would only change the color for social facilities enclosed in one building to brown (about 19%) and start to show the names of the rest. Even in the worst case (assuming that all the buildings already have names) we would show 74% currently invisible such objects, so it would be quite effective.

I still like this icon to be used, but I'm not going to argue if more people doesn't like my POV.

BTW: or we could also use some borders with name labels, maybe? This would show all the social facilities, irrespective of them being named or not, but I'm not sure how the border should look like and if it is not overkill in general (but for some places like orphanage it would be natural to show the area, like we do for schools).

More opinions and ideas would probably help.

**Comment by kocio-pl** [comment]
After some discussion on #660 now I feel that displaying the icon with text is preferable over just the label, [because it makes this style more universal (icons are language independent) while not obscuring other things (high zoom level is not crowded)](https://github.com/gravitystorm/openstreetmap-carto/issues/660#issuecomment-135128493).

**Comment by polarbearing** [comment]
Label and icon please. Some objects can have fancy names which do not reveal what they are. I mapped one called "The Gap".

**Comment by kocio-pl** [comment]
I've just made a special draft for this type of facility:
1) social_facility-14-29

**Comment by polarbearing** [comment]
@kocio-pl - good one. Could be seen as 'helping hand' as well as 'cocooning' which both leads to the intended association.

**Comment by math1985** [comment]
I haven't had time to look at this yet.

**Comment by kocio-pl** [comment]
I think new icon really makes sense and it's definitely better to have something different than community centre icon if possible:
social-facility-hands-19

**Comment by polarbearing** [comment]
Progress in this issue would be appreciated, does anything speak against the icon?

**Comment by math1985** [comment]
When I see the community centre icon on the map, it keeps reminding me of a school rather than a community centre? Am I'm the only one in that?

Also, I'm not sure if the current icon expresses for example a nursing home very well?

**Comment by kocio-pl** [comment]
Looks like nursing home is tagged differently ([amenity=nursing_home](http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dnursing_home)).

**Comment by polarbearing** [comment]
social_facility 40000 currently. Nursing home is the older style for tagging a subclass of social_facility.

We should discuss the community_centre icon in the other issue, and focus her on the later proposal by @kocio-pl Sep 24-28.

**Comment by polarbearing** [comment]
@math1985 - it is not clear what icon your comments on Nov 9 refer to. 

The PR currently implements the 'helping hand' icon from @kocio-pl, not the community centre one.

**Comment by mboeringa** [comment]
> I've just made a special draft for this type of facility:
> 1) alt text
> 2) alt text

Nice ones, I think I have a slight preference for the hands which bend inwards. This looks more natural, and makes the hands both more recognizable as such, and more "caring".

**Comment by kocio-pl** [comment]
@mboeringa I took 1) because 2) looks blurred for me and I personally have more trouble recognizing the shape alone, but I was trying to achieve exactly what you say.

**Comment by math1985** [comment]
I'm still not extremely fond of the icon, but I think it's better than nothing, so I'll accept this PR.

**Comment by math1985** [comment]
Sorry, I didn't see the icon was changed with respect to the preview. New icon looks fine to me!

**Pull request merged**
