### PR TITLE
Dog park color change

### PR DESCRIPTION
**Pull request by meased**
Continuation of #2216. Attempting to solve #2250.

Render dog parks like playgrounds with a paw pattern background.

dogparkinpark
(with barrier=fence)

dogpark

dog_park_node

### CODE REVIEW

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 05 ago 2016, alle ore 05:15, meased <notifications@github.com> ha scritto:
> 
> Render dog parks like playgrounds with a paw pattern background.


while dog parks and playgrounds could be seen as similar features from a conceptual point of view, for practical usage this idea seems counterproductive. It would lead to playgrounds and dog parks look the same without the pattern (in lower zoom levels) and therefore neither serve dog owners nor parents

**Comment by kocio-pl** [comment]
@dieterdreist You're right about this effect, but for me it's highly preferable to [hide details in lower zoom levels](https://en.wikipedia.org/wiki/Cartographic_generalization). I would definitely like to recognize them in micro scale, but on lower zoom levels only bigger/more complex structures should be visible, like parks and schools, not the playgrounds, dog parks or pitches, which are common parts of them.

@meased What about different colors for icon and label on points?

**Comment by meased** [comment]
Text and icon are different colors only because we currently render playgrounds on nodes that way. The reason I went with playground color for areas was to avoid making another green. Campground color may be another option.

**Comment by kocio-pl** [comment]
Oh, you're right! For me this version is worth merging as it is, but we still have to fix the general color inconsistency for leisure label/icon (see https://github.com/gravitystorm/openstreetmap-carto/issues/1794).

**Comment by math1985** [comment]
> @meased What about different colors for icon and label on points?

Is this related to #1355?

**Comment by kocio-pl** [comment]
No, I was talking only about matching icon and label colors, they don't have to match background color for me (look at the hospital colors for icon+label vs background).

**Comment by math1985** [comment]
Thanks! Looks good to me too.

**Comment by michaelzangl** [comment]
This was a feature I missed for a long time.

In Karlsruhe, we have dog park areas that e.g. are covered by trees. They are not rendered the right way since dog parks are rendered as solid textures - the same way the land cover is.

I suggest changing the texture background to be transparent or semi-transparent and increasing the z-index of dog park so that it is displayed above the landcover.

Example:
http://www.openstreetmap.org/#map=19/48.99757/8.37287

**Comment by kocio-pl** [comment]
@gravitystorm thinks that transparency is bad solution, so it's just out of question currently. We use simple heuristic however: smaller areas are rendered on bigger areas, so if the trees are just a part of dog park, they would cover it (see in the park), but it seems that in your case the dog park is small area compared to one big area with trees, so it is rendered on top.

**Comment by michaelzangl** [comment]
I know that heuristic. I think it makes perfect sense for "normal" areas. But a dog park - at least in our town, is more like a natural resort marked by signs and does not necessary need to be a separate area.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 16 ago 2016, alle ore 17:45, kocio-pl <notifications@github.com> ha scritto:
> 
> @gravitystorm thinks that transparency is bad solution


I think he is only against alpha values >0 and <1 because of "unpredictable" colors, while 0 and 1 are both OK.

**Pull request merged**
