### PR TITLE
Add test osm file

### PR DESCRIPTION
**Pull request by matthijsmelissen**
This file can be used for regression testing.
Load it in pgsql with:

osm2pgsql -s -U postgres -d gis --keep-coastlines rendertest/rendertest.osm

Do you think having a regression/unit test file like this in the repository would be useful? We could start with a simple file like it is now, and add more test cases as we go.

### CODE REVIEW

**Comment by math1985** [comment]
Extended file.

**Comment by math1985** [comment]
This is ready to merge now.

@gravitystorm Do you think this belongs in the repository?

**Comment by gravitystorm** [comment]
@math1985 I don't think it belongs here. The concept of unit testing is an important one but I'd rather do something like the mapnik automated tests i.e. a bunch of individual tests with changes detected by script, rather than an all-encompassing blob of test data to be manually checked.

I think some people will find it useful though, so perhaps it should be published separately? I'm not sure where you've positioned the data but if it's somewhere relatively data-free then it could be combined with extracts when developers are reloading their databases.

**Comment by math1985** [comment]
I created a separate repository for this file: https://github.com/math1985/openstreetmap-test-data

**Pull request closed without merging**
