### PR TITLE
add possibility of specifying hsl colours to shield generation script

### PR DESCRIPTION
**Pull request by nebulon42**
I wrote a small Python method to parse RGB e.g. rgb(150, 120, 130) or HSL e.g hsl(210, 20%, 50%) colour definitions. I think the shield generation script would benefit from it, since it makes playing with colours a lot easier.

If you don't think so too, please close this pull request.

P.S.: PR 2000, wow. :)

### CODE REVIEW

**Comment by pnorman** [comment]
The output of preprocessed code shouldn't really be edited by hand, so I don't see hsl or rgb has an advantage over hex.

**Comment by nebulon42** [comment]
Others might want to use the script in a different way and I found hsl handy when experimenting. But as I said it's just a suggestion and I don't mind if you don't see the added value.

**Comment by pnorman** [comment]
if this PR is changing shield output, it should also contain changes to all the shields, right?

**Comment by nebulon42** [comment]
Currently it does not change anything visually as any hex value will be returned without changes, see https://github.com/gravitystorm/openstreetmap-carto/pull/2000/files#diff-d6c0cb01945928a60a33f9441ed95cdeR136
Additionally, rgb and hsl are always converted to hex in the SVG.

**Comment by pnorman** [comment]
It's not a question of visual changes, it's a question of the files being up to date. If I run the script and copy/paste the output into the relevant files, `git diff` should show no changes.

**Comment by nebulon42** [comment]
> If I run the script and copy/paste the output into the relevant files, git diff should show no changes.

This is the case.

**Comment by pnorman** [comment]
To the script stroke_fill and such are just strings, and svg has HSL support

Can't you just do `config['motorway']['fill'] = 'hsl(0,100%, 50%'`?

**Comment by nebulon42** [comment]
>  svg has HSL support

SVG 2 supports HSL, SVG 1.1 only supports RGB and Hex notation. I'm not sure how widespread SVG 2 support is, but I've tried this before and neither my built-in image preview program nor Inkscape where able to display this correctly. I doubt that Mapnik supports SVG 2, but I might be wrong. A quick search didn't bring something up.

**Comment by pnorman** [comment]
> SVG 2 supports HSL, SVG 1.1 only supports RGB and Hex notation

Good point.

I'll have a closer look at the code, also I'm not sure how this best interacts with #1873

**Comment by nebulon42** [comment]
I think I will withdraw this for now, because I want to enhance it with Lch. The function can always be found at https://github.com/gmgeo/osmic/blob/master/tools/export.py#L532-L558.

Another good thing would be to bring Lch to carto. @pnorman if you need help, let me know.

**Comment by math1985** [comment]
> Another good thing would be to bring Lch to carto

+1, is it supported in Mapnik?

**Comment by pnorman** [comment]
> > Another good thing would be to bring Lch to carto

> +1, is it supported in Mapnik?

No, and doesn't need to be.

Carto takes colour functions and turns them into hex codes or rgba.

This is good because it lets us use new functions without a Mapnik upgrade, which is harder.

I'm working on some fairly complex carto changes for work, so I'm working on small changes to get familiar with the carto changes, and one of them is perceptual colourspaces (mapbox/carto#354)

**Pull request closed without merging**
