### PR TITLE
Drop incorrect text class from text-line

### PR DESCRIPTION
**Pull request by math1985**
This saves 4 out 20 seconds on ever Carto-run on my system, and was a bug
anyway.

See also #1941.

### CODE REVIEW

**Comment by rrzefox** [comment]
It also decreases the size of the resulting .xml by more than 150 kB for me, which is impressive.

**Comment by pnorman** [comment]
Isn't this used in [water-features.mss](https://github.com/gravitystorm/openstreetmap-carto/blob/master/water-features.mss#L117-L164)?

```mss
.text {
  [feature = 'waterway_dam'],
  [feature = 'waterway_weir'] {
    #text-poly[zoom >= 15],
    #text-line[zoom >= 15],
    #text-point[zoom >= 17] {
      ...
      #text-poly {
        ...
      }
      #text-line {
        ...
      }
      #text-point {
        ...
      }
    }
  }

  [feature = 'man_made_breakwater'][zoom >= 15],
  [feature = 'man_made_groyne'][zoom >= 15],
  [feature = 'man_made_pier'][zoom >= 15] {
    #text-poly,
    #text-line {
      ...
      #text-poly {
        ...
      }
      #text-line {
        ...
      }
    }
  }
}
```

**Comment by math1985** [comment]
Yes, thanks for catching.

**Comment by math1985** [comment]
Fixed, performance speed-up is still the same.

**Comment by math1985** [comment]
@pnorman Could you review this and #1947 by any chance?

**Pull request merged**
