### PR TITLE
move butcher icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
butcher_before

after
butcher_after

### CODE REVIEW

**Comment by matkoniecz** [comment]
In that case I prefer the current icon, new symbol looks for me like a credit card.

**Comment by kocio-pl** [comment]
I could recognize this icon only afterwards if the name was distinctive/familiar. Probably something like 2.1 from here:

http://cdn.vectorstock.com/i/composite/11,52/black-meat-icons-set-vector-1791152.jpg

would be even better (the emblematic meat itself, not how it's done...).

**Comment by matkoniecz** [comment]
@kocio-pl Is it happening also for a current icon?

**Comment by kocio-pl** [comment]
Do I recognize the current one? Yes, I do. Or what are you asking me?

**Comment by nebulon42** [comment]
Butcher is not ready for merge yet.

**Comment by pnorman** [comment]
> In that case I prefer the current icon, new symbol looks for me like a credit card.

I also saw it as a credit card before reading your comment.

> @kocio-pl Is it happening also for a current icon?

I didn't see the current icon as a credit card. The curve might be part of that. I like the hollow inside more too.

**Comment by matkoniecz** [comment]
> Butcher is not ready for merge yet.

Please, make a new pull once it will be ready.

**Pull request closed without merging**
