### PR TITLE
add rendering for amenity=doctors

### PR DESCRIPTION
**Pull request by nebulon42**
Implements #89 and part of #1165. Supercedes #1041.
SVG Icon: [nebulon42/osmic/health/doctor-16.svg](https://github.com/nebulon42/osmic/blob/master/health/doctor-16.svg)

http://www.openstreetmap.org/#map=19/48.21663/16.34037
before
not rendered

after
doctors_after

### CODE REVIEW

**Comment by math1985** [comment]
This icon is interpreted as a pharmacy (n=1).

**Comment by daganzdaanda** [comment]
I see the potential to read it as "pharmacy", but it can quickly be learned, and makes a good icon.
The other option at #1041 was a snake of Aesculap, which is well known, but horrible at those small sizes.

**Comment by nebulon42** [comment]
I this might be possible, yes, but I also think that in combination with the name and the very expressive pharmacy icon this is easily spotted as doctors.

**Comment by math1985** [comment]
@nebulon42 Can you include the phrase 'Closes #XXX' or 'Resolves #XXX' in your PR description? That way the issue automatically gets resolved when the PR is accepted.

**Comment by nebulon42** [comment]
Yes, sure.

**Comment by daganzdaanda** [comment]
Thank you all, finally we see doctors on the map! And it looks good!

I've found an extreme place: https://www.openstreetmap.org/relation/2128448
The doctors should probably be moved inside, but then it would be OK for me.

**Pull request merged**
