### PR TITLE
add amenity=charging_station icon

### PR DESCRIPTION
**Pull request by davidfg4**
Addresses #989 and #108 

http://wiki.openstreetmap.org/wiki/Tag:amenity%3Dcharging_station
This adds an icon for amenity=charging_station. If there is a name it should also be rendered, although very few charging stations have a name tag. The icon was taken from https://github.com/gmgeo/osmic per @nebulon42 's suggestion.
There are currently over 8000 charging_station points, and it would be good to be able to view them on the map. See http://overpass-turbo.eu/s/hr4 for where these are currently.

17:

18:

19:

### CODE REVIEW

**Comment by pnorman** [comment]
The icon fits in and the PR looks technically okay, but we never decided in #989 if we want to render charging stations or not. Having the PR lets us see how it looks.

**Comment by kocio-pl** [comment]
I don't have an opinion if we should render it or not, but the internal part of the icon (spark) is not clear to me on all these exports - could it be wider a bit?

**Comment by davidfg4** [comment]
Original, wider:
comparison

I think the original has better proportions and is clear enough, but the wider lightning bolt is a bit easier to see. I'd be happy to switch it over if a few people would like.

**Comment by kocio-pl** [comment]
I like wider more, but I think spark could be longer on top (not truncated like it is now).

**Comment by davidfg4** [comment]
Original, wider, taller:
comparison

**Comment by kocio-pl** [comment]
With wider and taller version the sparks are perfectly recognizable for me now, but I think they could be placed a bit lower.

**Comment by davidfg4** [comment]
With that version the bolt is two pixels from the top and three from the bottom. It would look weird below center.

**Comment by kocio-pl** [comment]
I don't think it would, but don't care that much for this detail - it's already an improvement to me.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 22 lug 2016, alle ore 15:14, David Gianforte <notifications@github.com> ha scritto:
> 
> I think the original has better proportions and is clear enough, but the wider lightning bolt is a bit easier to see. I'd be happy to switch it over if a few people would like.

I think wider is better recognizable, maybe you could even try to get rid of the pump and just keep the jack and the bolt (bolt in blue and slightly bigger in this case)

**Comment by sorcrosc** [comment]
> I think wider is better recognizable, maybe you could even try to get rid of the pump and just keep the jack and the bolt (bolt in blue and slightly bigger in this case)

Another way could be to get rid of the bolt and give more focus to the plug?

**Comment by davidfg4** [comment]
I agree, the wider/taller bolt is easier to see.

[The icon we have for fuel](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/fuel.16.svg) has a pump and gas hose, so it'd be nice of the electric charging icon was "similar but different". Looking around the internet I'm seeing similar lightning bolt on a "pump" with cord and plug design that was used in this icon. So it seems to be fairly standard and it would be good to stick with that.

It'd be nice to avoid the "bike shed effect", but if any of you want to explore other ideas feel free to mock them up so we can see.

**Comment by sorcrosc** [comment]
Sorry, it's my last post. The icon is good and I don't know if it could be better but just to explain.
I agree it should be similar to the fuel pump but the characteristic shape for which the pump is recognizable  is already lost, instead it gained two simbols (the bolt and the plug) none of which is so clear

**Comment by Barthwo** [comment]
I would propose an icon with a bigger plug, which is already in use in this POI map: http://www.flosm.de/html/POI-Karte.html#269265.97/49.4232406/6.96490407/0/chargingcar/chargingstation and also used by Osmand: https://github.com/osmandapp/OsmAnd-resources/blob/master/icons/svg/transport/charging_station.svg

**Comment by morray** [comment]
should be added and the bolt symbol is good enough at the moment and should not stop it

**Comment by math1985** [comment]
>  the PR looks technically okay

Are you sure the icon is pixel-aligned? It looks a bit blurry to me.

**Comment by math1985** [comment]
Merged, thanks @davidfg4.

Problems with the icon, if any, could be fixed in a follow-up PR.

**Comment by davidfg4** [comment]
Thanks @math1985.

It is aligned to pixels, but in order to differentiate between the cable the the prongs, the cable is a bit thicker than 1px, and the prongs are slightly less. Again, I didn't design this, it's from https://github.com/gmgeo/osmic

screenshot from 2016-07-25 17-57-34

**Comment by kocio-pl** [comment]
Am I right that [merged version](https://github.com/gravitystorm/openstreetmap-carto/blob/master/symbols/charging_station.16.svg) is the same as original (not [wider and taller](https://cloud.githubusercontent.com/assets/529761/17059861/7097464a-4fe4-11e6-828f-5ab522c67a0c.png))?

**Comment by davidfg4** [comment]
@kocio-pl yes

**Comment by kocio-pl** [comment]
I thought this:

> I agree, the wider/taller bolt is easier to see.

meant you wanted to replace the original with it. Do you really want to do that (and haven't done it yet) or I misunderstood you and you want to stick with it?

**Comment by davidfg4** [comment]
I'm perfectly happy with the original icon too, so at this point I'm not going to make a new PR to change it.

**Comment by kocio-pl** [comment]
I'd like to make some mockups and PR then. Could you share the link to the SVG version?

I'm against bikesheding and also [like to use osmic if possible](https://github.com/gravitystorm/openstreetmap-carto/pull/1615#issuecomment-123024599), but I prefer readability over pureness.

**Comment by davidfg4** [comment]
Sure, here is the larger bolt: http://gianforte.org/charging_station_LARGER_BOLT.16.svg

**Pull request merged**
