### PR TITLE
Add place=allotments

### PR DESCRIPTION
**Pull request by AMDmi3**
This tag is widely used in Russia: http://wiki.openstreetmap.org/wiki/Tag:place%3Dallotments however it not being rendered makes people unhappy and lead to incorrect tagging, so I hope we can finally implement it.

There's also a ticket (14 months old!) for it in trac: https://trac.openstreetmap.org/ticket/4486

### CODE REVIEW

**Comment by d1g** [comment]
> In OpenStreetMap we have a list of place values, from giant settlements down to single buildings. (city, town, village, hamlet, isolated_dwelling). This is a continuous range - any settlement can fit into this hierarchy

@gravitystorm yes, but these classes were extended according to governmental data ("Схема на основе официальной классификации" 

[9(11) classes from here](http://wiki.openstreetmap.org/wiki/RU:Key:place/Clarification#.D0.9F.D1.80.D0.B5.D0.B4.D0.BB.D0.B0.D0.B3.D0.B0.D0.B5.D0.BC.D0.B0.D1.8F_.D1.81.D1.85.D0.B5.D0.BC.D0.B0_.D0.BA.D0.BB.D0.B0.D1.81.D1.81.D0.B8.D1.84.D0.B8.D0.BA.D0.B0.D1.86.D0.B8.D0.B8_.D0.9D.D0.9F), cover every case from official docs, where 5 "worldwide" classes unable to describe.


It is most important to support 5 classes that overlap (you said them), but it is important to support regional-based schemes too because they give much more meaningful and usable (practical) results.

**Comment by matkoniecz** [comment]
> 9(11) classes from here

Is there an English-language documentation describing why yet another new values for key place were invented? Especially - what was so important reason that such drastic solution was used instead of using additional tags, that would play together with well established place tags?

For example from reading http://wiki.openstreetmap.org/wiki/Key:place it seems that place=allotments is for place=farm/isolated_dwelling/hamlet/village without some legal permit. I am quite curious why place=* + some additional tag was considered to be an inferior solution.

And note - I am looking for link leading to such documentation (this bug tracker is not a good place to create one).

**Comment by d1g** [comment]
@matkoniecz quick reply regarding 3 classes, suburb,quarter,neighbourhood it was here forever, before PR:

Hierarchy for parts of settlements: suburb,quarter,neighbourhoo
http://wiki.openstreetmap.org/wiki/Proposed_features/place%3Dneighbourhood

Some styles use suburb,quarter,neighbourhoo data reasonably well at low level zooms ([MapSurfer.NET](http://edward17.github.io/LayersCollection/))

**Comment by d1g** [comment]
@mackerski problem with place=* key is that it was defined as "named place"; and yes you couldn't blame anyone for tagging it place=* if object had name. It was never limited to 4 classes.

For example, place=island may belong to "natural" tags. BUT don't forget that there every single island within agglomeration with given name:

http://www.openstreetmap.org/way/26767311
http://www.openstreetmap.org/relation/1312631

I think one answer about place=allotments can be in their architecture and urban/rural planning.

As you can see; there no farms: http://taginfo.openstreetmap.ru/tags/place=farm but there http://taginfo.openstreetmap.ru/tags/place=allotments

Farms are typical for countries with farms, I don't think anybody could give definition what farm is. Can you define place=farm for every country?

Why do you want to place farms among (city, town, village, hamlet, isolated_dwelling)?

I understand intent to "keep it simple". But if you make it simpler than it is in the real life, this data will be less useful.

My opinion is that place=allotments can be seen as synonym to landuse=allotments.

AMDmi3 [suggested to render them as farms](https://github.com/gravitystorm/openstreetmap-carto/pull/147/commits/824ba01f088b3fa5b7d5cc20d14379c18eca2e46) is a good enough approximation for current tagged object IMO.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 27 giu 2016, alle ore 14:28, d1g <notifications@github.com> ha scritto:
> 
> For example, place=island may belong to "natural" tags.


-1, the natural tag for an island is the coastline, if the island has a name we will use the place object for the name. A name on the coastline refers to the coastline.

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 27 giu 2016, alle ore 14:28, d1g <notifications@github.com> ha scritto:
> 
> My opinion is that place=allotments can be seen as synonym to landuse=allotments


yes, the place implies the landuse likely, but landuse=allotments don't imply individual places. The requirement of the place=allotments tag, according to the wiki, is to be a settlement outside another settlement.
I think it should be rendered similar or like a place=hamlet.

**Comment by matkoniecz** [comment]
> My opinion is that place=allotments can be seen as synonym to landuse=allotments.

In that cases just use landuse=allotments.

**Comment by d1g** [comment]
> In that cases just use landuse=allotments.

No. Because some of them are landuse=residential. As was said in [message 4](https://github.com/gravitystorm/openstreetmap-carto/pull/147#issuecomment-23714053) and 5.

place=farm may used with landuse=residential; or with any other landuse and not limited to "farm"
place=farm doesn't imply landuse=farm (why do you think place=allotments would?)

**Comment by d1g** [comment]
landuse=allotments can be unnamed and sliced as many times as user(s) would like, but 

place=allotments should represent **only one name** ([Для присваивания названия объекту "дачное товарищество"](http://wiki.openstreetmap.org/wiki/RU:Tag:place%3Dallotments))

**Comment by mboeringa** [comment]
> landuse=allotments can be unnamed and sliced as many times as user(s) would like, but

To be honest, it would be far better if a new tag was introduced to define subdvisions, instead of re-using the existing tag. Just like there is now **cemetery=sector** tag (http://wiki.openstreetmap.org/wiki/Proposed_features/Cemetery_sector), for the **landuse=cemetery** tag.(http://wiki.openstreetmap.org/wiki/Tag:landuse%3Dcemetery)

**Comment by jojo4u** [comment]
Most of the rationale in https://wiki.openstreetmap.org/wiki/Tag:place%3Dallotments does not hold for me. Place is not about "official" status or cadastre. The seasonal/second home argument is reasonable for me.

I also have the problem that place=allotments has no population hierarchy and thus prominence on the map cannot me infered. There are only [three place=allotments with population](http://overpass-turbo.eu/s/h2m)=* with values of 9, 200, 300

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 29 giu 2016, alle ore 10:11, jojo4u <notifications@github.com> ha scritto:
> 
> I also have the problem that place=allotments has no population hierarchy and thus prominence on the map cannot me infered. There are only three place=allotments with population=* with values of 9, 200, 300


btw, the population values we typically have on place objects are in many or maybe all cases population values of the enclosing admin area

cheers,
Martin

**Comment by d1g** [comment]
@jojo4u

> Most of the rationale in ... does not hold for me.

Well yes, we have to say more. also [Wikipedia is 35K big but not-so good about it](https://en.wikipedia.org/wiki/Allotment_(gardening)#Russia). We have real farms (with farmers-owners, real equipment, regulated by law, with real buildings and not multilevel sheds that can't hold [Russian winter](https://en.wikipedia.org/wiki/Climate_of_Russia)). 

Allotments are different from "farms" because often you cannot have real equipment (say, tractors) permanently; law says you can't live there permanently; area is quite limited (but you can own several plots or pay for a non-standard plot) and thus you can't make allotments as your business model. You either get small money or goods/food enough to feed family. You never overproduce 100x times more than you can possibly consume like farmers do, you never have to keep tonnes of goods somewhere.

Allotments in post-soviet states sometimes were used as leisure (think of BBQ site) and other owners raise nothing but grass or flowers or rare species just for fun.

Some allotments are now abandoned because overall hype is gone today ("[The 1980s saw the peak of the dacha boom](https://en.wikipedia.org/wiki/Allotment_(gardening)#Russia)").

In this sense, allotments are different from "rice plantations" seen in Asian countries (I have to grow rice in dirt to feed my family and from traditional farms ("I will overproduce to get money or to feed my entire village"). You never know how exactly each plot is used or is it used at all. Yes you may go serious with your plot, but that's untrue that everybody does this (there many drawbacks and inefficiencies).

You will never see a true farmer using his lands for BBQ or to grow something for fun or use his land only every 3rd year.

**Pull request closed without merging**
