### PR TITLE
move florist icon to SVG

### PR DESCRIPTION
**Pull request by nebulon42**
Implements part of #1165.

before
florist_before

after
florist_after

### CODE REVIEW

**Comment by matkoniecz** [comment]
Really nice, new icon is much better.

**Comment by kocio-pl** [comment]
The top is great, but I would make leaves thinner on the bottom (like two arches together, not that soft edge).

**Comment by nebulon42** [comment]
I guess you mean something like that: florist-182
Which is actually more close to how tulip leaves are shaped, yes.

**Comment by kocio-pl** [comment]
Yes, that one would be good for me.

**Comment by math1985** [comment]
I also prefer the tulip.

**Comment by nebulon42** [comment]
Updated icon and preview.

**Pull request merged**
