### PR TITLE
rework admin boundaries (without z4 logic)

### PR DESCRIPTION
**Pull request by nebulon42**
This recreates the styling of #1938 without the problematic queries.
It would be grand if there could be a .2 release including these changes. Sorry for the problems this has caused.

### CODE REVIEW

**Comment by math1985** [comment]
Rolling out a release has the disadvantage that updating tiles gets slower for mappers, so I'd prefer not to release too often.

> Sorry for the problems this has caused.

Don't worry about that, it's not something you could have tested, as apparently it depends on very specific configuration options.

**Comment by nebulon42** [comment]
It has been quite some time. I would love to see a new release with this merged.

**Comment by math1985** [comment]
Thanks! Looks much better again. Sorry for the long wait!

**Comment by kocio-pl** [comment]
Thanks for this work and for merging it - it is great and fixes some of the most important problems I saw with low zoom on OSM!

**Comment by sommerluk** [comment]
Great work! Thanks!

**Comment by daganzdaanda** [comment]
Big thanks from me, too! The map makes a lot more sense now!

**Comment by mboeringa** [comment]
:+1:

**Comment by SomeoneElseOSM** [comment]
Excellent stuff - thanks very much.

**Pull request merged**
