### PR TITLE
Making railway stations appear as major buildings [WIP]

### PR DESCRIPTION
**Pull request by kocio-pl**
Related to https://github.com/gravitystorm/openstreetmap-carto/issues/327.

This code is not production ready, because it highlights all the buildings tagged with railway=station, but I want to do it only for building=train_station, to leave all the other buildings alone. Could anybody help me with it?

z18
eqwwzyjz

### CODE REVIEW

**Comment by dieterdreist** [comment]
sent from a phone

> Il giorno 25 set 2016, alle ore 04:05, kocio-pl <notifications@github.com> ha scritto:
> 
> This code is not production ready, because it highlights all the buildings tagged with railway=station, but I want to do it only for building=train_station, to leave all the other buildings alone. Could anybody help me with it?


railway=station on a building is mostly mistagged, because save rare cases train stations extend beyond a building (exceptions are underground stations)

**Comment by jojo4u** [comment]
Currently there is no way to distinguish active and inactive train station buildings. Only way might be wether the building is inside a public_transport=station area.

**Comment by kocio-pl** [comment]
It would make sense if we have something similar to amenity=place_of_worship. But you're probably right that railway=station is not the same [according to wiki](http://wiki.openstreetmap.org/wiki/Tag:railway%3Dstation#Things_to_avoid). It may be changed in the future, but currently we're talking about the whole area.

So for now I would go with [building=train_station](http://wiki.openstreetmap.org/wiki/Tag:building%3Dtrain_station) alone, because this rendering is not defined elsewhere and we're not bound by any specific idea what makes the building "major". One day, when station buildings being a part of the station can be tagged as defunct, we could rethink if we want to consider them major anyway or not.

That means I need to rework the code to use only building=train_station. The problem is that s putting `[building = 'train_station']` in the code [instead of `[railway = 'station']`](https://github.com/gravitystorm/openstreetmap-carto/pull/2371/files#diff-e0fd32db156f4279d089398056e22a79R37) just doesn't work.

**Comment by math1985** [comment]
railway=station is indeed not the right tag. It is also usually used to indicated the stop position. What are the problems with building=train_station?

**Comment by kocio-pl** [comment]
I don't know what I did wrong, but building=train_station works now as a major building [in my branch](https://github.com/kocio-pl/openstreetmap-carto/tree/station-building). Do you think we could reopen it and update the code?

**Comment by math1985** [comment]
> Do you think we could reopen it and update the code?

Sure.

**Pull request closed without merging**
