### PR TITLE
Add icons for shop=fabric and carpet

### LINKED ISSUE #3289: Add  special icon for shop=fabric
https://wiki.openstreetmap.org/wiki/Tag:shop=fabric
7.5k uses

No idea what the icon would look like. I don't think a roll of fabric would work. Any ideas @Tomasz-W?

### PR DESCRIPTION
**Pull request by Adamant36**
closes #3289 This PR adds icons for shop=fabric, shop=carpet, and shop=sewing. Its a good idea to add these icons because they look cool and other such reasons. 

fabric 
https://www.openstreetmap.org/#map=19/40.54160/-80.02588 (node)
shop fabric node z19

https://www.openstreetmap.org/#map=19/40.68446/-80.10688 (way)
shop fabric way z18

carpet
https://www.openstreetmap.org/#map=19/40.52959/-80.00775 (node)
shop carpet node z18

https://www.openstreetmap.org/#map=19/40.60540/-80.05051 (way)
shop carpet way z18

sewing
https://www.openstreetmap.org/#map=19/42.25782/-83.73792 (node)
shop sewing node z18

https://www.openstreetmap.org/#map=19/42.28757/-83.83305 (way)
shop sewing way z19

### CODE REVIEW

**Comment by kocio-pl** [comment]
It seems that `shop=sewing` has a low usage (<1k uses), so I think you should exclude it from this PR. Especially because it has competitor and it is not clear how it will end up:

taghistory 33

**Comment by Tomasz-W** [comment]
@Adamant36 No, it was a quite long and complitated discussion. But as these numbers are small, we can left this icon and add it in the future when situation will be clear.

**Comment by kocio-pl** [comment]
@Adamant36 Do you plan to test it?

**Comment by Adamant36** [comment]
Yeah sorry. I've been hella busy lately. I was just thinking about it though. So I'll do it sometime this weekend. Thanks for reminding me.

**Comment by kocio-pl** [comment]
Great! Please also remember to remove sewing section.

**Comment by Adamant36** [comment]
I will.

**Comment by kocio-pl** [comment]
I also don't see the difference, so no problem... Thanks for you both!

**Comment by matkoniecz** [comment]
Can you look at https://github.com/gravitystorm/openstreetmap-carto/issues/3575 ?

**Comment by Adamant36** [comment]
@matkoniecz, were you able to figure the problem out? It ran fine when I tested it.

**Comment by matkoniecz** [comment]
Yes, as mentioned it was insufficient checking on my side.

**Comment by Adamant36** [comment]
Thats good. I just thought id double check just in case.

**Comment by kocio-pl** [comment]
I'm always testing patches before merging, so at least they should really work and code should compile (but there can be other problems, of course).

**Pull request merged**
